### ISSUE TITLE
Hackathon code improvements

### ISSUE THREAD

**Issue by joeribekker** [open-formulieren/open-forms#101]
These issues were identified on the code introduced by the Hackathon and must be addressed.

- [x] Remove demo.json since it's not represntative for the actual purpose
- [ ] Use PIP version Django-DigiD-eHerkenning (**BLOCKED**)
- [x] Refactor ZGW contrib to be able to configure zaaktype and documenttype per form
- [x] Add tests for ZGW contrib module
- [x] Add tests for BRP contrib module
- [x] Move core/backends to submission module
- [x] Align the styles of core/backends and core/custom_field_types
- [x] formio_builder/builder.js contains BRP component, should be part of the BRP module/more dynamic?
- [x] Submission backend should run on submission completion, not on every step.
- [ ] Store some relation to the logged in person othern then a BSN field on Submission
- [x] Store submission backend results more elegantly
- [x] Storage of the form.io config is a stringified JSON leading to serializer issues

**Comment by sergei-maertens** [comment]
Most of these are tackled or obsolete
