### ISSUE TITLE
Form builder should show warning if there are duplicate formfield keys

### ISSUE THREAD

**Issue by stevenbal** [open-formulieren/open-forms#1043]
Issue raised by gemeente Den Haag:

If I submit a form that has multiple steps, only the info from the first step shows up in the submission PDF:

Form Steps:
![image](https://user-images.githubusercontent.com/29249171/145015088-fc17ef1b-f5aa-44f7-912e-4100efe6e495.png)

Example step (that does not show up in PDF):
![image](https://user-images.githubusercontent.com/29249171/145015408-09341d9f-1fed-4d20-93fc-61cd8a4116e9.png)

Submission PDF
![image](https://user-images.githubusercontent.com/29249171/145015201-146a75b2-bac4-4f84-9232-5f903dede553.png)

**Comment by stevenbal** [comment]
My mistake, the fields of the second formstep have the exact same names as in the first step, causing them not to show up after using `Submission.get_merged_data`. @sergei-maertens is this working as intended?

**Comment by sergei-maertens** [comment]
yes - we currently do not have a check/warning that tells you if form steps have the same `key`, but you should keep those unique over forms. We might at some point use a prefix to prevent this, but not sure yet what the best course of action is. The first step would be detecting non-unique keys in the form-builder and showing a warning.

**Comment by stevenbal** [comment]
> The first step would be detecting non-unique keys in the form-builder and showing a warning.

I'll use this issue to add the warning in the formbuilder admin
