### ISSUE TITLE
Als beheerder wil ik oude versies na een update nog steeds kunnen terugzetten

### ISSUE THREAD

**Issue by joeribekker** [open-formulieren/open-forms#1046]
We gebruiken export/import voor het opslaan en terugzetten van oudere versies van formulieren. Echter, we merken bij elke update dat de exports niet meer werken. Dit is ook te merken in de export voorbeelden in de documentatie.

We moeten dit meer robust maken.

**Comment by sergei-maertens** [comment]
-> one thing would be to at least store the version of open forms at the time the export was created

**Comment by sergei-maertens** [comment]
This would essentially require us to "apply" (data) migrations from between version creation and $now. We now have the indicator and warning showing that manual work may be needed.

I don't think it's feasible and/or worth the effort to make form exports forwards compatible. Let's discuss at some point?

**Comment by joeribekker** [comment]
Warning is good enough until the user story pops up again by users.
