### ISSUE TITLE
Toevoegen van een bijlage leidt tot een Javascript error op de bevestigingspagina, waardoor deze niet meer wordt getoond

### ISSUE THREAD

**Issue by alextreme** [open-formulieren/open-forms#1050]
Taiga 195

"Bevestigd dat dit inderdaad stuk loopt op het moment dat je een bijlage toevoegt en doorklikt naar de bevestigingspagina, het scherm is inderdaad leeg. Dit leidt inderdaad tot een javascript foutmelding die ik hieronder toon."

![2021-12-08_16-39](https://user-images.githubusercontent.com/226839/145238003-18f31116-0679-4db1-a7ca-84945f0bcfde.png)

**Comment by sergei-maertens** [comment]
Fixed via https://github.com/open-formulieren/open-forms-sdk/pull/142/commits/efb892ff781b910863b79bc2e03b7afe27c56b11
