### ISSUE TITLE
Form components should have a server registry for conversion to display strings

### ISSUE THREAD

**Issue by Bartvaderkin** [open-formulieren/open-forms#1059]
Currently we have a `display_value` template tag that together with the template rendering's string conversion makes a best effort to convert submitted data into strings for display in HTML and text (eg: various emails, confirmation page etc, usually through the form summary tag). This is a ugly unmaintainable elif and ignores the component and any special treatment (like file uploads).

Ideally we'd have a registry in Python where each component type is registered with a callable that receives the component definition and submitted value and returns a string for display. 

The callable would need to handle any localization and component options like for example `multiple`.

**Comment by sergei-maertens** [comment]
#1068 has the technical implementation details

**Comment by sergei-maertens** [comment]
This was done a while ago and finalized through the renderer interface.
