### ISSUE TITLE
Pricing is not being saved in a consistent manner

### ISSUE THREAD

**Issue by sergei-maertens** [open-formulieren/open-forms#1066]
Entered the following values in submissions:

* `12,00`
* `20,00`

The exact placement/absence of the comma is unsure - I can't remember.

But the submissions show `12` and `2000` for price, so clearly something is going wrong with the decimals.

**Comment by SilviaAmAm** [comment]
I tried entering numbers >1000, with/without decimals but I don't seem to be able to reproduce this issue.
Also tried waiting for the logic check to click outside of the field (on the event onBlur the `,00` is added to the field if it's not filled in manually).

On the other hand, the dollar currency doesn't seem to work.

**Comment by sergei-maertens** [comment]
I could not reproduce this myself either, and earlier this week some more race conditions were solved in https://github.com/open-formulieren/open-forms-sdk/commit/1990f275488455c69b498e7fff1c3d11f89ed6f8 which *may* have been the cause of the problem. We can re-open if we observe this (again).
