### ISSUE TITLE
Postal Code field does not apply validation

### ISSUE THREAD

**Issue by stevenbal** [open-formulieren/open-forms#1076]
Issue raised by gemeente Den Haag (Taiga 178)

It seems that the postal code field does not apply validation. An incomplete value can be entered, and the formstep can still be submitted:

![image](https://user-images.githubusercontent.com/29249171/145841879-6ce416cb-8ceb-43f8-8e34-a6c55a1af86e.png)

**Comment by stevenbal** [comment]
@sergei-maertens I see that postcode validation was implemented at some point (https://github.com/open-formulieren/open-forms-sdk/commit/1d4f879b2d144a9d958464a05084b2bc2ce0a3a1#diff-4c927600155fcb38ac8e74169003a5b1b363277b773909c3d4c0379d32da828c), is there a specific reason why this was removed?

**Comment by sergei-maertens** [comment]
Looking at the PR feedback, the philosophy is to make custom components as close to vanilla Formio as possible and at the time it seemed like the mask was sufficient validation.

This may have something to do with the validation on blur/on change as well, which is exposed in the form designer now I think.
