### ISSUE TITLE
Multi-value select widget does not work, only the first value is stored/remembered

### ISSUE THREAD

**Issue by sergei-maertens** [open-formulieren/open-forms#1090]
This also seems to apply for the ChoicesJS variant

**Comment by SilviaAmAm** [comment]
It seems to work in the Choicejs widget (see screenshot below). The two chosen values also appear in the overview page. However, it doesn't work for the HTML5 widget

![Screenshot from 2021-12-20 10-23-13](https://user-images.githubusercontent.com/19154114/146743846-503c076b-a42c-4602-a28d-2aef39cfb4ee.png)
