### ISSUE TITLE
Submission PDF does not show data for fields with same labels

### ISSUE THREAD

**Issue by stevenbal** [open-formulieren/open-forms#1099]
Related to https://github.com/open-formulieren/open-forms/issues/1043 and #1068 

It seems that the labels of the fields (rather than the keys) are being used as keys, causing some fields with the already used across other formsteps to not show up in the submission PDF

I think the same issue occurs for the email registration backend and the confirmation email, since they all use `Submission.get_printable_data()`

Would it help to group the data per FormStep?

**Comment by SilviaAmAm** [comment]
Discussed this with sergei and for now we are not going to tackle namespacing the labels.

Printable data will return a list of tuples with `(label, value)` instead of an ordered dict
