### ISSUE TITLE
Generic interface to enable/disable plugins

### ISSUE THREAD

**Issue by stevenbal** [open-formulieren/open-forms#1103]
Currently it is not possible to explicitly enable/disable a (registration/prefill/auth/...) plugin for an Open Formulieren instance. This means that in code, we sometimes have to "guess" whether or not certain plugins are configured properly.

TO DO:
- [x] Add JSONField to our `SingletonModel` GlobalConfig to store plugin identifiers and booleans to indicate if enabled or not
- [x] Plugins are enabled by default, have to be disabled explicitly
- [x] Generic form in the admin that shows all the registered plugins (starting with registrations/prefill/authentication) with checkboxes to enable/disable them (NOTE: Appointments is excluded)
- [x] Extend `BasePlugin` to validate whether plugin is enabled or not
- [x] Extend API's to only show enabled plugins (requires no frontend changes)
  - [ ] There can be edge cases where existing forms have selected plugins that are no longer disabled, should probably be removed silently?
 - [x] API schema should always show all non-demo/dev plugins

**Comment by joeribekker** [comment]
@sergei-maertens should this JSON field not be part of our Globalconfig (which is already a solo model)?

Other than that sounds good.

**Comment by sergei-maertens** [comment]
yeah let's make it a field on the existing model, I don't see why this wouldn't be an option.

Wouldn't be surprised if at some point we decide to make a nice UI page for all the global settings so it fits.
