### ISSUE TITLE
Support default location for appointments

### ISSUE THREAD

**Issue by joeribekker** [open-formulieren/open-forms#1111]
Instead of adding a field to select a location, we should add the option for the admin to select a specific location so the user doesn't have to. Typically in the case that there is only 1 location.

Unfortunately, the plugins have different support for this. Both plugins support getting a list of locations without providing any product. So we can present the admin with a list of locations to pre-select. Only Qmatic supports getting a list of products based on a location. For JCC, we can simply show all products and (same for Qmatic I guess) pass the pre-selected location to the create appointment function.

* [x] Allow admin to pre-select a location in admin UI. Note: This is not a default value that end user can still change.
* [x] If location is pre-selected, validate that location field is not set in admin UI (essentialy the user skips this selection in a form)
* [x] Pass location to `get_products` func in plugin, and `get_dates`, `get_times`, `create_appointment`.

The plugins are refactored so `get_products` takes an optional location (even if the plugin does not support it) so it works generic. If the plugin does not support it, it should still have the same effect for the end user: No location needs to be selected.

* [x] Validate that plugin supports (`plugin.supports_products_by_location`) product by location when the admin selects

**Comment by sergei-maertens** [comment]
Was implemented in Open Forms 2.2/2.3
