### ISSUE TITLE
Add "advanced" tab to Field Sets

### ISSUE THREAD

**Issue by joeribekker** [open-formulieren/open-forms#1123]
Taiga 210

This allows users to use local logic to hide/show groups of fields.

Undo this line: https://github.com/open-formulieren/open-forms/commit/7fb19662ab84df7e5a2080366ddd82c58a9943f8#diff-bb424d4e58746ac16d6f3becdb6c8b05997ef5f3ff16b68180a532aeac49a77bL26

**Comment by sergei-maertens** [comment]
See also #1129
