### ISSUE TITLE
Logic does not trigger correctly on prefilled data in the first step

### ISSUE THREAD

**Issue by joeribekker** [open-formulieren/open-forms#1128]
Taiga 204

When you prefill data, the logic seems to work on the submission data which is non-existant in the first step. This causes incorrect logic behaviour.

**Comment by SilviaAmAm** [comment]
This seems to be working as expected now: https://watch.screencastify.com/v/AlpL4tApLtDo9L6NW7ID

**Comment by joeribekker** [comment]
Awesome.
