### ISSUE TITLE
Add Sentry JS monitoring

### ISSUE THREAD

**Issue by alextreme** [open-formulieren/open-forms#1178]
Gezien enkele frontend/SDK JS errors zou ik aanraden om Sentry monitoring ook in te bouwen in de openforms SDK:

2 opties van wat ik heb gezien:

1) Inladen van de JS SDK loader via een crossorigin request:

https://sentry.maykinmedia.nl/settings/maykin-media/projects/open-forms/keys/d2b2b8150ead4c1282d188c50c4c9647/

<script src='https://sentry.maykinmedia.nl/js-sdk-loader/d2b2b8150ead4c1282d188c50c4c9647.min.js' crossorigin="anonymous"></script>

https://docs.sentry.io/platforms/javascript/install/lazy-load-sentry/

2) Inbouwen van de Sentry React SDK:

https://docs.sentry.io/platforms/javascript/guides/react/

**Comment by sergei-maertens** [comment]
Already exists: https://github.com/open-formulieren/open-forms-sdk/blob/main/src/sdk.js#L39

**Comment by alextreme** [comment]
Clear, assigned to Sjoerd in https://taiga.maykinmedia.nl/project/open-formulieren-deelnemende-gemeenten/issue/279 to activate.
