### ISSUE TITLE
Google Analytics does not measure form steps correctly

### ISSUE THREAD

**Issue by joeribekker** [open-formulieren/open-forms#1180]
Currently, Google Analytics measures views and pages but all forms are opened in the same page (called "Openforms").

We need to change the title of the window to match the form, and maybe even include the step, to get this working. This also makes the window title show nicely, so win-win.

**Comment by sergei-maertens** [comment]
I'd expect it to track the `window.location` in addition to the title. We could update the title as part of the navigation though.

**Comment by sergei-maertens** [comment]
In the SDK you should use [`useTitle`](https://github.com/streamich/react-use/blob/master/docs/useTitle.md) for this
