### ISSUE TITLE
File upload checks and fixes

### ISSUE THREAD

**Issue by Bartvaderkin** [open-formulieren/open-forms#1224]
Test form: maykin-test-uploads

**Checks and fixes**

* [x] Single file upload widget (filled with 0 files)
* [x] Single file upload widget (filled with 1 file)
* [x] Multiple file upload widget (filled with 0 files)
* [x] Multiple file upload widget (filled with 1 file)
* [x] Multiple file upload widget (filled with 2 files)

**Original description**

I uploaded two files in the same widget, then when I click to the summary page it flashes content for a second then turns grey.

My Firefox React debugger points to `src/components/FormStepSummary/ComponentValueDisplay.js` and the FileDisplay function.

Looking at the code it seems it only handles single file and not multiple=True (eg: it explicitly squashes when multiple instead of showing multiple links). Note this was refactored recently so YMMV.

Part of a longer Taiga 292 ticket (with other issues) 

Example: for HadM form 55 'Aanvragen subsidie vrijetijdseconomie ' (more examples in taiga thread)

**Comment by SilviaAmAm** [comment]
The problem seemed to be that the default value for empty file fields (multivalue enabled) is an array `[undefined]`.
