### ISSUE TITLE
If you check multiple values for a multiple selectboxes component, it renders an error on the frontend

### ISSUE THREAD

**Issue by joeribekker** [open-formulieren/open-forms#1227]
Taiga 301

Should we even offer the option "multiple values" for this component? Check with FormIO sandbox.
The error presented is:

![image](https://user-images.githubusercontent.com/96970/150355599-904f813f-9334-491c-961d-d1fc3dd48355.png)

**Comment by SilviaAmAm** [comment]
In FormIO, there is no 'multiple' functionality for the select boxes component

**Comment by joeribekker** [comment]
then we should probably remove it as well to prevent errors.
