### ISSUE TITLE
Columns go off the page

### ISSUE THREAD

**Issue by SilviaAmAm** [open-formulieren/open-forms#1254]
Taiga 334

If too many columns are specified, then they go off the page
![Screenshot from 2022-01-27 14-32-43](https://user-images.githubusercontent.com/19154114/151369017-f3773871-c680-466a-a332-4c405c3c0846.png)

**Comment by sergei-maertens** [comment]
Confirmed that this was a case of the end-user specifying multiple columns, mis-matching the `col-md-x` widths.

Just applying flexbox wrapping to this will also lead to unexpected results, so we need to revisit the columns component definition in the form designer (as the SDK does not have bootstrap!)

**Comment by SilviaAmAm** [comment]
We need to redesign the builder for the column component.

- [ ] The table under 'Kolomeigenschap' needs to be removed. (found in [src/components/columns/editForm/Columns.edit.display.js:35](https://github.com/formio/formio.js/blob/master/src/components/columns/editForm/Columns.edit.display.js#L35))

It needs to be replaced with a table where you can add the number of columns desired and specify their size in terms of percentage.
To do this we need:

- [ ] A table where you can add rows. Each row will have a dropdown with possible sizes: 25%, 33%, 50%, 66%, 75%. Could be added like in the radio component we add the values: [src/components/radio/editForm/Radio.edit.data.js:10](https://github.com/formio/formio.js/blob/master/src/components/radio/editForm/Radio.edit.data.js#L10).
- [ ] The column component needs to be extended to include the columns attribute in the schema. This will be a list where each element is the size of a column. 
```javascript
static schema(...extend) {
    return RadioComponent.schema({
      type: 'selectboxes',
      label: 'Select Boxes',
      key: 'selectBoxes',
      inline: false,
      columns: []  // NEW
    }, ...extend);
  }
```
- [ ] The template of the column needs to be updated so that depending on the number of values of the columns attribute, the right number of columns is shown.
- [ ] Each size value for a column will have a CSS class associated with it that gives the right size to the column
