### ISSUE TITLE
Close session on browser close

### ISSUE THREAD

**Issue by joeribekker** [open-formulieren/open-forms#1269]
Add `SESSION_EXPIRE_AT_BROWSER_CLOSE=True` to settings. Make it an env config. Default moet False blijven.

**Comment by Bartvaderkin** [comment]
Note from the Django docs:

> Some browsers (Chrome, for example) provide settings that allow users to continue browsing sessions after closing and re-opening the browser. In some cases, this can interfere with the SESSION_EXPIRE_AT_BROWSER_CLOSE setting and prevent sessions from expiring on browser close. Please be aware of this while testing Django applications which have the SESSION_EXPIRE_AT_BROWSER_CLOSE setting enabled.
