### ISSUE TITLE
Financial field with 0 decimals shows a comma

### ISSUE THREAD

**Issue by joeribekker** [open-formulieren/open-forms#1270]
![image](https://user-images.githubusercontent.com/96970/151606572-004cb837-ad16-4175-badf-ac30f503be1a.png)

**Comment by SilviaAmAm** [comment]
@joeribekker I don't seem to be able to reproduce this :thinking: Do you have a form where this happens so I can check it?

![Screenshot from 2022-02-02 09-56-40](https://user-images.githubusercontent.com/19154114/152122884-207c190d-84ae-486e-b033-6c509d3a00fa.png)
