### ISSUE TITLE
Family members component crashes forms if no auth?

### ISSUE THREAD

**Issue by joeribekker** [open-formulieren/open-forms#1275]

**Comment by SilviaAmAm** [comment]
The family member component can't work without login (it needs to retrieve the family members of the logged in user). So I added a warning in the admin builder that highlights if there is a custom_types_component and no login required.

**Comment by joeribekker** [comment]
@sergei-maertens @SilviaAmAm shouldn't we make sure the component doesn't crash the form at all times and also make this component show an error or nothing instead?
