### ISSUE TITLE
Form copy shares definitions with original form

### ISSUE THREAD

**Issue by SilviaAmAm** [open-formulieren/open-forms#1280]
Den Haag Taiga 234

When a form is copied, the copy is related to the original form definitions, despite them not being marked as 'reusable' in the form.

So if one makes updates to the copy, these are reflected in the original.

**Comment by SilviaAmAm** [comment]
Potential way of solving this:
- If the original form has a definition marked as reusable, then copy it as reusable and link the new form to the original definition.
- If the original form has a definition marked as NOT reusable, then make a new definition and link it to the copied form.

**Comment by joeribekker** [comment]
Sounds like a good solution, please make it so :D
