### ISSUE TITLE
Familymembers component should not crash the form if no BSN is known

### ISSUE THREAD

**Issue by joeribekker** [open-formulieren/open-forms#1302]
In #1275 this was solved in the form design by showing a warning if no autg option was selected, however, if for some reason there is still no BSN, the form does not need to crash.

Instead, we can show an empty component, or if possible a user friendly error message "Selecting family members is currently unavailable." or so.

**Comment by sergei-maertens** [comment]
Also requires the #1068 to be finished for the dynamic plugins. We've come a very long way with variables to finally finish that.

**Comment by sergei-maertens** [comment]
Depends on #2388 to be finished first
