### ISSUE TITLE
Option to start form directly

### ISSUE THREAD

**Issue by joeribekker** [open-formulieren/open-forms#1313]
Via Den Haag (Taiga 183) and others:

Most of the time, a CMS page is put before the actual form page. This requires the user to click twice to start the actual form (once on the start button in the CMS, and once the start button of Open Forms).

Since there can be different login options (!) we can not simply "start" the form automatically. We could however create the option to "redirect" to the proper (login)action automatically, based on a query parameter.

`/my-form?autostart=digid` (digid auth) or `/my-form?autostart=start` (no auth), etc.

The CMS button can then include this query parameter to skip the OF-start button(s).

**Comment by sergei-maertens** [comment]
See #1195
