### ISSUE TITLE
Checkboxes/radio buttons go over the cookies statement and mobile progress indicator

### ISSUE THREAD

**Issue by SilviaAmAm** [open-formulieren/open-forms#1318]
![Screenshot from 2022-02-09 15-28-44](https://user-images.githubusercontent.com/19154114/153221645-0d40f682-dcac-4a87-91f6-1454c52eb6fa.png)

![Screenshot from 2022-02-09 15-32-23](https://user-images.githubusercontent.com/19154114/153222257-b0eb45d0-5cc5-401f-82cf-64fa3a7c1bde.png)

**Comment by sergei-maertens** [comment]
Fixed via #2053 as well
