### ISSUE TITLE
SDK error on some types of required fields

### ISSUE THREAD

**Issue by Bartvaderkin** [open-formulieren/open-forms#1339]
If I have some types of components in a form (like the date component) and mark them as required and try to submit the field correctly gets marked in red as required, but I also see an  `Uncaught (in promise)  Array [ {…} ]` JS error in the console but without stacktrace or debugger. 

This notably doesn't happen with just a basic TextField.

If I have many components the Promised array mentioned in the error will grow and list many of the components.

This is reproducable by creating a new form with a default date component that is marked as required. Then in the SDK click Next (without entering anything) and view the JS console.

**Comment by Bartvaderkin** [comment]
@SilviaAmAm noted its related to #1076

**Comment by SilviaAmAm** [comment]
This was fixed by https://github.com/open-formulieren/open-forms-sdk/pull/161
