### ISSUE TITLE
SDK file and time components with required and multiple show error code when invalid

### ISSUE THREAD

**Issue by Bartvaderkin** [open-formulieren/open-forms#1344]
- [x] If I have a required fileupload component with multiple=True but don't upload a file I get an error code string '`array_nonempty`' as part of the error message:

    `Dit veld is verplicht.`
    `array_nonempty`

- [x] The same message shows up with a time component, also when required and multiple and nothing entered.

**Comment by sergei-maertens** [comment]
Need to validate this is indeed fixed

**Comment by sergei-maertens** [comment]
Still happens
