### ISSUE TITLE
SDK required single check box isn't initially marked as required

### ISSUE THREAD

**Issue by Bartvaderkin** [open-formulieren/open-forms#1345]
It does properly invalidate if you don't check it and try to submit, but initially there is no red star like the other components.

**Comment by sergei-maertens** [comment]
* Check if this is still the case
* Create UI design / variant in storybook if needed

**Comment by SilviaAmAm** [comment]
It's no longer the case:

![Screenshot from 2022-10-13 17-36-05](https://user-images.githubusercontent.com/19154114/195641500-9fcdc4ea-2599-4600-ad4d-b5b356ca4388.png)
