### ISSUE TITLE
Configure CORS for docker compose

### ISSUE THREAD

**Issue by SilviaAmAm** [open-formulieren/open-forms#1366]
Currently, when running the `docker-compose.yml` file, everything goes well until trying to start a form. This fails because the POST to the `/submission` endpoint fails with a 400: 

```
{ name: "formUrl", code: "invalid", reason: "URL is niet toegestaan volgens de domeinwhitelist" }
```

This is because the CORS settings are not configured. We should decide how we want these to be configured for the docker compose.

**Comment by sergei-maertens** [comment]
easiest is to use envvar for `CORS_ORIGIN_ALLOW_ALL=yes`
