### ISSUE TITLE
The appointment form flow is broken

### ISSUE THREAD

**Issue by sergei-maertens** [open-formulieren/open-forms#1374]
Taiga 419

After selecting a product, the locations are not loaded/displayed.

Additionally, there appear to be some CSP-related errors, but those are *not* the cause of the problem since disabling them doesn't fix it.

**Comment by sergei-maertens** [comment]
I managed to pin point this to CSP after all, in particular the usage of a different evaluator:

```js
Formio.use(ProtectedEval);
```
This is messing with the templates that are used in the query string(s) used to fetch the related data.

**Comment by sergei-maertens** [comment]
Couple more findings while debugging this. I set a breakpoint on `Formio.Components.Select.loadItems` where it's calling `makeRequest`.

On initial page load, this happens:

1. Call to `/api/v12/appointments/products` is made
2. Call to `/api/v12/appointments/locations?product_id=undefined` is made
3. Call to `/api/v12/appointments/dates?product_id=undefined&location_id=undefined` is made
4. Call to `/api/v12/appointments/times?product_id=undefined&location_id=undefined&date=` is made

note that this happens twice because of how Formio initializes, and is normal behaviour.

With the `ProtectedEval` disabled, after you select a product, we see a call made in the form of:

`/api/v12/appointments/locations?product_id=37` - the `{{ row.product }}` bit is evaluated, and now an ID is available. We also see this XHR call being made in the dev tools & runserver logs.

However, if you enable `ProtectedEval`, the actual template evaluation seems to be wrong, resulting in the URL `/api/v12/appointments/locations?product_id=undefined`. This call is NOT observed in the XHR calls (dev tools) nor runserver logs, most likely because the results for a GET call are cached in Formio, and it remembers the empty result set.

The root cause seems to be the bad evaluation of the template bit of the URL with the fresh data:

```js
const query = `product_id={{ row.${productComponentKey}.identifier || row.${productComponentKey} }}`;
```

**Comment by joeribekker** [comment]
Ewwwww
