### ISSUE TITLE
KvK prefill assumes that a certain type of company is returned, but not all companies return the same information

### ISSUE THREAD

**Issue by SilviaAmAm** [open-formulieren/open-forms#1399]
Taiga issue 384

We need to add more fields, like "naam", "statutaireNaam" that are in the API of the KvK. Currently, "eersteHandelsnaam" is a relic/custom logic to get the first entry from the array field "handelsnamen". While at it, we can add "Eigenaar" properties.

**Comment by joeribekker** [comment]
I'm rewording this ticket to the actual issue :)
