### ISSUE TITLE
Searching via the FormIO smart pulldown only returns 4 items

### ISSUE THREAD

**Issue by joeribekker** [open-formulieren/open-forms#1416]
This happens at least with the KvK prefill, when searching for "embedded" for example. It returns only a subset of all hits (or entries that should hit)

**Comment by sergei-maertens** [comment]
Possibly related: formio/formio.js#4378

Fairly certain the fix is https://github.com/formio/formio.js/commit/2e3a9fe2f5e1c93495b949b2866ca14f45ad0929, which requires to update to Formio 4.14+ (we are now on 4.13.x).

**Comment by joeribekker** [comment]
![image](https://user-images.githubusercontent.com/96970/224672532-cf932b48-857c-4965-8cdc-94b3de5996e8.png)

![image](https://user-images.githubusercontent.com/96970/224672604-f3298775-ec52-42e0-9965-339aeefbde7e.png)

**Comment by sergei-maertens** [comment]
Fixed in the new builder (still experimental)
