### ISSUE TITLE
Separate form from admin sessions

### ISSUE THREAD

**Issue by joeribekker** [open-formulieren/open-forms#1441]
Testing with demo plugins is really annoying atm.

You need to be logged in as admin to use demo plugins. But, specifically with prefill, you need to logout to reset your session. This however, also logs you out as admin...

## Spec added after refinement

**Current mechanisms clarification and context**

* There is only one Django session, backed by the session cookie. This session used to track both admin user authentication (`request.user`) and end-users without Django user who are filling out forms.
* We have a middleware that sets the session expiry based on the type of user (admin user or anon): https://github.com/open-formulieren/open-forms/blob/master/src/openforms/middleware.py#L29
* "Form sessions" are tracked by storing the IDs of started submissions in the django session, see https://github.com/open-formulieren/open-forms/blob/master/src/openforms/submissions/utils.py#L42. This allows users to have multiple submissions for the same or different forms in their session, allowing them to use multiple tabs. The frontend currently restricts this to one "form session" per form ID, i.e. you can fill out multiple different forms at the same time in different browser tabs/windows using the same Django session cookie. This is because the form ID is mapped to the submission ID in the local storage so that hard refreshes don't break the user experience.
* On logout, all authentication plugin session data must be destroyed. Every plugin can have [their own isolated/dedicated session key](https://github.com/open-formulieren/open-forms/blob/master/src/openforms/authentication/contrib/digid/plugin.py#L71) which is converted in the generic `FORM_AUTH_SESSION_KEY`, which in turn [is recorded on the `Submission` instance](https://github.com/open-formulieren/open-forms/blob/master/src/openforms/authentication/signals.py#L41). This is now performed by deleting the entire session, which also destroys the "admin session", i.e. you are logged out from the admin as staff user.

**Changes to make**

* [x] Scope the SDK/UI "form session" logout 
    - Currently, this does a `DELETE /api/v1/authentication/session` which destroys the entire session
    - [x] Add and call the endpoint for "form session" management: ``DELETE /api/v1/authentication/:uuid/session` with `uuid` the UUID of the submission.
    - [x] On succesful call, [remove the submission ID from the session](https://github.com/open-formulieren/open-forms/blob/master/src/openforms/submissions/utils.py#L49) and
    - [x] Make sure to implement the auth clean up
        - Delete the `FORM_AUTH_SESSION_KEY` from the session (it has been recorded in started submissions already anyway), see https://github.com/open-formulieren/open-forms/blob/master/src/openforms/authentication/signals.py#L68
        - Call plugin-specific logout cleanup, see https://github.com/open-formulieren/open-forms/blob/master/src/openforms/authentication/api/views.py#L60
        - Call submission auth cleanup, see https://github.com/open-formulieren/open-forms/blob/master/src/openforms/authentication/api/views.py#L57
* [x] Check all plugins for plugin-specific cleanup and implement it in the `logout` method
    - See https://github.com/open-formulieren/open-forms/blob/master/src/openforms/authentication/base.py#L68
    - This should at the least remove any session keys used exclusively by the plugin (DigiD, eHerkenning)
* [x] Deprecate the `/api/v1/authentication/session` endpoint, this will be removed in API version 2.0.0. OpenAPI 3 / drf-spectacular has constructions for this.
* [x] Document the [version requirements](https://open-forms.readthedocs.io/en/latest/developers/versioning.html#open-forms-sdk) - SDK 1.1 will require API version 1.1+

This allows us to implement the required changes without introducing breaking API changes:

* We add a new API endpoint (submission-specific)
* We swap the SDK over to use the new API endpoint

In the end, this means the `request.session` will no longer be flushed on "form session" logout, yet the reference to the submission will be gone in the session causing the SDK to start a new form submission.

**Comment by sergei-maertens** [comment]
Not technically simple, because the form session is what is used to check the admin logged in status for demo plugins. And afaik Django does not support _multiple_ session cookies and this is not something we'd "want to roll our own" for (too big of a security risk and maintenance burden).

**Comment by joeribekker** [comment]
Alright, I'm open to alternatives to remedy this annoyance.

* Can we destroy some key within the session without destroying the whole session? I mean, your form session can currently expire without your admin session.
* Can we clear the form session when you start a form that uses a demo plugin?

**Comment by sergei-maertens** [comment]
In terms of cleaning the session auth (so the BSN in case of DigiD login), we have a signal already that we tap into at the end of the submission: https://github.com/open-formulieren/open-forms/blob/master/src/openforms/authentication/signals.py#L67

Steven also added a small and mostly unused feature now to do logout at the plugin level: https://github.com/open-formulieren/open-forms/blob/master/src/openforms/authentication/base.py#L68 which allows for plugin-specific cleanup.

There is no such thing as "the form session". We store the UUIDs of the active submissions in the session, and on submission completion, the submission ID is removed from that session key. On logout we could delete that key completely, which logs you out from any form "sessions". We could also include the submission ID on the logout call and only remove that particular form session from the django session.

So I see a number of possibilities to handle this, it just has to be very clear what the Logius requirements are so we don't accidentally break that.

**Comment by sergei-maertens** [comment]
Specced out, see the edited description
