### ISSUE TITLE
File upload component displays error JSON from backend instead of message

### ISSUE THREAD

**Issue by Bartvaderkin** [open-formulieren/open-forms#1453]
Taiga DH 11

Formio dumps the whole response in the message: https://github.com/formio/formio.js/blob/280ba15cffd64f5936a7a2cccd45322ac81b92e8/src/components/file/File.js#L765

**Comment by Bartvaderkin** [comment]
I marked it as needs-backport but I'm not sure.

**Comment by joeribekker** [comment]
@sergei-maertens gaf aan dat dit naar een app moet, met een api/v1/formio/fileupload
