### ISSUE TITLE
Don't use "None" for anonymous users in timeline logging

### ISSUE THREAD

**Issue by joeribekker** [open-formulieren/open-forms#1467]
![image](https://user-images.githubusercontent.com/96970/160230792-b2d5eff2-70f7-49d0-b574-900004ad2139.png)

**Comment by Bartvaderkin** [comment]
This should be impossible:

The template uses `log.fmt_user`: https://github.com/open-formulieren/open-forms/blob/a47cb9e3f89300b611e56ce221a846a17c268917/src/openforms/logging/templates/logging/events/submission_start.txt#L2

Which shouldn't be able to output 'None': https://github.com/open-formulieren/open-forms/blob/a47cb9e3f89300b611e56ce221a846a17c268917/src/openforms/logging/models.py#L58-L67

Looking into what is going on.
