### ISSUE TITLE
Not applicable step still sent to backend

### ISSUE THREAD

**Issue by SilviaAmAm** [open-formulieren/open-forms#1480]
How to reproduce:

1. Make a form with 2 steps:
   - Step 1: Radio component with values `a` and `b`
   - Step 2: A text component
2. Add a logic rule: if radio component in step 1 has value `a`, mark step 2 as not applicable.
3.  Save form

Go to the SDK for the form:

1. Select `b` for the radio component and go to step 2.
2. Fill in some value for the textfield. Click on `next` to go to the summary page.
3. Now go back to step 1 and select `a`. Click on next.
4. From the summary page submit the form
5. Check the submission pdf => it contains the data from step 2

**Comment by joeribekker** [comment]
Please check of this still happens on master branch.

**Comment by Bartvaderkin** [comment]
I confirm this repro still happens in master/main. 

Also if you choose, B, enter text in the step 2, then on the summary go back and choose A, skip step 2 as expected, then on summary go back and choose B again it will skip past step 2 while keeping your entry from step 2 in the summary. (eg: if step 2 did depend on step 1 somehow (technically or logically for the user) you'd miss that).

Also the logic can break if you reload the page while filling in the form. Sometimes it keeps part of the data and you can end up at step 2 while it is marked as NVT in the sidebar.

**Comment by sergei-maertens** [comment]
I'm changing the implementation so that when a step data is submitted, any steps following are reset if they turn out to be not applicable. Patch is working locally:

```
(open-forms) ➜  open-forms git:(feature/1480-not-applicable-step-sent-to-backend) ✗ LOG_LEVEL=CRITICAL m render_report 572 

Submission 572 - Development
    Stap 1
        -----  -
        Radio  A
        -----  -
```
