### ISSUE TITLE
Dark mode is not legible

### ISSUE THREAD

**Issue by SilviaAmAm** [open-formulieren/open-forms#1483]
The dark mode in the Admin (especially the page with the form builder) do not look good in dark mode.

- [x] Get designs of how the dark mode should look in the admin
- [x] Implement by overwriting https://github.com/django/django/blob/stable/3.2.x/django/contrib/admin/static/admin/css/base.css#L60

**Comment by sergei-maertens** [comment]
@joeribekker can you sort out designs for how dark mode should look like? Maybe also check how the default django admin looks in dark mode and go from there?

**Comment by joeribekker** [comment]
@sergei-maertens Can you guys sort this out yourselves? I mean, it's basically a colorset right?

**Comment by sergei-maertens** [comment]
For reference, the standard admin styling in dark mode

![image](https://user-images.githubusercontent.com/5518550/161011274-486f6573-7709-4312-bf14-5192015b5939.png)
