### ISSUE TITLE
Multiple file uploads are not attached to the email (email registration plugin)

### ISSUE THREAD

**Issue by joeribekker** [open-formulieren/open-forms#1492]
Taiga deelnemende gemeenten 448

**Comment by Bartvaderkin** [comment]
I tried reproducing this with two single file components and I did see the files being attached.

I yet have to try with a multiple=True component, but this is blocked by #1538

**Comment by sergei-maertens** [comment]
What's the source of this issue? Taiga? Can we get back to the original reporter?

**Comment by joeribekker** [comment]
@sergei-maertens opgenomen in de  beschrijving.

**Comment by joeribekker** [comment]
Ik haal invalid-label er af omdat het 22 april nog bevestigd is dat het niet goed gaat.

**Comment by sergei-maertens** [comment]
Could reproduce this in the test environment, it looks like the `SubmissionFileAttachment` records aren't being created, which causes them not to be added to the e-mail either.

Now let's see if I can reproduce this in a dev environment.

**Comment by sergei-maertens** [comment]
Relates to #1310 as well
