### ISSUE TITLE
Multiple logic rules on the same component seem not to work?

### ISSUE THREAD

**Issue by joeribekker** [open-formulieren/open-forms#1494]
Taiga 442

I'm not sure what the exact conditions are, but there are (at least) 2 rules on the same component: `if X = A then ...`, and `if X = B then ...`. The last rule seems to be ignored.

**Comment by Bartvaderkin** [comment]
I have a minimal repro if I use a radio button with two values, and one logic rule triggered on one of the values to run two actions: block the next step and toggle a hidden html-content block to visible.

**Comment by Bartvaderkin** [comment]
I added a export with my repro form to the Taiga ticket 442
