### ISSUE TITLE
Add the "hidden" option to co-sign component

### ISSUE THREAD

**Issue by sergei-maertens** [open-formulieren/open-forms#1508]
### Thema / Theme

Form designer

### Omschrijving / Description

It's currently possible to hide the co-sign component through logic, but not to initially hide it and later display it.

Adding the "hidden" form designer option solves this.

--

Als formulierbouwer
Wil ik het component voor mede-ondertekenen eerst kunnen verbergen om het door middel van logica te kunnen tonen.
Zodat het component pas getoond wordt op het moment dat het ook nodig is.

Case: Het is momenteel mogelijk om het component voor mede-ondertekenen te verbergen door middel van logica, maar niet om het eerst te verbergen en later weer te geven. Het toevoegen van de "verborgen" optie in de formulier editor lost dit op.

### Added value / Toegevoegde waarde

Better user experience because the page/form is smaller initially and there are no weird flashes of components that are suddenly hidden.

### Aanvullende opmerkingen / Additional context

Originated from the DMN Hackathon

Related: PF-67

**Comment by hlmr-erik** [comment]
This is an issue we're encountering at Haarlemmermeer as well. Additionally, it would be nice if the conditions of showing the field could be set in the form-editor, as with most other fields.

![image](https://user-images.githubusercontent.com/111565013/185609200-f096ccb6-7a68-480e-9390-a9c16c8165dd.png)

**Comment by sergei-maertens** [comment]
Double checked and the new co-sign already had the option set.
