### ISSUE TITLE
Data of previously filled fields that become hidden is still present in the summary

### ISSUE THREAD

**Issue by SilviaAmAm** [open-formulieren/open-forms#1527]
### Product versie / Product version

1.0/1.1

### Omschrijf het probleem / Describe the bug

Taiga DH 27

If there is a form with logic that changes fields from hidden/visible, if the user enters data in one of these fields and then changes another field so that the previous field becomes hidden, the data is still kept in the submission and shown in the summary.

### Stappen om te reproduceren / Steps to reproduce

Minimal form:
1. Make a form with a radio button with values `a` and `b`. Add 2 text fields with key `fieldA` and `fieldB`. Both text fields are hidden.
2. Add 2 logic rules: if value of radiobutton is `a`, make `fieldA` visible. If value of radiobutton is `b`, make `fieldB` visible.

User:
1. Select radio button option `a`. 
2. Fill `fieldA` with some data
3. Now change radio button to `b`.
4. Fill `fieldB` with some data
5. Go to summary

Hier both fieldA and fieldB are shown with the data entered

### Verwacht gedrag / Expected behavior

Only the data of visible fields should be shown.

**Comment by sergei-maertens** [comment]
Fixed via https://github.com/open-formulieren/open-forms-sdk/commit/6d3d60a8161a668a859731b9afccf21a8cd380fb

**Comment by sergei-maertens** [comment]
Oh, i see that #1527 is still open
