### ISSUE TITLE
Submitting a form redirects user to start of form (if autologin is enabled)

### ISSUE THREAD

**Issue by stevenbal** [open-formulieren/open-forms#1533]
### Product versie / Product version

main

### Omschrijf het probleem / Describe the bug

When submitting a form that has an "Authenticatie automatische login" selected, the user is automatically redirected back to the start of the form, instead of being redirected to the page with the PDF download link.

![NI4YYM85zo](https://user-images.githubusercontent.com/29249171/165248345-ee218320-76dc-44a4-81c8-82d8691cc09a.gif)

### Stappen om te reproduceren / Steps to reproduce

1. Create a form with an authentication backend and select that authentication backend as "Authenticatie automatische login"
2. Fill in the form and press submit
3. Observe how you are redirected to the start of the form

### Verwacht gedrag / Expected behavior

The form should redirect you to the successful submission page, with the download link for the submission PDF

### Screen resolution

1920 x 1080

### Browser

Desktop

### OS

Linux

### Browser

Firefox

**Comment by stevenbal** [comment]
I added an example form, it seems that the user is now redirected to login on every formstep
[issue-1533.zip](https://github.com/open-formulieren/open-forms/files/8561138/issue-1533.zip)

**Comment by sergei-maertens** [comment]
This cannot possibly be a bug in 1.0.6, as this is a feature scheduled for the 1.1.0 release. So I've changed the version to `main`.
