### ISSUE TITLE
SDK File upload widget doesn't send DELETE request when removing

### ISSUE THREAD

**Issue by Bartvaderkin** [open-formulieren/open-forms#1539]
### Product versie / Product version

1.0.x

### Omschrijf het probleem / Describe the bug

After uploading a file in the file component the widget shows the filename with a red cross :x: to remove the file. This should send a DELETE request to the API and then remove the file from the internal data and UI.

But when I try this I don't see the DELETE in my browsers network tab anymore.

### Stappen om te reproduceren / Steps to reproduce

1. Create a form with a file upload and open it.
2. Open your network developer tab
3. Upload a file
4. Click the red cross to remove it

Or try this form: https://open-forms.test.maykin.opengem.nl/bart-test-upload2/

### Verwacht gedrag / Expected behavior

I expected the SDK to send the DELETE request (and not have regressed).

### Screen resolution

1920 x 1080

### Browser

Desktop

### OS

Linux

### Browser

Firefox

**Comment by Bartvaderkin** [comment]
After some logging it seems like at this point the `formio` variable is falsy and the call is not made: https://github.com/formio/formio.js/blob/f8d1eeeb67d10dd20574626c6e94608c24fdfa3c/src/components/file/File.js#L295 

I can't determine if this used this code path before, or it went through the `fileService`.

I also went back to the `1.0.0` tag in the SDK repo and the issue still occurs.

**Comment by sergei-maertens** [comment]
we did implement this endpoint for some reason though :thinking: 

Can we check if this did work in the oldest release candidate?

**Comment by Bartvaderkin** [comment]
I bisected this to last know working: https://github.com/open-formulieren/open-forms-sdk/commit/0ee24c67808773e85362632a47d6efc6539b2ba2

This change a few commits on the same development branch no longer works: https://github.com/open-formulieren/open-forms-sdk/commit/77e99358a625a9f242f09aa6368a8b7b2c816e88

I noticed it goes through this code path (eg there is a `formio` value): https://github.com/formio/formio.js/blob/f8d1eeeb67d10dd20574626c6e94608c24fdfa3c/src/components/file/File.js#L296

**Comment by Bartvaderkin** [comment]
I tried using the original src/formio/components/FileField.js code from the working version but that doesn't work: it seems like the components get initialized differently?

**Comment by sergei-maertens** [comment]
this *might* have something to do with the `url` option being passed down into the Formio options? not sure though

**Comment by Bartvaderkin** [comment]
I tried reverting and messing with the changes but they don't solve the issue. It feels like something outside the component changes the way this works.

**Comment by sergei-maertens** [comment]
Passing that `url` prop caused `formiojs/WebForm.setUrl` to be called with that URL, in turn causing `this.options.formio` to be instantiated with a separate Formio instance. I'm suspecting that's what did it.
