### ISSUE TITLE
Prefill fields in a column field not working

### ISSUE THREAD

**Issue by rbakels** [open-formulieren/open-forms#1560]
### Product versie / Product version

1.0.5

### Omschrijf het probleem / Describe the bug

When a field is contained in a column (markup) field, then the prefill logic is not triggered. 

I'm working on a custom prefill plugin and the get_prefill_values() method is not triggered when the field is contained in a column field. When the field is within a fieldset or just added to the canvas at a position, it is working properly. 

### Stappen om te reproduceren / Steps to reproduce

1. Add a column (50-50) to a form 
2. Add a field to the column and add a prefill option
3. Do the same for the right column
4. Open the form and notice the data isn't rendered.

### Verwacht gedrag / Expected behavior

The prefill logic is executed for fields contained in a column.

### Screen resolution

bigger

### Browser

Desktop

### OS

MacOS

### Browser

Safari

**Comment by rbakels** [comment]
I try to work on a patch myself (I'm not a Python coder though). I'll let you know if I have some update.

**Comment by sergei-maertens** [comment]
Thanks for the report, from the description I can already guess where it's going wrong. Nice catch :)
