### ISSUE TITLE
Clean up old workaround code

### ISSUE THREAD

**Issue by sergei-maertens** [open-formulieren/open-forms#1574]
This middleware should not be needed anymore now we're on Django 3.2

https://github.com/open-formulieren/open-forms/blob/eb7d7f46f5b8ff810eb8c226ba7af0195046d83f/src/openforms/middleware.py#L7

**Comment by Bartvaderkin** [comment]
I made the change in a PR, but I'm not 100% sure if the Django 3.x behavior is the same as this middleware. Looking at their code it doesn't do the Origin-header check. Additionally I had to set `SESSION_COOKIE_SAMESITE = "Lax"` in my `local.py` to get a samesite value.
