### ISSUE TITLE
Calendar shows incorrect on Safari on iPad

### ISSUE THREAD

**Issue by joeribekker** [open-formulieren/open-forms#1575]
### Product versie / Product version

1.0.6

### Omschrijf het probleem / Describe the bug

De kalender van het datumveld springt weg in Safari op de I-pad.

Taiga Vught

### Stappen om te reproduceren / Steps to reproduce

1. Add calendar field to form
2. Go to form in iPad in Safari

### Verwacht gedrag / Expected behavior

Shows correctly

### Screen resolution

unknown

### Browser

Tablet

### OS

iOS

### Browser

Safari

**Comment by Bartvaderkin** [comment]
Ik heb dit geprobeert te reproduceren, zowel in losse test als in het gelinkte formulier uit de Taiga Vught issue 13 maar dan lijkt alles goed te werken. Zie de schermfoto in de Taiga bijlages.

**Comment by Bartvaderkin** [comment]
De melder in Taiga bevestigd dat zij dit probleem ook niet meer zien, dus ik sluit deze ticket.
