### ISSUE TITLE
Allow the use of variables in the registration backends

### ISSUE THREAD

**Issue by joeribekker** [open-formulieren/open-forms#1579]
Addition to #1325 

With the introduction of variables, it would be nice to let the registration backend have access to these variables.

One of the nice things here is that we don't have to put everything in a form. For example, an internal BAG-id for a location can currently only be given to a registration backend if we add a hidden field to the form that is prefilled with a BAG-id. With variables, we simply let the variable be prefilled and never communicate this to the form - but instead attach the variable to a ZGW-API or StUF-ZDS field.

How this works exactly, it up for more discussion but as a start:

**StUF-ZDS**
- [x] Allow a variable to be added as ExtraElement or set it on any StUF-ZDS field #3238 

**ZGW-API**
- [x] Allow a variable to be added as Eigenschap or set it on any ZGW API field

**Objects API**
- [x] Allow a variable to be used a field-value of the matching Objecttype

**Email** - #2040
- [x] Allow a variable to be included in the email content or subject.
- [x] Allow variables to be included in the attachment.

**Camunda**
- [ ] Refactor the camunda process variable approach to make use of the form variables.

etc.

**Comment by joeribekker** [comment]
Refinement: Sergei doesn't want to half-ass this. This needs top-down approach where variables are mapped more generically.

**Comment by SilviaAmAm** [comment]
Den Haag also mentioned that they would like to use user-defined variables to 'structure the JSON' that they send to the registration backend (product aanvraag).

**Comment by joeribekker** [comment]
@SilviaAmAm mentioned or gave it prio? :)

**Comment by SilviaAmAm** [comment]
I don't think so!

**Comment by SilviaAmAm** [comment]
Additional info from DH:
- They would like to be able to configure which user defined variables will be sent to the registration backend.

**Comment by joeribekker** [comment]
Refinement: We decided to simply pass all user-defined variables to all registration backends
There will be another issue to make these variables excluded from the registration.

**Comment by Viicos** [comment]
Closing as implemented.
