### ISSUE TITLE
Use the original filename when downloading submission attachments

### ISSUE THREAD

**Issue by joeribekker** [open-formulieren/open-forms#1584]
### Thema / Theme

Admin

### Omschrijving / Description

Currently, when downloading attachments from a submission the filename is "download". Can we name this according to the actual file name?

Taiga Vught 14

### Added value / Toegevoegde waarde

Saves alot of manual renaming work

**Comment by Bartvaderkin** [comment]
Note this report seems to be about the download links in the registration email (when file attachment are disabled)
