### ISSUE TITLE
E-mail confirmation shows step titles even if no fields are shown

### ISSUE THREAD

**Issue by joeribekker** [open-formulieren/open-forms#1591]
### Product versie / Product version

master

### Omschrijf het probleem / Describe the bug

Just checked with Sergei. The PDF template contains an if-statement (`if node.haschildren` or something) but this if statement is missing from the mail summary template. Hence, in the mail shows step names even if there are no fields.

**Comment by Bartvaderkin** [comment]
Fun fact: this also happened in the email-registration backend template.
