### ISSUE TITLE
Expand test form

### ISSUE THREAD

**Issue by joeribekker** [open-formulieren/open-forms#1596]
Expand the test form with:

~~1. At least one logic related field~~
~~2. Upload field with a description saying to upload a file of 50MB~~
~~3. Upload in optional field~~
~~4. DigiD~~
~~5. Co-signing (waiting on #2716)~~
6. Repeating group

**Comment by sergei-maertens** [comment]
@LaurensBurger do you have a status update of this ticket?

**Comment by joeribekker** [comment]
Refinement: We need either a proper test procedure and/or automated tests like the forms in this ticket, to see if everything works. Whether this should be part of the CI is still up for debate. Also, if manually testing needs to be done, it needs to be clear which forms are part of this test.

Also, the examples might be good to include in automated tests.
