### ISSUE TITLE
Access to fonts is blocked by CORS policy

### ISSUE THREAD

**Issue by vaszig** [open-formulieren/open-forms#1615]
### Product versie / Product version

latest

### Omschrijf het probleem / Describe the bug

When embedding the SDK in a page, access to specific font resources is not allowed. 

"Access to font at ... has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource."

### Stappen om te reproduceren / Steps to reproduce

Embed the form in a cross domain context

### Verwacht gedrag / Expected behavior

Fonts should load

### Browser

Chrome, Firefox

**Comment by sergei-maertens** [comment]
We need to solve this at the uwsgi `--static-map` level or nginx level.
