### ISSUE TITLE
Enable text colors in content component editor widget

### ISSUE THREAD

**Issue by Bartvaderkin** [open-formulieren/open-forms#1620]
### Thema / Theme

Form designer

### Omschrijving / Description

Form creators want to be able to set text colors in the content component.

Currently this is disabled in the CK Editor options.

User also noted they expected to have unspecified other customization issues so maybe explore the available options to index if there is something useful.

via Taiga DH 37

- [x] Enable `fontColor` CKEditor option
- [x] Decide what to do with the presets (see below)

### Added value / Toegevoegde waarde

Request from Taiga

**Comment by Bartvaderkin** [comment]
The editor for the formio content-component is CKEditor, it has a fontColor plugin we can enable but the UI is a palette with predefined presets.

The defaults are limited but it allows to define our own preset colors as part of the CKEditor settings, but note the user can't add new colors.

Via: https://ckeditor.com/docs/ckeditor5/latest/features/font.html#configuring-the-font-color-and-font-background-color-features

The default looks like this:

![ckeditor-color-options](https://user-images.githubusercontent.com/54805673/168814777-3d3e8718-0985-468c-9858-9ea0ba0bd88b.png)

**Comment by sergei-maertens** [comment]
Should we consider switching Formio WYSIWYG to use TinyMCE? that would make the experience more consistent across the entire project, as we use TinyMCE already in our own django stuff.

**Comment by Bartvaderkin** [comment]
Discussed and we're going to add a admin configurable set of colors and pass it to the form builder through the admin template and some document.getXYZ().  (json_script tempalte tag + jsonScriptToVar JS functie)
