### ISSUE TITLE
List of prefill attributes doesn't refresh after switching plugin

### ISSUE THREAD

**Issue by Bartvaderkin** [open-formulieren/open-forms#1624]
### Product versie / Product version

1.0.x development (38f4a74c)

### Omschrijf het probleem / Describe the bug

When configuring prefill on a field the widget with attributes doesn't refresh after switching plugin in the widget above.

Via Taiga DH 52

### Stappen om te reproduceren / Steps to reproduce

1. Create or edit a form
2. Add a text field
3. In the prefill tab select 'Haalcentraal' as plugin.
4. Note the list of attributes
5. Switch the plugin to a different plugin
6. Note the list of attributes doesn't change to reflect the new plugin

### Verwacht gedrag / Expected behavior

Expect the list of attributes to update.

### Screen resolution

1920 x 1080

### Device

Desktop

### OS

Linux

### Browser

Firefox

**Comment by sergei-maertens** [comment]
Will be included in 1.1.0
