### ISSUE TITLE
Mede-ondertekenen werkt niet indien DigiD Eenmalig Inloggen aan staat

### ISSUE THREAD

**Issue by joeribekker** [open-formulieren/open-forms#1641]
### Product versie / Product version

1.1.0 / 1.0.8

### Omschrijving / Description

Indien DigiD "Eenmalig Inloggen" inloggen aan staat, dan kan een andere gebruiker niet mede-ondertekenen. De ingelogde persoon op het formulier behoudt zijn sessie op `*.digid.nl` en is door het drukken op de knop "Mede-ondertekenen" direct zelf weer ingelogd, en kan dus niet een partner oid laten inloggen.

Gemarkeerd als "improvement" omdat in de handleiding staat dat Eenmalig Inloggen uit moet staan voor Open Formulieren.

### Stappen om te reproduceren / Steps to reproduce

1. Zorg dat DigiD "Eenmalig Inloggen" aan staat bij DigiD.
2. Login met DigiD op een formulier dat het mede-ondertekenen component heeft
3. Klik op mede-ondertekenen
4. Zonder je DigiD gegevens in te vullen, log je nu in met DigiD
5. Je eigen naam staat er als mede-ondertekenaar.

### Verwacht gedrag / Expected behavior

@SilviaAmAm komt met een voorstel

**Comment by sergei-maertens** [comment]
This is fixed via the co-sign rework in #1530
