### ISSUE TITLE
Repeating components in Forms

### ISSUE THREAD

**Issue by SilviaAmAm** [open-formulieren/open-forms#1710]
### Thema / Theme

Other

### Omschrijving / Description

DH Taiga 42

Body of the Taiga issue: 

In een formulier er is een veldengroep waar de gebruiker informatie over hun auto moet toevoegen: 

--Veldengroep auto-----  
Kenteken:  
Kleur: …  
Electrisch: …

Heb je nog een auto? 
ja /nee

---------------------------------

Als de gebruiker nog een auto heeft dan verschijnt hetzelfde veldengroep nog een keer.

Dit momenteel wordt gebouwd in openforms door de veldengroep te herhaalen voor het maximale aantal keren dat de gebruikers gegevens zou kunnen invullen (en daarna met logica die zichtbaar/verborgen te maken).

Dit is moeilijk te doen als de veldengroep veel keer moet worden herhaald.

=> This should be implemented using the variables:
There should be a variable keeping track of how many times a group should be repeated and then with a loop the field can be repeated the desired number of times in the configuration.

**Comment by SilviaAmAm** [comment]
I started playing around with this. Wat I tried/some comments/thoughts:

- Temporary number field to keep track of the number of components
- Add a new action type which is "repeat a component"
- The repeat action:
    - Copies a component
    - Changes its id to something random
    - Changes its key to something predictable (the key will be used in the data, so if the component has a random key, between check logic calls it will become disconnected from the data). But we need to make sure that the key is unique in the form.
    - Does the same to any child component
    - Appends the copy component under the original
- Find a way to deal with the variables for the copies. These will "correspond" to the same FormVariable, but they will have a different key. We currently have a unique together constraint for a SubmissionValueVariable on the submission and the form variable. Maybe we could have a new field "repeat" in submissionValueVariable with a FK to the repeating form variable and then when a form step is persisted we can create a submissionValueVariable for any item in the data that has a key "originalKey-copy-X" ?

**Comment by SilviaAmAm** [comment]
After discussion:
We should have a new "Repeat" component (based on the fieldset).
Its value will be a list, containing the value of the fields.

**Comment by SilviaAmAm** [comment]
Design details from Joeri:

![image](https://user-images.githubusercontent.com/19154114/178225600-48fe2dff-4a3d-4d22-8b95-ba7f65358b13.png)

**Comment by sergei-maertens** [comment]
Frontend PR needs to be reviewed still.

**Comment by SilviaAmAm** [comment]
PR Frontend reviewed: https://github.com/open-formulieren/open-forms-sdk/pull/215
