### ISSUE TITLE
Variables key / label need higher max_len

### ISSUE THREAD

**Issue by SilviaAmAm** [open-formulieren/open-forms#1713]
### Product versie / Product version

latest

### Omschrijf het probleem / Describe the bug

The labels / keys given to components are often very long. 

- [ ] Currently the max_len for variables label / key is 100 chars, which is not enough. This should be increased.
- [ ] We should probably have a check in the formio edit form that the label key don't exceed this length.
- [ ] Maybe we should have a management command to check if there are forms with too long keys / labels in the components before migrating to the version with variables?

**Comment by sergei-maertens** [comment]
Change the charfield into a `models.TextField` and your problem is solved :-) let's keep it simple
