### ISSUE TITLE
Huge logo's show huge in the PDF

### ISSUE THREAD

**Issue by joeribekker** [open-formulieren/open-forms#1715]
### Product versie / Product version

1.1.1

### Omschrijf het probleem / Describe the bug

Even though you can set height and width in the design token, the website applies implicit max-height since the logo is contained in a header element. The same max-height should be applied in the PDF to prevent this:

![image](https://user-images.githubusercontent.com/96970/175895118-82f6fa52-8679-4c01-900d-53da3c7945ba.png)

### Stappen om te reproduceren / Steps to reproduce

Upload a logo that is huge (I used a PNG).

### Verwacht gedrag / Expected behavior

The logo size is restrictred.

**Comment by sergei-maertens** [comment]
Things to watch out for:

* PDFs with a non-white header background color: there may not be a white band above the header
* PDFs with/without logo/header -> vertical spacing should remain consistent
