### ISSUE TITLE
Don't overrule the street and city name when the user changed the prefilled values

### ISSUE THREAD

**Issue by joeribekker** [open-formulieren/open-forms#1717]
### Thema / Theme

API

### Omschrijving / Description

If you make use of the prefill streetname and city values based on postal code and house number, the user can still override these.
However, our prefill plugin (i think cache mechanism?) overrides the values, even if the user changed them.

I think with the introduction of variables, this changes, so blocked until variables is done.

**Tasks**

* [x] Reproduce the issue in master with feature flag "variables" off (make form, test if this is indeed a problem)
* [x] Enable the feature flag and check again :)

Source: DH Taiga 106

**Comment by dariomory** [comment]
The issue persists under both circumstances. I will dive into the SDK repository and arrange a solution.

**Comment by dariomory** [comment]
@joeribekker Manually tested again with a new form as suggested. For me the bug still happens:

![image](https://user-images.githubusercontent.com/58147939/177169937-ce414be8-a8e9-484f-8210-b2ae98ab84ee.png)
![Peek 2022-07-04 16-00](https://user-images.githubusercontent.com/58147939/177170132-b52a7f4f-ed9e-4cdd-97b0-3c228ac722e5.gif)

**Comment by joeribekker** [comment]
Okay. Can you pinpoint the cause? Is it the API that returns empty stuff or something else?

**Comment by dariomory** [comment]
> Okay. Can you pinpoint the cause? Is it the API that returns empty stuff or something else?

The form is filling the address every time the field logic is processed.

Solution: https://github.com/open-formulieren/open-forms-sdk/pull/212. Fill the form only when there are any changes to the postal code or number.

PS. I suggest an extra small change to put the API request within the if check to avoid making unnecessary requests.

**Comment by joeribekker** [comment]
Decided: Only autofill when the targets (streetname/city) are empty OR the targets are read-only.
