### ISSUE TITLE
Improve analytics support

### ISSUE THREAD

**Issue by sergei-maertens** [open-formulieren/open-forms#1721]
Enabling an analytics implies more than just filling out the ID/domain in the global configuration page:

* The relevant CSP directives for this particular analytics provider need to be added
* Typically you want to configure/enable the list of cookies in the analytics cookiegroup (django-cookie-consent)

All of these can be configured by hand, but this is cumbersome for non-programmers.

So, ideally we tap into the events that enable/disable an analytics provider.

1. When an analytics provider is enabled:
    - Create the necessary records for the CSP, using `openforms.config.models.CSPSetting`
    - Create the necessary cookies with the relevant domain/path (model `cookie_consent.Cookie`, must belong to `config.GlobalConfiguration.analytics_cookie_consent_group`)
2. When an analytics provider is disabled, "uninstall" these configurations
3. Ensure that all of the above actions are logged in `timeline_logger.TimelineLog` model (using `openforms.logging`)
4. Remove https://github.com/open-formulieren/open-forms/blob/master/src/openforms/config/models.py#L506 as this should be handled via 1.

**Comment by joeribekker** [comment]
We're you not happy with my #1294 ?

**Comment by sergei-maertens** [comment]
Ah I looked but didn't find any recent new issues, didn't see it was an older issue!
