### ISSUE TITLE
Make error messages in form WCAG compliant

### ISSUE THREAD

**Issue by SilviaAmAm** [open-formulieren/open-forms#1738]
### Thema / Theme

Frontend

### Omschrijving / Description

DH Taiga 110

Situation:
- A user doesn't fill in any field in a form with multiple compulsory fields
- Clicks on submit step => All the required fields show an error message.
- As soon as the user fills in a field all the error messages disappear (from all the fields).

This is not WCAG compliant. When the user fills in a field, the errors on the other fields should remain until the user corrects the errors on those fields.

### Added value / Toegevoegde waarde

Better accessibility

**Comment by joeribekker** [comment]
Check how we deviate from FormIO because FormIO does it correctly, and we don't :(
