### ISSUE TITLE
Viewing submissions gives an error

### ISSUE THREAD

**Issue by joeribekker** [open-formulieren/open-forms#1750]
### Product versie / Product version

1.1.3

### Omschrijf het probleem / Describe the bug

In the admin, going to any submission returns a 500 (database) error. Note that this doesn't seem to happen on latest, so it's possible it's only in the 1.1.x branch due to some migration/earlier backport. Please fix this on the 1.1.x branch and write a test to check this admin view.

```
  File "django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "elasticapm/instrumentation/packages/dbapi2.py", line 210, in execute
    return self._trace_sql(self.__wrapped__.execute, sql, params)
  File "elasticapm/instrumentation/packages/dbapi2.py", line 245, in _trace_sql
    result = method(sql, params)
ProgrammingError: column submissions_submissionstep.data does not exist
LINE 1: ...id", "submissions_submissionstep"."form_step_id", "submissio...
                                                             ^
HINT:  Perhaps you meant to reference the column "submissions_submissionstep._data".
```

Sentry: 311981

**Comment by sergei-maertens** [comment]
We managed to trace this back to an (accidental) deploy of 1.2.0 alpha version and then a rollback to 1.1.3 - so this is not a problem in the code, rather in the deployment code.
