### ISSUE TITLE
Add logic condition based on logged in/login entity (person or company)

### ISSUE THREAD

**Issue by joeribekker** [open-formulieren/open-forms#1763]
### Thema / Theme

Admin

### Omschrijving / Description

Often you want yo create a form to be filled in by a person OR a company, with minor changes in steps to follow.

We therefore need a logic condition like: if **login as person** ... and if **login as company**
I explicitely **don't** want to say: If logged in via DigiD. The above should be read as "if bsn is known" and "if kvk-number is known" regardless of login method.

### Added value / Toegevoegde waarde

Easily allow showing/hiding fields/steps based on who logs in.

**Comment by SilviaAmAm** [comment]
@joeribekker I think this is a duplicate of https://github.com/open-formulieren/open-forms/issues/1661 ?

**Comment by SilviaAmAm** [comment]
Closing because it's a duplicate
