### ISSUE TITLE
Clicking the link to display forms affected by changing a reusable form definition crashes the form builder

### ISSUE THREAD

**Issue by sergei-maertens** [open-formulieren/open-forms#1790]
### Product versie / Product version

latest

### Omschrijf het probleem / Describe the bug

Clicking the link in the warning in the screenshot crashes the editor:

![image](https://user-images.githubusercontent.com/5518550/179025962-d6d3a27e-7dc2-4398-945e-c252bc93a2cb.png)

Error from dev console:

![image](https://user-images.githubusercontent.com/5518550/179025888-3fefb8a1-6d7e-45d0-8782-e3cbc24e18f1.png)

### Verwacht gedrag / Expected behavior

No crash

### Browser

Brave Version 1.44.112 Chromium: 106.0.5249.119 (Official Build) (64-bit)

**Comment by sergei-maertens** [comment]
Happens on our own test environment

**Comment by sergei-maertens** [comment]
Check if this still happens and fix.

**Comment by SilviaAmAm** [comment]
This doesn't seem to happen anymore:
![Screenshot from 2022-10-14 12-00-43](https://user-images.githubusercontent.com/19154114/195820190-8f92cc74-5383-4585-9faf-c3990fa5d0cb.png)
![Screenshot from 2022-10-14 12-00-48](https://user-images.githubusercontent.com/19154114/195820195-c6d934ae-f522-4d76-9e48-0d105ca0130a.png)

**Comment by sergei-maertens** [comment]
I'm still getting this behaviour on our own test environment, form "Aanvraagformulier Ooievaarspas 1", form step "Inleiding". Using Brave (Chromium derivative)

**Comment by sergei-maertens** [comment]
I can only reproduce the crash with a production build
