### ISSUE TITLE
Tools om feedback te kunnen geven, waaronder minimaal GovMetric en Siteimprove, kunnen zonder tussenkomst van ...

### ISSUE THREAD

**Issue by joeribekker** [open-formulieren/open-forms#180]
...de leverancier door de gebruiker van de toepassing eenvoudig worden toegevoegd en geactiveerd.

Eis: Algemeen 6.
Zie ook NvI: 133

**Input van gemeente nodig**

- [ ] Relevante GovMetric documentatie
- [x] ~Relevante SiteImprove modules/documentatie~ Werkt reeds, getest met RSD.

**Verduidelijking**

[Feedbacktool Siteimprove.docx](https://github.com/open-formulieren/open-forms/files/6883694/Feedbacktool.Siteimprove.docx)
+ https://www.drupal.org/project/siteimprove

https://help.siteimprove.com/support/solutions/articles/80000448448-adding-siteimprove-analytics-javascript-to-your-website

**Actie van Gemeenten**

Documentatie nodig van GovMetric

**Comment by joeribekker** [comment]
Hedda laat deze ook zien :)
@aguldie, even schakelen

**Comment by BasvanRensDK** [comment]
@joeribekker net contact gehad met Haarlemmermeer. Zij gebruiken de feedback optie van Siteimprove en zullen specs aanleveren. @NgiNGN levert deze aan.

**Comment by joeribekker** [comment]
@BasvanRensDK volgens mij heb ik hier geen feedback op gekregen. Als dat inderdaad zo is, dan kan ik dit ticket niet meer binnen scope van het PvE oppakken aangezien we de laatste sprint in gaan.

**Comment by BasvanRensDK** [comment]
@joeribekker dat begrijp ik. Ik wil voor de backlog eea voorbereiden. Ik zal contact opnemen met GovMetric, want we hebben wel de juiste informatie van hen nodig.

**Comment by joeribekker** [comment]
Dit is aangeleverd voor GovMetric van Klant In Focus.

[Handleiding GovMetric CX Websnippet installatie 220322.pdf](https://github.com/open-formulieren/open-forms/files/9125994/Handleiding.GovMetric.CX.Websnippet.installatie.220322.pdf)
[Gemeente LV - HTML Webform Inpage WS2 Snippet 220525.html.txt](https://github.com/open-formulieren/open-forms/files/9125995/Gemeente.LV.-.HTML.Webform.Inpage.WS2.Snippet.220525.html.txt)

**Comment by joeribekker** [comment]
Overleg gehad met KIF en zij worden de stakeholder. Eind augustus krijgen we een testomgeving.

**Comment by joeribekker** [comment]
Blocked: Waiting for KIA to reply.

**Comment by SilviaAmAm** [comment]
Frontend PR not yet merged
