### ISSUE TITLE
Fieldname change in business logic once fieldname is changed

### ISSUE THREAD

**Issue by RobertDorenbuschEns** [open-formulieren/open-forms#1806]
### Thema / Theme

Other

### Omschrijving / Description

When a fieldname is used in a logic rule and that fieldname is changed, the rule is not working anymore. (pointing to an empty field)
Request: once an existing fieldname is changed then check if this fieldname is used in logic rule and if so, change it accordingly.

### Added value / Toegevoegde waarde

Improvement of stability and integrity of existing forms once they are changed.

**Comment by sergei-maertens** [comment]
I believe this will be/is solved through the variables feature - @SilviaAmAm can you confirm?

**Comment by SilviaAmAm** [comment]
I thought that we had already fixed this: https://github.com/open-formulieren/open-forms/issues/1330 (see first point).
So I will need to double check what is happening.

**Comment by RobertDorenbuschEns** [comment]
I think #1330 is to Warn user if logic involves non existing component. This request is to prevent that this will happen.

**Comment by sergei-maertens** [comment]
@SilviaAmAm I thought I saw some code that updates the variable key if the component key changes? But that may still not cascade down to the logic rules, so that would be a useful improvement! :)

**Comment by SilviaAmAm** [comment]
@sergei-maertens yes indeed! That was part of the fix for that ticket: https://github.com/open-formulieren/open-forms/blob/master/src/openforms/js/components/admin/form_design/form-creation-form.js#L354
