### ISSUE TITLE
Using logic to refer to repeating groups breaks logic evaluation

### ISSUE THREAD

**Issue by SilviaAmAm** [open-formulieren/open-forms#1838]
### Product versie / Product version

latest

### Omschrijf het probleem / Describe the bug

When referring to repeating groups in the advanced logic, if we refer to a non-existing item, we break the logic evaluation

Form to reproduce error:
[voorbeeld-herhalende-groepen.zip](https://github.com/open-formulieren/open-forms/files/9261052/voorbeeld-herhalende-groepen.zip)

### Verwacht gedrag / Expected behavior

- Create a form
- Add a repeating field called `groups` with a textfield inside
- Add an advanced logic rule with trigger `{"!=": [{"var": "groups.2"}, None]}`

Start the form in the SDK, add a group, see the error

**Comment by SilviaAmAm** [comment]
Things to discuss:
- Do we want to solve this in json-logic-py by catching the error of the glom access
- Do we want to add a jsonLogic 'len' operator
- How do we want to handle logic for repeating groups (iterating over a particular field in the groups).

**Comment by SilviaAmAm** [comment]
DH gave an examples of calculations that they would like to be able to do:

Repeating group "salaries":
- Currency field

Logic:
- Sum all salaries together
- Sum the 3rd and 5th salary toghether

**Comment by joeribekker** [comment]
Blocked by variable ordering refactor, vagely related to #1708
