### ISSUE TITLE
Help text in repeating groups is too long

### ISSUE THREAD

**Issue by SilviaAmAm** [open-formulieren/open-forms#1839]
### Product versie / Product version

latest

### Omschrijf het probleem / Describe the bug

The helptext is too long and can't be seen all

![Screenshot from 2022-08-04 17-42-34](https://user-images.githubusercontent.com/19154114/182889596-bb4847f3-06b9-4c42-8ce0-c77ab7e360e2.png)

**Comment by joeribekker** [comment]
SOlution: Shorten the message. If another item is also too long, a new ticket can be opened.
