### ISSUE TITLE
Retrieve SAML metadata via URL on the backend

### ISSUE THREAD

**Issue by joeribekker** [open-formulieren/open-forms#1849]
### Thema / Theme

Admin

### Omschrijving / Description

Currently, the metadata needs to be generated as a file, stored, and sent to Logius/eHerkenning broker. Instead, since this information is not secret, we can generate this on the fly via a View on a specific URL. This way, updating the certificates would be all that is needed and we can just communicate the URL to logius/eherkenning when there is a change.

This can just be a URL on the backend.

To even further improve the devops overhead, we can manage the certificates with the certificate manager introduced in ZGW-consumers.

Many of these improvements need to be done in other libraries and then incorporate them into Open Forms.

* [x] Move the cert-manager from zgw-consumers to a standalone library: django-simple-certmanager (use https://github.com/maykinmedia/default-app)
* [x] Make sure zgw-consumers is updated so it no longer has the internal cert-manager, but uses the django-simple-certmanager instead (pay attention to data migrations here)
* [x] In the DigiD-library, convert the use of file-system based certificates to use the django-simple-certmanager
* [x] In the DigiD-library, convert the DigiD and e-Herkenning settings to database settings in a solo-model
* [x] In the DigiD-library, create a view/url-pattern that generates the metadata on the fly based on the above settings
* [ ] Make sure existing settings keep working, like the privacy url-setting.

### Added value / Toegevoegde waarde

Less overhead for creating and managing these metadata files.

**Remaining tasks**

- [x] Get changes in django-digid-eherkenning
    - [x] Use config model in run-time code instead of settings
    - [x] Use config model/utility for management command (management command options can override the config)
    - [x] Update docs (see comment Ewen)
- [ ] Hook up metadata generation endpoints
- [ ] Set up nginx rate limiting for metadata endpoints

**Comment by Ewen-Lgy** [comment]
Changes to operate on open-formulieren:
- Add `django-simple-certmanager` to libraries requirements
- Add `simple_certmanager` to INSTALLED_APPS
- Add the urls located in _digid_eherkenning.metadata_urls_ in _openforms.urls_
- update theses guidelines since commands for generating metadata are not used anymore :
	- https://github.com/maykinmedia/open-forms-deployment/blob/main/requesting_eherkenning.md
	- https://github.com/maykinmedia/open-forms-deployment/blob/main/requesting_digid.md
- Change certificate stuff imported via `zgw_consumers` to `simple_certmanager`
