### ISSUE TITLE
When employees are logged in to a form, registration backends should add them as being an employee

### ISSUE THREAD

**Issue by joeribekker** [open-formulieren/open-forms#1862]
Followup on #1861

When employees login on behalf of a resident, a submission should typically have 2 persons attached to it:

1. The employee (employee number)
2. The person (bsn) or company (kvk) it involves

However, this is NOT a requirement since an employee can also fill in an internal form that is only used by employees and not meant for residents. So, we could also only have the employee number.

We need to modify the registration backend plugins

# Technical approach

Two aspects are relevant in this flow:

* We require "authentication details" to be able to prefill/register the correct
  attributes of the subject of the form
* We want third parties to be able to initiate/complete a form on behalf of a subject
  AND keep track of this fact.

## Constraints

* `Submission.auth_info` (reverse one-to-one of `AuthInfo.submission`) is the foundation
  for prefill/registration and not easily refactored (again)

* `AuthInfo` _does_ contain all the fields we'd need to keep track of the third party
  (called "registrator" from now on)

## Data model changes

* [x] Create abstract base model `BaseAuthInfo` from current model `AuthInfo` (except for the `submission` `OneToOneField`)
* [x] Derive `AuthInfo` from `BaseAuthInfo` (with the `submission` field) - this keeps the existing machinery intact
* [x] Add model `RegistratorInfo` derived from `BaseAuthInfo`, with an additional `submission` `OneToOneField`. Use the `_registrator` related name.
* [x] Define `Submission.registrator` as `Submission._registrator or Submission.auth_info`, meaning that if no explicit Registrator` is provided, the usual auth details is used for this purpose.

## Employee login flow

Currently, the employee logs in using OIDC by:

1. Click button -> redirected to Open Forms backend
2. Open Forms backend redirects to identity provider (IDP)
3. Employee logs in with IDP (if no active session exists)
4. Employee is redirected back to Open Forms backend
5. Open Forms backend creates/updates Django user + logs this user in. Employee details
   are stored in session.
6. Open Forms backend redirects back to form
7. SDK creates submission
8. Backend fires `submission_start` signal
9. Backend creates `AuthInfo` with employee details from the session and relates it to
   the submission.

This flow needs to be modified so the employee can additionally specify which
person/company they are acting on behalf of:

* [x] Once the employee is redirected to the Open Forms backend (5.) after succesful
      authentication and login, display an intermediate screen (POST form)

      * Button to skip additional information (register this explicitly!)
      * Input field for BSN
      * Input field for KVK

      See mockup: 

      ![image](https://user-images.githubusercontent.com/5518550/196141424-d0f9cdfd-7680-402e-b2b9-fe7d61882f44.png)

      Store these details in `request.session` so they can be processed in the
      `submission_start` signal handler.

* In the `submission_start` signal handler:

    * [x] If KVK/BSN is given, store those details in the `AuthInfo` model and the employee
          details in the `Registrator` model.
    * [x] If continued without extra details, store the employee details in `AuthInfo`

* [x] After the inbetween screen, continue the usual redirect flow (from 6. onwards)

### ZGW APIs plugin

- [x] If no BSN/KVK was provided, initiator needs to be the proper
      `betrokkeneType: medewerker` with correct `betrokkeneIdentificatie` details
- [x] If BSN/KVK was provided, these still need to the the initiator (same behaviour as
      currently based on `submission.auth_info`)
- [x] Add an (optional) configuration option ("registrator roltype") for the `RolType`
      name. This shall be looked up for the specified zaaktype in the
      [`roltypen`](https://redocly.github.io/redoc/?url=https://raw.githubusercontent.com/VNG-Realisatie/catalogi-api/1.1.0/src/openapi.yaml#tag/roltypen/operation/roltype_list) API endpoint.
- [x] If BSN/KVK was provided and `registrator roltype` is configured, create an
      additional rol/betrokkene with the zaak with the employee details
      (`betrokkeneType: medewerker`)

The original initiator/mede-initiator description is NOT correct with the semantics of
Zaakgericht werken - a "behandelaar" acting on behalf of a client can never be the real
initiator (see [reference](https://vng-realisatie.github.io/StUF-Standaarden/discussie/gemma/stuf-301-zkn/zaak-met-meerdere-initiators.html)).

![image](https://user-images.githubusercontent.com/96970/184366809-7482c21d-e940-4130-8562-61f6bbd2e727.png)

### StUF-ZDS plugin

- [x] If no BSN/KVK was provided, initiator needs to be the proper
      entity type `StUF:entiteittype="MDW"`, see `creeerZaak.xml` inside the element
      `<ZKN:heeftAlsInitiator ... />`
- [x] If BSN/KVK was provided, these still need to the the initiator (same behaviour as
      currently based on `submission.auth_info`)
- [x] TODO: figure out how to register additional rol/betrokkene for medewerker

![image](https://user-images.githubusercontent.com/96970/184373165-6208d4af-b3c6-4b00-aeb1-4dd22688492b.png)

**Comment by Bartvaderkin** [comment]
Notes:

- [ ] I don't see a KvK-field in neither the builder nor the SDK.
- [ ] I'm not aware of functionality how an employee can login on behalf of a resident besides using these fields
