### ISSUE TITLE
Field value re-appears when pressing backspace

### ISSUE THREAD

**Issue by dariomory** [open-formulieren/open-forms#1868]
### Product versie / Product version

latest

### Omschrijf het probleem / Describe the bug

When writing a (correct) ZIP code into a postcode field and delete the last character, it reappears in the field automatically.

![Peek 2022-08-16 15-20](https://user-images.githubusercontent.com/58147939/184889858-67b383fd-01a3-4ef4-9676-bed79ea6802c.gif)

### Stappen om te reproduceren / Steps to reproduce

1. Create form with a Postcode field.
2. Start a submission for the form.
3. Enter a valid zipcode.
4. Submit the form step.
5. Go back to the previous step.
6. (Refresh may be needed).
7. Modify the existing zipcode.

### Verwacht gedrag / Expected behavior

The user should be able to change the field.

### Screen resolution

1920 x 1080

### Device

Desktop

### OS

Linux

### Browser

Chrome

**Comment by SilviaAmAm** [comment]
I notice that if I delete the last letter of the postcode (like in the gif above) but I wait before I click outside the postcode field, this behaves correctly: the 'ongeldige postcode' message is shown and no logic check is sent to the backend.
If I click out of the field straight away, then the check logic call happens even though there is an error on the postcode field
