### ISSUE TITLE
Improve date validation configuration

### ISSUE THREAD

**Issue by SilviaAmAm** [open-formulieren/open-forms#1878]
### Thema / Theme

Other

### Omschrijving / Description

DH taiga user story 117, issue 50
DH Taiga user story 168, issue 161

What they basically want is, in the Min/Max fields: {{ field1 }} + 14

Currently, the date field has 2 fields "max date" and "min date":
![datefields](https://user-images.githubusercontent.com/19154114/185418312-c28987e1-0078-426d-b625-493a514e0711.png)

It is not possible here to specify that a date should not be in the future or that it should be between today and in 2 weeks time. It is possible to do this in the logic tab, but this makes it difficult to maintain.

The possibilities of validation that DH would like are:
- Specific max/min date range (already present)
- Max/min date range + or - X number of days (?)
- In the future (including and excluding today)
- In the past (including and excluding today)
- Larger than the date in another field +/- X days
- Smaller than the date in another field +/- X days

**Comment by sergei-maertens** [comment]
Possible overlap with #1889

**Comment by sergei-maertens** [comment]
![IMG_20220912_123224](https://user-images.githubusercontent.com/5518550/189632866-ff64187f-ba5b-4921-bb69-a9a45dc038de.jpg)
