### ISSUE TITLE
Special characters from StUF-BG are not always correctly prefilled

### ISSUE THREAD

**Issue by joeribekker** [open-formulieren/open-forms#1881]
### Product versie / Product version

1.1.5

### Omschrijf het probleem / Describe the bug

Reported by Haarlemmermeer. When StUF-BG replies one of these:

```xml
<ns2:geslachtsnaam>ÆïóňżƗ</ns2:geslachtsnaam>
<ns2:geslachtsnaam>Een grotere naamëáõłćĉċčḉŞ</ns2:geslachtsnaam>
```

Not every character is shown when used with prefilling... Please write a test case to validate this ticket and then fix the problem :)

**Comment by dariomory** [comment]
@joeribekker  A simple regression test passes. I am also unable to manually reproduce the issue.

![Peek 2022-08-24 12-56](https://user-images.githubusercontent.com/58147939/186401634-a5ae7eff-71c5-47bf-a2c7-542433a3748c.gif)

**Comment by sergei-maertens** [comment]
Please ensure that the file is saved with the same encoding as the StUF-BG responses are received. UTF-8 will probably work, cp1252 might be problematic.

**Comment by sergei-maertens** [comment]
@hlmr-david - can you provide some input on what the StUF-BG response encoding used it? Probably something else than UTF-8.

**Comment by sergei-maertens** [comment]
Thanks for the input, that should be enough to properly reproduce this!

**Comment by joeribekker** [comment]
Looked up the error logs on their instance:

```
<soap:Envelope xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/"><soap:Body><ns2:npsLa01 xmlns:ns4="http://www.w3.org/1999/xlink" xmlns:ns3="http://www.opengis.net/gml" xmlns:ns2="http://www.egem.nl/StUF/sector/bg/0310" xmlns:ns1="http://www.egem.nl/StUF/StUF0301"><ns2:stuurgegevens><ns1:berichtcode>La01</ns1:berichtcode><ns1:zender><ns1:applicatie>Digid-Prefill</ns1:applicatie></ns1:zender><ns1:ontvanger><ns1:applicatie>Open-Formulieren</ns1:applicatie></ns1:ontvanger><ns1:referentienummer>5fe4eca3-fbc7-490d-8b5a-53c5212fe2cf</ns1:referentienummer><ns1:tijdstipBericht>20220830182501966</ns1:tijdstipBericht><ns1:entiteittype>NPS</ns1:entiteittype></ns2:stuurgegevens><ns2:antwoord><ns2:object><ns2:inp.bsn>900174328</ns2:inp.bsn><ns2:geslachtsnaam>Een grotere naam\xeb\xe1\xf5&#x142;&#x107;&#x109;&#x10b;&#x10d;&#x1e09;&#x15e;</ns2:geslachtsnaam><ns2:voornamen>Voornaam</ns2:voornamen><ns2:geboortedatum>19730121</ns2:geboortedatum><ns2:verblijfsadres><ns2:wpl.woonplaatsNaam>Hoofddorp                                                                       </ns2:wpl.woonplaatsNaam><ns2:gor.straatnaam>Raadhuisplein</ns2:gor.straatnaam><ns2:aoa.postcode>2132TZ</ns2:aoa.postcode><ns2:aoa.huisnummer>1</ns2:aoa.huisnummer></ns2:verblijfsadres><ns1:tijdstipRegistratie xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:nil="true"/></ns2:object></ns2:antwoord></ns2:npsLa01></soap:Body></soap:Envelope>
```

```
ERROR openforms.prefill  exception in prefill plugin 'stufbg'
Traceback (most recent call last):
  File "/app/src/./openforms/prefill/__init__.py", line 161, in invoke_plugin
    values = plugin.get_prefill_values(submission, fields)
  File "/app/src/./openforms/prefill/contrib/stufbg/plugin.py", line 131, in get_prefill_values
    return self._get_values_for_bsn(submission.bsn, attributes)
  File "/app/src/./openforms/prefill/contrib/stufbg/plugin.py", line 106, in _get_values_for_bsn
    data = client.get_values(bsn, attributes)
  File "/app/src/stuf/stuf_bg/client.py", line 94, in get_values
    dict_response = xmltodict.parse(
  File "/usr/local/lib/python3.8/site-packages/xmltodict.py", line 327, in parse
    parser.Parse(xml_input, True)
xml.parsers.expat.ExpatError: not well-formed (invalid token): line 1, column 777
```

**Comment by joeribekker** [comment]
From the above we can see (years of experience - thanks @alextreme) that the characters `\xeb` and the likes are not UTF-8 characters... See below:

```
In [23]: b"\xeb".decode('utf-8')
---------------------------------------------------------------------------
UnicodeDecodeError                        Traceback (most recent call last)
Input In [23], in <cell line: 1>()
----> 1 b"\xeb".decode('utf-8')

UnicodeDecodeError: 'utf-8' codec can't decode byte 0xeb in position 0: unexpected end of data
```

The bytestring is actually, latin1 encoded, which does not match the header information:

```
In [24]: b"\xeb".decode('latin1')
Out[24]: 'ë'
```

We can also see the reverse:

```
In [26]: 'ë'.encode('utf-8')
Out[26]: b'\xc3\xab'

In [27]: 'ë'.encode('latin1')
Out[27]: b'\xeb'
```

In conclusion, this is not a bug, this is invalid data+header information provided to the prefill plugin.

**Comment by hlmr-erik** [comment]
We hebben deze eindelijk op kunnen pakken en sluiten. Wel kreeg ik dit nog mee van één van onze developers. Weet niet of jullie er iets mee (zouden moeten) kunnen, maar goed ;) 

> Blijkbaar wordt er vanuit open-formulieren geen content-type: text/xml;charset=UTF-8 meegegeven.
> Als de charset niet wordt meegegeven is de standaard encoding: text/xml; charset=ISO-8859-1
> 
> De webserver zegt: Moet je maar duidelijk zijn :slight_smile:

**Comment by joeribekker** [comment]
We kunnen inderdaad wel een `Accept` header meegeven zodat de server weet dat we enkel UTF-8 accepteren (en dat dus als `Content-Type` meegeeft. Is netjes :)

Ik wil er niet weer induiken maar ik vermoed toch dat jullie UTF-8 karakters zetten in de body terwijl jullie als header ISO-8859-1 meegeven. Dat zorgt voor de verwarring. Als jullie ISO-8859-1 karakters in de body zetten, en dat ook als header meegeven, was er geen probleem! Het moet consistent zijn :)
