### ISSUE TITLE
Currency fields should allow setting a max- or minimum value

### ISSUE THREAD

**Issue by hlmr-erik** [open-formulieren/open-forms#1882]
### Thema / Theme

Form designer

### Omschrijving / Description

When setting up a currency field, the form-editor as of yet doesn't allow for limits to be defined.

### Added value / Toegevoegde waarde

When applying for a government grant, it would be useful to make it clear that there is a maximum (or minimum) amount to be requested.

### Aanvullende opmerkingen / Additional context
This is the way it is set up in a regular 'number' field, which seems appropriate for currency fields as well:

![image](https://user-images.githubusercontent.com/111565013/185580511-370f1e69-a394-4be4-8624-86c8cbde5653.png)

Als formulierbouwer
Wil ik in een valuta-veld ook max en min waarden kunnen definiëren, net zoals dat nu bij een getal veld kan.
Zodat het voor een eindgebruiker bij het invullen van een subsidie aanvraag duidelijk te maken is dat er een maximaal (of minimaal) bedrag aan te vragen is.

Related: Dimpact PF-75

**Comment by Daveeeeeeeeeee** [comment]
Dit is dave
