### ISSUE TITLE
Make the error-text of fields customizable

### ISSUE THREAD

**Issue by hlmr-erik** [open-formulieren/open-forms#1884]
Als formulierbouwer
Wil ik dat teksten voor foutmeldingen “die nu hardcoded zijn”, te personaliseren zijn door de gemeente.
Dit zodat foutmeldingen specifieker zijn voor fouten die optreden, en formulieren gebruiksvriendelijker worden voor de invuller. Het “waarom” van de foutmelding moet duidelijker aan te geven kunnen zijn.

**Acceptatie criteria**

- Foutmeldingen moeten per “omgeving/gebruiksorganisatie” te personaliseren zijn.
- Deze foutmeldingen moeten mee vertaald worden in de taal waarop het formulier ingevuld wordt. 
- Een foutmelding moet gespecificeerd kunnen worden o.b.v. de fout.
  - voorbeeld:
    - Een getalveld word ingevuld met een getal buiten het toegestane bereik.
      - I.p.v. de melding ingevulde waarde is fout,
      - kan de melding zijn, ingevulde waarde is “te hoog” of “te laag”.
        - Meerdere foutmeldingsmogelijkheden kunnen aangeven bij een validatie.

**Comment by StefSchots1993** [comment]
https://dimpact.atlassian.net/browse/PF-61

**Comment by joeribekker** [comment]
Most likely this was solved already, doublecheck please.

**Comment by StefSchots1993** [comment]
@joeribekker - Zie ook https://dimpact.atlassian.net/browse/PF-61 maar hierbij nog de aanvulling van Haarlemmermeer voor verder refinement van de userstory.

Dit gaat oa. om min/max validaties die nog ontbreken voor de veldsoorten: Datum, datum/tijd, tijd en bedrag. 
Dus:

Datumcomponent

-error voor ingevoerde datum hoger dan opgegeven maximum
-error voor " lager dan opgegeven minimum

 Datum- en tijd component

-error voor ingevoerde datum/tijd hoger dan opgegeven maximum
-error voor " lager dan opgegeven minimum

 Tijdcomponent

-error voor ingevoerde tijd later dan opgegeven maximum
-error voor " vroeger dan opgegeven minimum
 
Bedragcomponent

-error voor ingevoerd bedrag hoger dan opgegeven maximum
-error voor " lager dan opgegeven minimum

Verder willen we voor nog te realiseren koppelingen met eigen databases (bijv. voor validatie of een ingevoerd zaaknummer voorkomt in een tabel voor te verantwoorden subsidies) een custom errortekst kunnen opgeven wanneer er geen, of juist wel een ‘hit’ teruggegeven wordt. Zoals ‘We kunnen uw zaaknummer niet vinden. Controleer of u het juiste zaaknummer heeft opgegeven’ of ‘Uw zaaknummer klopt’

**Comment by sergei-maertens** [comment]
self-reminder: checken wat NL Design System hier als richtlijnen voorschrijft, want impact op toegankelijkheid

**Comment by SilviaAmAm** [comment]
To do:
- [x] Check date and datetime components => here the widget prevents you from entering a date that is outside of the specified period. So there should be no need for this custom error?
- [ ] Time
- [x] Currency => here is is already possible to specify a custom error:
![Screenshot from 2023-08-08 09-41-57](https://github.com/open-formulieren/open-forms/assets/19154114/208150e1-48c4-4384-8e4e-b0a97ec15bba)

**Comment by sergei-maertens** [comment]
SDK todo

**Comment by hlmr-erik** [comment]
In order to offer clarity to end-users as to why they're getting an error, we'd like to specify a specific one for min-exceeded and max-exceeded. Currently there is only a single error for 'out of range' 
![afbeelding](https://github.com/open-formulieren/open-forms/assets/111565013/38913a19-e470-46cb-83d9-31c5db7de3f5)

**Comment by sergei-maertens** [comment]
Reopening so we can pick up the more fine-grained error messages.

**Comment by SilviaAmAm** [comment]
Clarification:  
We have these possible cases for validation:
 - Only `minTime` or only `maxTime` specified:
   Here we will show the 'minTime' or 'maxTime' error respectively
 - Both `minTime`/`maxTime` specified with `minTime < maxTime`:
   Here we show the 'minTime' error if `value < minTime`, and the error 'maxTime' if `value > maxTime`. If these are not present, we show 'invalid_time' error.
 - Both `minTime`/`maxTime` specified with `maxTime < minTime` (e.g. minTime 08:00, maxTime 01:00 of the next day):
   We show the 'invalid_time' error. Showing minTime/maxTime errors would be ambiguous.

For the data migration:
- Add the new minTime/maxTime custom errors
- In the frontend, check if you need to display minTime/maxTime errors. If these are not specified, fall back on `invalid_time` error.

**Comment by sergei-maertens** [comment]
SDK PR is still open
