### ISSUE TITLE
Enable 'maximum mode' in the datepicker component for choosing years only

### ISSUE THREAD

**Issue by hlmr-erik** [open-formulieren/open-forms#1889]
### Thema / Theme

Form designer

### Omschrijving / Description

A few of our forms need the functionality to be able to block when a certain calculation based on years is made, for example %currentyear% - 4 = block. 

However, the date-component - which does allow to make calculations based on %today% - only allows for full dates including months and days.
It would be nice if the date component could be adapted to offer setting it to 'year only', 'month and year only' and 'full date'.

These validations could be set statically (as we did for now), but then the forms would have to be adapted again every new year.

--

Als formulierbouwer
Wil ik een nieuw component dat zich gedraagt als een datum component maar dan alleen met jaren.
Zodat ik kan valideren op jaar en enkel jaar.

**Acceptatiecriteria**

Een datum validatie die controleert op [vandaag] [+ of -] [X jaar]. Reeds beschikbaar voor datum component dus op 1-1-2023, ipv 2023)

Case

Haarlemmermeer heeft een formulier waarin zij willen valideren voor welk Jaar een aanvraag wordt ingediend. Alleen het jaar is dan relevant, niet de dag.

### Added value / Toegevoegde waarde

To offer dynamic validations based on other time-units than full date.

### Aanvullende opmerkingen / Additional context

This seems possble with form.io's [maximum mode](https://cloud.githubusercontent.com/assets/13321142/13097253/30722118-d4e5-11e5-9a59-4363e16abbed.png) in the datepicker settings

To illustrate, the validations possible for a date component:
![image](https://user-images.githubusercontent.com/111565013/185627918-b9a95f3c-daf7-426a-a6c6-31f06cc58e00.png)

And the more limited ones for a regular 'number' component (which we've used now as a stand-in for a year-field):
![image](https://user-images.githubusercontent.com/111565013/185628054-21684d27-73fe-4ee0-b468-49585aed6257.png)

Related: Dimpact PF-68

**Comment by sergei-maertens** [comment]
I can't seem to find any working references to the `minMode` or `maxMode` in Formio - which version of Formio should have this? It's not available in 4.12 or 4.13 (which we use), nor on the latest version on https://formio.github.io/formio.js/app/builder

**Comment by hlmr-erik** [comment]
I'm not entirely sure which version has (had) this. It still shows in the help-docs, but I'm not sure what version that is https://help.form.io/userguide/forms/form-components#date-time . I faintly remember as well testing this functionality on https://formio.github.io/formio.js/app/builder , but the version currently on there indeed doesn't seem to have it. Will look into it some more to see what I can find, tbc...

**Comment by hlmr-erik** [comment]
It appears this functionality hasn't been active in form.io for some time. Ideally, what I mean would be something like this 
https://jsbin.com/fifibi/4/edit?js,console,output
![image](https://user-images.githubusercontent.com/111565013/189633438-a89cf5b5-0e51-4509-869e-ba41b8dd2a3b.png)
Yet, this doesn't seem to be in the toolkit of the current incarnation of form.io

**Comment by joeribekker** [comment]
I prefer an option in the date component (so we dont have to copy the code) but if a Year-component is that much easier, lets just do that.

**Comment by sergei-maertens** [comment]
@CharString reopening this so you can create a separate PR to include some documentation/recipe in the docs on how to do this.
