### ISSUE TITLE
Allow for pre- and suffixes in renaming uploads

### ISSUE THREAD

**Issue by hlmr-erik** [open-formulieren/open-forms#1890]
### Thema / Theme

Form designer

### Omschrijving / Description

Currently, it is possible to rename uploads to a pre-defined value or keep the original name. To pre- or suffix the original filenames has its benefits.

### Added value / Toegevoegde waarde

At times, a person who submitted a form might refer to a certain file by the name they uploaded it with (DCIM04564.jpg, Scan081.pdf) in subsequent contact - and at the same time, the municipality would like a neatly ordered set of uploads - it would be great if the filename of uploads could be set to get a pre- or suffix as well (voorkant_DCIM04564.jpg, toestemmingsverklaring_Scan081.pdf).

Related: Dimpact PF-69

*Template/Suffix/Prefix moet optioneel zijn*

**Comment by sergei-maertens** [comment]
I *think* this is possible using some sort of template expressions from Formio, but I'll have to look up the details itself. I remember the documentation being a bit iffy on this.
