### ISSUE TITLE
Enable setting tooltip icons next to the fields

### ISSUE THREAD

**Issue by hlmr-erik** [open-formulieren/open-forms#1892]
### Thema / Theme

Form designer

### Omschrijving / Description

As presenting the explanation for fields in the 'Description' field of the form-editor might not always be sufficient - and the 'Freeform text' component might be too intrusive - it would be nice to incorporate a middle ground by [enabling the tooltip 'i'](https://help.form.io/userguide/forms/form-components#tooltip) next to the fields.  

This way, additional guidance can be offered without overtly displaying the text to people who might not need it.

--

Als formulierbouwer 
Wil ik graag middels een Tooltip extra uitleg kunnen geven bij sommige velden
Zodat ik als gemeente extra begeleiding kan geven zonder de tekst openlijk te tonen aan mensen die dit niet nodig hebben. 

Case
Omdat het presenteren van uitleg bij velden in het veld 'Beschrijving' van de formulier-editor misschien niet altijd voldoende is, en het 'Vrije tekst' component misschien te opdringerig, zou het mooi zijn om een middenweg in te bouwen door [de tooltip 'i'](https://help.form.io/userguide/forms/form-components#tooltip) aan te zetten naast de velden.

### Aanvullende opmerkingen / Additional context

As it is in our current solution:

![image](https://user-images.githubusercontent.com/111565013/185641766-a6d4ab96-a4e7-4503-ba11-6dfab4a1e2cd.png)

Related: Dimpact PF-74

**Comment by sergei-maertens** [comment]
Thanks for the suggestion, this definitely makes sense!

The impact of the feature is:

* adding the tooltip to the form designer
* support templating variables in the tooltip
* support displaying tooltips in the SDK (this is the annoying bit because it further cements our dependency on formio/bootstrap, which we want to get rid of)
