### ISSUE TITLE
Size of pictures inside free text components doesn't get respected

### ISSUE THREAD

**Issue by hlmr-erik** [open-formulieren/open-forms#1901]
### Product versie / Product version

1.1.5

### Omschrijf het probleem / Describe the bug

When setting the size of a picture through the GUI of the 'free text' component...
![image](https://user-images.githubusercontent.com/111565013/185931091-463b7c1c-2bb8-4d6d-8718-33d319d6bfd5.png)

It gets respected in the form-editor view:
![image](https://user-images.githubusercontent.com/111565013/185931171-610fd079-86f7-4748-a90e-68b8d283cc6f.png)

But not in the form itself:
![image](https://user-images.githubusercontent.com/111565013/185931232-b27ce106-148b-4236-a650-ee31072bd319.png)

### Stappen om te reproduceren / Steps to reproduce

1. Go to https://haarlemmermeer.test.open-formulieren.nl/admin/forms/form/95/change/
2. Evaluate how the size of the pictures is set
3. Compare with resulting form: https://haarlemmermeer.test.open-formulieren.nl/erker/stap/erker

### Verwacht gedrag / Expected behavior

The size of pictures in the forms should match how they were set in the form-editor.

### Device

Desktop

### OS

Windows

### Browser

Chrome, Firefox

**Comment by sergei-maertens** [comment]
This could be because of the CSP headers & inline styles being blocked.

**Comment by Bartvaderkin** [comment]
This looks indeed like a CSP issue, when I test it locally with CSP disabled it works as expected, but online it generates CSP errors about inline styles.

Problem here is that the Form.io builder generates the HTML with the inline style as part of the component definition.
