### ISSUE TITLE
Using the TAB key in a freeform textfield, jumps to the next field in the form-editor

### ISSUE THREAD

**Issue by hlmr-erik** [open-formulieren/open-forms#1912]
### Product versie / Product version

1.1.5

### Omschrijf het probleem / Describe the bug

In trying to create indentation in a freeform textfield with the TAB key, instead it is registered as jumping to the next UI element in the editor. 

![firefox_2022-08-23_11 55 41](https://user-images.githubusercontent.com/111565013/186129489-a31abd82-a0f3-4085-b799-25b3db67ef5d.gif)

### Verwacht gedrag / Expected behavior

For the TAB key to create indentation when used inside a freeform text field.

**Comment by sergei-maertens** [comment]
I doubt this is properly supported in Formio in the first place - tab characters do not have meaning in HTML and the whitespace will just be treated as a single "space" character. The only way you can get indent content is by doing this through CSS.

**Comment by hlmr-erik** [comment]
> 

Indeed. I was confused about this because copying a text from Word does seem to take along tab-characters - but it turns out they are substituted with multiple single "space" characters. So copy-pasting from Word could be a workaround for now
