### ISSUE TITLE
Sending of confirmation mail is skipped

### ISSUE THREAD

**Issue by hlmr-erik** [open-formulieren/open-forms#1916]
### Product versie / Product version

1.1.5

### Omschrijf het probleem / Describe the bug

Sending the confirmation mail only succeeds in a [specific form consisting of a single page](https://haarlemmermeer.test.open-formulieren.nl/admin/forms/form/88/change/). All others appear to submit succesfully (confirmation page shows), however the mails don't get sent and show something similar to this in the log:
![image](https://user-images.githubusercontent.com/111565013/186169064-7e80bcac-41d9-416a-8b06-897d4297d605.png) 
![image](https://user-images.githubusercontent.com/111565013/186169887-4fd8624b-864a-423f-9dba-0e9d92c5ddc4.png)

### Verwacht gedrag / Expected behavior

Confirmation mail sends on all forms and/or a more elaborate logging message shows why it doesn't.

**Comment by sergei-maertens** [comment]
I suspect there is no e-mail field in the form that is marked as "confirmation e-mail recipient address"

**Comment by hlmr-erik** [comment]
> I suspect there is no e-mail field in the form that is marked as "confirmation e-mail recipient address"

It appears this was the case indeed :) Specifically those forms I tested didn't have that field configured, where most others did- haha. Thanks for the heads-up

**Comment by sergei-maertens** [comment]
> > I suspect there is no e-mail field in the form that is marked as "confirmation e-mail recipient address"
> 
> It appears this was the case indeed :) Specifically those forms I tested didn't have that field configured, where most others did- haha. Thanks for the heads-up

I remember debugging a similar issue with a local development form and feeling very stupid afterwards... :smile:
