### ISSUE TITLE
Dark scheme of the portal is unworkable

### ISSUE THREAD

**Issue by hlmr-dave** [open-formulieren/open-forms#1924]
### Product versie / Product version

latest

### Omschrijf het probleem / Describe the bug

The "dark scheme" of the Form designer is unworkable. Most of the text is unreadable and in some cases the action buttons as well.

### Stappen om te reproduceren / Steps to reproduce

![Screenshot 2022-08-25 at 16 33 07](https://user-images.githubusercontent.com/111569473/186695857-a4914730-9cc7-4a96-8582-d24cb669eacd.png)
![Screenshot 2022-08-25 at 16 33 31](https://user-images.githubusercontent.com/111569473/186695873-aa1bc51d-1030-4f75-a4d0-945555955793.png)

### Verwacht gedrag / Expected behavior

Please disable it and make it so that the default is always applied. Now I am blocked because of this unfinished functionality.

### Device

Desktop

### OS

iOS

### Browser

Chrome

**Comment by SilviaAmAm** [comment]
Things to fix:
- [ ] Hidden fields 
- [ ] Warning session is expiring

(Advanced logic was removed from the fieldset)

**Comment by hlmr-erik** [comment]
Don't know if these were already part of the re-opened story, but:
The MFA-QR code is unreadable in Dark mode:
![image](https://user-images.githubusercontent.com/111565013/217775946-5e78af58-0244-4254-9b44-7c9d8d31bf74.png)
(I obviously blurred out the QR code)

Same with the type of buttons like the 'Add form' button:
![image](https://user-images.githubusercontent.com/111565013/217776241-63f7f8ae-81d9-4209-a6f5-573d90d59700.png)

**Comment by sergei-maertens** [comment]
Can you please open a new issue for these findings?

**Comment by hlmr-erik** [comment]
Done: https://github.com/open-formulieren/open-forms/issues/2671 As it turned out, part of my initial finding was because of the 'Dark Reader' extension I used to try to reproduce the problem. However, part of it persists in Windows' native dark mode.

**Comment by sergei-maertens** [comment]
Thanks :)

The framework support (in this version of the framework) is limited to the media queries for dark/light scheme preferences. I think I saw that the next LTS release relaxes that a bit by using themes/theme names to target, so I'm not entirely sure how things behave with OS-mandated dark-mode etc.
