### ISSUE TITLE
Fields hidden as part of a fieldgroup show on the 'overview' step

### ISSUE THREAD

**Issue by hlmr-erik** [open-formulieren/open-forms#1927]
### Product versie / Product version

1.1.5

### Omschrijf het probleem / Describe the bug

It appears the fields that are displayed on the 'overview' step, aren't limited to fields that are actually visible in the form itself. 

Fields that are singularly set to 'hidden' don't show, but when the fields themselves aren't set to 'hidden'- yet the fieldgroup they are part of is hidden - they continue to appear.

On the overview page:
![image](https://user-images.githubusercontent.com/111565013/186848444-776d1d18-40d8-4051-b6a9-6e7194a625de.png)

Same part in the form (where this fieldset is hidden):
![image](https://user-images.githubusercontent.com/111565013/186848493-9c77d978-e3d7-43b6-8f71-ae641ef1f3ec.png)

### Verwacht gedrag / Expected behavior

To keep hidden fields from displaying on the 'overview' step

**Comment by sergei-maertens** [comment]
Are these fields hidden by form logic, or are you using the conditional display from the form designer itself?

Possibly related to #1871

**Comment by hlmr-erik** [comment]
The fieldgroup is hidden by checkbox in the form designer.

**Comment by sergei-maertens** [comment]
Check - we will reproduce this and look for a bugfix, the intent is definitely that if a container is hidden, the contents are also not visible.

**Comment by sergei-maertens** [comment]
Checked this with a radio (with options yes/no) and a fieldset with a non-hidden textfield inside it. The fieldset has (client-side) logic to only display when the radio value is set to `yes`. As of the `master` branch, this functions correctly, so earlier similar patches appear to be sufficient to resolve this issue too.
