### ISSUE TITLE
Upload field accepts files with re-named (false) extensions

### ISSUE THREAD

**Issue by hlmr-erik** [open-formulieren/open-forms#1929]
### Product versie / Product version

1.1.5

### Omschrijf het probleem / Describe the bug

When I upload a file where the mimetype doesn't match the extension (renamed from `file.zip` to `file.jpg`, `file.jpg` to `file.png` etc.), this isn't caught by the upload component. It is caught only upon trying to send the form. However, this doen't lead to a (visible) error message, so the user is left in the dark about why the form won't send.

Component accepts the file ( file_all_types_iphone.png is actually a renamed .jpg)
![image](https://user-images.githubusercontent.com/111565013/186880959-f767748e-8677-423f-a012-b3ac1dd7f228.png)

The error as shown in the network-tab upon trying to send:
`{"type":"https://haarlemmermeer.test.open-formulieren.nl/fouten/ValidationError/","code":"invalid","title":"Invalid input.","status":400,"detail":"","instance":"urn:uuid:9a1e4850-6468-4c82-8130-4e9ec6998807","invalidParams":[{"name":"data.Voeg een foto of kopie toe van een geldig paspoort of een identiteitskaart","code":"invalid","reason":"The file 'file_all_types_iphone.png' is not a valid file type."}]}`

### Verwacht gedrag / Expected behavior

For the upload component to catch that the mimetype doesn't match the extension, and display an error accordingly.

**Comment by sergei-maertens** [comment]
We cannot perform certain validation at upload time - there is no (secure) information about which form component the upload concerns. Any attempt to send this data from the form to the backend is susceptible to data alterations by the user/browser client, so it cannot be trusted.

Therefore, we can only perform this validation once the step is submitted and the files are being related to the step and relevant form field/component in that step, where we have the file validation configuration available as dictated by the form designer.

I suppose we _could_ do mime-type validation at upload time based on extension, spreading the validation over multiple phases, and we should also add a generic error display for backend errors during submission time.

Note that this is considered an edge case - changing extensions on purpose to trick client-side validation is considered "abuse" and for people that are trying to break the system, we don't focus on ensuring the "best user experience". :wink:

**Comment by hlmr-erik** [comment]
I agree that it would be an uncommon occurence, however I don't think it would be only due to malignant intent. For example, a user who is not very apt with computers, on seeing that the upload field only accepts *.pdf, *.png and *.jpg files, might see a solution in getting their *.tiff file uploaded in relabeling it to one of these. 
Or for various reasons, the file could get corrupted on a users system, causing the BE to reject it because its mime-type doesn't match the files content anymore. 
In these cases a somewhat descriptive warning to the users would be welcome.

**Comment by sergei-maertens** [comment]
That's a good perspective, thanks for the input! We'll take this into account when planning the next release development cycle.

**Comment by sergei-maertens** [comment]
Need to check if we can send/generate backend validation errors for formio to display
