### ISSUE TITLE
The application can't handle all special characters when received from logius

### ISSUE THREAD

**Issue by hlmr-dave** [open-formulieren/open-forms#1938]
### Product versie / Product version

1.1.5

### Omschrijf het probleem / Describe the bug

One of our developers noticed that we don't receive data if we use these characters in the name fields. 

---
De digid prefill gaat fout op een aantal speciale tekens. Onder andere de volgende tekens gaan fout in het geslachtsnaam veld:
<ns2:geslachtsnaam>ÆïóňżƗ</ns2:geslachtsnaam>
<ns2:geslachtsnaam>Een grotere naamëáõłćĉċčḉŞ</ns2:geslachtsnaam>

**Comment by sergei-maertens** [comment]
Duplicate of #1881
