### ISSUE TITLE
Een kenteken element waarbinnen Nederlandse kentekend worden gevalideerd (deze eis valt buiten het MVP).

### ISSUE THREAD

**Issue by joeribekker** [open-formulieren/open-forms#195]
Eis: Elementen 1g.
Zie ook NvI: 12, 68

**Tasks**

* [x] Add new field: Licenseplate ("Kenteken"). This field should have a default regex validation `^[a-zA-Z0-9]{1,3}\-[a-zA-Z0-9]{1,3}\-[a-zA-Z0-9]{1,3}$` and a maximum length of 8.
* [x] Add and translate proper error message.

**Verduidelijking nodig**

~Moet formaat gecontroleerd worden? Of is het een RDW-koppeling? Of gaat het om BSN-Kenteken relatie?~

**Comment by LBozarov** [comment]
@joeribekker hier gaat om de streepjes en dus geen RDW koppeling
