### ISSUE TITLE
Allow number fields to not use separators

### ISSUE THREAD

**Issue by joeribekker** [open-formulieren/open-forms#1950]
### Thema / Theme

Frontend

### Omschrijving / Description

Add an option to use plain numbers like a bsn or KvK number that do not have any dots or commas.

### Added value / Toegevoegde waarde

More flexibility and allows number fields to be used for other things, like the KvK number.

**Comment by dariomory** [comment]
@joeribekker Similar behavior can be achieved by setting decimals to `0`. Does that work?

![Peek 2022-09-02 15-27](https://user-images.githubusercontent.com/58147939/188156600-6e8da7f2-4550-411a-af3c-1bc65f71bcc1.gif)

**Comment by joeribekker** [comment]
Refinement: We're keeping it as it is because the examples "KvK and BSN" are identifiers that happen to use digits and not numbers. They should not be treated as numbers. Numbers should be formatted as numbers and they are.
