### ISSUE TITLE
Pausing a form multiple times creates a "invalid" link in new notification (email)

### ISSUE THREAD

**Issue by LaurensBurger** [open-formulieren/open-forms#1959]
### Product versie / Product version

1.1.5, 2.0.x, 2.1.x

### Omschrijf het probleem / Describe the bug

When a user uses the "Pauzeren" button in a form more then once, the links included in the following emails contain links that return a 403 error to the user:
![image](https://user-images.githubusercontent.com/112621537/188107096-68760a3a-eef7-404b-911d-fbfc9cc0b4bd.png)

The link in the first notification will still work. 

### Stappen om te reproduceren / Steps to reproduce

1. Start a form with steps that requires authentication
2. Pause the form, fill in email, ok
3. Click the link from the mail you recieved
4. Pause the form again, fill in email, ok
5. Check if link from initial email works
6. Check if link from second email works

### Verwacht gedrag / Expected behavior

- The link should be available as it's mentioned in the email: "Link is valid untill x" 
- The user should not get a new link if it's not usable

Interne referentie: HadM 26

**Comment by joeribekker** [comment]
@LaurensBurger does it work correctly when no auth (like DigiD) is used?

**Comment by LaurensBurger** [comment]
@joeribekker it works correctly when no authentication is used

**Comment by sergei-maertens** [comment]
I suspect the auth attributes hashing is the culprit here.

**Comment by SilviaAmAm** [comment]
I saw this stack trace on our test environment for endpoint `/submissions/fb606874-fe93-48fa-b4b3-f898132dbe5a/r3-2caee824a6894cff129c/resume`

```
AttributeError: 'NoneType' object has no attribute 'form_step'
  File "django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "django/views/generic/base.py", line 98, in dispatch
    return handler(request, *args, **kwargs)
  File "django/views/generic/base.py", line 189, in get
    url = self.get_redirect_url(*args, **kwargs)
  File "openforms/submissions/views.py", line 121, in get_redirect_url
    return self.get_form_resume_url(submission)
  File "openforms/submissions/views.py", line 146, in get_form_resume_url
    submission.get_last_completed_step().form_step.form_definition.slug
```

Possibly related?

**Comment by LaurensBurger** [comment]
> I saw this stack trace on our test environment for endpoint `/submissions/fb606874-fe93-48fa-b4b3-f898132dbe5a/r3-2caee824a6894cff129c/resume`
> 
> ```
> AttributeError: 'NoneType' object has no attribute 'form_step'
>   File "django/core/handlers/exception.py", line 47, in inner
>     response = get_response(request)
>   File "django/core/handlers/base.py", line 181, in _get_response
>     response = wrapped_callback(request, *callback_args, **callback_kwargs)
>   File "django/views/generic/base.py", line 70, in view
>     return self.dispatch(request, *args, **kwargs)
>   File "django/views/generic/base.py", line 98, in dispatch
>     return handler(request, *args, **kwargs)
>   File "django/views/generic/base.py", line 189, in get
>     url = self.get_redirect_url(*args, **kwargs)
>   File "openforms/submissions/views.py", line 121, in get_redirect_url
>     return self.get_form_resume_url(submission)
>   File "openforms/submissions/views.py", line 146, in get_form_resume_url
>     submission.get_last_completed_step().form_step.form_definition.slug
> ```
> 
> Possibly related?

This is caused by me, opening links from last week's test but the steps in the form were removed.

**Comment by dariomory** [comment]
Thanks for clearing it up @LaurensBurger. Let us know if there are any updates on reproducing the issue.

**Comment by sergei-maertens** [comment]
Marking this as blocked until we can reproduce it

**Comment by SilviaAmAm** [comment]
Sjoerd and I tried this on the DH test environment and on Vught prod environment and we can reproduce it.

It is important not to be logged in as admin when resuming the form the second time.
