### ISSUE TITLE
Design token values are ignored

### ISSUE THREAD

**Issue by LaurensBurger** [open-formulieren/open-forms#1960]
### Product versie / Product version

1.1.5

### Omschrijf het probleem / Describe the bug

The CSS that is generated through the Organisation configuration > Design token values are not being used:
![image](https://user-images.githubusercontent.com/112621537/188121196-b0f7357e-e351-436b-bfd8-1523ec48761e.png)

Interne referentie: HadM 25

### Stappen om te reproduceren / Steps to reproduce

1. Add te following json to the Design Token Values:
{"link": {"color": {"value": "#000"}, "hover": {"color": {"value": "#CCC"}}}, "footer": {}, "layout": {"bg": {"value": "#e6e6e6"}}, "page-footer": {"bg": {"value": "#04a5bb"}, "fg": {"value": "#fff"}}}
2. Check a form that contains a link 
3. Inspect the link element and see all css overrides

### Verwacht gedrag / Expected behavior

The values supplied in Design token values should be overriding the standard values

**Comment by joeribekker** [comment]
I'm 99.9% sure this is because you used the "latest" documentation (which has different design tokens) in combination with 1.1.5 version of Open Forms. If not, feel free to re-open.

**Comment by joeribekker** [comment]
PS. I changed the default documentation setting to "stable" so you won't end up in docs that are in beta by default.

**Comment by LaurensBurger** [comment]
I do believe this is an issue - i can reproduce it on multiple instances and versions: The default values from core-css.css are always overriding the user provided values. 
A test on version 1.0.13 where these defaults are not present the user input does work, and adding !import to the values on "latest" also solves the problem - which is why i think the json provided is correct.
