### ISSUE TITLE
Add server-side SSL verification in plugin checks

### ISSUE THREAD

**Issue by joeribekker** [open-formulieren/open-forms#1973]
### Thema / Theme

Admin

### Omschrijving / Description

Before doing a HTTP-check, we should check if the server certificate is properly configured (we cannot check our client certificate because if it fails or passes it will return some HTTP response).

Checking the server certificate does not imply a valid HTTP-response, but does imply a valid certificate being configured on our end.

### Added value / Toegevoegde waarde

Easier debugging or problems.

**Comment by joeribekker** [comment]
Setting medium prio because debugging these things is super annoying.

**Comment by sergei-maertens** [comment]
A while ago I was prototyping this and concluded that it's just not feasible. See https://github.com/maykinmedia/django-simple-certmanager/issues/29 for details.
