### ISSUE TITLE
Een dropdown element, waarbij een zoekfunctie beschikbaar is die binnen dat element kan zoeken en filteren (deze ...

### ISSUE THREAD

**Issue by joeribekker** [open-formulieren/open-forms#198]
...eis valt buiten het MVP).

Eis: Elementen 1j.

**Comment by joeribekker** [comment]
Form.IO support dit, graag beschikbaar maken via admin en styling in SDK moet gebeuren.

**Comment by SilviaAmAm** [comment]
This is present in the admin, but not yet in the SDK
