### ISSUE TITLE
Map component doesn't accept location to continue

### ISSUE THREAD

**Issue by hlmr-dave** [open-formulieren/open-forms#1981]
### Product versie / Product version

1.1.5

### Omschrijf het probleem / Describe the bug

When I select a spot on the map it doesn't register and I can't continue.
![Screenshot 2022-09-06 at 12 35 35](https://user-images.githubusercontent.com/111569473/188614359-4f64d32e-d6af-4524-8ace-f92f8a4e4ec4.png)

### Device

Desktop

### OS

MacOS

### Browser

Chrome

**Comment by joeribekker** [comment]
Let's tackle this with the map user stories that are incoming.

**Comment by joeribekker** [comment]
@LaurensBurger can you test if this is still an issue?

**Comment by LaurensBurger** [comment]
@joeribekker No - tested both chrome and firefox, with and without location permissions and both allow me to continue

**Comment by joeribekker** [comment]
Pre-Refinement: Oppakken met Dimpact / Kaartmateriaal update indien dit nog speelt. Milestone verwijderd.
Laurens kan het niet reproduceren dus ik sluit het ticket. Als het nog speelt @hlmr-dave laat het vooral weten.
