### ISSUE TITLE
Different text in confirmation email depending on your answers

### ISSUE THREAD

**Issue by hlmr-dave** [open-formulieren/open-forms#1985]
### Thema / Theme

Form designer

### Omschrijving / Description

We have a from and depending on your answers the reply period is different. Now the confirmation email can only be one specific text. What we ideally need is 2 options. 
1. Custom confirmation email per form
2. A Template with variable fields depending form fields.
![Screenshot 2022-09-06 at 12 57 05](https://user-images.githubusercontent.com/111569473/188618181-ac0bd79f-7dcc-46ff-95bd-5668c99f23fc.png)

**Comment by sergei-maertens** [comment]
You can use the filled in data in the templates and make comparisons against that date. For example:

```django
{% if someField == 'some-answer' %}
reactietermijn 1
{% elif someField == 'other-answer' %}
reactietermijn 2
{% else %}
reactietermijn 3
{% endif %} 
```
(newlines zijn voor de leesbaarheid - dit kan allemaal op 1 lijn).

Relevante documentatie: https://open-forms.readthedocs.io/en/stable/manual/templates.html

**Comment by joeribekker** [comment]
@hlmr-dave is dat voldoende?

**Comment by joeribekker** [comment]
Ik sluit deze gezien er geen antwoord is en het volgens ons al kan.
