### ISSUE TITLE
Feedback from presentation

### ISSUE THREAD

**Issue by joeribekker** [open-formulieren/open-forms#1986]
* [ ] #2000
* [ ] #2002
* [ ] #2001

**Extra's**

* [ ] #2003

**Comment by sergei-maertens** [comment]
> Can we make compound variables: Variable "naam" = `{{ prefill.voornaam }} {{ prefill.last_name }}`

I can't find an issue for it, but I've expressed my wish to Silvia to be able to define the initial value of a variable as a json-logic expression (or a template could work too here).

At the moment it's possible with a logic trigger `true` that sets the value of a new variable, but being able to skip that computational step would be very nice.

**Comment by joeribekker** [comment]
Closed as meta ticket.
