### ISSUE TITLE
As a admin i want the fields in a field group to inherit certain properties from the field group

### ISSUE THREAD

**Issue by LaurensBurger** [open-formulieren/open-forms#1997]
### Thema / Theme

Form designer

### Omschrijving / Description

When logic is used to show or hide a field group, the fields in this group do not behave the same as the field group. This causes admins to believe the form's fields are hidden when in reality they do not get hidden. which results in them being present in the results/confirmation.
It would make sense in the case of "veldengroepen" the "velden" within the group inherits the "hidden" and "clear if field is hidden" attributies from the group.

**Comment by hlmr-erik** [comment]
Related to https://github.com/open-formulieren/open-forms/issues/1927
