### ISSUE TITLE
nonce in Siteimprove template in wrong spot?

### ISSUE THREAD

**Issue by LaurensBurger** [open-formulieren/open-forms#2012]
### Product versie / Product version

1.1.5

### Omschrijf het probleem / Describe the bug

The nonce that is supposed to be attached to the script element is attached to the incorrect script and is causing a csp error: 
![image](https://user-images.githubusercontent.com/112621537/189328817-b6bc278f-78f5-4b6c-b64f-2d9736a2b579.png)
```javascript
<script type="text/javascript" nonce="{{ request.csp_nonce }}">
/*<![CDATA[*/
(function() {
var sz = document.createElement('script'); sz.type = 'text/javascript'; sz.async = true;
sz.src = '//siteimproveanalytics.com/js/siteanalyze_{{ analytics_tools_config.siteimprove_id|escapejs }}.js';
var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(sz, s);
})();
/*]]>*/
</script>
```
I believe the nonce should be attached to the "sz" var:
```javascript
<script type="text/javascript">
/*<![CDATA[*/
(function() {
var sz = document.createElement('script'); sz.type = 'text/javascript'; sz.async = true; sz.nonce="{{ request.csp_nonce }}";
sz.src = '//siteimproveanalytics.com/js/siteanalyze_{{ analytics_tools_config.siteimprove_id|escapejs }}.js';
var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(sz, s);
})();
/*]]>*/
</script>
```
which will allow the external script to load correctly: 
![image](https://user-images.githubusercontent.com/112621537/189328668-8f3361c5-6a8b-4780-9fba-5fe14361a6f3.png)

**Tasks**

* [x] Add `sz.nonce="{{ request.csp_nonce }}"` to the snippet (like in the second code block above)

**Comment by sergei-maertens** [comment]
This might be mis-configuration

1. nonce is required for inline scripts, as the default CSP blocks inline scripts
2. siteimproveanalytics should be added to the dynamic CSP configuration, so that it's included the policy

Ewen's feature now should install that configuration after enabling an analytics provider, but that will only be available from the 2.0.0 release onwards

**Comment by alextreme** [comment]
Discussed with Laurens. Note @sergei-maertens that the siteimprove widget creates a script-tag on-the-fly, and by placing the nonce on sz.nonce the nonce should be set properly.

I have asked him for a form to make the issue reproducable, for HadM we see siteimprove working but I noticed additional CSP variables were set in the deployment.

**Comment by joeribekker** [comment]
@LaurensBurger can you indicate if this was solved? I Don't know where this happened.

**Comment by sergei-maertens** [comment]
> Discussed with Laurens. Note @sergei-maertens that the siteimprove widget creates a script-tag on-the-fly, and by placing the nonce on sz.nonce the nonce should be set properly.
> 
> I have asked him for a form to make the issue reproducable, for HadM we see siteimprove working but I noticed additional CSP variables were set in the deployment.

In that case it'll have to be both on the script tag and the dynamically created script, otherwise the SZ script will not run in the first place.

This does not look solved yet, but it should be an easy patch. For Paul maybe?
