### ISSUE TITLE
Advanced logic rule on Fieldgroup renders different result compared to Logic from form (tab)

### ISSUE THREAD

**Issue by LaurensBurger** [open-formulieren/open-forms#2024]
### Product versie / Product version

latest + 1.1.5

### Omschrijf het probleem / Describe the bug

When changing the visibility of a formgroup, the result differs when using different logic routes to unhide the group.
Using the advanced logic on from within the formgroup unhides it in the step for the user, but results are missing in the confirmation
Using the logic Tab to create te same rule the results are showing in the confirmation.

### Stappen om te reproduceren / Steps to reproduce

Start with a radio selection and 2 (hidden)field groups and apply the following logic to the field group:
Radio X:
yes
no

Field group Y logic:
If "form component" X has value "yes"
property "hidden" is False

Field group Z logic:
no logic

Form logic:
if "form component" X "is equal" "value" "yes"
then "form component Z" "hidden" False

The result is both Y and Z are shown in results, but Y is missing in both pdf and email

internal ref: Venr 34 + deLie 62

**Comment by sergei-maertens** [comment]
Verify on test environment, should be fixed in 2.0!

**Comment by LaurensBurger** [comment]
@sergei-maertens can confirm formgroup is visible in registration & pdf.
