### ISSUE TITLE
Some variable property was incorrectly named after migration

### ISSUE THREAD

**Issue by joeribekker** [open-formulieren/open-forms#2055]
### Product versie / Product version

2.0.0-beta0

### Omschrijf het probleem / Describe the bug

![image](https://user-images.githubusercontent.com/96970/191059783-30489af2-a67a-4a61-bd6a-28f5769714bd.png)

This prevented me from re-saving the form.

### Verwacht gedrag / Expected behavior

Maybe slugify the property names when creating variables for them? Not sure how much hassle this costs to fix logic and such.

**Comment by SilviaAmAm** [comment]
Discussed: to deal with this problem we need to make a management command that checks if there are invalid form field keys.

This command needs to be hook up to the version upgrade check.
