### ISSUE TITLE
Repeated logging in the admin is cluttering the logs

### ISSUE THREAD

**Issue by joeribekker** [open-formulieren/open-forms#2059]
### Product versie / Product version

2.0.0-beta0

### Omschrijf het probleem / Describe the bug

Can we remove these repeated logic log-lines entirely in the submission admin page.

![image](https://user-images.githubusercontent.com/96970/191063428-ee18abe7-70b4-4ca5-92f6-b50b3176f770.png)

They serve no purpose.

**Comment by sergei-maertens** [comment]
Is this in the submission log inline? In that case, we need to filter out the log records based on the template they use, because these log records _are_ used in the logic log page and contain a lot more structured data not displayed here. This is what Ewen worked on.

**Comment by joeribekker** [comment]
Ah. Yes, this is the submission admin page.
