### ISSUE TITLE
Untranslated string in migration

### ISSUE THREAD

**Issue by joeribekker** [open-formulieren/open-forms#2060]
### Product versie / Product version

2.0.0-beta0

### Omschrijf het probleem / Describe the bug

This text is added automatically to the intro text by a migration, to replace the hardcoded (same) text:

![image](https://user-images.githubusercontent.com/96970/191063834-b006172d-6bf8-46f9-82f9-182db4f0c2c0.png)

Either the string is not yet translated (I thought it was in the PR) or the language is not picked up in the migration.

**Comment by sergei-maertens** [comment]
Turns out translations aren't activated during migrations (did a quick test).

```py
def report_translation(*args):
    current_lang = translation.get_language()
    print(f"Current language: {current_lang}")
    msg = _("Please click the button below to start the form.")
    print(msg)
```

Output:

```
(open-forms) ➜  open-forms git:(release/2.0.0-beta.0) ✗ m migrate forms
Operations to perform:
  Apply all migrations: forms
Running migrations:
  Applying forms.0003_test_translations...Current language: None
Please click the button below to start the form.
```
