### ISSUE TITLE
"Pagina afdrukken" blocked by CSP

### ISSUE THREAD

**Issue by LaurensBurger** [open-formulieren/open-forms#2062]
### Product versie / Product version

latest

### Omschrijf het probleem / Describe the bug

When trying to print a page CSP is triggered preventing the window.print() command to execute.

```json

{
  "csp-report": {
    "document-uri": "https://open-formulieren-test.domein.nl/form/",
    "referrer": "",
    "violated-directive": "script-src-elem",
    "effective-directive": "script-src-elem",
    "original-policy": "default-src 'self'; img-src 'self' data: https://service.domain.nl/; style-src 'self' 'nonce-3nRQ5zYUpD131Zux7qupVw=='; script-src 'self' 'nonce-3nRQ5zYUpD131Zux7qupVw=='; frame-ancestors 'self'; base-uri 'self'; frame-src 'self'; report-uri /csp/report/",
    "disposition": "enforce",
    "blocked-uri": "inline",
    "line-number": 1,
    "source-file": "https://open-formulieren-test.domein.nl/form/",
    "status-code": 200,
    "script-sample": ""
  }
}

```

### Stappen om te reproduceren / Steps to reproduce

Click "Pagina Afdrukken" from the a11y toolbar and watch console print the CSP error.

### Verwacht gedrag / Expected behavior

The browser should initiate a print screen to print the current page.

### Device

Desktop

### OS

Linux

### Browser

Chrome, Firefox

**Comment by sergei-maertens** [comment]
Either add the CSP nonce to the inline JS, or move it to the bundle (probably the latter is the best option)

**Comment by Bartvaderkin** [comment]
This is inline javascript from a classic Django template on the backend, so we probably don't want a fix for this in the SDK bundle?
