### ISSUE TITLE
"eigenschapnaam" starting with "info", "warning", "success" applies style to form

### ISSUE THREAD

**Issue by LaurensBurger** [open-formulieren/open-forms#2073]
### Product versie / Product version

latest

### Omschrijf het probleem / Describe the bug
intern ref: delie 56

When the "eigenschapnaam" starts with one of these words the css is applied to the form. this is caused by the wildcard in the CSS selector:
```css
.openforms-form-control[class*=info]
```
![image](https://user-images.githubusercontent.com/112621537/191949965-06ecdcc7-6105-437c-9fd0-7e0192c4914c.png)

### Verwacht gedrag / Expected behavior

When a field has this class intentionally added there is no need to use a wildcard:
```css
.info
```
will suffice in these cases

**Comment by SilviaAmAm** [comment]
Also reported by Den Haag (Taiga user story 244, issue 211)
