### ISSUE TITLE
Underscores in postcode/BSN fields are read out by screen reader

### ISSUE THREAD

**Issue by SilviaAmAm** [open-formulieren/open-forms#2080]
### Product versie / Product version

2.0.0-beta.0

### Omschrijf het probleem / Describe the bug

DH Taiga user story 222, issue 202

The MASK has underscores and those are read with 1 specific screen reader (Windows narrator).

**Comment by SilviaAmAm** [comment]
With screen reader ORCA on firefox, I could not reproduce this. When I tab navigate to these inputs:
![Screenshot from 2022-09-26 16-35-46](https://user-images.githubusercontent.com/19154114/192304473-f04c7d22-4e2b-4ec4-9ee9-3081cdb02c3e.png)
I hear:
"Postcode entry" (then I press tab) "BSN entry"

**Comment by SilviaAmAm** [comment]
According to DH they hear this with Windows narrator

**Comment by SilviaAmAm** [comment]
With BrowserStack I tested a form with a postcode and a BSN field. This is what the screen reader reads out when tabbing to the fields:

Windows:
- Edge: Edit blank
- Firefox: Edit has autocomplete blank
- Chrome: Edit blank

BrowserStack uses NVDA with windows as the screen reader

**Comment by joeribekker** [comment]
I'm labelling this as wontfix. As much as I want to give the best experience to everyone with any screen reader, this case seems to happen rarely and although it's not correct, it's not really wrong either (a person that can see/read also sees underscores).
