### ISSUE TITLE
Repeating group shown by frontend logic with required fields gives error when filled in

### ISSUE THREAD

**Issue by SilviaAmAm** [open-formulieren/open-forms#2081]
### Product versie / Product version

2.0.0-beta.0

### Omschrijf het probleem / Describe the bug

https://watch.screencastify.com/v/apSMwHSLyx14grX9WOyq

### Stappen om te reproduceren / Steps to reproduce

Create a form with:
- A radio button with values ja / nee
- A fieldset with frontend logic that says: This field should show: True, if the component 'radio' has the value 'ja'.
- Inside the fieldset a repeating group (always open first row checked)
- Inside the repeating group a required textfield

Now fill in the form:
- Click 'ja' in the radio
- Try to fill in the text field, an error appears straight away

**Comment by SilviaAmAm** [comment]
This seems to happen because clicking the 'save' of the edit group triggers the [onReactSubmit](https://github.com/open-formulieren/open-forms-sdk/blob/main/src/components/FormStep.js#L419) if there is a validation error :thinking:

**Comment by sergei-maertens** [comment]
Looks like a bug in Formio - I could reproduce the behaviour on https://formio.github.io/formio.js/app/sandbox with Formio 4.12.7 (same version as used in SDK)

**Comment by sergei-maertens** [comment]
Found the fix in formio: https://github.com/formio/formio.js/commit/5fada97284a443d5b0d74bac2896708042465aea

This is pretty invasive and I don't want to (monkey) patch this, let's wait until Silvia is done with upgrading the internal formio version used in the SDK

**Comment by sergei-maertens** [comment]
The saving/changing of the data in the first row is broken in Formio 4.13.x still, and also in 4.14.y :(
