### ISSUE TITLE
Form-editor misses components in 1.1.6

### ISSUE THREAD

**Issue by hlmr-erik** [open-formulieren/open-forms#2095]
### Product versie / Product version

1.1.6

### Omschrijf het probleem / Describe the bug

The postcode and date fields still show in forms that had it preconfigured, however they don't appear anymore in the toolbox and show an 'unknown component' message in the WYSIWYG-editor:
![image](https://user-images.githubusercontent.com/111565013/193219743-63c4345f-957a-4fb9-9feb-52030b57675f.png)

**Comment by SilviaAmAm** [comment]
I noticed this also on Venray test for date, bsn and cosign component

**Comment by SilviaAmAm** [comment]
Fixed by https://github.com/open-formulieren/open-forms/pull/2097
