### ISSUE TITLE
As a user i can bypass "block continuing to next step"

### ISSUE THREAD

**Issue by LaurensBurger** [open-formulieren/open-forms#2096]
### Product versie / Product version

latest

### Omschrijf het probleem / Describe the bug

In cases where a user changes their mind and go back a step and if this step triggers the logic that disables the continuation of the form they are still able to click the final step  of the form (overzicht) and complete the form.

This user has previously selected: nee, but changed their mind and returned to the step and selects: ja
![image](https://user-images.githubusercontent.com/112621537/193237633-ef28262c-c0f8-43a4-96af-7887acb477f4.png)
The next step is now disabled. But this does't prevent them from clicking "overzicht" and submitting the old data:
![image](https://user-images.githubusercontent.com/112621537/193238043-b1525e43-0cc5-4ca6-b54d-ffad654c0b60.png)

### Verwacht gedrag / Expected behavior

When the next step is disabled, the submit and overzicht steps should also be disabled.

**Comment by joeribekker** [comment]
latest on september 30 was just before 2.0.0-beta.0 / just after 1.1.5

@LaurensBurger can you still reproduce this in 2.1.0-alpha.2 (latest now).

**Comment by LaurensBurger** [comment]
@joeribekker still possible

**Comment by joeribekker** [comment]
@SilviaAmAm can you have a look at this? If there be dragons then we move it to 2.2 but otherwise I want this in 2.1 if still possible.

**Comment by SilviaAmAm** [comment]
Notes:
- Clicking on the 'overzicht' link (or navigating to the overzicht by changing the URL) doesn't actually persist the data of the with the condition. So if the user actually submits the step, the form has valid data.
- In the `update` endpoint of the form step, there is no check to see if the `can_submit` is true or false, so a malicious user could make a request to persist the data and then navigate to the overzicht.
- In the `_complete` endpoint of the submission, there is no check to see if all the steps can be submitted.

So, things to fix:
- Make links non-clickable in case of a 'block going to the next step' 
- Add check in the `update` endpoint or the `_complete` endpoint to check if the step can be submitted
