### ISSUE TITLE
Label for each iteration of the repeating group

### ISSUE THREAD

**Issue by SilviaAmAm** [open-formulieren/open-forms#2101]
### Thema / Theme

Frontend

### Omschrijving / Description

Taiga issue 266

At the moment, when a user is filling in a repeating group, each iteration doesn't have its own title (for example item 1, item 2,...).

This is present in the overview page but not while filling the form.

Note: I remember we were discussing this, but I couldn't find a related issue.

**Comment by hlmr-erik** [comment]
This is on our wishlist @Haarlemmermeer as well. Some overlap with: https://github.com/open-formulieren/open-forms/issues/1883
