### ISSUE TITLE
Required fields not in viewport can cause users to get "stuck" at bottom

### ISSUE THREAD

**Issue by LaurensBurger** [open-formulieren/open-forms#2103]
### Product versie / Product version

1.1.6

### Omschrijf het probleem / Describe the bug

internal ref: venr 27

Having many fields can cause the browser to not react to the warning about the field being required, which could be caused because the fields are not in the view port.
The user is instead left at the bottom of the page with a disabled "next" button and has to scroll up to find the fields that have warnings.

"Stuck" at bottom:
![image](https://user-images.githubusercontent.com/112621537/193798637-3a50f97c-da30-4d56-b390-0f3062a807de.png)

After manually scrolling up:
![image](https://user-images.githubusercontent.com/112621537/193798868-0fbcd296-55cd-42ec-bcaf-e2458c32afa2.png)

### Stappen om te reproduceren / Steps to reproduce

1. Have a step with many fields, at least enough to not see a required field when clicking "volgende"
2. Do not fill in the required field
3. Scroll down
4. Click "volgende"
5. Button will turn grey as user should be directed to warning about requirement, but instead the screen remains at the bottom

### Verwacht gedrag / Expected behavior

The user should be alerted, even if the field is not visible. 

### Screen resolution

any

### Device

Desktop, mobile

**Comment by SilviaAmAm** [comment]
I think this is the same issue as https://github.com/open-formulieren/open-forms/issues/2082
So we should backport the fix to fix it in 1.1.7

**Comment by joeribekker** [comment]
@LaurensBurger I guess this was fixed then in 2.0? If not, please re-open the ticket
