### ISSUE TITLE
Starting an embedded form while logged into the admin, doesn't work (CSRF)

### ISSUE THREAD

**Issue by joeribekker** [open-formulieren/open-forms#2104]
### Product versie / Product version

2.0.0-beta0

### Omschrijf het probleem / Describe the bug

When you integrate Open Forms into your own website, you see the form without errors and click start, you then get a CSRF error.

```json
{
  "type":"https://example.com/fouten/PermissionDenied/",
  "code":"permission_denied",
  "title":"Je hebt geen toestemming om deze actie uit te voeren.",
  "status":403,
  "detail":"CSRF Failed: Referer checking failed - no Referer.",
  "instance":"urn:uuid:8035c81f-35a0-4a10-850b-ca11e0d7839f"
}
```

Similar to https://github.com/open-formulieren/open-forms/issues/1627 ?

Starting the same form when incogito or logged out of Open Forms, it works.

**Comment by sergei-maertens** [comment]
Fixed via #2116
