### ISSUE TITLE
Suspending a form shows error/warning - logout failed

### ISSUE THREAD

**Issue by LaurensBurger** [open-formulieren/open-forms#2114]
### Product versie / Product version

latest

### Omschrijf het probleem / Describe the bug

When a user suspends a form an error occurs:
![image](https://user-images.githubusercontent.com/112621537/194037006-d73eb67f-12a5-4b29-86eb-bb146d7a2b09.png)

The session is correctly paused and the user will receive an email.

The error is caused by a incorrect url being called to logout of the session:
**DELETE** /api/v1/authentication/session
That results in:
405 Method Not Allowed

It should contain the session uuid:
**DELETE** /api/v1/authentication/uuiddd-uuid-uuid-uuid-uuiduuiduuid/session
That results in:
204 No Content

**Comment by sergei-maertens** [comment]
The deprecated endpoint was indeed deleted - we'll have to patch the SDK for this. The culprit is in `FormStepSaveModal.js`
