### ISSUE TITLE
Opmaak fields are wrongly included in "Formfields are always required" setting

### ISSUE THREAD

**Issue by LaurensBurger** [open-formulieren/open-forms#2120]
### Product versie / Product version

1.1.7

### Omschrijf het probleem / Describe the bug

These "opmaak" fields have no user input and should not have:
```json
  "validate": {
    "required": true
  },
```
added to them when the global setting is enabled.
![image](https://user-images.githubusercontent.com/112621537/194247688-42f59991-e820-4e89-835f-f174175fd686.png)
![image](https://user-images.githubusercontent.com/112621537/194247922-d4943dc6-f988-49cb-af54-e870f430c9a6.png)

**Comment by sergei-maertens** [comment]
I see a reference in #1724 that should have fixed this, but apparently it wasn't backported.

**Comment by LaurensBurger** [comment]
#1724 seems to only include "content". the issues is also affecting the "fieldgroup" and "columns" components:
![image](https://user-images.githubusercontent.com/112621537/194493804-462a363e-ed24-4bd0-a0c6-755804f7651f.png)
![image](https://user-images.githubusercontent.com/112621537/194494077-e900a332-cc20-4ca6-918c-7ec8492e2413.png)

**Comment by sergei-maertens** [comment]
@LaurensBurger is this something you noticed in the JSON, or is it actually causing problems?

**Comment by joeribekker** [comment]
@sergei-maertens @LaurensBurger can you decide if this ticket should remain open or can it be closed?

**Comment by sergei-maertens** [comment]
I'll take care of updating the patch, it's weird how it's now including and cause problems/confusion in the future.
