### ISSUE TITLE
Show Form button doesn't show form

### ISSUE THREAD

**Issue by marc4gov** [open-formulieren/open-forms#2121]
### Product versie / Product version

release/2.0.0

### Omschrijf het probleem / Describe the bug

After saving a (simple) form as `admin` user, it doesn't show up when I hit the 'Show Form' button.
In the logs I get a 404 error like so `2022-10-06 10:30:40,416 WARNING django.server  "GET /eenadres/ HTTP/1.1" 404 16927`

### Stappen om te reproduceren / Steps to reproduce

1. Add and save a form
2. Hit 'Show form'
<img width="1196" alt="Schermafbeelding 2022-10-06 om 10 37 00" src="https://user-images.githubusercontent.com/9572139/194264177-792c360a-8fc9-4bdb-ab08-257df96112b4.png">

### Verwacht gedrag / Expected behavior

I would expect a preview of the created form
<img width="632" alt="Schermafbeelding 2022-10-06 om 10 40 44" src="https://user-images.githubusercontent.com/9572139/194265001-5398ef52-3fd8-49ad-b03f-877e146945ec.png">

### OS

MacOS

### Browser

Chrome, Safari

**Comment by alextreme** [comment]
Misschien moet je het formulier actief maken?

**Comment by marc4gov** [comment]
nee, dat maakt niet uit, maar dan krijg ik wel een andere error `2022-10-06 11:54:58,485 WARNING django.server  "GET /static/sdk/open-forms-sdk.js HTTP/1.1" 404 1936`

**Comment by alextreme** [comment]
Als je een andere error krijgt dan is je formulier nu wel toegankelijk.

De SDK 404 geeft aan dat je lokale Open Formulieren installatie niet in orde is, de OpenFormulieren SDK is niet geinstalleerd of beschikbaar:

https://open-forms.readthedocs.io/en/latest/installation/docker_compose.html?highlight=install%20SDK

https://open-forms.readthedocs.io/en/latest/installation/config.html?highlight=SDK

**Comment by marc4gov** [comment]
Ok, correct. Wel handig als dat met de installatie van open-forms automatisch meekomt, ipv dat je het apart moet installeren
