### ISSUE TITLE
Progress indicator doesn't scroll all the way

### ISSUE THREAD

**Issue by SilviaAmAm** [open-formulieren/open-forms#2139]
### Product versie / Product version

2.0.0-rc.1

### Omschrijf het probleem / Describe the bug

Taiga DH user story 257, 234

When there is a long progress indicator with many steps, on mobile it is impossible to scroll all the way to the bottom.

### Stappen om te reproduceren / Steps to reproduce

- Create a form with 10 steps
- Open it on mobile
- Try to scroll to 'bevestiging'

Tested on DuckDuckGo browser and Chrome on Android

### Screen resolution

smaller

### Device

Mobile

### OS

Android

### Browser

Chrome

**Comment by SilviaAmAm** [comment]
We discussed and decide that this should wait until we do the refactor of the progress indicator

**Comment by joeribekker** [comment]
Adding low prio to this ticket because filling in a 13-step form on your mobile seems a little masochistic. However, some people might only have a mobile phone making it painful but the only way to do it.

**Comment by joeribekker** [comment]
Sergei gaf aan dat markup gerefactored kan worden om dit netjes op te pakken (overlap met ticket over mobile css)

**Comment by joeribekker** [comment]
Refinement: Will be picked up with NLDS/Utrecht

**Comment by sergei-maertens** [comment]
Fixed via open-formulieren/open-forms-sdk#603
