### ISSUE TITLE
The SDK CSS and JS URLs need to have a redirect

### ISSUE THREAD

**Issue by joeribekker** [open-formulieren/open-forms#2141]
### Product versie / Product version

2.0.0-rc0

### Omschrijf het probleem / Describe the bug

Currently, the pre 2.0 URLs no longer work, like `/static/sdk/open-forms-sdk.js`
The version is now included, like this: `/static/sdk/1.2.1/open-forms-sdk.js`

I'm fine with versions BUT we need a generic URL as well.

When you integrate the snippet in your CMS, you typically don't want to update the snippet or your CMS website as a whole, just because you updated Open Forms that comes with a different SDK version.

So, please add (back) the generic URLs `/static/sdk/open-forms-sdk.js` and `/static/sdk/open-forms-sdk.css`

**Comment by sergei-maertens** [comment]
The logic has always been that a tagged (semver) release has the version number in the SDK urls, while running `latest` did not have a version number in there.
