### ISSUE TITLE
(Offer the option to) not include the text from confirmation page in PDF

### ISSUE THREAD

**Issue by hlmr-erik** [open-formulieren/open-forms#2143]
### Thema / Theme

Other

### Omschrijving / Description

We'd like to include a text on the confirmation page to highlight the option of downloading the filled form as a PDF. However when this instruction is included in the PDF itself, it isn't appropriate.

On the confirmation page:
![image](https://user-images.githubusercontent.com/111565013/200253518-84af8a0d-1aa7-4ff3-93e4-c3507de69467.png)

As of now this text ends up in the PDF as well, and this cannot be set/changed:
![image](https://user-images.githubusercontent.com/111565013/195048389-3d3824cc-8f7b-45eb-a932-6df5e4fb6ed9.png)

**Comment by joeribekker** [comment]
Suggestion:

![image](https://user-images.githubusercontent.com/96970/210745668-7060ba76-d194-4992-8dbe-1197e0e0eeb4.png)
