### ISSUE TITLE
Refactor the SDK snippet in the admin

### ISSUE THREAD

**Issue by joeribekker** [open-formulieren/open-forms#2146]
### Thema / Theme

Admin

### Omschrijving / Description

The SDK snippet is currently shown at the bottom of the form designer. This snippet is ONLY needed when you want to paste this form on your website.

First of all, this doesn't seem like the best approach: hardcoding the JS snippet in your CMS. Second, if you do this, you typically only do it once, so 99% of the time the snippet is shown for no reason.

Idea: Let's create a new "generator page" where you simply select the form, press "generate snippet" button and it will show the JS/CSS to paste on your website. We can then also provide some basic instructions on how to do it. Additionally, we can add a link on the form detail/designer page that goes to this generator page, with the form pre-selected.

### Added value / Toegevoegde waarde

1. Less cruft in the main form page
2. Room for additional instructions on the generator page

**Comment by SilviaAmAm** [comment]
@joeribekker the snippet was removed by this PR: https://github.com/open-formulieren/open-forms/pull/2239

**Comment by joeribekker** [comment]
I'll leave this ticket exist because of the feature until an actual request comes along to do this.

Meanwhile, the fix in the above PR solves the immediate issue.

**Comment by sergei-maertens** [comment]
The generator aspect appears to be solved with some built-in support in the respective CMS'es used by the organizations, so closing this as 'stale'.
