### ISSUE TITLE
CSS issue with mode-selection buttons in Logic-tab in Formbuilder

### ISSUE THREAD

**Issue by Bartvaderkin** [open-formulieren/open-forms#2156]
### Product versie / Product version

master branch ~ commit dac5380fca3e8bfb

### Omschrijf het probleem / Describe the bug

![Screenshot from 2022-10-12 15-20-30](https://user-images.githubusercontent.com/54805673/195354066-fc594e79-cd1c-4731-8309-1d4054408ac2.png)

Margins and icon placement are not correct.

### Stappen om te reproduceren / Steps to reproduce

Click on the logic tab in the form builder.

### Screen resolution

bigger

### Device

Desktop

### OS

Linux

### Browser

Firefox

**Comment by joeribekker** [comment]
I'm closing this as it will (hopefully) be fixed by #2736
