### ISSUE TITLE
Een element moet kunnen worden aangepast in type zonder het bestaande element te verwijderen en een nieuwe toe ...

### ISSUE THREAD

**Issue by joeribekker** [open-formulieren/open-forms#216]
...te voegen. Bij deze aanpassingen blijft het element staan op dezelfde plek in het formulier (deze eis valt buiten het MVP).

Eis: Elementen 6.
Zie ook NvI: 17, 72, 146

**Verduidelijking**

Dit klinkt als een feature dat heel erg past bij een vorige oplossing en niet bij de huidige drag-en-drop functionaliteit. We horen graag of dit nog nodig is en hoe het dan zou moeten werken.

**Comment by joeribekker** [comment]
@BasvanRensDK legt in de projectgroep voor hoe vaak, wanneer, voor welke cases dit gebruikt wordt. @joeribekker geeft verder aan dat het veel werk is en slechts voor een beperkte set aan velden kan gaan werken.

**Comment by LBozarov** [comment]
@joeribekker deze mag vervallen.
