### ISSUE TITLE
Als formulierbouwer wil ik de sub-waarden van alle objectregistraties, waaronder HaalCentraal kunnen hergebruiken in alle daarna-volgende attributen

### ISSUE THREAD

**Issue by joeribekker** [open-formulieren/open-forms#2169]
Als formulierbouwer wil ik de sub-waarden van alle objectregistraties, waaronder HaalCentraal kunnen hergebruiken in alle daarna-volgende attributen, zodat ik context kan toevoegen aan het formulier.

Oorsprong: https://github.com/Dimpact-Samenwerking/Open-Formulieren/issues/51
RTM: 4.2
Story points: 40
Business value: 5

**Comment by sergei-maertens** [comment]
Once this is done, this means we can also pretty much drop everything of our `npFamilyMembers` component type which now performs certain queries to either StUF-BG or HaalCentraal BRP bevragen - if we can model it that this query is done as part of the form/submission execution and the data becomes available in variables, we can then focus on getting the values into the selectboxes/dropdown options to choose from.

**Comment by joeribekker** [comment]
> we can also pretty much drop everything of our npFamilyMembers component

I don't think it's being used but is there any migration path? Or move to deprecated components in the designer?

**Comment by sergei-maertens** [comment]
yeah, it should be possible to convert usage of it automatically into the respective logic actions to fetch the details and create a logic rule for affected forms

**Comment by joeribekker** [comment]
I want to discuss what to do with this ticket. The basic function is now in but there's lots of good stuff in this ticket to make everything better.

**Comment by joeribekker** [comment]
Refinement: Went over all bullets, updated them and decided the rest will come up when requested.
