### ISSUE TITLE
Een gebruiker kan een element of groep als zijnde 'repeterende' vraag toevoegen. Bijvoorbeeld in de situatie waarbij ...

### ISSUE THREAD

**Issue by joeribekker** [open-formulieren/open-forms#217]
...gezinsleden kunnen worden toegevoegd of extra bijlagen (deze eis valt buiten het MVP).

Eis: Elementen 7.
Zie ook NvI: 147

Tasks:
- [x] Activate multiple values for input fields https://github.com/open-formulieren/open-forms/pull/882
- [ ] Clarify if this needs to be done for fieldSets too

**Comment by joeribekker** [comment]
Form.io heeft support hiervoor maar styling moet nog gebeuren. Hier is een apart ticket voor ergens.

**Comment by sergei-maertens** [comment]
Styling issue: https://github.com/open-formulieren/open-forms-sdk/issues/8
