### ISSUE TITLE
Kaartmateriaal - Selecteeren eigen achtergrondkaart (PDOK/WMS/WMTS)

### ISSUE THREAD

**Issue by joeribekker** [open-formulieren/open-forms#2173]
Als formulierbouwer wil ik mijn eigen achtergrondkaart (PDOK/WMS/WMTS) kunnen selecteren voor het kaartattribuut, zodat ik de klant de relevante data laat zien en gebruik kan maken van het gemeentelijk kaartmateriaal.

Voorbeeld: Voor een aanvraag over snoeien in de openbare ruimte is een luchtfoto relevant. Voor een aanvraag van een vergunning is een BRT-kaart relevant.

Oorsprong: https://github.com/Dimpact-Samenwerking/Open-Formulieren/issues/40 RTM: 7.1 Story points: 20 Business value: 3

**Comment by joeridiederen** [comment]
Als MVP voor achtergrondkaart: BRT-A en Luchtfoto via PDOK
