### ISSUE TITLE
Kaartmateriaal - Navigeren binnen het kaartmateriaal

### ISSUE THREAD

**Issue by joeribekker** [open-formulieren/open-forms#2176]
Als formulierbouwer wil ik dat de klant de mogelijkheid krijgt om zelf te navigeren binnen het kaartmateriaal, zodat de klant altijd het juiste frame kan selecteren.

- Voorbeeld: Ik wil mijn eigen adres kunnen zoeken, waarna de kaart mij bij het juiste punt brengt.
- Voorbeeld: Ik wil de kaart kunnen verslepen met mijn vinger(s) of muis.

Oorsprong: https://github.com/Dimpact-Samenwerking/Open-Formulieren/issues/43 RTM: 7.3 Story points: 1 Business value: 3

Related: Dimpact PF-31

**Comment by hlmr-dave** [comment]
PF-31 / #2176 Navigeren binnen kaartmateriaal 
Bij deze story kan ik een aantal zaken hangen:

- We willen bij het navigeren binnen de kaart, dat het zoomniveau behouden wordt als er geklikt wordt op de kaart om een pin te plaatsen.
We willen ook dat men niet gelijk in de kaart kan scrollen met de kaart.
- Wat we hiermee bedoelen is: als je aan het scrollen bent met je mouse-wheel, om van boven naar beneden te gaan van het formulier, en je muis komt te staan op de kaart dat hij dan direct in- of uitzoomt. Dat willen wij niet. Wij maken ook gebruik van de leaflet en het is mogelijk om daar een overlay voor te gooien dat er een toestenbord key gebruikt moet worden in combinatie met het scrollen om met de kaart te kunnen in- en uitzoomen. 
-Op mobiel gedraagt dit hetzelfde dat je met het swipen niet de kaart verplaatst tenzij je twee vingers gebruikt.

-Misschien beter om hier een nieuwe story voor te maken, maar we willen een knop waarmee de kaart direct een pin plaatst op jouw locatie en daar naartoe
![Screenshot 2023-06-29 at 01 21 53](https://github.com/open-formulieren/open-forms/assets/111569473/9eb566b3-0823-4da7-ad46-69e2140374d0)
![Screenshot 2023-06-29 at 01 30 08](https://github.com/open-formulieren/open-forms/assets/111569473/c7d77809-bb50-4fa6-ba86-563fe5005026)
 gaat. Nu start hij bij jouw locatie als je toegang geeft tot je locatie maar als je weg navigeert dan kan je niet meer makkelijk terug naar je eigen locatie. 

Je kan de voorbeelden ook zelf live zien https://www2.formulieren.haarlemmermeer.nl/formulieren/direct-melden/no-login/locatie en kies overig.
