### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'prefill_plugin'

### ISSUE THREAD

**Issue by SilviaAmAm** [open-formulieren/open-forms#2206]
### Product versie / Product version

2.0.0-rc.0

### Omschrijf het probleem / Describe the bug

Sentry 317885

Seen on Den Haag test environment

```python
    def get_prefill_variables(self) -> List["SubmissionValueVariable"]:
        prefill_vars = []
        for variable in self.variables.values():
            prefill_plugin = variable.form_variable.prefill_plugin # Error here!
            if prefill_plugin == "":
                continue
            prefill_vars.append(variable)
        return prefill_vars
```

**Comment by sergei-maertens** [comment]
I suspect this is a race condition with the celery task to re-couple form variables and/or form modifications which made the form variable dissapear while the submission variable still exists?

**Comment by SilviaAmAm** [comment]
I think so! I think they were doing load tests, so celery had many tasks to go through. Probably the form was filled in again before the task to recouple could complete.
