### ISSUE TITLE
Setting logo size with design-token makes logo in e-mail display unscaled

### ISSUE THREAD

**Issue by hlmr-erik** [open-formulieren/open-forms#2219]
### Product versie / Product version

1.1.7

### Omschrijf het probleem / Describe the bug

When setting the size of the logo with design-tokens thus:
![image](https://user-images.githubusercontent.com/111565013/196775073-ba1f8bf2-e960-4a7f-8ccb-174c9be730a4.png)

The logo in the forms and PDF resizes accordingly, however, it seems to throw off the resizing done in the e-mail: the image is displayed in its original size (a png of ~1000px in this case).

![image](https://user-images.githubusercontent.com/111565013/196776206-3e2cff33-05bc-4e66-be88-6dc697abddb8.png)

Without these design tokens in place the image is resized to a (OpenForms default) size:
![image](https://user-images.githubusercontent.com/111565013/196777304-39e10c64-6316-4935-9388-25d51315a7b2.png)

**Comment by hlmr-erik** [comment]
@Bartvaderkin The design-tokens used are correct; the link you provided shows the tokens for 2.0 - our instance is on 1.1.7 hence these apply: https://open-forms.readthedocs.io/en/1.1.7/configuration/general/styling.html Also, the size of the logo is scaled correctly (following the size set w/token) in the form itself - it just goes wrong in the e-mail.

**Comment by sergei-maertens** [comment]
This is included in the 1.1.8 bugfix release

**Comment by hlmr-erik** [comment]
@sergei-maertens @Bartvaderkin This still doesn't work properly in Outlook (w/ OpenForms 2.0.0) 
![image](https://user-images.githubusercontent.com/111565013/201962246-a26645ff-c477-4c9d-8705-a4980d44b082.png)
 I looked at the source of the e-mail and there I see 'px' added to the image size settings: 
![image](https://user-images.githubusercontent.com/111565013/201961833-51e033c8-c751-4589-bbc7-5fd5b379bc02.png)
This seems to be the culprit https://stackoverflow.com/a/20990036/19595009

**Comment by sergei-maertens** [comment]
@pi-sigma feel free to look into this

**Comment by hlmr-erik** [comment]
@sergei-maertens That could have explained it very well, though I just tested it in our production environment running 1.1.8 with the same result.

**Comment by pi-sigma** [comment]
@hlmr-erik Do you mean you get the same *wrong* results on 1.1.8? In that case, can you share a screenshot of the type you posted above? It seems to be working fine for me on 1.1.8.

**Comment by hlmr-erik** [comment]
@pi-sigma Indeed. Attached are the screenshots after sending a form on our production environment running OpenForms 1.1.8 
![image](https://user-images.githubusercontent.com/111565013/202695951-42992b6f-d5e8-4878-a976-6c608c9c2bb5.png)
![image](https://user-images.githubusercontent.com/111565013/202696733-17a3b7c4-b3ca-403d-8f06-1616c6fb2ad0.png)

And the set of design-tokens:
`{"color": {"link": {"value": "#07838f"}, "link-hover": {"value": "#9d2f86"}}, "footer": {"color": {"value": "#000"}, "background": {"value": "#07838f"}}, "layout": {"background": {"value": "#e6e6e6"}}, "logo-header": {"width": {"value": "400px"}, "height": {"value": "125px"}}, "page-header": {"color": {"value": "#07838f"}, "background": {"value": "#FFFFFF"}}}`

**Comment by joeribekker** [comment]
Since  we cannot reproduce this behaviour, please tell us which exact application you are using to view emails

**Comment by hlmr-erik** [comment]
In Thunderbird as well as KPN Webmail the header image shows like this
![image](https://user-images.githubusercontent.com/111565013/202745105-350e5eb8-3cae-4e78-a751-d9a64d1585e0.png)
Whereas in the PDF and in the form itself it does show in the right dimensions

**Comment by joeribekker** [comment]
I'm removing the backport label.

It's not a critical issue and the workaround is to just use an image that has the proper size :)
