### ISSUE TITLE
Een gebruiker kan condities in formulieren opnemen. De gebruiker krijgt alleen die stappen of velden gepresenteerd ...

### ISSUE THREAD

**Issue by joeribekker** [open-formulieren/open-forms#225]
...die bij de ingestelde condities horen.

Eis: Elementen 15.
Zie ook NvI: 151

**Tasks**

- [x] Bug remains that you can go back a step, even if it is marked as n.v.t.

**Comment by sergei-maertens** [comment]
need to check this with the current state of logic
