### ISSUE TITLE
Siteimprove not working

### ISSUE THREAD

**Issue by LaurensBurger** [open-formulieren/open-forms#2250]
### Product versie / Product version

latest

### Omschrijf het probleem / Describe the bug
internal: Rot 34

When adding siteimprove analytics: 

- CSP rules are added correctly

![image](https://user-images.githubusercontent.com/112621537/198017616-18e41b5d-c645-4087-92bd-140899d77aac.png)

- Cookies are added, but the "AWSELBCORS" cookie contains the localdomain instead of the siteimprove ID + domain: [accountID].global.siteimproveanalytics.io

subsequently no requests are made to: siteimproveanalytics.com, this behavious does not change when adding the "correct" cookies

**Comment by joeribekker** [comment]
Koppeling met Dimpact https://github.com/Dimpact-Samenwerking/Open-Formulieren/issues/4

**Comment by alextreme** [comment]
Discussed this with Laurens and after investigating this further with @joeribekker 

https://github.com/open-formulieren/open-forms/tree/master/src/openforms/analytics_tools

All non-Google analytics snippets (siteimprove, piwik, matomo) are not activating as expected. The snippets attempt to make use of `siteimprove_enabled` on the solo model however the model only has `is_siteimprove_enabled` and `enable_siteimprove_analytics`.

So this needs to be corrected and properly tested that when activating one of the analytics tools that these correctly appear (with the configured ID) in the rendered template.
