### ISSUE TITLE
Afspraken - Afspraak maken voor meerdere personen en meerdere producten

### ISSUE THREAD

**Issue by StefSchots1993** [open-formulieren/open-forms#2265]
### Thema / Theme

API

### Omschrijving / Description

- Probleembeschrijving/Organisatiebehoefte
Als inwoner wil ik voor meerdere personen en/ of producten tegelijk 1 afspraak maken. Ik krijg daarvoor automatisch een ruimer tijdvak. Ik krijg alleen de producten te zien die ik tegelijk met het 1e product kan aanvragen OF ik krijg de melding ‘deze combinatie is niet mogelijk’ als ik een product van een andere balie kies.

- Op welke onderdelen en/of schermen heeft het verzoek betrekking?
Koppeling afsprakensystemen JCC en Qmatic

- Mogelijke oplossingsrichtingen
Nieuwe API-calls

Get list of available dates for multiple services and customers
Get list of available times for multiple services and customers
Book an appointment for multiple customers and multiple services
Get all groups of services which can be booked together for a specific branch
- Wijze van totstandkoming

![173570745-062e6d63-0287-425b-9cee-3d23318dbc04 png (643×605) - Google Chrome 2022-11-01 08 07 50](https://user-images.githubusercontent.com/84498045/199178224-d366627d-dc1d-4cee-aedd-1c0fe8ae49c5.png)

### Added value / Toegevoegde waarde

- Geef aan welke waarde de wijziging toevoegt voor de bedrijfsvoering
Als gemeente kan ik medewerkers aan de balie efficiënt inzetten.

- Geef aan welke waarde de wijziging toevoegt voor de dienstverlening

Inwoners kunnen met hele gezin tegelijk langskomen en hoeven niet apart een afspraak te maken.
Arbeidsmigranten kunnen meerdere zaken tegelijk regelen (bijvoorbeeld tijdens de avondopenstelling op maandagavond).

### Aanvullende opmerkingen / Additional context

[Beschrijving JCC-Afspraken internetafsprakenadapter GGS2.pdf](https://github.com/Dimpact-Samenwerking/Open-Formulieren/files/9109444/Beschrijving.JCC-Afspraken.internetafsprakenadapter.GGS2.pdf)

De beschrijving van de koppeling met JCC-Afspraken.

**Comment by StefSchots1993** [comment]
@joeribekker - Ik kan het label Dimpact niet meegeven. Een rechten kwestie?

**Comment by StefSchots1993** [comment]
Oudere reactie van @joeribekker:

<html>
<body>
<p dir="auto" style="box-sizing: border-box; margin-top: 0px; margin-bottom: 16px; color: rgb(201, 209, 217); font-family: -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, Helvetica, Arial, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(13, 17, 23); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">Er is een afweging te maken:</p>

Speciaal formulier voor afspraken | Regulier formulier met afspraak functies
-- | --
voordelen | voordelen
Betere UI/UX mogelijk | Meer flexibiliteit met velden en stappen
nadelen | nadelen
Weinig formulier aanpassingen mogelijk | Formulier bouwen is lastig
- | UX is niet optimaal

<p dir="auto" style="box-sizing: border-box; margin-top: 0px; margin-bottom: 16px; color: rgb(201, 209, 217); font-family: -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, Helvetica, Arial, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(13, 17, 23); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">Besproken en akkoord om hier een "speciaal" formulier voor te maken. Dit formulier moet het volgende kunnen (nieuw, naast bestaande functionaliteit):</p><ul dir="auto" style="box-sizing: border-box; padding-left: 2em; margin-top: 0px; margin-bottom: 16px; color: rgb(201, 209, 217); font-family: -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, Helvetica, Arial, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(13, 17, 23); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><li style="box-sizing: border-box; margin-left: 0px;">Locatie niet uitvragen als er maar 1 locatie is</li><li style="box-sizing: border-box; margin-top: 0.25em; margin-left: 0px;">Product van te voren kunnen selecteren (vanaf de product pagina)</li><li style="box-sizing: border-box; margin-top: 0.25em; margin-left: 0px;">Meerdere producten en personen kunnen inplannen in 1 afspraak</li><li style="box-sizing: border-box; margin-top: 0.25em; margin-left: 0px;">Mail sturen (of niet in het geval de afspraak service deze stuurt) met daarin de product vereisten</li></ul><p dir="auto" style="box-sizing: border-box; margin-top: 0px; margin-bottom: 16px; color: rgb(201, 209, 217); font-family: -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, Helvetica, Arial, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(13, 17, 23); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">Typisch bestaat er slechts 1 formulier voor het maken van een afspraak. Daarbinnen kies je het product/producten.</p><p dir="auto" style="box-sizing: border-box; margin-top: 0px; margin-bottom: 16px; color: rgb(201, 209, 217); font-family: -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, Helvetica, Arial, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(13, 17, 23); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><strong style="box-sizing: border-box; font-weight: 600;">Nog uit te zoeken</strong></p><ul dir="auto" style="box-sizing: border-box; padding-left: 2em; margin-top: 0px; margin-bottom: 0px !important; color: rgb(201, 209, 217); font-family: -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, Helvetica, Arial, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(13, 17, 23); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><li style="box-sizing: border-box; margin-left: 0px;">Hoe speciaal is het speciale formulier? Is het een "vaste stap" of is het gewoon 1 hardcoded formulier?<span> </span><a class="user-mention notranslate" data-hovercard-type="organization" data-hovercard-url="/orgs/maykinmedia/hovercard" data-octo-click="hovercard-link-click" data-octo-dimensions="link_type:self" href="https://github.com/maykinmedia" style="box-sizing: border-box; background-color: transparent; color: var(--color-fg-default); text-decoration: none; font-weight: 600; white-space: nowrap;">@maykinmedia</a></li><li style="box-sizing: border-box; margin-top: 0.25em; margin-left: 0px;">Hoe kan Open Formulieren de juiste "vereisten" meesturen in de bevestigingsmail, als deze afhankelijk zijn van het gekozen product (of meerdere)? Hedda zoekt nog uit of dit in qmatic beheerd kan worden.</li></ul>
</body>
</html>Er is een afweging te maken:

Speciaal formulier voor afspraken	Regulier formulier met afspraak functies
voordelen	voordelen
Betere UI/UX mogelijk	Meer flexibiliteit met velden en stappen
nadelen	nadelen
Weinig formulier aanpassingen mogelijk	Formulier bouwen is lastig
-	UX is niet optimaal
Besproken en akkoord om hier een "speciaal" formulier voor te maken. Dit formulier moet het volgende kunnen (nieuw, naast bestaande functionaliteit):

Locatie niet uitvragen als er maar 1 locatie is
Product van te voren kunnen selecteren (vanaf de product pagina)
Meerdere producten en personen kunnen inplannen in 1 afspraak
Mail sturen (of niet in het geval de afspraak service deze stuurt) met daarin de product vereisten
Typisch bestaat er slechts 1 formulier voor het maken van een afspraak. Daarbinnen kies je het product/producten.

Nog uit te zoeken

Hoe speciaal is het speciale formulier? Is het een "vaste stap" of is het gewoon 1 hardcoded formulier? https://github.com/maykinmedia
Hoe kan Open Formulieren de juiste "vereisten" meesturen in de bevestigingsmail, als deze afhankelijk zijn van het gekozen product (of meerdere)? Hedda zoekt nog uit of dit in qmatic beheerd kan worden.

**Comment by StefSchots1993** [comment]
@joeribekker  - Weet niet of een comment in het verzoek een juist kanaal is voor deze vraag, maar ik doe het toch even.
Dit verzoek was destijds 1 november uitgevraagd om op te pakken en vanuit de SaaS groep kreeg ik vragen over de Status van dit verzoek. Ik was zelf in de veronderstelling dat deze ook ingepland zou worden, maar volgens mij is dat niet gebeurd? klopt dat?
Heeft dit verzoek een kans in de eerst opvolgende sprint?

**Comment by joeribekker** [comment]
heh, vandaag mee begonnen :)

**Comment by StefSchots1993** [comment]
gekoppeld aan https://github.com/Dimpact-Samenwerking/Open-Formulieren/issues/9
