### ISSUE TITLE
Accessibility - Waarneembaar - tekstalternatief /niet textuele context SC 1.1.1. A

### ISSUE THREAD

**Issue by StefSchots1993** [open-formulieren/open-forms#2266]
### Thema / Theme

Frontend

### Omschrijving / Description

**Thema**
Tekst alternatieven voor alle niet-tekstuele content, zodat die veranderd kan worden in andere vormen die mensen nodig hebben, zoals grote letters, braille, spraak, symbolen of eenvoudiger taal.

**Omschrijving**
Tekstalternatief bij het gemeente logo is nu "terug naar website" dit is volgens de WCAG niet voldoende. "terug naar website [organisatienaam]" is een tekstalternatief wat wel goed is.
De formulierstappen in het "rechter menu" hebben op dit moment geen tekst alternatief.

### Added value / Toegevoegde waarde

**Uitleg succescriterium**
Alle belangrijke niet-tekstuele content zoals afbeeldingen, knoppen en formulier invulvelden, moeten een tekstueel alternatief of naam hebben. Dan kan de voorleessoftware van blinde bezoekers die informatie voorlezen.

### Aanvullende opmerkingen / Additional context

[.Deelonderzoek techniek DimPact formulieren systeem WCAG 2.1 AA.pdf](https://github.com/open-formulieren/open-forms/files/9907908/default.Deelonderzoek.techniek.DimPact.formulieren.systeem.WCAG.2.1.AA.pdf)

**Comment by jiromaykin** [comment]
Dit issue kan verder worden opgepakt zodra issue https://github.com/open-formulieren/open-forms/issues/2428 klaar is.

**Comment by sergei-maertens** [comment]
Frontend still WIP
