### ISSUE TITLE
Accessibility - Waarneembaar - Aanpasbaar (info en relaties) SC 1.3.1 A

### ISSUE THREAD

**Issue by StefSchots1993** [open-formulieren/open-forms#2267]
### Thema / Theme

Frontend

### Omschrijving / Description

Thema 
- Beschrijving van thema/onderdeel binnen open formulieren

Omschrijving
- Op de overzichtspagina's komen koppen voor die slechts met "strong" zijn opgemaakt of slechts groter zijn afgebeeld dan reguliere tekst. De "strong" koppen zijn ook met het **th element** opgemaakt maar hiermee is incorrect de relatie tussen deze koppen en het onderliggende gedeelte van de tabel aangegeven. Het is semantisch correcter om de tabel in diens geheel op te splitsen en deze koppen aan te geven met een caption element of om de relaties binnen de tabel expliciet aan te geven met headingen id attributen. De grotere koppen zouden met heading elementen aangegeven moeten worden. Dit probleem komt op elke overzicht pagina voor.

![Accessibility - Waarneembaar - Aanpasbaar (info en relaties) SC 1 3 1 A · Issue #87 · Dimpact-Samenwerking_Open-Formulieren - Google Chrome 2022-11-01 08 52 29](https://user-images.githubusercontent.com/84498045/199185216-5ca9a857-332b-482c-a0b6-a0f4c8f5a163.png)

- Aan de rechterkant van elke formulier pagina staat een overzicht met stappen. Binnen dit overzicht word dikgedrukte tekst gebruikt om aan te geven welk stap de huidige stap is. Deze informatie is ook aangegeven met behulp van een kop bovenaan de pagina en daarom is dit succes criterium op dit punt niet afgekeurd. Toch wordt ook aangeraden om deze informatie in dit overzicht nogmaals te communiceren op een manier die ook beschikbaar is met hulpsoftware

### Added value / Toegevoegde waarde

Uitleg van succescriterium
Alle informatie die visueel wordt overgedragen, dient ook tekstueel of semantisch (in betekenisvolle code) te worden overgedragen. Op deze manier kan de informatie ook aan blinde bezoekers worden voorgelezen. Let in het bijzonder op het
volgende:
![Accessibility - Waarneembaar - Aanpasbaar (info en relaties) SC 1 3 1 A · Issue #87 · Dimpact-Samenwerking_Open-Formulieren - Google Chrome 2022-11-01 08 52 53](https://user-images.githubusercontent.com/84498045/199185287-e99730b1-671d-42bb-8db8-f501674f5395.png)

### Aanvullende opmerkingen / Additional context

[.Deelonderzoek techniek DimPact formulieren systeem WCAG 2.1 AA.pdf](https://github.com/open-formulieren/open-forms/files/9907919/default.Deelonderzoek.techniek.DimPact.formulieren.systeem.WCAG.2.1.AA.pdf)

**Comment by SilviaAmAm** [comment]
De structuur van de overzicht pagina was  in deze PR aangepast: https://github.com/open-formulieren/open-forms-sdk/pull/256
(het is geen tabel meer). Maar de relaties tussen de stappen/data moet nog gebeuren

**Comment by sergei-maertens** [comment]
Re-opening because not every item seems to be addressed yet.

**Comment by sergei-maertens** [comment]
From what I gather that's still to do:

* The progress indicator should ideally be wrapped in a `nav` element rather than a plain old `div` (correct?)
* Add an aria attribute to indicate the currently active step in the progress indicator, perhaps an aria-label "Current step: <name of step>"?

**Comment by jiromaykin** [comment]
Yes, semantic `nav` for the ProgessIndicator is better + note-to-self about aria-label code here: https://github.com/open-formulieren/open-forms-sdk/pull/301/files
