### ISSUE TITLE
Accessibility- Aanpasbaar - Inputdoel identificeren SC 1.3.4. AA here

### ISSUE THREAD

**Issue by StefSchots1993** [open-formulieren/open-forms#2268]
### Thema / Theme

Frontend

### Omschrijving / Description

Thema
Het doel van elk invoerveld waarmee informatie over de gebruiker wordt verzameld, kan door software worden bepaald.

**Omschrijving**
Bij geen van de formulieren is gebruik gemaakt van een autocomplete attribuut. Het autocomplete attribuut zou gebruikt moeten worden bij alle velden die informatie van de gebruiker vragen die in de volgende lijst voorkomt: https://www.w3.org/TR/WCAG21/#input-purposes.

### Added value / Toegevoegde waarde
**Uitleg van het succes ciriterium**
Het doel van elk invoerveld waarmee informatie over de gebruiker wordt verzameld, kan door software worden bepaald wanneer:

De invoervelden een doel dienen dat is geïdentificeerd in de paragraaf Inputdoelen voor componenten van de gebruikersinterface; en
De content wordt geïmplementeerd met technologieën waarmee de verwachte betekenis van de gegevens van het invoerformulier kan worden geïdentificeerd.

### Aanvullende opmerkingen / Additional context

[.Deelonderzoek techniek DimPact formulieren systeem WCAG 2.1 AA.pdf](https://github.com/open-formulieren/open-forms/files/9907942/default.Deelonderzoek.techniek.DimPact.formulieren.systeem.WCAG.2.1.AA.pdf)

### Tasks

* [x] Add autocomplete field to textield, postal code

**Comment by joeribekker** [comment]
Ik ben zelf niet zo'n fan van je voorstel. Zo komen er wel heel veel velden bij, die miniem van elkaar afwijken.

Ook ga je dan problemen krijgen als je vraagt naar: gegevens partner, gegevens kind, etc. Als je daar dan allemaal voornaam-veld bij gebruikt, wil de browser dat steeds voor-invullen?

Ik neig meer naar "autocomplete" attribuut beschikbaar maken in de form designer, met een dropdown. Die kunnen de designers dan zelf instellen. Ik zie het hergebruik van form-stappen in OF als voldoende vriendelijk: Als je eenmaal de stap netjes hebt gemaakt om persoonsgegevens in te vullen, kan je die hergebruiken MET de autocomplete velden al ingesteld.
