### ISSUE TITLE
Accessibility - Onderscheidbaar - Minimum contrast SC 1.4.3. AA 

### ISSUE THREAD

**Issue by StefSchots1993** [open-formulieren/open-forms#2269]
### Thema / Theme
Frontend

### Omschrijving / Description
**Omschrijving**
 - De visuele weergave van tekst en afbeeldingen van tekst heeft een contrastverhouding van ten minste 4,5:1, behalve in de volgende gevallen: Bij de formulieren staan witte teksten op blauwe knoppen. Deze teksten hebben een contrast van 4,3:1. Het minimum contrast voor dergelijke teksten is 4,5:1 verplicht. 

### Added value / Toegevoegde waarde
**Succescriterium**
Het doel van dit succescriterium is om voldoende contrast te bieden tussen de tekst kleur en de achtergrondkleur, zodat de tekst goed kan worden gelezen door kleurenblinde of slechtziende bezoekers. 

### Aanvullende opmerkingen / Additional context

[.Deelonderzoek techniek DimPact formulieren systeem WCAG 2.1 AA.pdf](https://github.com/open-formulieren/open-forms/files/9907952/default.Deelonderzoek.techniek.DimPact.formulieren.systeem.WCAG.2.1.AA.pdf)

**Comment by StefSchots1993** [comment]
https://github.com/Dimpact-Samenwerking/Open-Formulieren/issues/89

**Comment by jiromaykin** [comment]
Voorstel om de huidige kleur (=hsl(200, 99%, 37%)/#0180be) voor alle blauwe knoppen met witte tekst te veranderen naar hsl(200, 99%, 35%)/#0177b2 - dit resulteert in een contract-ratio van 4,9.
![screenshot-voorna-contrast](https://user-images.githubusercontent.com/118177951/204264027-2777900c-44dd-4b2e-9afd-580a8e083106.png)

**Comment by sergei-maertens** [comment]
re-opening, SDK needs to be updated still
