### ISSUE TITLE
Accessibility - Bedienbaar - Toetsenbord (navigeren) SC 2.1.1. A

### ISSUE THREAD

**Issue by StefSchots1993** [open-formulieren/open-forms#2270]
### Thema / Theme

Frontend

### Omschrijving / Description
**Thema** 
- Maak alle functionaliteiten bedienbaar vanaf het toetsenbord. Alle functionaliteit van de content is bedienbaar via een toetsenbord interface zonder dat afzonderlijke toetsaanslagen aan tijd gebonden zijn, behalve als de onderliggende functie een invoer vereist die afhangt van het pad dat de gebruiker aflegt en niet alleen van de eindpunten.

**Omschrijving**
- Bij geen van de formulieren is het mogelijk om met behulp van het toetsenbord een stap terug te gaan in het formulier. Dit komt omdat de "vorige" of "volgende" stap geen focus ontvangt. Dit komt omdat deze link geen **href** attribuut heeft. 
- Bij formulieren waar om een handtekening gevraagd word is het niet mogelijk om de "ververs" knop te gebruiken zonder gebruik te maken van de muis. 

**Nice to have**
-  De functionaliteit om überhaupt een handtekening te zetten kan ook niet bediend worden met het toetsenbord. Dit valt strikt gesproken onder de uitzondering genoemd binnen het SC, maar aangeraden wordt om gebruikers een alternatieve methode aan te beiden om hun handtekening te zetten die niet afhankelijk is van de muis.

### Added value / Toegevoegde waarde

**Uitleg van het succescriterium**
- Als de toetsenbordfocus met de toetsenbordinterface verplaatst kan worden naar een component van de pagina, dan kan de focus ook met alleen de toetsenbordinterface weer van dat component weg worden bewogen, en , als er meer nodig is dan de standaard pijl of tabtoetsen of andere standaard methoden om de focus te verplaatsen, dan wordt de gebruiker geïnformeerd over de manier waarop de focus kan worden verplaatst.

### Aanvullende opmerkingen / Additional context

[.Deelonderzoek techniek DimPact formulieren systeem WCAG 2.1 AA.pdf](https://github.com/open-formulieren/open-forms/files/9907956/default.Deelonderzoek.techniek.DimPact.formulieren.systeem.WCAG.2.1.AA.pdf)

**Comment by StefSchots1993** [comment]
https://github.com/Dimpact-Samenwerking/Open-Formulieren/issues/90

**Comment by SilviaAmAm** [comment]
Sinds deze PR https://github.com/open-formulieren/open-forms-sdk/pull/240 is het mogelijk om naar de vorige pagina te navigeren met de toetsenbord.

**Comment by SilviaAmAm** [comment]
Gerelateerde issue voor de border: https://github.com/open-formulieren/open-forms/issues/2410

**Comment by jiromaykin** [comment]
Voorstel om de randen, die de focus bij knoppen kunnen tonen, iets dikker te maken dan de randen die nu verschijnen bij de keuzerondjes en de aankruisvakjes:
![onfocus-styles](https://user-images.githubusercontent.com/118177951/204514373-c148cd3c-18cc-4873-9867-c46127fa0ce3.png)
