### ISSUE TITLE
Accessibility - Tijd - Timing aanpasbaar SC 2.2.1. A

### ISSUE THREAD

**Issue by StefSchots1993** [open-formulieren/open-forms#2271]
### Thema / Theme

Frontend

### Omschrijving / Description
**Thema**
Geef gebruikers genoeg tijd om content te lezen en te gebruiken. Voor elke tijdslimiet die door de content wordt ingesteld geldt ten minste een van de volgende zaken.

**Omschrijving**
De formulieren hebben een tijdslimiet waarna de gebruiker automatisch wordt uitgelogd. Een dergelijke tijdslimiet zou uitgezet, aangepast of verlengt moeten kunnen worden. Aangezien het uitzetten of aanpassen van deze tijdslimiet zou kunnen leiden tot beveiligingsissues in het geval van dergelijke formulieren wordt aangeraden om de gebruiker de mogelijkheid teg even om de tijdslimiet te verlengen. Dit houd in dat de gebruiker gewaarschuwd wordt 20 seconden voordat de tijdslimiet verloopt en met een makkelijke handeling de tijdslimiet kan verlengen(bijvoorbeeld door op de spatiebalk te drukken). Let op dat dit om een status bericht gaat (zie SC 4.1.3 voor eisen rondom statusberichten).

### Added value / Toegevoegde waarde
**Uitleg van het succescriterium**
- Als een bezoeker beperkt de tijd heeft om iets te lezen of te doen op de pagina, dient de mogelijkheid geboden te worden om de tijd uit te zetten, aan te passen (tot ten minste tien keer de standaard tijdperiode) of te verlegen ( minstens tien keer) Dit succescriterium is vooral belangrijk voor blinde en cognitief beperkte bezoekers.
Let in het bijzonder op

**Formulieren**
Als de sessie binnen een bepaalde tijd verloopt, dient deze te kunnen worden uitgezet, aangepast of verlengd.

**Banners, sliders, scrollende content:**
Beweging moet kunnen worden gepauzeerd, zodat de bezoeker de tijd heeft om de informatie te lezen / functionaliteit te bedienen.

**Refresh**:
Voorkom dat de pagina automatisch ververst na een bepaalde tijd.
Dit succescriterium moet in samenhang met Succescriterium 3.2.1 worden beschouwd, dat limieten stelt aan veranderingen van content of context als gevolg van een gebruikersactie.

### Aanvullende opmerkingen / Additional context

[.Deelonderzoek techniek DimPact formulieren systeem WCAG 2.1 AA.pdf](https://github.com/open-formulieren/open-forms/files/9908010/default.Deelonderzoek.techniek.DimPact.formulieren.systeem.WCAG.2.1.AA.pdf)

**Comment by StefSchots1993** [comment]
https://github.com/Dimpact-Samenwerking/Open-Formulieren/issues/91

**Comment by jiromaykin** [comment]
Op dit moment krijgt de gebruiker, indien de sessie op het punt staat te eindigen, de optie om de sessie verlengen. Dit is volledig toegankelijk via het toetsenbord.
De standaard sessie tijd kan door beheerders worden aangepast (maar mag bij een inlog met DigiD niet langer zijn dan  15 minuten).
![session-end](https://user-images.githubusercontent.com/118177951/205872186-700d8bd8-fc7e-4bfc-a750-e020a652263b.png)

**Comment by jiromaykin** [comment]
Gesloten omdat aan de criteria wordt voldaan: "Als de sessie binnen een bepaalde tijd verloopt, dient deze te kunnen worden uitgezet, aangepast of verlengd."
