### ISSUE TITLE
Accessibility - Navigeerbaar - Paginatitel 2.4.2 A

### ISSUE THREAD

**Issue by StefSchots1993** [open-formulieren/open-forms#2272]
### Thema / Theme

Frontend

### Omschrijving / Description
Thema: Webpagina's hebben titels die het onderwerp of doel beschrijven

**Omschrijving**
- Alle pagina's binnen de steekproef hebben dezelfde waarde binnen het titel element. "OpenForms". Deze waarde moet uniek zijn voor elke pagina. Let op dat ook verschillende pagina's binnen hetzelfde formulier unieke waardes moeten hebben in het title element.

### Added value / Toegevoegde waarde

**Uitleg succescriterium**
Bied een duidelijke, beschrijvende titel voor webpagina's. Gebruik hiervoor in HTML het title element. Een goede titel is belangrijk voor bezoekers met verschillende beperkingen. Het biedt een belangrijk hulpmiddel bij het navigeren door de website; men weet direct waar een pagina over gaat.

### Aanvullende opmerkingen / Additional context

[.Deelonderzoek techniek DimPact formulieren systeem WCAG 2.1 AA.pdf](https://github.com/open-formulieren/open-forms/files/9908051/default.Deelonderzoek.techniek.DimPact.formulieren.systeem.WCAG.2.1.AA.pdf)

**Comment by StefSchots1993** [comment]
https://github.com/Dimpact-Samenwerking/Open-Formulieren/issues/92

**Comment by SilviaAmAm** [comment]
Page titles can be added to the SDK with the [useTitle](https://github.com/streamich/react-use/blob/master/docs/useTitle.md) hook. Note the second point of this comment: https://github.com/open-formulieren/open-forms-sdk/pull/269#pullrequestreview-1144280470
