### ISSUE TITLE
Accessibility - Begrijpelijk- Assistentie bij invoer / fout identificatie SC 3.3.1. A

### ISSUE THREAD

**Issue by StefSchots1993** [open-formulieren/open-forms#2273]
### Thema / Theme

Frontend

### Omschrijving / Description

**Thema**
- Help gebruikers om fouten te vermijden en ze te verbeteren. Als een invoerfout automatisch ontdekt wordt, dan wordt het onderdeel waar de fout zit geïdentificeerd en de fout wordt tekstueel aan de gebruiker meegedeeld.

**Omschrijving**
- Als een gebruiker een veld niet of verkeerd invult en vervolgens de focus van het veld afhaalt verschijnt er een foutmelding. Dezelfde foutmelding verschijnt als een formulier verstuurd wordt zonder dat alle verplichte velden juist zijn ingevuld. In veel gevallen meld deze foutmelding echter niet dat er iets is mis gegaan. Een foutmelding zoals bijvoorbeeld "dit veld is verplicht" meld niet dat er iets is mis gegaan en een gebruiker die denkt dat die dat veld heeft ingevuld zou de melding kunnen zien als een standaardmelding die altijd en permanent bij dat veld staat. Een melding zoals "Dit verplichte veld is niet ingevuld" zou een voorbeeld zijn van een foutmelding die wel wordt goedgekeurd. Dit probleemkomt bij elk formulier voor,

### Added value / Toegevoegde waarde

**Uitleg van het succescriterium**
Zorg voor goed identificerende foutmeldingen, wanneer een formulier niet kan worden verstuurd. Verwijs tekstueel naar het invoerveld dat niet correct is ingevuld. Vermijd woorden als 'dit veld is verkeerd ingevuld'. Voor blinde bezoekers is het namelijk beter om concreet de naam van het veld te noemen.

### Aanvullende opmerkingen / Additional context

[.Deelonderzoek techniek DimPact formulieren systeem WCAG 2.1 AA.pdf](https://github.com/open-formulieren/open-forms/files/9908078/default.Deelonderzoek.techniek.DimPact.formulieren.systeem.WCAG.2.1.AA.pdf)

**Comment by StefSchots1993** [comment]
https://github.com/Dimpact-Samenwerking/Open-Formulieren/issues/93

**Comment by jiromaykin** [comment]
@joeribekker Het enige verplichte veld dat nu een gespecificeerde invul-fout aangeeft is het Postcode veld. 
Ik weet niet of ik in de SDK een dynamische message kan toevoegen aan de standaard "Dit veld is verplicht." message die nu uit de back-end komt.

**Comment by joeribekker** [comment]
* [ ] Vervang "dit veld is verplicht" -> "Dit verplichte veld is niet ingevuld"
* [ ] Als er genoeg context is in de validator, dan graag de melding maken: "Het verplichte veld {naam veld} is niet ingevuld"
* [ ] Gelieve all foutmeldingen te voorzien van de veldnaam, zoals hierboven, indien mogelijk.
