### ISSUE TITLE
Accessibility - Robuust - Compatibel/ Statusberichten SC 4.1.3

### ISSUE THREAD

**Issue by StefSchots1993** [open-formulieren/open-forms#2276]
### Thema / Theme

Frontend

### Omschrijving / Description

**Thema** 
- In content kunnen statusberichten door software worden bepaald met behulp van rol of eigenschappen, zodat de berichten aan de gebruiker getoond kunnen worden zonder dat deze de focus krijgen.

**Omschrijving**
- In content kunnen statusberichten door software worden bepaald met behulp van rol of eigenschappen, zodat de berichten aan de gebruiker getoond kunnen worden zonder dat deze de focus krijgen.

### Added value / Toegevoegde waarde

**Uitleg van succescriterium**
In content die is geïmplementeerd met opmaaktalen kunnenstatusberichten door software worden bepaald met behulp van  rol (role) of eigenschappen (properties), zodat hulptechnologieën de berichten aan de gebruiker kunnen laten zien zonder dat ze de focus krijgen

### Aanvullende opmerkingen / Additional context

[.Deelonderzoek techniek DimPact formulieren systeem WCAG 2.1 AA.pdf](https://github.com/open-formulieren/open-forms/files/9908131/default.Deelonderzoek.techniek.DimPact.formulieren.systeem.WCAG.2.1.AA.pdf)

**Comment by StefSchots1993** [comment]
https://github.com/Dimpact-Samenwerking/Open-Formulieren/issues/96

**Comment by joeribekker** [comment]
Als ik de PDF lees gaat het om alle fout-berichten, die voorzien moeten worden van een aria-live / role:

![image](https://user-images.githubusercontent.com/96970/207292465-f69a4b3b-1713-40e9-b365-baa536119d8d.png)
