### ISSUE TITLE
Een gebruiker kan stappen in een formulier via een intelligente wijze overslaan. Van stap 1 naar 3 zonder ...

### ISSUE THREAD

**Issue by joeribekker** [open-formulieren/open-forms#229]
...stap 2 te zien.

Eis: Sturing Formulier 3.

**Comment by sergei-maertens** [comment]
This is the behaviour where a step is conditional based on filled out data in (an) earlier step(s)

**Comment by sergei-maertens** [comment]
Need to verify this with the current state of form logic.
