### ISSUE TITLE
namshi/smtp vereist root rechten op OpenShift

### ISSUE THREAD

**Issue by ThomasIAm** [open-formulieren/open-forms#2295]
### Product versie / Product version

2.0.0

### Omschrijf het probleem / Describe the bug

Bij het uitrollen van Open Formulieren op OpenShift loopt de namshi/smtp container stuk op en chmod operatie. Het lijkt erop dat deze applicatie ervanuit gaat dat er root rechten beschikbaar zijn in een omgeving, maar dat is niet gewenst in onze situatie.

Ik ben zelf aan het kijken of er een alternatief is wat ik kan shift-and-lift'en, maar wellicht dat jullie hier een goed idee over hebben.

```
+ sed -ri '
s/^#?(dc_local_interfaces)=.*/\1='\''[0.0.0.0]:8025 ; [::0]:8025'\''/;
s/^#?(dc_other_hostnames)=.*/\1='\'''\''/;
s/^#?(dc_relay_nets)=.*/\1='\''10.128.8.249\/23'\''/;
s/^#?(dc_eximconfig_configtype)=.*/\1='\''internet'\''/;
' /etc/exim4/update-exim4.conf.conf
+ update-exim4.conf -v
using non-split configuration scheme from /etc/exim4/exim4.conf.template
chmod: changing permissions of '/var/lib/exim4/config.autogenerated': Operation not permitted
```

### Stappen om te reproduceren / Steps to reproduce

1. Rol de namshi/smtp container uit op OpenShift. Bijvoorbeeld door `oc new-app namshi/smtp` uit te voeren.
2. Tijdens het opstarten van de container zie je de volgende output:
```
+ sed -ri '
s/^#?(dc_local_interfaces)=.*/\1='\''[0.0.0.0]:8025 ; [::0]:8025'\''/;
s/^#?(dc_other_hostnames)=.*/\1='\'''\''/;
s/^#?(dc_relay_nets)=.*/\1='\''10.128.8.249\/23'\''/;
s/^#?(dc_eximconfig_configtype)=.*/\1='\''internet'\''/;
' /etc/exim4/update-exim4.conf.conf
+ update-exim4.conf -v
using non-split configuration scheme from /etc/exim4/exim4.conf.template
chmod: changing permissions of '/var/lib/exim4/config.autogenerated': Operation not permitted
```

### Verwacht gedrag / Expected behavior

De SMTP-oplossing zou geen root rechten nodig moeten hebben om te kunnen draaien. In dit geval zou de applicatie geen chmod commando uit mogen voeren.

### Device

Anders / Other

### OS

Anders / Other

**Comment by sergei-maertens** [comment]
De SMTP oplossing in de `docker-compose.yml` is maar een hulpmiddel en niet vereist voor productie/echte omgevingen. Je kan gerust een andere SMTP service gebruiken of deployen.

Dit is wat ons betreft out-of-scope.
