### ISSUE TITLE
Implement translations UI in form designer

### ISSUE THREAD

**Issue by sergei-maertens** [open-formulieren/open-forms#2314]
Depends on #2313 to save the translations, epic #2170

We need to implement/add a basic UI to manage translations in the form designer. In the future it's likely we'll get an export/import functinality as well for outsourced translations.

## Form tab

Wireframe
![image](https://user-images.githubusercontent.com/5518550/200286357-5df59cc4-8d7c-4d63-b4bb-33ec1a17beec.png)

- [x] Reorganize tab content in sections `Details` and `Configuration` - we can use the blue or grey dividers used in other tabs
  
  * "Details" contains the translatable fields (name, explanation template)
  * Configuration contains all the other fields

- [x] Add tabbed translation interface for the translatable fields. `settings.LANGUAGE_CODE` should be the first, and the remaining languages are additional tabs. Activating a tab shows the same form but with the content from that particular language.

## Steps and fields tab

Wireframe
![image](https://user-images.githubusercontent.com/5518550/200286412-dfbe7182-d817-45a5-9c3b-eb846387b1fa.png)

- [x] Wrap the "Form definition" section fields in translation tabs
- [x] Fields that are not translatable should become read-only except for when the primary language tab is active.

## Confirmation tab

- [x] Add translation tabs wrapper to every section (section header goes _above_ the tabs)

## Literals tab

- [x] Add translation tabs wrapper

## Formio component UI

Loading and persisting these translations is tracked via #2315

This concerns the edit component modal (left pane with config, right pane with preview)

- [x] Add a tab "translations" to every component
- [x] Add a nested tab interface with a tab for every supported language
- [x] Within a language tab, allow editing (datagrid?) the key-value map.
- [x] Only take translatable fields into account: label, description, select/radio option labels, content HTML...

Formio does not support context-aware translations, it's simply a key-value map. So the left side (key) should display the values that are filled out in the other form designer tabs, while the right side will have the translated version for that key.

## General considerations

These apply to all the tabs/sections

**Comment by stevenbal** [comment]
I think this one can be closed now? Since #2315 is done as well
