### ISSUE TITLE
Implement saving formio translations

### ISSUE THREAD

**Issue by sergei-maertens** [open-formulieren/open-forms#2315]
Epic #2170

Formio by default applies translations to a number of properties:

* `component.label`
* `component.description`
* `component.placeholder`
* `component.tooltip`
* `option.label` (for select, radio etc.)

Dynamic translations are a bit sketchy with Formio, so we need to build our own solution to
be able to inject these. Furthermore, we will ensure translations remain re-usable and
store them with the `FormDefinition` model.

- [ ] Add a JSONField `FormDefinition.translations`. The intended structure inside is:
  ```json
  {
    "nl": {
      "<componentPropertyValue>": "<Dutch translation>"
    }
  }
  ```
- [ ] Hook up loading and saving this translations data in the form designer (see #2314)

**Comment by stevenbal** [comment]
@sergei-maertens while working on this, I noticed that the solution I was working on does not really seem to work too well in the case of reused translations. For instance, say I have a field `Field1` with the following translations: `{"en": {"foo": "bar"}}`. If I then create a second field `Field2` that uses the same literal `foo` somewhere and navigate to the `Translations` tab, there are no translations shown there yet (not until the configuration is saved and reloaded).

Is this a big issue?

**Comment by sergei-maertens** [comment]
> @sergei-maertens while working on this, I noticed that the solution I was working on does not really seem to work too well in the case of reused translations. For instance, say I have a field `Field1` with the following translations: `{"en": {"foo": "bar"}}`. If I then create a second field `Field2` that uses the same literal `foo` somewhere and navigate to the `Translations` tab, there are no translations shown there yet (not until the configuration is saved and reloaded).
> 
> Is this a big issue?

It's far from ideal, but I think for the time being we can accept this is the way it is. Once there's a "ready enough" implementation to review, we can revisit this aspect and check how we can fit a solution in the implementation ("now" or later).

**Comment by stevenbal** [comment]
#2437 is ready for review, I split off three issues to address the remaining stuff:
- https://github.com/open-formulieren/open-forms/issues/2475
- https://github.com/open-formulieren/open-forms/issues/2477
- https://github.com/open-formulieren/open-forms/issues/2478
