### ISSUE TITLE
Define data model to configure data-fetching actions (JSON services)

### ISSUE THREAD

**Issue by sergei-maertens** [open-formulieren/open-forms#2332]
Epic #2169

This initially focuses on JSON-based services. SOAP/StUF will be handled in a separate model.

- [x] Define model `variables.ServiceFetchConfiguration` with the fields:
      * `service` FK to `zgw_consumers.Service` - this will be used for authentication credentials etc. 
      * `path` - URL relative to `Service.api_root` -> endpoint to hit
      * `method` - `GET|POST` (POST because Haal Centraal goes that way, this should not be used to mutate data!)
      * `headers` JSONField - merged with default service headers. If duplicates exist, this value overrides duplicates.
      * `query_params` - querystring parameters (not used with POST)
      * `body`: JSONField, used with POST only and only supports JSON (for now)
      * `data_mapping_type`: `none|JsonLogic|jq`
      * `mapping_expression` JSONField - actual object/JSON/primitive for mapping type jsonLogic, string to be validated with python-jq if mapping type is `jq`
- [x] Add python-jq and implement mapping expression validation
- [x] Expose the model `variables.ServiceFetchConfiguration` in the admin (for developers/superusers primarily)

**Comment by CharString** [comment]
Validation only checks whether the expression is syntactically correct JsonLogic/jq, so no regard to input or output.
