### ISSUE TITLE
Hiding fieldsets doesn't clear their data

### ISSUE THREAD

**Issue by SilviaAmAm** [open-formulieren/open-forms#2340]
### Product versie / Product version

2.0.0

### Omschrijf het probleem / Describe the bug

Den Haag Taiga issue 334 

If a fieldset is marked as hidden by logic, the values of the components inside the fieldsets are not cleared.

### Stappen om te reproduceren / Steps to reproduce

Create a form with:
- A radio button with values `a` and `b`
- A fieldset with a text field inside. Mark the fieldset as "hidden"
- Logic rule: if the radio has value a: mark the fieldset as visible

Fill in the form:
- Select `a` for the radio
- Enter in the text field `This data should be cleared`
- Select `b` for the radio
- Submit the form

Check the submission => The textfield variable was not cleared

Example form on our maykin test environment: slug `test-data-clearing`

### Verwacht gedrag / Expected behavior

The data inside fieldsets should be cleared

**Comment by pi-sigma** [comment]
The difficulty is that field sets are not associated with a `form_variable`, so by the time one gets to the logic that handles the submission data ([submissions/admin.py](https://github.com/open-formulieren/open-forms/blob/master/src/openforms/submissions/admin.py) and [submissions/models/submissions.py](https://github.com/open-formulieren/open-forms/blob/master/src/openforms/submissions/models/submission.py)), the only variables directly available for inspection or modification are those for the radio button and for the text field. It is of course possible to get a hold of the field set in [submissions/admin.py](https://github.com/open-formulieren/open-forms/blob/master/src/openforms/submissions/admin.py) via `submission` > `form_id` > `form_step` > `form_definition`. It seems *ad hoc* to check the `hidden` value of the field set in the `change_view` function and then proceed to modify the attribute of the text field. However, doing it "properly" may require more global changes.

**Comment by sergei-maertens** [comment]
I'm seeing the problem because the logic is inverse - the default state is hidden and logic makes it visible, so the trigger cannot be used in "inverse" mode to clear some data.

Essentially, after/while evaluating all the logic rules, it seems like we need to do an extra reconciliation step to make the data consistent with the form configuration, which mutates the data, which in turn is input for further logic evaluation :thinking: 

this is a tough one

**Comment by sergei-maertens** [comment]
I started backporting this, but then came across tests for #1755 and #2056 which _aren't_ backported but affect the same codepaths. I don't think it's feasible to apply the backport for this ticket either, especially because it's inconsistent with similar earlier fixes, so I'm removing the label.
