### ISSUE TITLE
Deleting user deletes related audittrails

### ISSUE THREAD

**Issue by SilviaAmAm** [open-formulieren/open-forms#2352]
### Product versie / Product version

2.0.0

### Omschrijf het probleem / Describe the bug

DH Taiga user story 319, issue 318

If a user is deleted from the admin, then any auditrails related to that user are deleted too.

### Stappen om te reproduceren / Steps to reproduce

- Update a submission in  the admin
- See that there is an audittrail for this action
- Delete this user
- See that the audittrail has disappeared

### Verwacht gedrag / Expected behavior

It shouldn't be deleted

**Comment by sergei-maertens** [comment]
Solution: delete `delete_user` permission:

* remove from `default_groups.json` fixture
* add data migration to remove the permission from existing groups
