### ISSUE TITLE
Add a static variable for 'today'

### ISSUE THREAD

**Issue by hlmr-erik** [open-formulieren/open-forms#2357]
### Thema / Theme

Form designer

### Omschrijving / Description

We'd like to prefill a certain field with today's date. This is possible with the static variable 'now'; however this includes the (dynamic) time as well.
Thus
![image](https://user-images.githubusercontent.com/111565013/202160944-0ba1a603-fa5a-428d-8099-6c627c6ca6f9.png)
Leads to
![image](https://user-images.githubusercontent.com/111565013/202160967-27b8466c-e3af-46d3-a437-6e66542adf8a.png)
Which, as an unwanted side-effect triggers form-validation every second because it keeps updating. 

I tried to use the jsonlogic `{"today": []}` in this place, but it didn't work (returned a nondescript error in the formbuilder when trying to save) and played around to see if I could get the [operators on 'now' used in templates](https://open-forms.readthedocs.io/en/latest/manual/templates.html#formattering-van-variabelen) working here, but to no avail as well.

**Comment by hlmr-erik** [comment]
@SilviaAmAm I did try this, also tried changing the field to a text-field to circumvent the restrictions of a `datetime `field. Just the JSON-logic doesn't support the same syntax as in templates, so I tried to fiddle around a bit like this: 
![image](https://user-images.githubusercontent.com/111565013/202388680-986f2a65-001b-4a7e-8c74-ae837c0772ef.png)
but that didn't work

**Comment by SilviaAmAm** [comment]
Ahh I meant in the default value of the component, but I hadn't realised that there you can only use the date picker to set the default value but not a string with the variables:
![Screenshot from 2022-11-17 09-37-27](https://user-images.githubusercontent.com/19154114/202397601-7ed449cb-b0aa-411a-8757-ab23af512908.png)
And I see that adding it to the json of the component causes a 500 in the backend when starting the form :/

**Comment by SilviaAmAm** [comment]
https://github.com/open-formulieren/open-forms/pull/2383 added a today variable

**Comment by hlmr-erik** [comment]
> #2383 added a today variable

So this can be closed then :) I only recently found out as well that it is possible to achieve with the 'now' variable and Django templating
