### ISSUE TITLE
SDK: The first header in the page is H2 (there is no h1)

### ISSUE THREAD

**Issue by SilviaAmAm** [open-formulieren/open-forms#2360]
### Thema / Theme

Frontend

### Omschrijving / Description

Den Haag user story 323, issue 321

On the start page, the name of the form is a H2 (there is no H1). 
The progress indicator title is also an H2.
On the form step pages, the title of the step is also an H2.

(Same problems on the summary page and the confirmation page).

### Added value / Toegevoegde waarde

Accessibility

**Comment by joeribekker** [comment]
Discussed with Sergei. For now, we 'll go for the simple solution which should be WCAG correct:

h2->h1
h3->h2
etc.
