### ISSUE TITLE
Design token: --Link-hover-color not used consistent throughout forms

### ISSUE THREAD

**Issue by LaurensBurger** [open-formulieren/open-forms#2377]
### Product versie / Product version

latest

### Omschrijf het probleem / Describe the bug

```json
    "link": {
        "color": {
            "value": "#000"
        },
        "hover": {
            "color": {
                "value": "fuchsia"
            }
        }
    }
```
--of-Link-color is (correctly) used for most hyperlinks with the exception of the progress-indicator. The hover token instead is only used in a single component of the forms the a11y-toolbar:
![image](https://user-images.githubusercontent.com/112621537/203314820-38b1fc60-0b98-4fb2-8ce1-faa2332a33bb.png)

This might be intentional but as a form designer i expect the links that originate from either the wysiwyg editor and text fields to also use the --link-hover-color token.

**Comment by SilviaAmAm** [comment]
In the start page, link 1 has the correct colour and hover colour, but link 2 has only the right colour (not hover colour). 
![hover-start-page](https://user-images.githubusercontent.com/19154114/209168673-7988b431-0cdb-4f34-a16f-b73245b292cd.png)

In the step, it's the same. Both link 1 and 2 have the right colour but not the hover colour.
![hover-step](https://user-images.githubusercontent.com/19154114/209168679-5e67cc99-600a-49a6-8f67-faf47ec0590a.png)

I'm don't think that the Progress indicator steps should have the link colour / hover?  :thinking:
