### ISSUE TITLE
Een gebruiker kan een overzicht (samenvatting) krijgen van de in het formulier ingevulde gegevens en de mogelijkheid ...

### ISSUE THREAD

**Issue by joeribekker** [open-formulieren/open-forms#240]
...krijgen om deze ingevulde gegevens alsnog aan te passen (teruggaan).

Eis: Verzending 5.
Zie ook NvI: 159

**Acceptance criteria**

- [x] When the last (available) step of a form is submitted, a summary page is shown
- [x] The summary page displays the details of every form step in the form, displaying the submitted data
- [x] Each form step summary is properly styled
    - [x] Using the FormIO form renderer in read-only mode
    - [x] Every form step has a link to "edit" the data, which returns to that particular step in the form to edit

Notes:

- the read-only mody can _probably_ be achieved by setting FormIO to the 'html' render mode, but this needs to be confirmed/checked with the docs
- the links/URLs to a particular step depend on #178 -- so placeholders for the time being are fine
- currently the SDK only works for single-step forms, this also depends on #178

**Comment by BasvanRensDK** [comment]
@joeribekker is het mogelijk om het overzicht niet te tonen? Zodat de gebruiker het formulier optioneel ervoor kiest om bij een formulier het overzicht te tonen?

**Comment by sergei-maertens** [comment]
@BasvanRensDK op dit moment is overzichtspagina een cruciale stap om de inzending te bevestigen en doorzetten naar achterliggende registratie, maar maak gerust een user story aan in de backlog die na het PvE kan opgepakt worden (ik ga er even vanuit dat dit geen bestaande userstory is nu). :-)

Kort antwoord: niet mogelijk (op dit moment)
