### ISSUE TITLE
SDK: Border on `:focus-visible` missing from buttons

### ISSUE THREAD

**Issue by SilviaAmAm** [open-formulieren/open-forms#2410]
### Product versie / Product version

SDK commit: 5575d97f09edf514965bdcae516e1f3a9366fd32

### Omschrijf het probleem / Describe the bug

Since this commit: https://github.com/open-formulieren/open-forms-sdk/commit/5575d97f09edf514965bdcae516e1f3a9366fd32 

The nice orange border around buttons that are in focus (using tab navigation) is missing.
![Screenshot from 2022-11-28 16-10-26](https://user-images.githubusercontent.com/19154114/204312353-9cd01537-38ba-4dc0-ae20-107768c2c41b.png)

### Verwacht gedrag / Expected behavior

When using tab navigation, the buttons at the bottom of the form should have the border colour.

**Comment by jiromaykin** [comment]
The orange border is only orange in Firefox (in different browsers they have a different on-focus style color) but they could have the same border-style as we now use for the checkboxes and radiobuttons (part of Accessibility improvement issue: https://github.com/open-formulieren/open-forms/issues/2270)
