### ISSUE TITLE
Een gebruiker kan een inzending van een formulier exporteren naar een bestandsformaat, minimaal zijnde XML- en ...

### ISSUE THREAD

**Issue by joeribekker** [open-formulieren/open-forms#242]
...JSON-bestandsformaat.

Eis: Verzending 7.
Zie ook NvI: 161

**Tasks**

* [x] Add bulk export action in admin to export data in XML format. This can be plain XML.
* [x] Add bulk export action in admin to export data in JSON format. This can be plain JSON.

Examples:

```
<?xml version="1.0" encoding="UTF-8" ?>
<submissions>
    <submission>
        ... all rows as in CSV <key>value</key>
    </submission>
    ...
</submissions>
```

```
[{
     ... all rows as in CSV "key": "value"
}]
```

**Verduidelijking nodig**

~Dit lijkt op een export in CSV/Excel zoals staat in #182 . Wat houdt deze export dan in? Of is dit het wegschrijven als bestanden naar een bestandssysteem?~

**Comment by joeribekker** [comment]
In overleg met de stakeholders is JSON voldoende gebleken in combinatie met het toevoegen van velden als extraElementen in XML-StUF.

**Comment by joeribekker** [comment]
In overleg met gemeenten MPV label verwijdert door onduidelijkheid.

**Comment by joeribekker** [comment]
Verder doorgeschoven door blijvende onduidelijkheid.

**Comment by joeribekker** [comment]
Met groep overlegt: Dit is soortgelijk aan Excel/CSV

**Comment by KingYoshi** [comment]
@Bartvaderkin Hoi Bart. Ik zou graag met je in contact komen. Kan ik je ergens bereiken, op Discord of elders? Vriendelijke groet.

**Comment by sergei-maertens** [comment]
@KingYoshi please do not harass contributors to this project. This is completely off-topic and not appreciated.
