### ISSUE TITLE
Allow steps to be hidden from overview when not applicable/disabled

### ISSUE THREAD

**Issue by LaurensBurger** [open-formulieren/open-forms#2444]
### Thema / Theme

Form designer

### Omschrijving / Description

internal: utr 13 + DH 382 + BD

As a form designer i want to be able to hide steps of the form that are disabled. The current solution shows all steps and grey's out steps that become irrelevant based on input from the user.

Allowing the form designer to hide these steps next to disabling them creates cleaner results for the users.

New progress-indicator:
![image](https://user-images.githubusercontent.com/112621537/206171171-1fa402a7-1a2e-4441-965e-a823a77ae982.png)

Current:
![image](https://user-images.githubusercontent.com/112621537/206171383-a6e95f47-8398-44d1-a6ee-e95d6fad93c8.png)

### Aanvullende opmerkingen / Additional context

in addition - this could also be part of a change where form steps are enabled, instead of disabled. 
requested by - bld

**Comment by joeribekker** [comment]
Refinement: Add design token option to hide n/a-steps

**Comment by sergei-maertens** [comment]
> Refinement: Add design token option to hide n/a-steps

So the wish of DH to make this a per-form setting is therefore not honoured - is that the conclusion?

**Comment by sergei-maertens** [comment]
@joeribekker the implementation using a design token is an accessibility violation, see https://github.com/open-formulieren/open-forms-sdk/pull/385#pullrequestreview-1369199725 for more details

**Comment by joeribekker** [comment]
You say this so strongly while I doubt its an accessibility issue. See reaction in the PR.

Setting this per form is inconsistent behaviour. If anything, then it's per step even. If this becomes a new issue, we can tackle it then.

Let's go for the resolution discussed in refinement.

**Comment by sergei-maertens** [comment]
I was wrong, clearly! Thanks for clearing it up - this approach is the most elegant one then :)
