### ISSUE TITLE
Repeating groups: fields shown by trigger from within repeating group, missing from overview

### ISSUE THREAD

**Issue by LaurensBurger** [open-formulieren/open-forms#2449]
### Product versie / Product version

2.0.0 / 2.1.0

### Omschrijf het probleem / Describe the bug

If a field has been made visible through clientside logic it is missing from the results/overview page.
![image](https://user-images.githubusercontent.com/112621537/206210049-7aecff28-9356-4880-ae55-1a90252a9ca8.png)
After saving item:
![image](https://user-images.githubusercontent.com/112621537/206211150-839a6f12-a7aa-47c5-a74f-c9b71183df1a.png)
results:
![image](https://user-images.githubusercontent.com/112621537/206212881-dcae1cba-cef7-4061-9f56-a538cc54c0b9.png)

data is present in submission:
test: [{'naam': 'Name', 'radio2': 1, 'leeftijd1': 99, 'justahiddencomponent': 'witnessme!'}]

**Comment by SilviaAmAm** [comment]
If we have a form with a repeating group containing 2 fields:
- A radio button with key `radioCondition` that can have values `a` and `b`
- A textfield with key `conditionallyVisible` with frontend logic saying that this field should show if the radio button has a value of `a`

Then in the `is_visible_in_frontend` function, the data will look like this:
```
{'repeatingGroup': [{'radioCondition': 'a', 'conditionallyVisible': 'Some data'}, {'radioCondition': 'b'}]}
```
But the condition looks like this:
```
{'eq': 'a', 'show': True, 'when': 'repeatingGroup.radioCondition'}
```
The key `repeatingGroup.radioCondition` is used to access the value in the data, but this doesn't have the index to refer to a specific iteration. So the rcondition evaluates to `False` even though it should be true for the first iteration.
