### ISSUE TITLE
SubFactories/Traits don't ensure Form.translation_enabled is always consistent with the current model

### ISSUE THREAD

**Issue by CharString** [open-formulieren/open-forms#2456]
### Product versie / Product version

dev

### Omschrijf het probleem / Describe the bug

What does it mean to have, say, a `FormDefinition` with `name_en` and `name_nl` set? But this holds for any object in the tree under a form.

### Screen resolution

None

### Device

None

### OS

None

**Comment by joeribekker** [comment]
Is this a philosophical question?

**Comment by CharString** [comment]
Aren't all data model questions? Until they trigger unexpected/unwanted behaviour.

It was unclear to me how to interpret the intention behind having these states of the data model and what we would expect from the factory.  Whether `translation_enabled` is expected to be True if any of the connected forms and definitions have been translated.
I guess the warning that was added since to the form designer for untranslated content when `translation_enabled` *is* True, shows both cases occur. I felt such validation was upcoming in some form, and wondered if not having this handled by the factory default would trip tests using it; an default instance from a factory should pass all validation.
