### ISSUE TITLE
DigiD OIDC doesn't work after keycloak update

### ISSUE THREAD

**Issue by SilviaAmAm** [open-formulieren/open-forms#2458]
### Product versie / Product version

all versions

### Omschrijf het probleem / Describe the bug

In the old version of Keycloak, the BSN of the user was saved as an attribute of the user after the first log in. 
Open Forms relies on the data retrieved from the `userinfo` endpoint for extracting the claims. In the old situation, the BSN was present in the response of the `userinfo` endpoint.

The problem for Keycloak in this situation is that many BSNs are present in the database and this is not desirable from the privacy point of view.

In the new situation, when the user logs into DigiD, the BSN is saved in the session. From the session it is added to the tokens (id and access token). This means that the BSN is present in the tokens, but not in the response from the `userinfo` endpoint.

We didn't notice that this wasn't working until now, because any users that had been used to log in  in the old situation still had the BSN saved in the database from previous logins. So everything went smoothly.

If possible, we should see if the BSN can be extracted from the tokens instead of the response from the `userinfo` endpoint.

### Screen resolution

None

### Device

None

### OS

None

**Comment by stevenbal** [comment]
Related issue in library: https://github.com/maykinmedia/mozilla-django-oidc-db/issues/59
