### ISSUE TITLE
Registratie - Specificeren locatie MS Graph

### ISSUE THREAD

**Issue by StefSchots1993** [open-formulieren/open-forms#2469]
### Thema / Theme

Plugins

### Omschrijving / Description

Via: Horst Taiga 35

- Wij willen zelf de locatie generiek (eventueel per formulier, is niet noodzakelijk) specificeren binnen de huidige plugin MS Graph.
- Plugin MS Graph
- Toevoegen extra veld voor locatie in configuratie plugin.

### Added value / Toegevoegde waarde

**Toegevoegde waarde voor bedrijfsvoering**
We kunnen formulieren op een besloten Sharepointlocatie registreren. En daarna gerobotiseerd verder verwerken. Formulieren liggen daardoor binnen enkele minuten bij de afhandelaar in plaats van binnen 1 werkdag.

**Toegevoegde waarde voor de dienstverlening**
De indiener heeft sneller een reactie op de aanvraag omdat het formulier direct bij de afhandelaar lig

### Aanvullende opmerkingen / Additional context

https://github.com/Dimpact-Samenwerking/Open-Formulieren/issues/99
Label Dimpact / Horst aan de Maas

**Comment by StefSchots1993** [comment]
@joeribekker  - Verzoek vanuit Horst aan de Maas en Venray, zij zouden voor een intern project graag deze plug-in gerealiseerd zien. Met name vanuit hen de volgende vragen voor je deze eventueel in een sprint zou kunnen oppakken.
- Op welke termijn zou dit mogelijk op gepakt kunnen worden? - is de komende sprint een eventueel een mogelijkheid?
- Kun je een inschatting van de mogelijke kosten geven? Beide gemeenten willen deze ontwikkeling zelf financieren.

**Comment by joeribekker** [comment]
Paar dagen werk, komende sprint kan. Meer prio dan afspraken?

**Comment by StefSchots1993** [comment]
> Afspraken heeft wel meer prio, maar Venray en Maashorst zien dit wel graag gerealiseerd vanuit een gezamenlijk project en willen dit beide financieren. Voor ze een besluit kunnen nemen moeten ze intern ook de kosten kunnen verantwoorden. Ik zag overigens ook dat Maashorst er al een Taiga ticket voor had waarin ook al e.e.a. besproken was rond dit topic.

**Comment by SilviaAmAm** [comment]
@joeribekker Fixed by https://github.com/open-formulieren/open-forms/pull/2526 ?
