### ISSUE TITLE
Form designer FormIO translations UI: WYSIWYG content field translations

### ISSUE THREAD

**Issue by stevenbal** [open-formulieren/open-forms#2475]
Related issue: https://github.com/open-formulieren/open-forms/issues/2315

Issue raised in https://github.com/open-formulieren/open-forms/pull/2437

The `vrije tekst` field is a WYSIWYG content field, which will not work properly with the default translations setup implemented in the above PR. It should probably have a different translations tab that only shows one WYSIWYG editor per language, because only the content is translatable.

Question: will this content be picked up by FormIO's translation engine, or should we translate it when serializing the FormStepDefinition?

**Comment by sergei-maertens** [comment]
> Question: will this content be picked up by FormIO's translation engine, or should we translate it when serializing the FormStepDefinition?

It will be picked up, at least according to the default template: https://github.com/formio/formio.js/blob/4.13.x/src/templates/bootstrap/html/form.ejs#L5

```ejs
{{ctx.t(ctx.content)}}
```
the `t` function translates it.

**Comment by CharString** [comment]
Closed by #2544 (don't know why this wasn't automagically picked up)
