### ISSUE TITLE
Als beheerder wil ik dat de e-mailberichten die vanuit de formulieren component worden verstuurd voldoen aan de ...

### ISSUE THREAD

**Issue by joeribekker** [open-formulieren/open-forms#251]
...standaarden zoals deze opgenomen zijn in de Veilige E-mail Coalitie. Deze standaarden worden beschreven op https://nl.internet.nl/test-mail/ en bevatten tenminste: IPv6, Dmarc, Dkim, SPF, DNSSEC, Dane en Starttls (deze eis valt buiten het MVP).

Eis: Techniek 7.
Zie ook NvI: 84, 85, 111, 166

**Taken**

Zie technische issues: #152, #153 (en indien ruimte #142)

* [x] Fix what we can fix from our side.

**Comment by joeribekker** [comment]
Documenteer wat OF kan regelen en wat gemeente zelf moet regelen. En demonstreer/vertel dat dit bij RID naar behoren werkt.

**Comment by sjoerdie** [comment]
test.openformulieren is dit nu ingeregeld.
