### ISSUE TITLE
Celery worker dies if the pod has been down too long

### ISSUE THREAD

**Issue by joeribekker** [open-formulieren/open-forms#2521]
### Product versie / Product version

2.0.2

### Omschrijf het probleem / Describe the bug

If a Celery worker pod is down and you bring it up again, it doesn't connect to Redis anymore.

Reported by @sjoerdie 

Might be this https://stackoverflow.com/questions/52072305/celery-worker-stops-after-being-idle-for-a-few-hours

### Screen resolution

None

### Device

None

### OS

None

**Comment by LaurensBurger** [comment]
Haarlemmermeer 14

**Comment by joeribekker** [comment]
Probably fixed/related by #2927

**Comment by sergei-maertens** [comment]
The health checks are available in the latest version and Sjoerd was adding them to our cloud deployments tooling. I haven't seen a PR yet though

**Comment by sergei-maertens** [comment]
#3092 did some additional efforts + backporting of the fixes, so this will be resolved with the next patch releases
