### ISSUE TITLE
maxDate/minDate validation of datetime component causing issues 

### ISSUE THREAD

**Issue by LaurensBurger** [open-formulieren/open-forms#2525]
### Product versie / Product version

2.x.x

### Omschrijf het probleem / Describe the bug

After saving the maxDate of a datetime componenten we can see the following data being saved:
```json 
                    "maxDate": {
                        "mode": "",
                        "delta": {
                            "days": null,
                            "years": null,
                            "months": null
                        },
                        "operator": "add",
                        "variable": "now",
                        "includeToday": null
                    },
```
Which causes no errors but when we reopen the componentin the form designer we see:
![image](https://user-images.githubusercontent.com/112621537/210317611-e882aa59-be98-4908-9b83-421549c1d263.png)

At this point the frontend will cause a 500: sentry 321892, because there is no method defined for the validation.

The component needs to be saved again in the backend with at least a mode/method assigned to maxDate and minDate.

There should be a possibility to remove the validation and this should be correctly displayed in the form designer. If the method can not be empty it should not be possible to remove them.

This can be reproduced by removing the validation from the component for either maxDate of minDate field.

**Comment by SilviaAmAm** [comment]
To reproduce the 500, create a form with:
- A date component
- Save and continue editing the form
- Go to the validation tab of the date component
- Remove "vaste waarde"
![remove-vaste-waarde](https://user-images.githubusercontent.com/19154114/213125534-59ad3f36-9848-4370-904a-dc7401b8637b.png)

Now try filling in the form => A 500 error is returned from the backend
