### ISSUE TITLE
De beheerder kan medewerkers die formulieren beheren laten inloggen (Single Sign On) met hun account van ADFS ...

### ISSUE THREAD

**Issue by joeribekker** [open-formulieren/open-forms#254]
...of AzureAD (deze eis valt buiten het MVP).

Eis: Autorisatie En Gebruikersbeheer 2.
Zie ook NvI: 56, 168

**Comment by joeribekker** [comment]
Wat rest hier is testen of OIDC ook werkt ADFS/AzureAD.

**Comment by joeribekker** [comment]
Voor Den Haag werkt dit al maar dan met Keycloak er tussen... Is dit voldoende?

**Comment by sergei-maertens** [comment]
ADFS on prem & Azure AD ondersteunen in principe allebei Open ID connect, dus met de generieke koppeling moet dit werken. @joeribekker zullen we dit testen met onze eigen AAD?

**Comment by sergei-maertens** [comment]
Tested with our own Azure AD configuration and works as intended
