### ISSUE TITLE
Migrating logic rules can cause errors

### ISSUE THREAD

**Issue by joeribekker** [open-formulieren/open-forms#2542]
### Product versie / Product version

latest (2.1.0-alpha1)

### Omschrijf het probleem / Describe the bug

_Sentry: 322890_

While updating to the latest version, the migration that tries to generate a logic-sentence bugs out.
I think it happened on this expression, with `rdelta` with the following exception:

`Unexpected number of operation arguments, got 1, expected 3`

```json
{
    "and": [
        {
            "<": [
                {
                    "date": {
                        "var": "geboortedatumMedebewoner"
                    }
                },
                {
                    "-": [
                        {
                            "today": []
                        },
                        {
                            "rdelta": [
                                21
                            ]
                        }
                    ]
                }
            ]
        },
        {
            ">": [
                {
                    "date": {
                        "var": "geboortedatumMedebewoner"
                    }
                },
                {
                    "-": [
                        {
                            "today": []
                        },
                        {
                            "rdelta": [
                                38
                            ]
                        }
                    ]
                }
            ]
        }
    ]
}
```

Also, I think we should encapsulate this whole operation with try/except and just fill in "Unable to figure out representation." or something. This data migration is not critical to bug out like this. Exception logging can still happen ofcourse.

**Comment by sergei-maertens** [comment]
this is actually a bug in the description generation, not in the migration handling
