### ISSUE TITLE
Appointment future ticket

### ISSUE THREAD

**Issue by joeribekker** [open-formulieren/open-forms#2543]
* [x] Add the appointment-mode to the API so the frontend can render te proper views
* [x] Create a frontend appointment-flow, according to the mockup below
* [x] If there is only 1 location available, don't ask the user for the location but just "select" it
* [x] The final step (of the appointment flow) will need to ask for certain fields, that are to be retrieved from the APIs (required fields, like last name, date of birth, etc.)

**Comment by sergei-maertens** [comment]
All items are ticked off in the current implementation in the SDK/backend.
