### ISSUE TITLE
Accessibility - Cookie banner is overlapping footer links

### ISSUE THREAD

**Issue by LaurensBurger** [open-formulieren/open-forms#2549]
### Product versie / Product version

latest

### Omschrijf het probleem / Describe the bug

The cookie notice should not overlap the footer as this block accessibility to the list items in the footer. Which in turn causes the focus on these items to not be visible.

### Verwacht gedrag / Expected behavior

Desktop
![image](https://user-images.githubusercontent.com/112621537/212094000-fa5bb3b6-f64c-4d7a-a7f4-4a9dee8dcab4.png)

Mobile
![image](https://user-images.githubusercontent.com/112621537/212094122-1af1c6c7-2521-418f-b168-0dce4727ec11.png)

**Comment by sergei-maertens** [comment]
doesn't work as expected yet on mobile

**Comment by jiromaykin** [comment]
Issue seems to be only occurring in Chrome on Android, possibly due to "URL bar resizing"
