### ISSUE TITLE
Compare date and time with variable 'now' + some delta

### ISSUE THREAD

**Issue by SilviaAmAm** [open-formulieren/open-forms#2557]
### Thema / Theme

Form designer

### Omschrijving / Description

DH Taiga issue 359, user story 361

At the moment, there is no way to have a date and a time in a form and combine them to compare them to a datetime.

For example, in DH they have a form to report road works. In this form there are a date and a time field to specify the start of the road works.
In case that the combination date + time are more than 24h in the future, some logic is applied.

To do:
- Figure out how to compare the date + the time fields with a variable
- Figure out if its possible to specify a delta for a datetime in the jsonlogic package.

**Comment by sergei-maertens** [comment]
We'll see next week if this can fit in 2.1.0 or not - for now I've set it to 2.2.0, but I'll try my best!
