### ISSUE TITLE
Date variable (user variable) is stored as date + time 

### ISSUE THREAD

**Issue by LaurensBurger** [open-formulieren/open-forms#2581]
### Product versie / Product version

2.0.0 - latest

### Omschrijf het probleem / Describe the bug

this causes issues with logic, where a date variable is expected but a datetime variable is used.
https://github.com/open-formulieren/open-forms/blob/c129aa820712f5dda98aea9148d07e9a4ec31745/src/openforms/submissions/models/submission_value_variable.py#L348
Adding .date() to this line solves this issue for form logic.

### Screen resolution

None

### Device

None

### OS

None

**Comment by sergei-maertens** [comment]
note: this brings us in the domain of [#2324](https://github.com/open-formulieren/open-forms/issues/2324)
