### ISSUE TITLE
Replace the 403 on the root URL

### ISSUE THREAD

**Issue by LaurensBurger** [open-formulieren/open-forms#2615]
### Thema / Theme

Other

### Omschrijving / Description

This 403 for all request (except a beheerder's) on the root of the domain seems to cause issues for municipalities who wish to scan/crawl their OF domain. 
Analytics tools/website analyzers etc. are reporting OF is "blocking" their activity.

Does this 403 serve a purpose, or could it be replaced by a page with a 200 referring non-beheerder users back the the organisation website? 

### Aanvullende opmerkingen / Additional context

reported by: siteimprove, monsido

**Comment by sergei-maertens** [comment]
> Does this 403 serve a purpose, or could it be replaced by a page with a 200 referring non-beheerder users back the the organisation website?

If the main website URL is configured, this redirect behaviour is exactly what happens.

it is intentional because that list page exposes _all_ the available forms which should not be information shown/leaked to regular non-staff users.
