### ISSUE TITLE
Allow payment to be disabled for certain users

### ISSUE THREAD

**Issue by LaurensBurger** [open-formulieren/open-forms#2617]
### Thema / Theme

Form designer

### Omschrijving / Description

internal: utr 39 + lv 70

Utr: As a form designer i want to create forms that (for instance) need to be paid directly when user is auth_bsn, but when the user is auth_kvk we do not require this payment and instead send a invoice. The former is an example, I would like to be able to use logic in order to determine if payment is necessary or not 

LV: We would like to skip/disable payment under certain conditions - this condition could be when the form is completed by someone else (like a employee) or when the user has no possibility to pay online. 

### Aanvullende opmerkingen / Additional context

This could be achieved by creating a condition where if the price = 0, payment gets disabled. At the moment 0 will start a payment request for 0.

**Comment by joeribekker** [comment]
Refinement: Let's do amount=0 means no payment
