### ISSUE TITLE
Improve robustness/visibility of "bad" variables used in choice-widgets

### ISSUE THREAD

**Issue by sergei-maertens** [open-formulieren/open-forms#2623]
Context: https://github.com/open-formulieren/open-forms/pull/2595#discussion_r1089188861

#2595 adds the feature to populate the dropdown/radio/selectboxes values from a variable. This _will_ be combined in the future with the feature to fetch data from remote services and store (a subset/subpath) of them in variables.

Currently the implementation has a line to check whether the json logic expression needs to be applied or not:

```py
is_obj = isinstance(items_array[0], dict)
```

This is fragile if the `items_array` is not homogenous - there's no guarantee that all items are a dict or even have the same keys/structure (response data from other APIs may be sparse, this is especially prevalent with the existing StUF services!).

What happens (expected) then is that the `jsonLogic` call for the lookup will fallback to the `None` value, possibly yielding non-unique values.

**Tasks**

- [ ] Add a check for duplicate values - log these both to the submission via `logevent` and to Sentry via `logger.warning(...)`
- [ ] If there are duplicate values, make them unique by adding a suffix (`0`, `1` etc.) (?)

**Comment by SilviaAmAm** [comment]
@sergei-maertens I am thinking that there is also the possibility that the user adds the same answer multiple times. Maybe we should:
- If a value is `None`, don't add it to the options
- When all items are processed, remove duplicate options
