### ISSUE TITLE
Detect invalid variable-based options configuration

### ISSUE THREAD

**Issue by sergei-maertens** [open-formulieren/open-forms#2624]
https://github.com/open-formulieren/open-forms/blob/ef167eabad493fdbe05fc651d1e87a9eedb3f446/src/openforms/formio/dynamic_config/dynamic_options.py#L53

Currently this configuration is logged within the submission audit trail, which is good to get visibility but a bit too late. We can improve this in a number of ways:

**Logging**

- [ ] Add `logger.warning(...)` call to get this in Sentry too (developers then have an idea of the source of issues)

**Warning in form designer**

The form-designer state has a full picture of the available variables (and their datatype, ideally?). In this first iteration, we limit the warnings to form variables related to components (so do nothing for user-defined variables, except for maybe validate that the UDV is a type: array variable).

Set up the warning (like similar warnings) at the form definition level to check that components configured with `itemsExpression` have `valueExpression` specified:

1. Match up the form variable for the given `itemsExpression`
2. If the form variable component is a `editgrid` (repeating group) component -> show a warning if `valueExpression` is not configured
3. If the form variable component is not an `editgrid` component -> show a warning if `valueExpression` is configured (as this doesn't have any effect)

In the future we'll figure out how to deal with user defined variables.

- [ ] Implement a warning/check in the form-designer.

**Comment by SilviaAmAm** [comment]
After implementing the changes from [this remark](https://github.com/open-formulieren/open-forms/pull/2630#issuecomment-1411890704), there is no longer the `valueExpression`. So this issue is now irrelevant.
