### ISSUE TITLE
Add logic/conditions to items in a group (selectboxes/radios/dropdown)

### ISSUE THREAD

**Issue by LaurensBurger** [open-formulieren/open-forms#2629]
### Thema / Theme

Form designer

### Omschrijving / Description

request: Utrecht 27

As a form designer i want to be able to show and hide items from a group of answers/options. Just like i can show and hide a group or field.
This feature will reduce the amount of fields i need to create to build a form as each deviation from the "common" answers is now also contained in the same group instead of creating a separate object for them.

Current situation:
![image](https://user-images.githubusercontent.com/112621537/215743180-c105543d-ef65-4f32-ada6-b0c236dd96cf.png)

New situation:
![image](https://user-images.githubusercontent.com/112621537/215744218-dc6a2725-adc6-45ae-a5ee-ebbcbbc02444.png)

![image](https://user-images.githubusercontent.com/112621537/215744960-d7a9e1b5-4650-46c2-8bcb-27ee0712bfd9.png)

**Comment by joeribekker** [comment]
Refinement: If #3277 is NOT fixed this prio becomes higher (or someone should fix #3277)

**Comment by joeribekker** [comment]
Refinement: This should be possible with setting lists of options. Someone check and document this as a recipe + downloadable form example.

**Comment by sergei-maertens** [comment]
Confirmed that the functionality is there, however there is an issue with being able to set the default value of the array user defined variable.

Other than that, I have an example form and will add an example to the documentation.

**Comment by sergei-maertens** [comment]
We will not backport the editor fixes, however there is a workaround: you can use a logic trigger `true` to always initialize the variable with a fixed list of options, and then another trigger + action to extend this list.
