### ISSUE TITLE
De beheerder kan betalingen ontvangen die doorgezet worden naar verschillende rekeningen. Dus kunnen koppelen ...

### ISSUE THREAD

**Issue by joeribekker** [open-formulieren/open-forms#265]
...op verschillende iDeal aansluitingen met daar bijhorende bankrekeningen. Voorbeeld: de betaling van formulier A gaat naar rekening 1, de betaling van formulier B gaat naar rekening 2.

Eis: Betalen 2.

**Comment by Bartvaderkin** [comment]
Currently if you select the Ogone payment backend you have to pick an OgoneMerchant instance (which has a PSPID etc).

We need to clarify if this cover this story or if we need something else, like sending additional parameters with the payment.

**Comment by sergei-maertens** [comment]
-> ensure frontend shows dropdown of available merchants

**Comment by sergei-maertens** [comment]
Fixed via a51c1a5618e1a4c294db35b5713b812e36967061, which allows selection of a merchant in a dropdown.
