### ISSUE TITLE
Get street and city request not triggered from fields in repeating group

### ISSUE THREAD

**Issue by LaurensBurger** [open-formulieren/open-forms#2656]
### Product versie / Product version

latest + 2.0.0
Utrecht 45

### Omschrijf het probleem / Describe the bug

The fields within a repeating group do not trigger the request to the endpoint and fail to retrieve city and street name. 
![image](https://user-images.githubusercontent.com/112621537/216972335-47221cbc-3a71-4a9b-b2a2-bbd9e5a0608a.png)

### Stappen om te reproduceren / Steps to reproduce

![image](https://user-images.githubusercontent.com/112621537/216972700-23611f41-dc51-4115-8041-7d4782a90392.png)

**Comment by sergei-maertens** [comment]
I wondered when this would be reported... :)

**Comment by joeribekker** [comment]
Similar to #2728

**Comment by joeribekker** [comment]
Refinement: Utrecht heeft dit al ingericht maar werkt nog niet. De verwachting is dat als dit gefixed is, het daarna wel werkt :)

**Comment by sergei-maertens** [comment]
Simple patch that can easily be backported, let's service our customers :)
