### ISSUE TITLE
Add AV-support to file uploads and provide user feedback

### ISSUE THREAD

**Issue by joeribekker** [open-formulieren/open-forms#2663]
### Thema / Theme

Other

### Omschrijving / Description

You can install AV on infrastructure level but this can cause errors when a file is deleted without Open Forms knowing about it. So, we can support AV out of the box and provide user feedback if needed.'

* [x] Add Docker container for AV to Docker compose (see https://hub.docker.com/r/clamav/clamav) and make sure ClamAV can scan uploaded files.
* [x] Add AV-integration in Open Forms by scanning finished uploaded file, or stream in progress (not sure which is possible atm)
* [x] Raise validation error if a virus is found, causing an error on the user facing frontend
* [x] Make sure an infected file is deleted and removed from the File Upload component
* [x] Add settings in General config admin, to talk to the AV-server.
* [x] Make AV an optional enabled feature.
* [x] Add documentation on adding this container and configure the AV settings

This is a minimal approach to AV. In the future we will most likely support infrastructure level scanning, different AV software, etc. 

### Added value / Toegevoegde waarde

AV in Open Forms

**Comment by SilviaAmAm** [comment]
Note: python wrapper for clamAV: https://docs.clamav.net/manual/Installing/Community-projects.html#python
