### ISSUE TITLE
QR-code for enabling MFA unreadable in dark mode

### ISSUE THREAD

**Issue by hlmr-erik** [open-formulieren/open-forms#2671]
### Product versie / Product version

2.0.3

### Omschrijf het probleem / Describe the bug

A collegue just tried to login to the admin portal for the first time, and noticed she couldn't scan the QR-code in dark mode:
![image](https://user-images.githubusercontent.com/111565013/217781190-f634ed4c-6730-49e9-b3e6-fbe2c95b6b04.png)
(QR code blurred for obvious reasons)

This only goes for the QR-code used for the initial setup: Upon investigating using Windows' native dark mode (no plugins), at first I couldn't reproduce it: The QR-codes in the TOTP tab of the admin panel -do- show with a white background.

### Stappen om te reproduceren / Steps to reproduce

1. Set Windows (10) to dark mode
![image](https://user-images.githubusercontent.com/111565013/217781764-49ed9725-f673-4f0a-a1ab-8728bc20414c.png)

2. Delete current (if any) TOTP device from the OF admin-panel

3. Login and try to set the TOTP device anew

### Tasks

* [ ] Enforce white background for QR-code (so also in dark mode)
* [ ] Make sure there is some white padding (10px?) around the QR-code

**Comment by pi-sigma** [comment]
Does the problem only occur on Windows or is it confirmed for other platforms? The QR code works for me when I follow the steps from above and recreate the TOTP device with dark mode enabled (on fedora linux). There is also some white padding around the QR code.

**Comment by hlmr-erik** [comment]
The same happens on OSX when I set Firefox to its native dark mode thus:
![image](https://user-images.githubusercontent.com/111565013/218467375-169f316e-8094-43d2-a93a-df0262d33ff2.png)
Just setting OSX to dark mode isn't sufficient, as this only changes the looks of the OS itself to dark mode - not the apps running on it. I suspect this might be the reason setting Fedora to dark mode isn't sufficient as well; as with Windows there is a separate setting to include all apps to run in dark mode as well:
![image](https://user-images.githubusercontent.com/111565013/218468628-1434e723-4b03-412d-8d5a-4f380584bcec.png)
