### ISSUE TITLE
Mobile view for forms looks horrible

### ISSUE THREAD

**Issue by sergei-maertens** [open-formulieren/open-forms#2673]
Inconsistent widths en spacing that is very "off".

Iphone 12 pro simulator in Chrome dev tools:

![image](https://user-images.githubusercontent.com/5518550/217819786-57814958-015a-4bb6-987b-937ff83b9c48.png)

**Comment by LaurensBurger** [comment]
- Menu does not close when selecting a step
- long string overflows container
- header and footer are too big compared to other content
- too much padding + margins left and right
- Step title and menu/step indicator are always identical which takes up alot of space
- Dropdown fields also have a search which immediately pops up the user keyboard which causes big shift
- Overview page: Lables are bold and answers/data normal, which isn't easy to read
- datetime modal can only closed by clicking outside of modal

**Comment by sergei-maertens** [comment]
Back to in-progress because of above remarks
