### ISSUE TITLE
Mobile: Start form buttons styling is not mobile

### ISSUE THREAD

**Issue by LaurensBurger** [open-formulieren/open-forms#2679]
### Product versie / Product version

latest

### Omschrijf het probleem / Describe the bug

The buttons on mobile differ between the start and the rest of the form, where once started the buttons are centered, the start form buttons are missing this mobile specific look:
![image](https://user-images.githubusercontent.com/112621537/218411541-ac9a3718-00b3-4a0e-b564-dd9e8d222803.png)

This does however only occur when authentication methods like DigiD are enabled for the form:
![image](https://user-images.githubusercontent.com/112621537/218412214-ae6e1219-d272-4185-8cc8-b765fa5cd022.png)
(correct mobile style button)

### Screen resolution

None

### Device

None

### OS

None

**Comment by sergei-maertens** [comment]
@SilviaAmAm how does this behave after the button refactor?

**Comment by SilviaAmAm** [comment]
It has the same problem, the buttons with login options are not centered on mobile

**Comment by sergei-maertens** [comment]
Checked this with Joeri and considered the various design options - the conclusion is that this is the lesser evil.

The with-login options reserve space for DigiD/eHerkenning logo's to the right. Using centered text on those buttons in combination with the buttons looks very unnatural. Expanding the anonymous button and centering that in the combination also looks very weird.

I'm not ruling out that if a stakeholder requests this, we add design tokens so the alignment/behaviour can be controlled, but for now: wontfix.
