### ISSUE TITLE
Perform service fetch operations only when required

### ISSUE THREAD

**Issue by CharString** [open-formulieren/open-forms#2688]
*From DH: "We need better speed on the service fetch, 2-5s without user feedback is a no-go"*

Taiga DH: 510 and 509

On form logic evaluation, this action type is one that updates variables so needs to be executed immediately (not go into the collection bucket).

#2169 suggests the fetch should only be done if the target variable has no value yet in the submission.

But the fetch action *should* be performed if any of the variables bound in the fetch parameters (path, query, headers, etc.) has changed value since the previous fetch, because it will result in a different request and therefore possibly different response. 

- [ ] only perform when we have no value yet (either because of the initial state or because previous fetches had 5XX errors)
- [ ] parse what names are bound in the fetch configuration ?
- [ ] persist what values those have when we perform the fetch operation ?
- [ ] re-fetch if bound values have changed in the context => should result in a different request !
- [ ] obey http caching headers like {vary, pragma, cache-control, etag} etc.

 
Requires #2454

**Comment by joeribekker** [comment]
I feel like this will become an issue when its used, but lets first observe how and how often this used and poses a problem.

**Comment by joeribekker** [comment]
Refinement: Not breaking but will cause slow forms. Needs stakeholder backing

**Comment by SilviaAmAm** [comment]
DH Refinement: This has priority for Den Haag

**Comment by SilviaAmAm** [comment]
Chris mentions that the problems are:
- The requests are done sequentially
- We often perform the same requests multiple times

The second problem could be solved with a caching proxy but then the headers on the API response need to let the caching proxy actually cache the responses. However, DH uses service fetch with the Objects API, which sets the header `Cache-Control: no-cache, must-revalidate, no-transform, no-store`.  So this would have to be changed to  be able to use caching.

**Comment by joeribekker** [comment]
@joeribekker Add results of meeting with Ritense here.
