### ISSUE TITLE
Mobile: Dropdown search field causes annoying behaviour

### ISSUE THREAD

**Issue by LaurensBurger** [open-formulieren/open-forms#2689]
### Product versie / Product version

latest

### Omschrijf het probleem / Describe the bug

When a user opens a dropdown field on mobile both the dropdown opens and because the focus is in the search field the user's keyboard also opens. This causes the screen to first shift down because of the dropdown opening and up again because of the keyboard opnening, which in turn can overlap the items available in the dropdown

On mobile the search field should either not get focus after opening the dropdown, or not be visible at all

before slecting dropdown:
![image](https://user-images.githubusercontent.com/112621537/218432907-f5d61680-8e6c-4fdd-b788-e147e021699e.png)

after selecting dropdown (don;t mind the dropdown background bug):
![image](https://user-images.githubusercontent.com/112621537/218433007-f238db5b-bd45-43c1-b4f0-3623a72ffbd4.png)

**Comment by SilviaAmAm** [comment]
This seems fixed after working on this issue: https://github.com/open-formulieren/open-forms/issues/2686

**Comment by joeribekker** [comment]
@LaurensBurger please check if you can reproduce this in the latest latest :)

**Comment by LaurensBurger** [comment]
@joeribekker semi fixed - When the mobile user opens the dropdown while they have no more "scroll" space at the bottom - this still happens:
![image](https://user-images.githubusercontent.com/112621537/221200467-90a86256-7e24-4a92-a579-3889dda91342.png)

**Comment by joeribekker** [comment]
@LaurensBurger can they still scroll the fields into view?

**Comment by LaurensBurger** [comment]
yes - it's not impossible to pick something from the list, just not nice

**Comment by sergei-maertens** [comment]
I'll take a look if there's an easy fix, but since this is some behaviour in choices.js which is used via formio I don't think I want to jump through many hoops here

**Comment by sergei-maertens** [comment]
I can't reproduce this on Brave on my Android phone - there is some shifting/scrolling happening, but not in an inconsistent manner. I don't see the shift down then up again happening 🤔 

Being completely scrolled down (i.e. there not being any more scroll space at the bottom), focusing the dropdown then results in the view scrolling up to bring the search field in the viewport and that looks like this:



![Image](https://user-images.githubusercontent.com/5518550/221907613-5b5c9943-adb0-44c5-95a8-1bb6bd14fcb5.png)

**Comment by sergei-maertens** [comment]
Evaluated in the office with a couple of test forms/variations and the behaviour is deemed acceptable.
