### ISSUE TITLE
Cancel fileupload adds extra fileupload section on bottom page

### ISSUE THREAD

**Issue by LaurensBurger** [open-formulieren/open-forms#2692]
### Product versie / Product version

latest

### Omschrijf het probleem / Describe the bug

![image](https://user-images.githubusercontent.com/112621537/218445598-8c0d91b9-efed-4ebf-8033-e17da4d0faf5.png)
![image](https://user-images.githubusercontent.com/112621537/218446534-c3b1923c-b228-450f-820e-4800fa205858.png)

```html
<input type="file" style="height: 0; width: 0; visibility: hidden;" tabindex="-1">
```

**Comment by joeribekker** [comment]
If this turns out to be hard, we can move it to another milestone.
