### ISSUE TITLE
Documentation improvements

### ISSUE THREAD

**Issue by sergei-maertens** [open-formulieren/open-forms#2696]
There is some outdated and disconnected documentation now related to service fetch:

- [x] The documentation about JSON logic mentions `map` not being available - this is no longer the case (see https://open-forms.readthedocs.io/en/latest/manual/forms/logic.html#id1)
- [x] The documentation about form field choices doesn't mention that these can be dynamic (https://open-forms.readthedocs.io/en/latest/manual/forms/form_fields.html#keuzelijst should link to https://open-forms.readthedocs.io/en/latest/manual/forms/examples/dynamic_options.html) and/or be restructured to mention this feature.

**Comment by stevenbal** [comment]
@sergei-maertens do we have an example of a use case for the `map` operation? I legitimately can't think of anything that somewhat fits in with the existing examples :sweat_smile:
