### ISSUE TITLE
Add "voorletters" prefill attributes to Stuf-BG, Stuf-BG plugin doesn't allow the ability to prefill 'voorletters'

### ISSUE THREAD

**Issue by LaurensBurger** [open-formulieren/open-forms#2710]
### Thema / Theme

Other

### Omschrijving / Description

SED: 41 + Utrecht 62 + LV 126

The Stuf-BG prefill plugin seems to be missing the ability to prefill using the initials/voorletters. Only voornamen is available:

https://github.com/open-formulieren/open-forms/blob/master/src/stuf/stuf_bg/templates/stuf_bg/StufBgRequest.xml

**Comment by alextreme** [comment]
Ook genoemd door Rotterdam. @joeribekker thoughts?

**Comment by alextreme** [comment]
Discussed with Joeri: "zit dat er nog niet in?!" and permission to assign to Victorien
