### ISSUE TITLE
Allow fields to be filled with co-sign information

### ISSUE THREAD

**Issue by LaurensBurger** [open-formulieren/open-forms#2716]
### Thema / Theme

Plugins

### Omschrijving / Description

SED: 34

These points were not completed in the PVE: https://github.com/open-formulieren/open-forms/issues/296#:~:text=Add%20Co%2DSign,TODO%3A%20how%20exactly%3F

co-sign data is available in the submission and could be available to use as prefill values.
This will allow the form builder to show the co-signers information in the summary and registration systems.

**Comment by joeribekker** [comment]
Afgeleide hiervan is enkel het BSN van de co-signer opnemen bij de inzending. De rest is vooral "bevestiging". Voorstel teruggelegd bij SED.

**Comment by joeribekker** [comment]
SED heeft aangegeven dat het BSN opnemen in de PDF voor nu voldoende is.
