### ISSUE TITLE
updateZaak_Lk01 for payment KeyError: 'omschrijving'

### ISSUE THREAD

**Issue by LaurensBurger** [open-formulieren/open-forms#2717]
### Product versie / Product version

2.0.0 / 2.1.0

### Omschrijf het probleem / Describe the bug

sentry: 312722, 312723

updateZaak message is not being sent after payment is completed. other tasks like e-mail work as intended.

**Comment by joeribekker** [comment]
Not sure how far the backport is needed, I thought this worked before (and tested in the field) and that there's unit tests.

**Comment by sergei-maertens** [comment]
Fixed via cb4b033d0611932083fb4f7bc6a6380939ba0071

**Comment by sergei-maertens** [comment]
Backported to 1.1.x via 79ff463b5baf4650b9a8e0e18542d3fd726a120e
