### ISSUE TITLE
Document things that don't work in repeating groups

### ISSUE THREAD

**Issue by joeribekker** [open-formulieren/open-forms#2735]
See: https://github.com/open-formulieren/open-forms/issues?q=is%3Aissue+is%3Aopen+label%3A%22topic%3A+repeating+group%22

and more?

**Comment by joeribekker** [comment]
This ticket deserves its own label :)

**Comment by sergei-maertens** [comment]
Location for documentation: https://open-forms.readthedocs.io/en/latest/manual/forms/form_fields.html#tekstveld

-> add section "repeating group" and document limitations there
