### ISSUE TITLE
2.1.0 Tests

### ISSUE THREAD

**Issue by LaurensBurger** [open-formulieren/open-forms#2750]
### Product versie / Product version

2.1.0

### Omschrijf het probleem / Describe the bug

w.i.p

### Date/Datetime 
- [x] #2826
- [x] #2768
- [x] #2769
- [x] #2827
- [x] #2828

### General
- [x] #2770
- [x] #2771
- [ ] "Automatisch invullen" always shows: email (low)
- [ ] between 1200px and 767px width Tables (50/50) overlap progress indicator (low)
- [ ] Number has no: read only (low)

### Repeating groups
- [ ] Titles of columns and fieldgroups showing after saving repeating group item (this seems inconsistent compared to overview where only fiedlgroup titles show, also removing the titles still renders ":" in the saved RG item. (low)

### Maps
- [ ] maps overlap buttons in admin, cookie banner in front (low)
- [ ] 2 maps in 1 step: only 1 get's location (firefox, chrome is janky) (low)

**Comment by joeribekker** [comment]
@LaurensBurger can you add the prio according to your opinion behind each bullet?

You can look at them like this:

- medium annoyance to the submitter? yes -> higher
- high annoyance to the editor? yes -> higher
- data loss?: yes -> higher
- workaround? yes -> lower
- visual only? yes -> lower

**Comment by joeribekker** [comment]
Too old to be picked up.
