### ISSUE TITLE
Font colour and alignment are ignored in free text components

### ISSUE THREAD

**Issue by hlmr-erik** [open-formulieren/open-forms#2757]
### Product versie / Product version

2.0.3

### Omschrijf het probleem / Describe the bug

In the form editor the colour and alignment are displayed properly (coloured asterisk and aligned to the right):
![image](https://user-images.githubusercontent.com/111565013/220839063-35cf3658-2262-4361-96eb-2714b5904051.png)

Though not in the resulting form:
![image](https://user-images.githubusercontent.com/111565013/220839094-5b9ecbf1-1e1c-4586-b8a6-f52bf9fe3f8c.png)

### Screen resolution

None

### Device

Desktop

### OS

Windows

### Browser

Firefox

**Comment by joeribekker** [comment]
Initial assessment: Valid bug but seems like a minor annoyance.

**Comment by joeribekker** [comment]
Refinement: Maybe the asterisk is black because the inline style is blocked by CSP

**Comment by joeribekker** [comment]
Refinement: Should be fixed. @SilviaAmAm checks if this is done.

**Comment by SilviaAmAm** [comment]
Issue: https://github.com/open-formulieren/open-forms/issues/2895
Fixed in: https://github.com/open-formulieren/open-forms/pull/3001/files
