### ISSUE TITLE
File component with same key (one inside repeating group) give 405 when uploading file

### ISSUE THREAD

**Issue by SilviaAmAm** [open-formulieren/open-forms#2758]
### Product versie / Product version

2.1.x

### Stappen om te reproduceren / Steps to reproduce

Create a form with:
- A file upload component with key `attachment`
- A repeating group
- A file component inside the repeating group, with key `attachment`

Now fill in the form:
- Try to upload a file to the component outside the repeating group
=> An error appears that the file could not be uploaded. In the console we see that the backend returned a 405 error.

**Comment by SilviaAmAm** [comment]
Note: if duplicate key is in another step, then a 500 error happens when submitting the form step

**Comment by joeribekker** [comment]
Initial assessment: Seems like there is a high chance of this happening in a bigger form but there is a workaround. I think the error can become apparant quickly when the form is manually tested once.

**Comment by joeribekker** [comment]
Related to #2734 and #2728

**Comment by SilviaAmAm** [comment]
It is no longer  possible to add components with the same key, even inside repeating groups.

![Screenshot from 2023-06-29 12-08-05](https://github.com/open-formulieren/open-forms/assets/19154114/06d996d1-ca1c-42fa-a682-e8525aca5b13)
