### ISSUE TITLE
File component with dot in key doesn't work

### ISSUE THREAD

**Issue by SilviaAmAm** [open-formulieren/open-forms#2759]
### Product versie / Product version

2.0.x

### Omschrijf het probleem / Describe the bug

If a form contains a file component with key `nested.file`, then it looks like a file has been uploaded in the widget, but no file has been added to the submission data.

### Stappen om te reproduceren / Steps to reproduce

Create a form with:
- A file component with key `nested.file`

Now fill in the form:
- Upload a file to the widget
- Submit the step and go to the overview
=> No file is shown in the overview.
- Submit the form
=> No file is present in the submission

**Comment by joeribekker** [comment]
Initial assessment: For the submitter, this looks like data-loss and since there are no warnings for submitter and handler this seems urgent.

**Comment by SilviaAmAm** [comment]
This seems to work on 2.1.x

**Comment by sergei-maertens** [comment]
Added backport label as I _suspect_ it will be an easy backport, but if not, we limit it to a workaround.

**Comment by sergei-maertens** [comment]
> This seems to work on 2.1.x

was fixed via #2449, looking at the commit history
