### ISSUE TITLE
Checkbox not capitalised in summary page

### ISSUE THREAD

**Issue by SilviaAmAm** [open-formulieren/open-forms#2760]
### Product versie / Product version

2.0.x, 2.1.x

### Omschrijf het probleem / Describe the bug

DH Taiga issue 428 / user story 429

The value of checkboxes is shown lower case in the summary page of a form:
![Screenshot from 2023-02-23 09-40-50](https://user-images.githubusercontent.com/19154114/220858661-73ddec58-3a73-4162-9183-f960480aca87.png)
![Screenshot from 2023-02-23 09-40-57](https://user-images.githubusercontent.com/19154114/220858666-22e36f86-2f52-4257-8cf2-990498793bb4.png)

### Stappen om te reproduceren / Steps to reproduce

Create a form with:
- A checkbox (selectvakje)

Fill the form:
- Go to the summary page
=> Observe lower case

**Comment by joeribekker** [comment]
Initial assessment: Bug but only causes minor inconvenience, even though its presented to the end user.
