### ISSUE TITLE
Allow different locations for help/description texts

### ISSUE THREAD

**Issue by LaurensBurger** [open-formulieren/open-forms#2766]
### Thema / Theme

Frontend

### Omschrijving / Description

internal: utr 9

To create a clear look in the forms, the help texts could be hidden behind a actionable button or revealed when with a hoover over an icon. The same way we use in the form designer:
![image](https://user-images.githubusercontent.com/112621537/221190359-bb42d471-25f1-450b-b876-16fba9c0bbe9.png)

**Comment by hlmr-erik** [comment]
Related to: https://github.com/open-formulieren/open-forms/issues/1892

**Comment by sergei-maertens** [comment]
Supported via tooltips, as mentioned by Erik.
