### ISSUE TITLE
Setting validation on date+datetime component requires "opslaan" before parameters can be set

### ISSUE THREAD

**Issue by joeribekker** [open-formulieren/open-forms#2768]

**Comment by sergei-maertens** [comment]
-> first check if this is still relevant in the latest version, could be fixed by other editor fixes earlier. If fixed, please relate that ticket to this one.

**Comment by LaurensBurger** [comment]
Not present in latest

**Comment by sergei-maertens** [comment]
Was likely fixed via #2695 then
