### ISSUE TITLE
max/min dates/months/years are ignored in validation tab

### ISSUE THREAD

**Issue by joeribekker** [open-formulieren/open-forms#2769]

**Comment by pi-sigma** [comment]
Works:
   * setting max/min date/datetime via validation tab
   * updating max/min date/datetime via component JSON
   * coordination between frontend/backend
 
Doesn't work
   * updating max/min date/datetime via validation tab once the component has been set

**Comment by pi-sigma** [comment]
Depending on **(a)** *how* `maxDate` (or `minDate`) is specified in `js/components/form/edit/date-edit-form.js` and (b) *when* the values are selected in the validation tab, it is inserted into the component JSON at different levels.

1. "bare" keys (`years`, `months`, `days`) are suitable for setting the component for the first time (meaning they are inserted at the right level).
2. "dotted" keys (`openforms.${fieldname}.delta.years`) are suitable for changing the component after it has been set.
3. "dotted" keys are inserted at the wrong level when setting the component for the first time, "bare" keys are inserted at the wrong level when changing the component.

If you you define both types of components (so there are two fields in the validation tab for each of `year`, `month`, `day`) and insert different values, this is the result after setting up the validation (`days = 1`, `openforms.${fieldname}.delta.days = 8`) and changing it (`days = 25`, `openforms.${fieldname}.delta.days = 77`).

```
{
  "label": "Date / Time",
  "key": "dateTime",
  "openForms": {
    "maxDate": {
      "mode": "relativeToVariable",
      "delta": {
        "days": 77,
        "years": 1,
        "months": 1,
        "openForms": {
          "maxDate": {
            "delta": {
              "days": 8,
              "years": 8,
              "months": 8
            }
          }
        }
      }
    }
  },
  "days": 25,
}
```

The configuration that will be used is `years = 1`, `months = 1`, `days = 77`. The inner- and outermost occurrences of `years` etc. are ignored.

**Comment by sergei-maertens** [comment]
oh, interesting! this is definitely not how it was intended :)

**Comment by sergei-maertens** [comment]
Looking at the backend code/type hints, the intended format of the component is:

```json
{
    "type": "date",
    "openForms": {
        "minDate": {
            "mode": "relativeToVariable",
            "includeToday": null,
            "variable": "dob",
            "delta": {
                "years": 18,
                "months": 0,
                "days": 0
            },
            "operator": "add"
        }
    },
    "datePicker": {
        "minDate": "2023-03-02T15:18:00+02:00"
    }
}
```
