### ISSUE TITLE
Create smarter data structure for Formio data

### ISSUE THREAD

**Issue by sergei-maertens** [open-formulieren/open-forms#2784]
Thought occurred after seeing https://github.com/open-formulieren/open-forms/pull/2783/files

We often have some assumptions about the component keys not being nested, e.g. `component["key"] in submission_data`, which is too simplistic. Formio allows specifying nested paths by using `.`-characters as separators, e.g. `nested.key` which results in a nested submission data structure `{"nested": {"key": "value"}}`.

A smarter datastructure could apply this lookup behaviour with simple python operations and make it more intuitive to do the right thing.

Known places that should use this:

* `openforms.submissions.logic.datastructures.DataContainer.get_updated_step_data`
* `openforms.submissions.models.submission_value_variable.SubmissionValueVariablesState`
* `openforms.submissions.form_logic`
* `openforms.variables.utils.get_variables_for_context`
* `openforms.submissions.viewsets.SubmissionStepViewSet.logic_check`
* ...

**Comment by sergei-maertens** [comment]
```py
formio_data = FormioData(data_dict)
val = formio_data["foo.bar"]
formio_data["foo.bar"] = val
```
-> desired API

**Comment by joeribekker** [comment]
Let's re-evaluate priority when it can be related to other tickets / reported issues.
