### ISSUE TITLE
Update text of pause / resume form modal

### ISSUE THREAD

**Issue by SilviaAmAm** [open-formulieren/open-forms#2789]
### Thema / Theme

Frontend

### Omschrijving / Description

DH Taiga issue 430 / user story 435

Update the text of the modal to:

[Kop]Opslaan en later verdergaan

[Tekst]Vul hieronder uw e-mailadres in. U krijgt dan een mail met link om het formulier verder in te vullen. Dit kan op elk apparaat waar u de link opent. De link blijft maximaal 7 dagen actief. Uw e-mailadres: 

[knop] Later verdergaan
![afbeelding](https://user-images.githubusercontent.com/19154114/221842574-adf0199d-c5d0-4bb6-a238-56c64f212efc.png)

**Comment by SilviaAmAm** [comment]
@sergei-maertens Indeed, it depends on either `form.incomplete_submissions_removal_limit` or `config.incomplete_submissions_removal_limit`. Should I add it somewhere so that it's passed to the frontend or should I not include this in the text?

**Comment by sergei-maertens** [comment]
I want to have a broader discussion about text configuration when Joeri is back!

**Comment by joeribekker** [comment]
Prima om de tekst aan te passen met de configuratie waarde. Bredere discussie is ook goed maar hoeft dit niet te blokkeren.
