### ISSUE TITLE
Server error / 500.html template, verwijzingen naar Bootstrap bijwerken en toevoegen SRI

### ISSUE THREAD

**Issue by alextreme** [open-formulieren/open-forms#2796]
### Thema / Theme

Other

### Omschrijving / Description

Gerapporteerd door Den Haag als lage-prio bevinding (ZGW Taiga #467), naar aanleiding van een server error als response op een API call.

Momenteel wordt er gebruik gemaakt van een 500.html template met externe verwijzingen naar een verouderde bootstrap ( https://github.com/twbs/release ), de aanbeveling is om dit bij te werken (Bootstrap 3 is sinds 2019 EOL) en gebruik te maken van Subresource Integrity ( https://developer.mozilla.org/en-US/docs/Web/Security/Subresource_Integrity ).

Nieuwe versie mag tevens in onze default-project landen wat mij betreft.

### Added value / Toegevoegde waarde

Verhelpen pentestbevinding & discussie hierover voorkomen.

**Comment by sergei-maertens** [comment]
Is al opgelost via 5e48a329d347ceb6935088935e19e7d342467b90 en is beschikbaar sinds 2.1.0-alpha.2, komt dus in 2.1.0 release.

**Comment by alextreme** [comment]
Excuus voor de overbodige issue en dank, ik zet 'm over naar default-project en OIP veel netter zo.
