### ISSUE TITLE
long filename in fileupload that causes error -> overflows container

### ISSUE THREAD

**Issue by LaurensBurger** [open-formulieren/open-forms#2808]
### Product versie / Product version

2.1.0.rc0

### Omschrijf het probleem / Describe the bug

![image](https://user-images.githubusercontent.com/112621537/222381334-fd388718-a057-4720-b138-c11dc249aa8c.png)

**Comment by joeribekker** [comment]
Refinement: Apply css rule break-word

**Comment by pi-sigma** [comment]
Discussed with @joeribekker: decided to remove ellipsis on all viewports and let filename wrap around. Trashcan icon and filesize should move to separate line.
