### ISSUE TITLE
"+ Add Another" button styling not consistent 

### ISSUE THREAD

**Issue by LaurensBurger** [open-formulieren/open-forms#2813]
### Product versie / Product version

2.1.0.rc0

### Omschrijf het probleem / Describe the bug

The "+ Add Another" button looks different depending on the component, specifically the button for repeating groups, they are styled as "primary" while the other buttons in the form are just plain buttons:
![image](https://user-images.githubusercontent.com/112621537/222668892-d9982297-3228-4b87-8c34-6a902dd5e673.png)

### Verwacht gedrag / Expected behavior
Since they serve the same purpose they should also look the same.

**Comment by joeribekker** [comment]
Refinement: We picked the blue/primary button
