### ISSUE TITLE
Fix form variable data type information

### ISSUE THREAD

**Issue by sergei-maertens** [open-formulieren/open-forms#2822]
There's been some ping-ponging with date/datetime components and the data types of the underlying variables.

Sentry 321980 occurred because a Date component was trying to parse its value as a `datetime` type.

-> create a data migration, loop over all components in every form and check all the `type: "date"` component variables that they have the correct type.

workaround: editing the form in the admin and saving it again, this re-creates the variables with the correct type.

**Comment by joeribekker** [comment]
Refinement:

Q: Should this be really fixed in the data migration
A: Yes

Q: is the problem that the form component is of type date but the variable is of type datetime
A: yes
