### ISSUE TITLE
Date in logic rules only work when formatted: yyyy-mm-dd, otherwise form breaks "Could not parse date '10-10-2020'" (low)

### ISSUE THREAD

**Issue by joeribekker** [open-formulieren/open-forms#2826]

**Comment by joeribekker** [comment]
@LaurensBurger can you provide the steps to reproduce this?

**Comment by joeribekker** [comment]
Refinement: Might have to do with browser locale?

**Comment by LaurensBurger** [comment]
![image](https://user-images.githubusercontent.com/112621537/223097412-6b8898f2-46a2-4bae-967e-a2eac5251dd8.png)
action 1 works
action 2 results in:
![image](https://user-images.githubusercontent.com/112621537/223097623-5047cdc0-c99b-42bd-9bba-d24852ebde9f.png)
