### ISSUE TITLE
Setting the value of datetime to "now" through logic causes constant _check_logic (low)

### ISSUE THREAD

**Issue by joeribekker** [open-formulieren/open-forms#2827]

**Comment by joeribekker** [comment]
Refinement: Truncate seconds with JSON logic as quick solution, better would be to limit resolution to mintes.

**Comment by LaurensBurger** [comment]
logic to create condition
```json
{
  "component": "",
  "variable": "dataTime10",
  "formStep": null,
  "formStepUuid": null,
  "action": {
    "type": "variable",
    "value": {
      "var": "now"
    }
  }
}
```
![Peek 2023-03-06 12-38](https://user-images.githubusercontent.com/112621537/223100049-8d01de22-d0b4-4319-a17d-69d809e4f8a8.gif)

**Comment by sergei-maertens** [comment]
self-reminder -> check if this is resolved

**Comment by sergei-maertens** [comment]
Verified this is still happening, and another bug is also happening crashing the form start in the first place.
