### ISSUE TITLE
Turning on piwik/piwik pro/matomo causes CSP connect-src to be added

### ISSUE THREAD

**Issue by SilviaAmAm** [open-formulieren/open-forms#2842]
### Product versie / Product version

2.0.x, 2.1.x

### Omschrijf het probleem / Describe the bug

DH Taiga issue 412 / user story 437

If these analytics tools are turned on, then a CSP directive is added: `connect-src https://hosted.analytics.service`

This blocks the forms from loading.

**Comment by sergei-maertens** [comment]
Some extra information: `connect-src` falls back to `default-src` if not specified. By specifying it via the analytics config, only the analytics source is included which effectively blocks from making fetch calls to `self`.

If unspecified, it follows the `default-src` which includes `self`, causing fetch *not* to break.

**Comment by SilviaAmAm** [comment]
Piwik Pro also changes the the font-src directive, which means that the fonts also give a CSP error and can't be loaded. Maybe we should change how the analytics tools add CSP directives so that they don't remove the 'self'?

**Comment by sergei-maertens** [comment]
Maybe it's better to ensure our baseline includes the necessary directives if we're going to use these. Alternatively, why can't the analytics configuration add these to the `default-src` rather than `font-src`/`connect-src`? That one is configured already through `CSP_DEFAULT_SRC` so there is at least one value specified.

Alternatively, we can extend this:

```py
# we must include this explicitly, otherwise the style-src only includes the nonce because
# of CSP_INCLUDE_NONCE_IN
CSP_STYLE_SRC = CSP_DEFAULT_SRC
CSP_SCRIPT_SRC = CSP_DEFAULT_SRC
```

to be:

```py
# we must include this explicitly, otherwise the style-src only includes the nonce because
# of CSP_INCLUDE_NONCE_IN
CSP_STYLE_SRC = CSP_DEFAULT_SRC
CSP_SCRIPT_SRC = CSP_DEFAULT_SRC
CSP_FONT_SRC = CSP_DEFAULT_SRC
CSP_CONNECT_SRC = CSP_DEFAULT_SRC
```
