### ISSUE TITLE
Content component missing option to include it in summary page

### ISSUE THREAD

**Issue by SilviaAmAm** [open-formulieren/open-forms#2845]
### Product versie / Product version

2.0.x, 2.1.x

### Omschrijf het probleem / Describe the bug

DH Taiga issue 83 / user story 88

All components have a check box in the edit form to specify whether it should be shown in the summary. However, the content component is missing this checkbox.
![afbeelding](https://user-images.githubusercontent.com/19154114/223766732-4a60fea8-08d3-4b85-9861-392659c21680.png)
![afbeelding](https://user-images.githubusercontent.com/19154114/223766839-f385f354-dac4-4401-80b1-47f7a5049603.png)

**Comment by sergei-maertens** [comment]
I remember this being deliberate

**Comment by SilviaAmAm** [comment]
Ah! I was looking for old tickets on this, but couldn't find the reason. Do you remember what the reason was?

**Comment by sergei-maertens** [comment]
@SilviaAmAm had to find a commit to lead me to the issue, but it's documented here: https://github.com/open-formulieren/open-forms/issues/1451#issuecomment-1077506877 - so it's only displayed in the PDF if the component itself is visible (after evaluating logic), but never in summary, confirmation email or submission export. I believe the rationale was that you only display in summary what the user filled out themselves.

**Comment by SilviaAmAm** [comment]
Found this other ticket mentioning it: https://github.com/open-formulieren/open-forms/issues/421#issuecomment-1152523724

**Comment by joeribekker** [comment]
Refinement: Decided to add the option but with the default "False". This makes it possible to add it to the summary and still maintain the same behavior for existing forms.
