### ISSUE TITLE
Forms with "old" non applicable logic cannot be imported 

### ISSUE THREAD

**Issue by LaurensBurger** [open-formulieren/open-forms#2849]
### Product versie / Product version

2.x.x

### Omschrijf het probleem / Describe the bug

These forms heve been migrated from 1.x.x to 2.x.x but exporting and importing them from a 2.x.x to another 2.x.x returns:
`Something went wrong while importing form: {'actions': [{'form_step': [ErrorDetail(string='Invalid hyperlink - Incorrect URL match.', code='incorrect_match')]}]}
`

This can be solved by manually removing the url present in formLogic.json from "form_step" where actions.action.type = "step-not-applicable"

![image](https://user-images.githubusercontent.com/112621537/224320824-18a9d565-6e0c-4b79-a168-3d6c16011659.png)

**Comment by SilviaAmAm** [comment]
I think this is beause after the migration the forms have both `form_step` and `form_step_uuid` in the action of the logic rule. But if the step is changed from the UI, it will only update form_step_uuid, so then there would be discrepancies between the two.
