### ISSUE TITLE
Productaanvraag - Definitie formulierdata in productaanvraag

### ISSUE THREAD

**Issue by StefSchots1993** [open-formulieren/open-forms#2853]
### Thema / Theme

API

### Omschrijving / Description

Userstory 
Als afnemer van Open Formulieren die OF wil integreren met een ander product
Wil ik dat formuliervelden vanuit Open Formulieren als label-value pair van het type string in de productaanvraag worden opgeslagen, zodat de e-Suite ze als zaakdata.label met value voor hergebruik als procesgegevens beschikbaar kan stellen.
Zodat deze waarden in de e-Suite verwerkt kunnen worden, zonder het proces aan te passen.

Toelichting:
Op de huidige implementatie met de e-Suite wordt de inhoud van het object als proces.inhoud opgeslagen, in tegenstelling tot e-Suite formulieren, waar de data als zaakdata.inhoud wordt opgeslagen. Het is gewenst dat inhoud als zaakdata.inhoud wordt opgeslagen.
Zo blijven de daaropvolgende processen werken.

Uit de refinement 17-02-23 ATOS/Maykin/Dimpact:
Data waarvan het datatype eenvoudig herleidbaar is wordt door ATOS met het juiste datatype in de e-Suite opgeslagen. 
Denk hierbij met name (naast strings) aan getallen, locatie, data en tijd.

### Aanvullende opmerkingen / Additional context

Subissue van https://github.com/open-formulieren/open-forms/issues/2852

**Comment by StefSchots1993** [comment]
https://dimpact.atlassian.net/browse/PF-45

**Comment by joeribekker** [comment]
Dit wordt gedekt in #2852
