### ISSUE TITLE
Productaanvraag - Definitie zaakdata in productaanvraag

### ISSUE THREAD

**Issue by StefSchots1993** [open-formulieren/open-forms#2854]
### Thema / Theme

API

### Omschrijving / Description

Userstory
Als integratiespecialist 
wil ik weten met welke labels ik de zaakdata in de Productaanvraag moet opslaan
zodat deze waarden in de e-Suite verwerkt kunnen worden.

Aanvullende opmerkingen:
Zaakdata reverse engineren naar productaanvraag

Voorstel naar aanleiding van de refinement:

        "data": {
            "zaakgegevens": {
		"identificatie": "123123",  //De unieke identificatie van de ZAAK binnen de organisatie die verantwoordelijk is voor de behandeling van de ZAAK. Wordt in de e-Suite NIET gebruikt als zaaknummer.
		"taal" : "Nederlands", //Enum:[ English, Nederlands ]
                "aanvraagtype": "verhuizing", //Uniek kenmerk van het type aanvraag
                "communicatiekanaal": "Internet", //string($uri) maxLength: 1000
                "omschrijving": "Verhuizing Blaak 27", //Een korte omschrijving van de zaak. maxLength: 80
                "toelichting": "Nieuw huis gekocht" //Een toelichting op de zaak. maxLength: 1000
            },
Nb.

Het kenmerk wordt door de e-Suite niet gebruikt als zaaknummer: de e-Suite blijft haar eigen nummer hanteren.
Het 'aanvraagtype' wordt in de e-Suite gemapped met het zaaktype
Omschrijving wordt in de e-Suite gemapped met het veld 'Omschrijving'
Toelichting wordt in de e-Suite gemapped met het veld 'Reden start Zaak'

### Aanvullende opmerkingen / Additional context

Substory van https://github.com/open-formulieren/open-forms/issues/2852

**Comment by StefSchots1993** [comment]
https://dimpact.atlassian.net/browse/PF-46

**Comment by joeribekker** [comment]
Ik denk dat het meeste hiervan kan worden ingegeven middels variablen of hardcoded template tekst.

De Zaak wordt niet aangemaakt VOOR de ProductAanvraag dus verdere zaakgegevens hebben we niet.
