### ISSUE TITLE
Productaanvraag - Definitie locatie in productaanvraag

### ISSUE THREAD

**Issue by StefSchots1993** [open-formulieren/open-forms#2855]
### Thema / Theme

API

### Omschrijving / Description

Userstory
Als Productowner zaakgericht werken
wil ik dat locatiegegevens in de Productaanvraag worden opgeslagen
zodat deze waarden in de e-Suite verwerkt kunnen worden.

Aanvullende opmerkingen:
ophalen bij ATOS doorgeven aan maykin coördinaten wms-laag

Acceptatiecriteria

Als er binnen de 'geometry' in de productaanvraag een locatie vermeld is, wordt deze door de e-Suite automatisch als zaaklocatie verwerkt

Als er buiten de 'geometry' in de productaanvraag een locatie vermeld is, wordt deze als zaakdata.locatie opgeslagen

Als de zaaklocatie binnen de 'geometry' in de productaanvraag een lijn of vlak is wordt deze door de e-Suite automatisch als punt zaaklocatie verwerkt

Voorstel voor zaaklocatie is om GeoJson op te slaan in de productaanvraag.

Voorbeeld voor zaaklocatie:

   "geometry": {
            "type": "Point", # GeometryCollection, LineString, MultiLineString, MultiPoint, MultiPolygon, Point, Polygon
            "coordinates": [52.36673378967122, 4.893164274470299],
        },

MVP Open Formulieren is dat een enkele kaart de indicatie 'zaaklocatie' kan krijgen

MVP e-Suite is dat de coordinaten op deze plek als ZaakLocatie worden opgeslagen

De overige kaarten worden als GeoJSON in de AanvraagGegevens (catch-all) opgeslagen

Zie schema: [objecttypes/productaanvraag-dimpact at patch-1 · joeridiederen/objecttypes](https://github.com/joeridiederen/objecttypes/blob/patch-1/community-concepts/productaanvraag/productaanvraag-dimpact)

### Aanvullende opmerkingen / Additional context

subissue van https://github.com/open-formulieren/open-forms/issues/2852

**Comment by StefSchots1993** [comment]
https://dimpact.atlassian.net/browse/PF-47

**Comment by joeribekker** [comment]
Ik zie de geo-gegevens niet staan in het JSON schema van Joeri Diederen...

Opnemen in template:
```
"geometry": {% submission.geo_json %}
```

Met als resultaat:

```
"geometry": {
  "type": "Point",
  "coordinates": [52.36673378967122, 4.893164274470299]
}
```
