### ISSUE TITLE
Productaanvraag - Bron vastleggen in productaanvraag

### ISSUE THREAD

**Issue by StefSchots1993** [open-formulieren/open-forms#2856]
### Thema / Theme

API

### Omschrijving / Description

Userstory

Als afnemer van Open Formulieren waarbij ik wil OF wil integreren met een zaaksysteem eSuite
Wil ik wil ik dat de bron vastgelegd wordt bij de productaanvraag
Zodat deze automatisch overgenomen kan worden in het zaakafhandelsysteem.

Voorstel om de bron vast te leggen in de productaanvraag:

          "bron" : {
      "title" : "Bron",
      "description" : "Bron waaruit de productaanvraag voortkomt",
      "type" : "object",
      "properties" : {
        "naam" : {
          "title" : "Naam",
          "description" : "Naam van de bron",
          "type" : "string",
          "examples" : [
            "Open Formulieren"
          ]
        },
        "kenmerk" : {
          "title" : "Kenmerk",
          "description" : "Kenmerk van de productaanvraag zoals bekend bij de bron. Bijvoorbeeld ID van de submission in Open Forms",
          "type" : "string",
          "examples" : [
            "a43e84ac-e08b-4d5f-8d5c-5874c6dddf56"
          ]
        }
      },
      "required" : [
        "naam"
      ]
    },
Uit de refinement: de bron is een aanvulling op het 'kanaal' zoals in deze in de referentielijsten-API staat.

Aanvullende opmerkingen / Additional context
Subissue van https://github.com/open-formulieren/open-forms/issues/2852

**Comment by StefSchots1993** [comment]
https://dimpact.atlassian.net/browse/PF-49

**Comment by joeribekker** [comment]
Opnemen in template:
```
	"bron": {
		"naam": "Open Formulieren",
		"kenmerk": "{{ submission.uuid }}"
	},
```
