### ISSUE TITLE
Productaanvraag - De Productaanvraag mag niet langer bewaard blijven dan bijbehorend zaakdossier

### ISSUE THREAD

**Issue by StefSchots1993** [open-formulieren/open-forms#2858]
### Thema / Theme

Frontend

### Omschrijving / Description

Userstory
Als informatiebeheerder
wil ik dat een productaanvraag niet later vernietigd wordt dan de bijbehorende zaak
zodat alle zaakinformatie op tijd vernietigd wordt.

Naar aanleiding van de refinement;

Context
Gewenst is dat het object vernietigd wordt als de zaak vernietigd is. Vereist is daardoor een relatie tussen de zaak en het object. 
De e-Suite kan geen relatie tussen de zaak en het object leggen, omdat de e-Suite geen Open Zaak is.

MVP
Is dat het object door de e-Suite verwijderd wordt, zodra met zekerheid is vastgesteld dat de inhoud van het object overgenomen is als zaakdata binnen de e-Suite.

Waarschijnlijk is overleg met ATOS nodig over hoe dit in beide “oplossingen” te realiseren.

### Aanvullende opmerkingen / Additional context

Subissue van https://github.com/open-formulieren/open-forms/issues/2852

**Comment by StefSchots1993** [comment]
https://dimpact.atlassian.net/browse/PF-51

**Comment by joeribekker** [comment]
@StefSchots1993 ik vind architectureel dat Open Formulieren hier niets aan moet doen. Dit ligt bij archiefbeheer, en hoe een afhandelcomponent eventueel een zaak aanmaakt van een productaanvraag.

**Comment by joeribekker** [comment]
Refinement: Closing here because this is indeed not tackled within Open Forms but more in Open Zaak and/or Objects API or supplier solution.
