### ISSUE TITLE
Koppeling PDOK/BRT t.b.v. tonen kaartje voor MOR

### ISSUE THREAD

**Issue by joeribekker** [open-formulieren/open-forms#286]
Eis: Koppelingen 5q.

Zie technisch issue: #157 

**Verduidelijking**

* [ ] Navigeer kaartje naar postcode huisnummer (optioneel?)
* [x] Prikkertje kunnen plaatsen op willekeurig punt
* [x] Start prikkertje op "huidige" locatie
* [x] Resultaat van kaartje zijn geo-coordinaten en/of dichtsbijzijnde postcode + huisnummer
* [x] Add map to summary page

**Comment by shea-maykinmedia** [comment]
Note that this should also solve #157
