### ISSUE TITLE
URL balk - Favicon en naam in adresbalk klantspecifiek maken

### ISSUE THREAD

**Issue by StefSchots1993** [open-formulieren/open-forms#2863]
### Thema / Theme

Frontend

### Omschrijving / Description

Userstory
Als afnemer van Open Formulieren en als publieke instantie (als gemeente).
Wil ik een eigen favicon en tekst bij de tab van een formulier zelf kunnen instellen. 
Zodat een aanvrager die een formulier invult duidelijk kan zien dat de “site” waarop het formulier wordt ingevuld van de “Gemeente” is. 

Acceptatiecriteria

Zou instelbaar moeten zijn in de algemene configuratie

Zou volgens WCAG richtlijnen, voor zover die er zijn, te personaliseren moeten zijn door de instantie die OF gebruik

Voorbeeld
![168554658-cd5b24f8-9063-4047-9ceb-10bf9a69fc80 png (285×35) - Google Chrome 2023-03-08 13 03 04](https://user-images.githubusercontent.com/84498045/224307638-63700215-a4f1-4d46-af9f-5cc9c3d8e094.png)
Zou eigenlijk zo moeten zijn
![173571696-afec7958-3e45-4832-95da-f82038308859 png (232×35) - Google Chrome 2023-03-08 13 03 17](https://user-images.githubusercontent.com/84498045/224307677-bc447e15-1b71-4a91-9fdc-e63cc2f40406.png)

**Tasks**

* [ ] The page title should be: `<form or step title> | <org name>` (form title only on first page, form step title on steps; org name can be taken from the general configuration

**Comment by StefSchots1993** [comment]
https://dimpact.atlassian.net/browse/PF-54

**Comment by LaurensBurger** [comment]
#2491

**Comment by sergei-maertens** [comment]
Checks done - the SDK fix should be sufficient, as the backend document title is already set via the global configuration organization name, see https://github.com/open-formulieren/open-forms/blob/3775c27fdba843096e881645b2f30a121bf35d67/src/openforms/templates/master.html#L11
