### ISSUE TITLE
The zaaktype does not refresh if the Catalogi API is changed

### ISSUE THREAD

**Issue by SilviaAmAm** [open-formulieren/open-forms#2879]
### Product versie / Product version

2.1.x

### Omschrijf het probleem / Describe the bug

I want to change the ZGW APIs that are used by Open Forms, but there was a zaaktype selected in the radio of this page: `/admin/zgw_apis/zgwconfig/`. After changing the catalogi API, the choices of zaaktypen don't seem to be refreshed. It is not possible to unselect the previous choice so when saving, the backend returns an error because the selected zaaktype does not exist.

### Stappen om te reproduceren / Steps to reproduce

1. Create a service for the Zaken / Catalogi / Documenten API in openforms
2. Go to `/admin/zgw_apis/zgwconfig/` and select the services that we just configured
3. Select a Zaaktype among the suggested choices
4. Now go back to the service configuration for the catalogi API and change the URL (Or add a new service for a different Catalogi API)
5. Go back to `/admin/zgw_apis/zgwconfig/` and change the Catalogi API
=> The zaaktype don't seem to refresh

### Verwacht gedrag / Expected behavior

It should be possible to change the catalogi API

Note: A playwright test would be good for this

### Screen resolution

None

### Device

None

### OS

None

**Comment by sergei-maertens** [comment]
there's no JS for this here, it's pure Django backend (i.e. no dependent fields) I'm not sure I'd consider this a bug rather than just a not-fleshed out implementation.

**Comment by sergei-maertens** [comment]
Reopening as the dependencies in OF need to be updated.
