### ISSUE TITLE
De gebruiker kan inloggen met DigiD, eHerkenning en eIDAS.

### ISSUE THREAD

**Issue by joeribekker** [open-formulieren/open-forms#288]
Eis: Authenticatie En Basisgegevens 1.
Zie ook NvI: 173

**Comment by SilviaAmAm** [comment]
- [ ] Digid
- [ ] EHerkenning
- [ ] eIDAS

**Comment by SilviaAmAm** [comment]
Related PRs:
- Open-Forms branch: https://github.com/open-formulieren/open-forms/pull/476
- Open-forms-deployment branch: https://github.com/maykinmedia/open-forms-deployment/pull/5

**Comment by sergei-maertens** [comment]
eHerkenning PRs are merged, not deployed yet.
