### ISSUE TITLE
Vrije tekst veld - focus shifts after change

### ISSUE THREAD

**Issue by LaurensBurger** [open-formulieren/open-forms#2889]
### Product versie / Product version

2.1.0

### Omschrijf het probleem / Describe the bug
Entering tekst in this component is made very difficult because after each "change" the field will lose focus, and the user needs to refocus to continue typing - just to lose focus again.

![Peek 2023-03-16 11-15](https://user-images.githubusercontent.com/112621537/225586327-9c342e0a-9d57-492f-9875-95c377170938.gif)

**Comment by sergei-maertens** [comment]
This also happens to (but is less annoying) the other fields like Label / Key etc.

I suspect this is the culprit: https://github.com/open-formulieren/open-forms/blob/master/src/openforms/js/components/formio_builder/builder.js#L423 (from 212df96f5c9a0c3d6ff50304fc2b4db3b8911e92)
