### ISSUE TITLE
Inline colours for content field doesn't work if you are logged in as admin

### ISSUE THREAD

**Issue by SilviaAmAm** [open-formulieren/open-forms#2895]
### Product versie / Product version

2.1.0

### Omschrijf het probleem / Describe the bug

Explanation:
 - This happens only if you are logged in as admin. 
 - [This code](https://github.com/open-formulieren/open-forms/blob/master/src/openforms/forms/api/serializers/form_definition.py#L117) is ran multiple times if you are logged in as admin:
```python
rewrite_formio_components_for_request(
      instance.configuration_wrapper,
      request=self.context["request"],
)
```
 -  This results in the inline style being converted to the `style` tag (with CSP nonce), and in the subsequent calls the `style` tag is removed from the HTML (resulting in no colour).
 - This is because when we are admin, we have the extra the `admin_only_fields` which include `translations` (see code [here](https://github.com/open-formulieren/open-forms/blob/master/src/openforms/api/serializers.py#L139 )). This then causes [this super call](https://github.com/open-formulieren/open-forms/blob/master/src/openforms/forms/api/serializers/form_definition.py#L108) to run [this code](https://github.com/open-formulieren/open-forms/blob/master/src/openforms/translations/api/serializer_helpers.py#L11) from the `TranslationsFieldMixin`. The `FormDefinitionTranslationsSerializer` calls the `to_representation` of the `FormDefinition` serializer and so the `rewrite_formio_components_for_request` is called multiple times.

### Stappen om te reproduceren / Steps to reproduce

- Create a form with a content field with colour red
- Fill in the form when you are an admin
- Fill in the form when you are not logged in as admin
- Observe the difference

### Verwacht gedrag / Expected behavior

Both admin and non-admin should see the same thing

### Screen resolution

None

### Device

None

### OS

None

**Comment by joeribekker** [comment]
Refinement: Some super call calling itself which needs to eb resolved.
