### ISSUE TITLE
Component made visible by checkbox being true are emptied on _check_logic

### ISSUE THREAD

**Issue by LaurensBurger** [open-formulieren/open-forms#2900]
### Product versie / Product version

2.1.0
Reported by: Utrecht, Horst a/d Maas

### Omschrijf het probleem / Describe the bug

Only occurs for when made visible by checkbox (still looking into Choices)

![Peek 2023-03-17 09-21](https://user-images.githubusercontent.com/112621537/225851403-aa12f1f1-094f-4d97-8a07-8c6435ba205d.gif)
![Peek 2023-03-17 09-28](https://user-images.githubusercontent.com/112621537/225852715-9e4eb436-8322-43a4-8701-cfd883aea163.gif)

If the component that was shown by checkbox is in a different group, this bug does not occur:
![Peek 2023-03-17 10-00](https://user-images.githubusercontent.com/112621537/225859361-2e07f041-9509-4989-8d4c-013849404fdf.gif)

**Comment by LaurensBurger** [comment]
If a checkbox is part of a group - a field from outside that group that is shown if that checkbox is true is emptied on echt check_logic request, while fields that are in the same group, or part of another group/columns are not emtpied:
![image](https://user-images.githubusercontent.com/112621537/226312363-7c8947c0-907b-4c6a-83c2-0e86be660e8e.png)

When the same fields and logic are applied to a checkbox that is not part of a group, this bug does not occur:
![image](https://user-images.githubusercontent.com/112621537/226312823-f142881a-0d42-4444-8b29-468202b69e62.png)

**Comment by SilviaAmAm** [comment]
Not sure if I understand the bug correctly, but seeing this behaviour (which definitely is a bug, just not sure if the same one):

Create a form with:
- A Fieldset called 'Fieldset with checkbox' with inside:
    - A checkbox
    - A textfield called 'Text in group with checkbox' with frontend logic saying 'Show if the checkbox is `true`'
- A textfield called 'Text outside group with checkbox' with frontend logic saying 'Show if the checkbox is `true`'
- A fieldset called 'Fieldset without checkbox' with inside:
    -  A textfield called 'Text in group without checkbox' with frontend logic saying 'Show if the checkbox is `true`'

Now fill in the form:
- Check the checkbox => All the textfields appear
- Type in any textfield => The values disappear after logic check.

**Comment by sergei-maertens** [comment]
@SilviaAmAm I think you're spot on with the analysis and the cause (so the bugfix seems correct)

While trying to make sense of everything I talked to Laurens too to verify some things, and the clear-on-hide behaviour does happen with components made visible with frontend logic even if they are outside of the/any field group - the case of https://user-images.githubusercontent.com/112621537/225859361-2e07f041-9509-4989-8d4c-013849404fdf.gif is not reproducible.

Checkboxes seems fine - I can see in the debugger that these send actual boolean values, and the value is being tested by checking if the checkbox value is truthy in the map (so there's no comparison of string boolean vs. boolean happening there). If the frontend would send `{"someCheckboxesValue": "false"}`, this would be broken, but that's not the case.
