### ISSUE TITLE
Document and make sure import/export works with service fetch configured in forms.

### ISSUE THREAD

**Issue by joeribekker** [open-formulieren/open-forms#2908]
As minimal resolution for #2683:
We do need to resolve any export crashes if they happen and document that service fetch is not exported/imported.

**Comment by joeribekker** [comment]
Refinenent: Confirmed that is NOT blocked and @chris should fix this :)

**Comment by CharString** [comment]
Export and import "work": they don't crash, but it results in a complete form recreated, but with possibly broken foreign keys to service fetch configurations / services that may have been deleted in the meanwhile. 

These breaks will become apparent when trying to use the form. Right now (1069bd4605cda87e6871eebf2d182cc604afa327) it's unclear if it will break the modal as that is not hooked up yet. So I want to recheck this when that is done, before I document the behaviour.

**Comment by CharString** [comment]
#2884 Might want to pull these commits in too.

**Comment by sergei-maertens** [comment]
if #2884 lands in 2.2, that's enough imo
