### ISSUE TITLE
Filling email very slowly causes cursor to jump to the beginning of the input field

### ISSUE THREAD

**Issue by SilviaAmAm** [open-formulieren/open-forms#2909]
### Product versie / Product version

2.1.x

### Omschrijf het probleem / Describe the bug

DH Taiga issue 450

### Stappen om te reproduceren / Steps to reproduce

Create a form with:
- an email field
- a content field with an inline colour

In the SDK:
- Fill in your email very slowly
=> after you type a character and then wait, the cursor jumps to the start of the line

**Comment by SilviaAmAm** [comment]
This happens because after each logic check, the html id in the nonce that is added in the `id`  of components with inline styles changes. This causes the configuration to be considered 'changed' here: https://github.com/open-formulieren/open-forms-sdk/blob/main/src/components/FormStep/index.js#L501
This causes the form to be rerendered and the function restoreFocus() is called for the email component

**Comment by SilviaAmAm** [comment]
Den Haag noticed this happening again, so I'm re-opening the issue (See Taiga for more details).

**Comment by sergei-maertens** [comment]
Fixed via ec731dd0bb39d3a0a69d12252fd024f17674cb3f
