### ISSUE TITLE
Problems uploading .heic files

### ISSUE THREAD

**Issue by SilviaAmAm** [open-formulieren/open-forms#2911]
### Product versie / Product version

2.1.x

### Omschrijf het probleem / Describe the bug

DH Taiga issue 317

There seem to be issues with uploading `.heic` files in the file upload component. Files provided by den haag (see DH taiga)
- sample1.heic 
- sample2.heic

=> In a file component where all file types are allowed for upload, only `sample1.heic` is accepted (`sample2.heic` is seen as a `.heif` file)
=> In a file component where only `.heic` file types are allowed, neither file is accepted. It looks like in the formio widget the mime type for both files is guessed to be `image/heif` and so both fail the validation.

Extra note:
The error messages are escaped when they shouldn't be?
![Screenshot from 2023-03-21 10-22-25](https://user-images.githubusercontent.com/19154114/226567241-82fb139e-34f5-413b-a286-af6ce7f6bf99.png)

### Stappen om te reproduceren / Steps to reproduce

Create a form with
- An upload component with only `.heic` files accepted
- An upload component with all file types accepted

Fill in the form with the files provided above

### Screen resolution

None

### Device

None

### OS

None

**Comment by CharString** [comment]
Refinement:
What does DH need exactly to get the Ooievaarspas life?

From what I read from [wiki](https://en.wikipedia.org/wiki/High_Efficiency_Image_File_Format), heif is a container which may contain an image that uses heic compression.
Both provided files are HEIF files, and only from sample2.heic, libmagic can determine that the contents uses heic compression... 

```py
In [1]: import magic

In [2]: sample2 = open("sample2.heic", "rb").read()

In [3]: sample1 = open("sample1.heic", "rb").read()

In [4]: magic.detect_from_content(sample1)
Out[4]: FileMagic(mime_type='image/heif', encoding='binary', name='ISO Media, HEIF Image')

In [5]: magic.detect_from_content(sample2)
Out[5]: FileMagic(mime_type='image/heic', encoding='binary', name='ISO Media, HEIF Image HEVC Main or Main Still Picture Profile')
```

Asked differently, can they process any heif file? And is it enough to let any heif file with a .heic extension through?

**Comment by CharString** [comment]
To be clear: I haven't looked into the double escaping of the error message.

**Comment by CharString** [comment]
["There is no elegant solution"](https://stackoverflow.com/questions/58269428/i18next-react-trans-component-escaping-characters-correctly) fixing the escaping dives through FormIO into i18next. I vote for "wontfix"
