### ISSUE TITLE
Als gebruiker moet ik zowel binnen als buitengemeentelijke verhuizingen door middel van 1 formulier kunnen doorvoeren. ...

### ISSUE THREAD

**Issue by joeribekker** [open-formulieren/open-forms#292]
...Het systeem moet weten of het om een verhuizing binnen de gemeente of intergemeentelijk is. Deze mogelijkheden moeten verschillend afgehandeld kunnen worden. Bij de uitvraag moet de gemeentecode dus opgevraagd worden.

Eis: Authenticatie En Basisgegevens 3b.
Zie ook NvI: 95

**Tasks**

* [x] Veld Gemeente woonplaats (zie comments) moet gekoppeld kunnen worden uit StUF-bericht aan een veld.

**Comment by joeribekker** [comment]
@BasvanRensDK komt hierop terug.

**Comment by BasvanRensDK** [comment]
@joeribekker zojuist met Arno Schaafsma gesproken. Hij geeft het volgende aan: 

In de standaarduitvraag voor een natuurlijk persoon zit BSN, geboortedatum. Echter niet de woonplaats. Deze zou binnengehaald moeten worden met het veld:   'Gemeente van inschrijving' (zo heet het veld volgens Stuf.

Kun jij hier verder iets mee? 
Zo ja, GO!
Zo nee, morgen heb ik om 10.30 uur een afspraak met Arno. Je zou dan kunnen aanhaken om het verder duidelijk te krijgen.
