### ISSUE TITLE
Validation can be skipped by pausing a form

### ISSUE THREAD

**Issue by LaurensBurger** [open-formulieren/open-forms#2928]
### Product versie / Product version

2.1.0

### Omschrijf het probleem / Describe the bug

When a user pauses a form and uses the link form the pause email to get back to the form the next form steps seems to always be "available" and clicking this step ignores validation.
![image](https://user-images.githubusercontent.com/112621537/227226707-52f0d811-0c31-4a23-9980-729b4ea43d4e.png)
1) The step that was paused and where the user returns
2) Checkboxes that are required
3) step: Buffbufff is available and after clicking:
![image](https://user-images.githubusercontent.com/112621537/227227005-0863cfb4-0eda-42da-a125-53e0a3e5a536.png)

This also works on the "overview" step, Pausing a form in the final step before "overview" would allow you to submit the form with empty **required** fields.

### Stappen om te reproduceren / Steps to reproduce

Create a form with 1 step
In this step drag a component that is **required**

Start the from and in the this step pause the form
Follow the link in the e-mail
Click on overview
Submit an empty form!
![image](https://user-images.githubusercontent.com/112621537/227232983-74444bd4-fd1a-4e4a-84a1-669917ca8efe.png)
![image](https://user-images.githubusercontent.com/112621537/227233216-8742b939-a3a3-483e-9b41-55f314642e03.png)

### Screen resolution

None

### Device

None

### OS

None

**Comment by joeribekker** [comment]
Refinement: Pending stakeholder.

**Comment by sergei-maertens** [comment]
The great Backend Validation ticket runs validation on the data when pausing the form too, it only disregards empty required fields. Finally, on the final submissions/confirmation page, the full backend validation runs again and prevents submission of invalid data.

Closing as stale.
