### ISSUE TITLE
Preventing: NotAuthenticated: "Authenticatiegegevens zijn niet opgegeven."

### ISSUE THREAD

**Issue by LaurensBurger** [open-formulieren/open-forms#2929]
### Thema / Theme

Other
DH: 479 (added 7-4 describes the way this error occurs which is not user friendly)

### Omschrijving / Description

looking into these errors (sentry 292298) it seems these are almost always caused by either:

- User's session has expired. (try to continue after X hours/days)
- User paused the session, but tries to continue anyway

In both situations the user is redirected to the first step of the form - which causes the user to try and continue their session which was destroyed in the meantime. 

If users who pause their submission and after timing out are directed to a page informing them of their session expiring and not to step 0 of the form with the option to go back to step X, but instead allow them to choose to start a "fresh" session or return to "main_website". 
In the case of pausing: Show them a page with instructions on how to continue their session from their e-mail. and return to "main_website". 

This will decrease the amount of errors we see from these actions.

**Comment by SilviaAmAm** [comment]
@LaurensBurger I can reproduce the first case (pause form and then click on 'begin form'). But I can't reproduce the second (let session expire and then click on 'begin form').
