### ISSUE TITLE
De gebruiker kan namens of met meerdere gebruikers inloggen (deze eis valt buiten het MVP) (zie subpunten):

### ISSUE THREAD

**Issue by joeribekker** [open-formulieren/open-forms#295]
Eis: Authenticatie En Basisgegevens 4.

* [x] #296 
* [x] #297 
* [ ] #298 
* [x] #299

**Comment by BasvanRensDK** [comment]
@joeribekker dat is juist en akkoord!

**Comment by joeribekker** [comment]
Ik sluit dit meta ticket en laat het rest punt op zichzelf staan.
