### ISSUE TITLE
Allow calculation of days between x and y (timedelta)

### ISSUE THREAD

**Issue by LaurensBurger** [open-formulieren/open-forms#2953]
### Thema / Theme

Form designer

### Omschrijving / Description

Sentry: 327615
utr: 66

As a form designer i want to calculate the amount of days between 2 dates. 
While i can use the provided validation on a date(time) component there is currently no way to use it in other ways to for example:
Show the amount of days a person is requesting a permit for X
The days until event y

Currently trying to deducting the following dates:
```
"date1": "2023-03-16T00:00:00+01:00", 
"date2": "2023-03-24T00:00:00+01:00", 
```
does result in: 
```
datetime.timedelta(days=8)
```
But the form crashes: "Object of type timedelta is not JSON serializable."

**Comment by joeribekker** [comment]
Refinement: `date X - date Y = Z` should result (and be serialized) in a ISO period string. Then you should also be able to do: `Z < P14D`
