### ISSUE TITLE
De gebruiker kan (wanneer de situatie daarom vraagt) zijn/haar mede gezinsleden selecteren om mee te verhuizen.

### ISSUE THREAD

**Issue by joeribekker** [open-formulieren/open-forms#297]
Eis: Authenticatie En Basisgegevens 4b.

* [x] (Re)add the selection of family members-component (can be under advanced section - no need to create a separate group for it in the builder).
* [x] Make sure it (still) works with Haal Centraal BRP API
* [x] Add support for StUF-BG plugin

**Comment by alextreme** [comment]
Deassigning due to shifting Shea to a different project
