### ISSUE TITLE
StUF-postalcode needs to use capital letters

### ISSUE THREAD

**Issue by joeribekker** [open-formulieren/open-forms#2977]
### Product versie / Product version

2.1.1

### Omschrijf het probleem / Describe the bug

The StUF spec requires postalcode to be in capital letters.

![image](https://user-images.githubusercontent.com/96970/231157030-5d2d9f9e-e6a5-46bb-a36d-bf3e94c29b6e.png)

I think this can just be enforced in the StUF-template with ``|upper`` or something (for bezoekadres and verblijfsadres)

### Screen resolution

None

### Device

None

### OS

None

**Comment by sergei-maertens** [comment]
Needs backport all the way to 1.1.x
