### ISSUE TITLE
Dockerfile does not build in rootless docker alternative "Podman"

### ISSUE THREAD

**Issue by svenvandescheur** [open-formulieren/open-forms#2978]
### Product versie / Product version

2.1.1

### Omschrijf het probleem / Describe the bug

The Dockerfile does not work with Podman, an alternative to Docker that is rootless and used at a customer of Open Forms. The main issues seems to be that certain `VOLUME`/`COPY` instructions result into permissions being set to the root user, which can be mitigated by setting the `USER` earlier in te process and passing the `--chown=maykin` flag to the `COPY` statement copying the source.

### Stappen om te reproduceren / Steps to reproduce

 - Install `Podman`
 - Clone repository.
 - Run `podman build .` in the project directory.

### Verwacht gedrag / Expected behavior

Should build.

### Screen resolution

None

### Device

None

### OS

None

**Comment by joeribekker** [comment]
That it doesn't work with podman is not a bug but a feature request imo.

**Comment by sergei-maertens** [comment]
No podman support planned - images built with docker can run in podman.
