### ISSUE TITLE
Als medewerker die werkt bij een overheid kan ik namens de gebruiker zonder authenticatie het formulier invullen, ...

### ISSUE THREAD

**Issue by joeribekker** [open-formulieren/open-forms#298]
...denk hierbij aan een baliemedewerker van een gemeente. Het is hiermee mogelijk om de authenticatie over kunnen slaan. Standaard staat deze functionaliteit uit, de beheerder kan deze activeren.

Eis: Authenticatie En Basisgegevens 4c.
Zie ook NvI: 177

**Comment by joeribekker** [comment]
@BasvanRensDK overlegt met @Hedda-van-Ooijen en @aguldie 

Gaat vooral om formulieren waar je echt geauthenticeerd voor moet zijn.

**Comment by joeribekker** [comment]
@BasvanRensDK volgens mij heb ik hier geen feedback op gekregen. Als dat inderdaad zo is, dan kan ik dit ticket niet meer binnen scope van het PvE oppakken aangezien we de laatste sprint in gaan.

**Comment by sergei-maertens** [comment]
This is possible through the employee authentication, they can then specify the BSN/KVK number
