### ISSUE TITLE
Prevent user from restarting the form

### ISSUE THREAD

**Issue by SilviaAmAm** [open-formulieren/open-forms#2986]
### Product versie / Product version

2.1.x

### Omschrijf het probleem / Describe the bug

Den Haag Taiga issue 480

The problem is that if you start a form anonymously and then go to the start page and log in with DigiD, you go through the flow of entering the credentials for DigiD, but then when you get back to the form, you are still filling it in anonymously.

### Stappen om te reproduceren / Steps to reproduce

Go to a form where you can both start it anonymously or after logging in with DigiD:
- Start the form anonymously
- Click on 'Previous page'
- Now log in with Digid

=> When you get back to the form you are still anonymously filling it in

### Verwacht gedrag / Expected behavior

It should either:
- Not be possible to go back to the start page (you shouldn't be able to click on the 'startpagina' step in the progress indicator, and if changing the url you should be redirected to the first step?)
- The start page should show a button 'Continue filling in' instead of all the login/start buttons

### Screen resolution

None

### Device

None

### OS

None

**Comment by joeribekker** [comment]
Refinement: Option 2 would be nice, added with the option to restart entirely. Classifying as low due to it's mostly a developer/designer thing.
