### ISSUE TITLE
HTML visible is summary (overzicht) page

### ISSUE THREAD

**Issue by SilviaAmAm** [open-formulieren/open-forms#2987]
### Product versie / Product version

2.1.x

### Omschrijf het probleem / Describe the bug

Den Haag Taiga issue 472

If there is HTML in the label/description/values of a form, these are shown as text in the summary page
![Screenshot from 2023-04-13 16-16-55](https://user-images.githubusercontent.com/19154114/231787732-a4934095-b599-409b-bed2-ebd5853f2821.png)
![Screenshot from 2023-04-13 16-17-04](https://user-images.githubusercontent.com/19154114/231787741-7848fcd2-a55d-4e73-b09a-d52821c77dfb.png)

### Stappen om te reproduceren / Steps to reproduce

Create a form with:
- A textfield with label `Tekstveld <b>Some HTML</b>`

Fill in the form:
- Input some text in the textfield => The label has 'Some HTML' in bold
- Go to the summary Page => The label has the raw HTML

### Screen resolution

None

### Device

None

### OS

None

**Comment by joeribekker** [comment]
Refinement: This (formio) feature is not something that we support and should not be used. The renderer should not interpret these HTML characters as HTML, thus all chars needs to be escaped.
