### ISSUE TITLE
Allow disabling "Save current information" for forms.

### ISSUE THREAD

**Issue by svenvandescheur** [open-formulieren/open-forms#3004]
### Thema / Theme

Other

### Omschrijving / Description

"Save current information" is undesirable in some deployments of Open Forms. I propose adding a Boolean field `save_allowed` (default=`True`) on the `Form` model and exposing in the admin and `FormSerializer`.

- The SDK can then respond by not showing  the "Save current information" button.
- TBD: How to handle submission of data if save_allowed=`False`?

### Added value / Toegevoegde waarde

Some organizations don't want to use forms with features like this or may have other approaches to dealing with these flows. Making this configurable provides for this scenario.

**Comment by sergei-maertens** [comment]
Internally in the code this is called `suspend`, so adding a model/API field `suspend_allowed` is a nice feature.

This requires:

- [ ] Adding model and serializer fields
- [ ] Expose field in the API for the SDK
- [ ] Add validation check in suspend/resume endpoints - these must return 403 when suspending is disabled for the form
- [ ] Update the SDK to read this field and conditionally display the pause/suspend/save button.
