### ISSUE TITLE
Pasted templates (that include styling) cause confirmation emails to fail. 

### ISSUE THREAD

**Issue by LaurensBurger** [open-formulieren/open-forms#3010]
### Product versie / Product version

2.0.x + 2.1.x

### Omschrijf het probleem / Describe the bug

When a template is pasted by a form designer and it contains (extra) tags like <span> the confirmation might not send at all because of the following error:

`unsupported operand type(s) for +=: 'NoneType' and 'str'`
sentry: 331077

The submission is successful, but the confirmation is never sent.

We should either warn the form designer about the use of these tags in the confirmation or make sure we van process whatever the form designer has used in their confirmation templates.

### Stappen om te reproduceren / Steps to reproduce

Create a form with a confirmation template that has a link nested deep inside tags or use this example:

```html 
<p>Beste {{ voornaam }} {{ voorvoegsel }} {{ achternaam }},</p>
<p>
  Wij hebben uw formulier ontvangen. Alle informatie die
  wij ontvangen, leggen wij vast met een zaaknummer. Dit document heeft als
  zaaknummer: {{ public_reference }}.
  <span class="normaltextrun"
    >Uw informatie verwerken wij binnen 3 werkdagen. Bij vragen nemen wij
    telefonisch of per mail contact met u op.&nbsp;</span
  ><span class="eop">&nbsp;<br /></span
  ><span class="normaltextrun"
    >Heeft u zelf vragen? Bel 063111111 of mail naar </span
  ><span style="font-size: 9pt; font-family: 'Segoe UI', sans-serif"
    ><a href="mailto:info@formdudes.nl" target="_blank" rel="noopener"
      ><span class="normaltextrun"
        ><span
          style="
            font-size: 11pt;
            font-family: 'Calibri', sans-serif;
            color: #0563c1;
          "
          >info@formdudes.nl</span
        ></span
      ></a
    ></span
  ><span class="normaltextrun"
    >. Wij vragen naar het zaaknummer als u contact met ons opneemt.</span
  >
</p>
<p>Met vriendelijke groet,<br />formdudes.</p>
<p>{% appointment_information %} {% payment_information %}&nbsp;</p>

```

### Screen resolution

None

### Device

None

### OS

None

**Comment by sergei-maertens** [comment]
WYSIWYG editors commonly have issues with pasting from Word - could this be what's happening here?

**Comment by joeribekker** [comment]
@bart-maykin Reproduce, check traceback and put the full traceback in this ticket to work further
