### ISSUE TITLE
Als formulierbouwer Wil ik dat ik meer gegevens van een medeondertekenaar kan pre-fillen in het medeondertekeningscomponent

### ISSUE THREAD

**Issue by joeribekker** [open-formulieren/open-forms#3022]
Als formulierbouwer
Wil ik dat ik meer gegevens van een medeondertekenaar kan pre-fillen (lees, alle persoonsgegevens, i.p.v. alleen naam) in het medeondertekeningscomponent, 

Zodat ik van alle, bij de aanvraag betrokkene personen, logica kan toepassen die persoonsgegevens, om daarmee te controleren of een specifieke subsidie aangevraagd mag worden.

**Case**
Sommige subsidies kunnen maar aan één van twee partners worden toegekend. Om dit in een formulier te controleren, willen we zowel het BSN van de initiatiefnemer - als dat van de partner controleren met een database van personen die eerder subsidie hebben ontvangen.

Momenteel vult het onderdeel medeondertekening alleen de naam van de medeondertekenaar in.

Idealiter zouden we dezelfde hoeveelheid gegevens willen kunnen prefillen als voor de initiatiefnemer. Dus niet alleen het BSN, maar ook het adres enz.

**Comment by hlmr-erik** [comment]
Ik ving onlangs ergens op dat het niet toegestaan is (zou zijn?) om binnen een actieve DigiD sessie nogmaals in te loggen. Zojuist kwam ik bij de Belastingdienst een situatie tegen waarin precies dat gebeurde; dat is dan wel vreemd
![image](https://github.com/open-formulieren/open-forms/assets/111565013/2e3a3520-9f44-484a-b826-9a7661f5958a) Nadat mijn partner met DigiD ondertekend had ik zelf nog steeds ingelogd

**Comment by StefSchots1993** [comment]
https://dimpact.atlassian.net/browse/PF-80

**Comment by joeribekker** [comment]
@hlmr-erik Ik heb dat ook maar weer gehoord maar kon het nooit echt vinden in de documentatie. Volgens mij gooien commerciële gateways/identity brokers ook roet in het eten omdat die zelf de sessie managen. De Belastingdienst heeft een eigen gateway vermoed ik en kan daarin flexibeler zijn.

Desalniettemin, vind ik het omvormen van mede-ondertekenen wel goed zodat de noodzaak om samen achter 1 computer te zitten zo verdwijnt. Het wordt tevens gebouwd als component dus de "oude" manier houden we nog wel even er in zitten.

**Comment by joeribekker** [comment]
Duplicate van #2467
