### ISSUE TITLE
Upgrade to Django 4.2

### ISSUE THREAD

**Issue by sergei-maertens** [open-formulieren/open-forms#3049]
Checklist to prepare the Django 4.2 LTS upgrade

**3rd party packages to verify/make compatible**

- [x] django-admin-index (should be fine, see https://github.com/maykinmedia/django-admin-index/pull/87)
- [x] django-autoslug (-> update to django-autoslug 1.9.9)
- [x] django-axes (#3218)
- [x] django-better-admin-arrayfield (#3737)
- [x] django-camunda (no changes needed, it's compatible)
- [x] django-capture-tag (outdated but should work)
- [x] django-colorfield
- [x] django-cookie-consent
- [x] django-cors-headers
- [x] django-decorator-include (not maintained, but [appears to work with Django 4.2](https://github.com/twidi/django-decorator-include/pull/92) at least)
- [x] django-digid-eherkenning
- [x] django-hijack
- [x] django-modeltranslation
- [x] django-ordered-model (not in metadata, but appears to work)
- [x] django-privates (v2.0.0 was released to confirm support) 
- [x] django-redis (5.3.0, i.e. thelatest version supports Django 4.2)
- [x] django-solo
- [x] django-tinymce
- [x] django-treebeard
- [x] django-yubin (#3218)
- [x] mozilla-django-oidc-db (confirmed in maykinmedia/mozilla-django-oidc-db#64)
- [x] maykin-django-two-factor-auth[phonenumbers]
- [x] django-timeline-logger
- [x] django-csp
- [x] #3877
- [x] mail-cleaner  https://github.com/maykinmedia/mail-cleaner/pull/5
- [x] djangorestframework~=3.13.0 (upgrade to 3.14)
- [x] drf-nested-routers
- [x] djangorestframework-camel-case
- [x] django-filter
- [x] drf-jsonschema-serializer
- [x] drf-polymorphic
- [x] drf-spectacular
- [x] sentry-sdk[django]
- [x] elastic-apm
- [x] zgw-consumers

**Open Forms itself**

- [x] dark theme for tinymce (https://github.com/open-formulieren/open-forms/pull/3235/commits/d9731f6af09dbefc3b108af93d7efb4d5fef4224)
- [ ] Check deprecation warnings
- [x] Remove `ugettext*` variants (the `u` prefix can be dropped)
- [x] Bump the version of Django's intersphinx version to 4.2
- [x] CSRF_TRUSTED_ORIGINS needs to have the protocol
- [x] Update dark mode handling for TinyMCE? See [here](https://github.com/open-formulieren/open-forms/blob/b6ef8f577bb303f84c79c3910a688b2aa2216fce/src/openforms/js/components/admin/form_design/Editor.js#L12-L14) and [here](https://github.com/open-formulieren/open-forms/blob/b6ef8f577bb303f84c79c3910a688b2aa2216fce/src/openforms/js/initTinymce.js#L35-L37)
- [x] Migrate from `pytz` to `zoneinfo`

**Comment by ErhanCitil** [comment]
Ik heb het samen nagelopen met @sergei-maertens en we zijn tot de conclusie gekomen dat de versie van `django-autoslug` compatible is met Django 4.2 en Python 3.10. Dus het is geschikt voor Open Forms.

**Comment by ErhanCitil** [comment]
`Django Axes`: Deze package wordt gebruikt in Open Forms met de versie _5.31.0_, ik heb gekeken naar de originele bron code en het ondersteunt `Python 3.10 en Django 3.2` in de nieuwere versie. Deze versies worden ook gebruikt bij `Open Forms`. 

Het enige wat er gedaan moet worden is het updaten van de package naar een nieuwere versie in de requirements, de laatste versie op dit moment is: `6.0.5`.

**Comment by ErhanCitil** [comment]
`Django-Camunda`: Dit is een package van Maykin zelf, op het eerste gezicht zie ik dat de code wel werkt met `Django 4.2`. Alleen er moeten kleine aanpassingen gedaan worden en ik ga de test verbeteren zodat we zeker zijn dat het werkt met versie 4.2 van Django.

**Comment by ErhanCitil** [comment]
`Django Colorfield`: De nieuwste versie van deze package dat is op dit moment: `0.9.0`. Deze nieuwe versie heeft support voor DJango versie 3.2/4.2 en Python versie 3.10 wat gebruikt wordt in Open Forms. Dus het is een kwestie van updaten van de package naar versie 0.9.0.

Ik heb de tox bestand bekeken en de GitHub actions en de tests die slagen.

**Comment by ErhanCitil** [comment]
`Django-digid-eherkenning`: Is al geupdate door Sergei en Chris. De laatste versie wordt gebruikt in Open Forms. In de tox test zie ik dat het werkt met Django 4.2 en in de GitHub Actions staat hij op groen. 

Deze package kan goedgekeurd worden op de bovenstaande lijst.

**Comment by ErhanCitil** [comment]
`Django Hijack`: In Open Forms wordt deze package gebruikt met de versie `3.1.6`, de nieuwste versie dat is `3.4.1` deze ondersteunt wel Django versie `4.2`. Dit kan je zien aan de releases en in de GitHub Actions zie je dat het vinkje groen is met de test voor Django versie 4.2. Het is ook compatible met Python versie 3.10. 

Alleen de `Django Hijack` package moet geupdate worden naar `3.4.1` in de requirements en voor de rest niks anders.

**Comment by ErhanCitil** [comment]
@sergei-maertens ik heb gekeken naar de package `django-modeltranslation` ik denk wel dat het werkt met Django versie 4.2 maar weet het niet zeker, omdat ze het nergens hebben vermeld en geen tests hebben voor de Django versies. Ik zie wel dat het compatible is met Python versie 3.11 dat is de reden dat ik denk dat het werkt. Wat moet ik nu doen? Een fork maken en dan tests toevoegen of gaan jullie dan de package updaten in de requirements naar de nieuwste versie?

**Comment by ErhanCitil** [comment]
`Django Redis`: Zoals Sergei heeft vermeldt werkt de versie `5.3.0` met `Django versie 4.2` en `Python versie 3.10`. Dit kunnen we terug zien in de [CHANGELOG](https://github.com/jazzband/django-redis/blob/master/CHANGELOG.rst), en zien we ook aan de tests in de GitHub Actions.

Deze package moet geupdate worden in de requirements naar de versie `5.3.0` in Open Forms.

**Comment by ErhanCitil** [comment]
`Django Solo`: In Open Forms wordt de versie `2.0.0` gebruikt, er is een nieuwere versie waarbij er support is voor `Django 4.2` en Python `3.10 & 3.11`.  Dit kunnen we zien in [CHANGELOG](https://github.com/lazybird/django-solo/releases/tag/2.1.0), en er is een [tox test](https://github.com/lazybird/django-solo/blob/master/tox.ini) en in de GitHub actions wordt de tox test getest dus het bewijst dat Django versie 4.2 compatible is met het project.

Dus de package moet in de requirements geupdate worden van `2.0.0` naar `2.1.0`.

**Comment by ErhanCitil** [comment]
`Django Treebeard`: De versie `4.7` van deze package support `Django versie 4.2`, dit zien we terug in de [CHANGE](https://github.com/django-treebeard/django-treebeard/blob/master/CHANGES.md). In de readme wordt het ook beschreven dat er support is voor Django versie 4.2. Daarnaast zien we in de [Tox test](https://github.com/django-treebeard/django-treebeard/blob/master/tox.ini) dat er getest wordt de versie 4.2 en in de [GitHub Workflow](https://github.com/django-treebeard/django-treebeard/blob/master/.github/workflows/test.yml) zien we dat ook terug komen met de groene vinkje.

Dus de package `django-treebeard` moet in de requirements geupdate worden van `4.5.1` naar `4.7`.

**Comment by ErhanCitil** [comment]
`Django Filter`: Deze package heeft de versie `2.4.0` in Open Forms, de nieuwste versie dat compatible is met `Django versie 4.2` is ` django-filter 23.2 `. Dit staat beschreven in de [CHANGES](https://github.com/carltongibson/django-filter/blob/main/CHANGES.rst), en in de [Tox Tests](https://github.com/carltongibson/django-filter/blob/main/tox.ini). 

Deze package moet dus geupdate worden van versie `2.4.0` naar `23.2` in de requirements, en het kan afgevinkt worden in de bovenstaande lijst.

**Comment by sergei-maertens** [comment]
@ErhanCitil je mag gerust pull requests maken naar open forms om deze dependencies te updaten! Ik zorg even dat er een fork is onder maykinmedia

**Comment by ErhanCitil** [comment]
> @ErhanCitil je mag gerust pull requests maken naar open forms om deze dependencies te updaten! Ik zorg even dat er een fork is onder maykinmedia

Isgoed zal ik doen!

**Comment by ErhanCitil** [comment]
`Django Capture Tag`: Deze package al sinds 2016 niet meer geupdate en werkt met hele oude Django versies. Daarom heb ik hier van een fork gemaakt op de maykinmedia github en ga ik het updaten zodat het werkt met Django 4.2.

**Comment by ErhanCitil** [comment]
`Django timeline logger`: Deze package heb ik geupdate er staat een [pull request](https://github.com/maykinmedia/django-timeline-logger/pull/23) voor klaar.

**Comment by ErhanCitil** [comment]
`Elastic APM`: Deze package is compatible met Django versie 3.10 en 3.11. De package kan wel geupdate worden naar versie 6.17.0, daar zal ik wel een pull request voor aanmaken.

**Comment by ErhanCitil** [comment]
`Sentry SDK`: Deze package is ook compatible met Django 4.2 en Python 3.10/3.11. Dit heb ik geconcludeerd uit de tox test en de GitHub workflow. Ik zal een pull request aanmaken waarbij ik deze package update naar de laatste versie.

**Comment by ErhanCitil** [comment]
`Django better admin arrayfield`: Deze package heb ik geupdate, de [pull request](https://github.com/maykinmedia/django-better-admin-arrayfield/pull/1) is klaar om nagekeken te worden.

**Comment by ErhanCitil** [comment]
`Django Capture Tag`: @sergei-maertens, zoals je in deze [pull request](https://github.com/maykinmedia/django-capture-tag/pull/3) kan zien heb ik alleen de tests moeten verbeteren. Voor de rest werkt alles met Django 4.2 en Python 3.10. Dus het is aan jullie de keuze of jullie de fork willen gebruiken of de originele broncode.

**Comment by CharString** [comment]
@ErhanCitil  django-timeline-logger en drf-jsonschema-serializer hebben nieuwe releases op Pypi staan nu.

**Comment by ErhanCitil** [comment]
django-decorator-include kan ook afgevinkt worden in het lijstje, [Hier zien we dat het werkt met 4.2](https://github.com/twidi/django-decorator-include/pull/92).

**Comment by ErhanCitil** [comment]
Ik zie aan de hand van de GitHub actions dat django-jsonform werkt met Django 4.2 en Python 3.10.

**Comment by ErhanCitil** [comment]
`drf-polymorphic`: Deze package is van Maykin zelf, ik heb de Tox test en de GitHub workflows verbeterd. Hij is ready om na gekeken te worden. [Link naar pull request](https://github.com/maykinmedia/drf-polymorphic/pull/5)

**Comment by ErhanCitil** [comment]
drf-nested-routers: Bij deze package heb ik de tox test en de GitHub workflow verbeterd en het ziet te werken met Django versie 4.2 en Python versie 3.10. Dus de originele bron code kan gebruikt worden.

**Comment by ErhanCitil** [comment]
django-csp: voor deze package heb ik tests toegevoegd om zeker te weten dat het werkt met Django versie 3.2 en Python versie 3.10. Je kan het terug vinden in deze [pull request](https://github.com/maykinmedia/django-csp/pull/1).

**Comment by ErhanCitil** [comment]
django-csp-reports: Voor deze package heb ik ook alleen tests toegevoegd en ik zie het dat werkt met Django versie 3.2 en Python verise 3.10. Dus de huidige versie kan blijven staan. [pull request](https://github.com/maykinmedia/django-csp-reports/pull/1)

**Comment by sergei-maertens** [comment]
Unblocked for the rest of the upgrade now :tada:
