### ISSUE TITLE
File upload widget: add functionality of using the camera to add a photo

### ISSUE THREAD

**Issue by SilviaAmAm** [open-formulieren/open-forms#3050]
### Thema / Theme

Frontend

### Omschrijving / Description

DH Taiga issue 380 / user story 381

In the widget of the file upload, we can currently only browse local files:
![Screenshot from 2023-05-03 12-02-28](https://user-images.githubusercontent.com/19154114/235887362-978987a2-be7f-4a51-96b7-e5d0743528ae.png)

In Formio, it is also possible to use the camera to upload photos:
![Screenshot from 2023-05-03 12-04-53](https://user-images.githubusercontent.com/19154114/235887722-c92929c2-8fa5-4a1f-be61-fcf2a96bb4e1.png)

### Added value / Toegevoegde waarde

Convenience for the user

**Comment by LaurensBurger** [comment]
On mobile users are able to simply select their camera when clicking "bladeren". Works on iOS and Android.

**Comment by SilviaAmAm** [comment]
This is good for DH!
