### ISSUE TITLE
Include price logic in export

### ISSUE THREAD

**Issue by LaurensBurger** [open-formulieren/open-forms#3071]
### Thema / Theme

Form designer

### Omschrijving / Description

internal: Utr 81

As a form designer i do not want to redo all the price logic for a form after importing. 
I would like to import a form and the logic to be included, leaving only the selection of the exact product and payment provider after importing to make the form work.

**Comment by sergei-maertens** [comment]
Obsoleted now that price logic rules are removed and replaced with regular logic rules, which are included in exports.
