### ISSUE TITLE
WYSIWYG editor loses focus after each keystroke

### ISSUE THREAD

**Issue by Shoord** [open-formulieren/open-forms#3083]
### Product versie / Product version

2.1.0

### Omschrijf het probleem / Describe the bug

When writing in the rich content (WYSIWYG) field of the component 'Opmaak' > 'Vrij tekst', the field loses focus on each keystroke (after typing 1 digit). I.e you can't keep typing without clicking the field after each keystroke.

### Stappen om te reproduceren / Steps to reproduce

1. Open the details page of a form
2. Open the 'Stappen en velden' tab
3. In the screen painter, open the category 'Opmaak'
4. From 'Opmaak' drag the component 'Vrije tekst' to the right
5. The component settings open as pop-up
6. Click the WYSIWYG input field and start typing
7. Notice that you can't keep typing / the field losing focus after each digit

### Verwacht gedrag / Expected behavior

I expect to be able to keep typing

### Screen resolution

1920 x 1080

### Device

Desktop

### OS

MacOS

### Browser

Chrome, Safari

**Comment by SilviaAmAm** [comment]
I think this issue might have been fixed in version 2.1.1: https://github.com/open-formulieren/open-forms/issues/2889

**Comment by joeribekker** [comment]
@Shoord Welcome to the Open Forms Github!

Please re-open this ticket if it turns out this is not fixed in 2.1.1 or later.

**Comment by Shoord** [comment]
Thanks @joeribekker , I'll verify it again as soon as we upgrade. At this point, I assume it'll work accordingly.
