### ISSUE TITLE
Blocked 'next' button does not become active if user not logged in as admin

### ISSUE THREAD

**Issue by SilviaAmAm** [open-formulieren/open-forms#3114]
### Product versie / Product version

2.1.x, latest (d6ac4d1b60199b02c81179d3825adb3bb862b108)

### Omschrijf het probleem / Describe the bug

DH Taiga issue 503

If there is logic that blocks/unblocks the 'next' button of a form step, this seems to not work properly if the user is not logged in as admin.

### Stappen om te reproduceren / Steps to reproduce

Create a form with:
1. A step with a text field called `Field A`
2. A step with a text field called `Field B`
3. A logic rule saying: If `Field A` is equal to `Field B` and the step `step 2` has been reached, block going to the next step.
![Screenshot from 2023-05-24 16-05-40](https://github.com/open-formulieren/open-forms/assets/19154114/8de6fdde-9875-41ca-91c6-b0bf97a88fe4)

Fill in the form as follows (:warning:  Make sure you are not logged in as admin!!):
1. Fill `A` in the first step
2. Fill `B` in the second step and go to the next step (overview page)
3. Now go back to the first step and change `A` to `B`, then go to the next step.
4. In the second step, the 'next' button is blocked. Change `B` to `A` => The button does not become active again

Note: This doesn't happen if you are logged in as admin. Then the button becomes active as expected.

### Verwacht gedrag / Expected behavior

The button should not stay blocked.

### Screen resolution

None

### Device

None

### OS

None

**Comment by joeribekker** [comment]
Refinement: Part of a set of problems when logged in as admin (like content field colors?) and Sergei mentions caching? Marked as important due to user-facing problem.
