### ISSUE TITLE
Add new template snippet for co-sign to release notes

### ISSUE THREAD

**Issue by sergei-maertens** [open-formulieren/open-forms#3122]
#3085 added a snippet to our default confirmation e-mail template which needs to be added for existing instances as the default template has since been persisted in the database (or even overridden).

See https://github.com/open-formulieren/open-forms/pull/3085/files#diff-6fa0cd22f1a767b8a8c0cf01b3964faff7f66aff8b8fcf795a11fd4608930c95

**Comment by SilviaAmAm** [comment]
After discussion with Joeri (see https://github.com/open-formulieren/open-forms/issues/1530#issuecomment-1586858384), we should put this in a template tag and then automatically add it to the template around where the payment info is present.
