### ISSUE TITLE
Update generate_prefill_from_spec command

### ISSUE THREAD

**Issue by bart-maykin** [open-formulieren/open-forms#3127]
Update the generate_prefill_from_spec command to be fully compatible with oas 3.0.0 and 3.0.3

**Comment by joeribekker** [comment]
Refinement: When cursing happens because this is needed we will (try to) pick this up.

**Comment by sergei-maertens** [comment]
https://pypi.org/project/openapi3-parser/ - to now properly record it in the issue :)
