### ISSUE TITLE
Hidden file fields trigger validation on check_logic

### ISSUE THREAD

**Issue by LaurensBurger** [open-formulieren/open-forms#3128]
### Product versie / Product version

2.0.7
internal: rsd 120

### Omschrijf het probleem / Describe the bug

This issue is not present in 2.1.0+

Having a hidden file component in a form step causes the validation to trigger immediately on check_logic. 

### Stappen om te reproduceren / Steps to reproduce

Create form step with required fields
Add a file component and set it to hidden
Load the form and watch "This field is required" message pops up without any interaction

### Screen resolution

None

### Device

None

### OS

None

**Comment by joeribekker** [comment]
Refinement: 2.0.x still has support until september so we're adding it to our backlog but with low prio since there is a fix (namely: upgrade to 2.1)

**Comment by sergei-maertens** [comment]
Managed to find the root cause via #2213 - this caused the `defaultValue` of file fields also to be `null` instead of `[]`, which leads to the backend changing that `None` into an `[]`, which in turns triggers validation on the frontend.

**Comment by sergei-maertens** [comment]
Looks like ffb2d6558fd4bcacc7f352b9cd6a7fd05bd900a9 did the trick - this was #2436 all over again.
