### ISSUE TITLE
Form definitions with long names cause 500 when copied

### ISSUE THREAD

**Issue by LaurensBurger** [open-formulieren/open-forms#3130]
### Product versie / Product version

2.1.0 / 2.2.0

### Omschrijf het probleem / Describe the bug

When a form definition has  a long name, the new copy of this form definition will have a even longer name because the new copy will include 
(copy)
Original name: **This is a pretty looong title for a formdefinition**
New name: **This is a pretty looong title for a formdefinition (copy)**

Which results in a 500 for the user: value too long for type character varying(50)

### Stappen om te reproduceren / Steps to reproduce

Create a form definition with the title:
This is a pretty looong title for a formdefinition
Try to copy this form definition:
![image](https://github.com/open-formulieren/open-forms/assets/112621537/6811ab47-16b6-4084-b519-1a00f0e281b5)

**Comment by joeribekker** [comment]
Refinement: Okay, we truncate the part before the (copy) and add ellipsis.
