### ISSUE TITLE
Not possible to replace a form definition with overlapping variable names 

### ISSUE THREAD

**Issue by LaurensBurger** [open-formulieren/open-forms#3132]
### Product versie / Product version

2.x.x
internal: venray 63
### Omschrijf het probleem / Describe the bug

When a form definition has to be replaced by another form definition that contains the same variables as the original the form cannot be saved. a warning appears about duplicates.
![image](https://github.com/open-formulieren/open-forms/assets/112621537/348fbcc1-1275-4a5c-8821-c10f33cf4b68)

This causes confusion since the form builder believes the old form definition is removed after confirming to remove the form definition from the form.

This might cause them to manually start adjusting component/variable names in order to save the form. 

The solution is to save the form after removing the "old" form definition, which clears the variable names for the "new" definition and not trigger this error.

### Stappen om te reproduceren / Steps to reproduce

Create a form and create a new step, choose to import a form definition instead of creating a new one.
Select a common "block" with personal detail component
Add a new step and again choose a form definition
Pick another common common "block" with personal detail component.
You should see the error about duplicate components - this is expected.

Now remove both steps
Add a new step
import one of the same definition, or another with overlapping components
![image](https://github.com/open-formulieren/open-forms/assets/112621537/3751a3b4-7fdf-4808-bbaf-8772119c285b)
Even with only 1 step/definition the error is still triggered. thus the form cannot be saved

**Comment by SilviaAmAm** [comment]
I can't properly reproduce this issue :thinking: But I do see this issue:
1. Add a reusable form definition
2. Add the same form definition
![Screenshot from 2023-06-20 18-07-57](https://github.com/open-formulieren/open-forms/assets/19154114/f54a1386-8599-41c9-8f72-0ad1cb6c7262)
=> No warning appears that there are duplicate variables:
![Screenshot from 2023-06-20 18-08-06](https://github.com/open-formulieren/open-forms/assets/19154114/99ef90e0-e6cc-4601-affe-41c1e11f619c)
If I delete one of the steps, both variables disappear.

**Comment by SilviaAmAm** [comment]
Discussed: we should:
- Preventing using twice the same form definition
- Check why no JS warning appears when adding a new definition with overlapping variables (the warning appears only if you try to save
