### ISSUE TITLE
Can't start form in maintenance mode as form designer/admin

### ISSUE THREAD

**Issue by LaurensBurger** [open-formulieren/open-forms#3139]
### Product versie / Product version

2.1.3 - latest
reported by: Nopolder, Vught, SED, Horst

### Omschrijf het probleem / Describe the bug

Being logged in as a admin/form designer does not allow me to start a form that is set to maintenance mode.
![image](https://github.com/open-formulieren/open-forms/assets/112621537/10dbeb96-9317-41dc-b7db-4498ad2669eb)
![image](https://github.com/open-formulieren/open-forms/assets/112621537/1bec89c2-a627-4892-94d0-040935b6841b)

This should be possible and is causing interruptions in the "flow" of form designing

**Comment by sergei-maertens** [comment]
Can confirm, I ran into this and recently and thought I was doing something wrong myself
