### ISSUE TITLE
It's not possible to revert "Data removal" settings in a form

### ISSUE THREAD

**Issue by LaurensBurger** [open-formulieren/open-forms#3161]
### Product versie / Product version

2.1.x

### Omschrijf het probleem / Describe the bug

lv 85
When you set custom data removal in a form, it is impossible to remove them and in turn  making the form default back to the data removal settings in the general config.
The fields in this tab can not be saved when Null.
![image](https://github.com/open-formulieren/open-forms/assets/112621537/48166d13-e01b-40c1-8eae-fe81107d3223)

### Screen resolution

None

### Device

None

### OS

None

**Comment by joeribekker** [comment]
Refinement: Annoying for editor, reported by real life use. Seems like an easy to tackle fix.
