### ISSUE TITLE
De beheerder heeft de mogelijkheid om het ingevulde formulier in combinatie met een XML- of JSONbestand inclusief ...

### ISSUE THREAD

**Issue by joeribekker** [open-formulieren/open-forms#318]
...bijlagen geautomatiseerd op een bestandslocatie te kunnen plaatsen middels een beveiligde verbinding. Dit zodat een interne applicatie deze data zelfstandig kan oppakken (deze eis valt buiten het MVP).

Eis: Afhandeling 8.

**Comment by Bartvaderkin** [comment]
I think we covered this by including the merged data as a JSON file in the Microsoft Graph backend.
