### ISSUE TITLE
Haal centraal HR prefill

### ISSUE THREAD

**Issue by SilviaAmAm** [open-formulieren/open-forms#3185]
### Thema / Theme

Plugins

### Omschrijving / Description

Den Haag Taiga 528

Text of the issue:

_Graag willen we bij de HaalCentraal configuratie een tweede API kunnen aanroepen. Nu kunnen we er maar 1 gebruiken. Om eHerkenning nuttiger te kunnen gebruiken voor prefill gegevens. Nu gebruiken we HaalCentraal alleen voor DigiD, maar willen we dus ook gebruiken voor eHerkenning in de HaalCentraal HR API aanroep._

HR: Handelregister 

Edit: Unclear what Haal Centraal HR is, waiting for info form DH.

**Comment by joeribekker** [comment]
Refinement: Hier zal ook token-exchange voor moeten werken.

Up to the author of this ticket to add #3127 if needed.

**Comment by SilviaAmAm** [comment]
Den Haag says they don't actually need Haal Centraal HR

**Comment by SilviaAmAm** [comment]
Clarification by DH:

- This is a DH specific api
- We can use token exchange
