### ISSUE TITLE
Adding reusable form definitions with conflicting keys doesn't show warning

### ISSUE THREAD

**Issue by SilviaAmAm** [open-formulieren/open-forms#3188]
### Product versie / Product version

2.2.x

### Omschrijf het probleem / Describe the bug

- Create 2 reusable form definitions, both with a `textfield` component.
- Create a form.
- Add both form definitions created above
- Notice that you don't see a warning. If you save the form, you do get an error

### Screen resolution

None

### Device

None

### OS

None

**Comment by joeribekker** [comment]
Refinement: Annoying to editors but its caught with an error upon save so no immediate action.
