### ISSUE TITLE
Change the text next to the label for optional fields

### ISSUE THREAD

**Issue by SilviaAmAm** [open-formulieren/open-forms#3201]
### Thema / Theme

Frontend

### Omschrijving / Description

DH Taiga 530

Currently, DH has `(optioneel)` next to form fields that are optional (and no asterisks next to required fields).

However, DH would like this to become `(niet verplicht)`.

In the code: 
https://github.com/open-formulieren/open-forms-sdk/blob/main/src/formio/templates/checkbox.ejs#L21
https://github.com/open-formulieren/open-forms-sdk/blob/main/src/formio/templates/label.ejs#L8

### Added value / Toegevoegde waarde

This has to do with which words are expected to be known to someone with B1 dutch.

**Comment by sergei-maertens** [comment]
This also affects the react-intl translations in the SDK!

**Comment by SilviaAmAm** [comment]
This looks like it was mostly done in this issue https://github.com/open-formulieren/open-forms/issues/3651
