### ISSUE TITLE
Formulier editor - Meerdere checkboxes "check en bevestig" op bevestigingspagina

### ISSUE THREAD

**Issue by StefSchots1993** [open-formulieren/open-forms#3203]
### Thema / Theme

Frontend

### Omschrijving / Description

Userstory

Als formulierbouwer 
Wil ik meerdere checkboxes met te personaliseren “check en bevestig” teksten kunnen plaatsen op de bevestigingspagina.
Zodat ik als gemeente extra nadrukkelijk een aantal “controle en bevestigingsvragen” kan stellen aan de eindgebruiker op de bevestigingspagina.

Case
Op dit moment verschijnt er alleen een standaard checkbox op de laatste pagina.

![Formulier editor - Mogelijkheid voor meerdere checkbox vragen voor waarheid of extra kosten · Issue #82 · Dimpact-Samenwerking_Open-Formulieren - Google Chrome 2023-03-29 17 43 23](https://github.com/open-formulieren/open-forms/assets/84498045/44af6f7e-22bc-45d7-b7ba-67e274e09a7a)

Afgezien van het feit dat we deze zin niet aanpasbaar is (vertalen), zouden we graag andere/extra checkboxen introduceren in deze stap. Bijvoorbeeld zoiets als:
 'Ik beloof dat ik dit formulier naar waarheid heb ingevuld en geen relevante informatie heb weggelaten'.

Natuurlijk is het mogelijk om deze checkboxes op de vorige pagina toe te voegen als workaround; maar voor de user-experience is het beter is als de gebruiker een overzicht heeft van het hele formulier (zoals op het 'Controleer en bevestig' tabblad) voordat deze kiest om akkoord te gaan met deze dingen.

Dit zou er zo uit kunnen zien:
![image-20230329-171026](https://github.com/open-formulieren/open-forms/assets/84498045/73140031-92be-421d-be28-4f4bcb606166)

Acceptatiecriteria

Gepersonaliseerde checkbox teksten moeten mee te vertalen zijn met de rest van de pagina

Er moeten meerdere checkboxes te presenteren zijn op de bevestigingspagina

**Verduidelijkingsvraag Joeri**
Niet duidelijk genoeg: Wil je zelf checkboxjes + teksten kunnen toevoegen op de bevestigingspagina (Size: Large)? Of moet er gewoon optioneel eentje bij over de belofte (Size: Small)?

**Verduidelijking Haarlemmermeer**
Het gaat ons er om 1 specifieke checkbox te kunnen toevoegen, of zoals in de text van Joeri:
Of moet er gewoon optioneel eentje bij over de belofte (Size: Small)?

**STEF: als PO vanuit Dimpact ben ik wel benieuwd naar hoeveel meerwerk het is, wanneer de tekst vrij te vullen inplaats van alleen de belofte naar waarheid die Haarlemmermeer wil, eveneens als dat teksten meevertaald moeten/kunnen worden, Dit zijn namelijk wel opmerkingen die meegegeven zijn vanuit het wijzigingstafel pannel van de overige OF afnemers.**

**Comment by sergei-maertens** [comment]
Discussed this a bit more with Bart - we're not doing the full generic approach yet, BUT we are preparing for it and looking at the grander scheme of things.

1. There will be a new endpoint that provides a list of checkboxes that should be displayed. The existing endpoint will be deprecated (and removed in OF 3.0)
2. The endpoint will return a list of Formio component definitions, to be consistent with how appointments is reworked. We need to do this now as refactoring that later will require breaking changes
3. I'm picking up the frontend aspect to make sure we can render formio checkbox definitions

So this makes this ticket bigger than initially assessed, but otherwise the inconsistencies will catch up with us in the future.

**Comment by sergei-maertens** [comment]
SDK PR pending

**Comment by hlmr-erik** [comment]
It seems to currently only be possible to introduce this extra checkbox as a -global- option. However, as alas I hoped would have been apparent from the 'kunnen' in the first sentence of the story, we'd prefer it optional; so able to set it in the config of a specific form. A declaration of truthfulness is applicable only in a specific subset of our forms in which legal constraints oblige us to ask this of end users.

**Comment by sergei-maertens** [comment]
While I understand your perspective, this is ambiguous from the user story, especially as it's being compared with the privacy checkbox option which is also a global configuration.

Can you please list these requirements explicitly in the future? Now I don't see any mention of this in the acceptance criteria :(

Making this configurable per form is a considerable amount of extra work, as the available endpoints are not at all form specific currently.
