### ISSUE TITLE
Site ID parameter is empty when making a request to Piwik Pro

### ISSUE THREAD

**Issue by SilviaAmAm** [open-formulieren/open-forms#3216]
### Product versie / Product version

2.1.3

### Omschrijf het probleem / Describe the bug

When making a POST request to Piwik Pro, the `siteid` parameter is empty.

We need to figure out why.

### Screen resolution

None

### Device

None

### OS

None

**Comment by sergei-maertens** [comment]
Possibly same problem as #3136?
