### ISSUE TITLE
Uploads that have been removed are still present in registration

### ISSUE THREAD

**Issue by LaurensBurger** [open-formulieren/open-forms#3219]
### Product versie / Product version

2.1.3

### Omschrijf het probleem / Describe the bug

When a user uploads a file and contrinues to the next step, and later returns to a step to delete the uploaded file/upload another file, all files will be included in the registration, even the ones that were removed by the user.

### Stappen om te reproduceren / Steps to reproduce

upload file:
![image](https://github.com/open-formulieren/open-forms/assets/112621537/59774a7b-7da6-4e10-90a8-786aad6ab8c1)

Continue the form to "overzicht" and click "wijzigen" to return tot he step with the upload

Remove current upload 

Add new upload:
![image](https://github.com/open-formulieren/open-forms/assets/112621537/208200af-f2a0-4ed4-9073-71de7f97c366)

"Overzicht" will show only the new upload:
![image](https://github.com/open-formulieren/open-forms/assets/112621537/61e7653e-eec1-4aa8-b0bc-cbc97b88b464)

But in the registration Both files are present:
![image](https://github.com/open-formulieren/open-forms/assets/112621537/4d1cfd37-680c-4ffa-8eb6-c1ff3ddcb345)

### Verwacht gedrag / Expected behavior

The deleted upload should not be included in the registration.

### Screen resolution

None

### Device

None

### OS

None

**Comment by joeribekker** [comment]
Refinement: Needs to be fixed.
