### ISSUE TITLE
Remove logic rule logging

### ISSUE THREAD

**Issue by joeribekker** [open-formulieren/open-forms#3239]
Investigate if this feature is used (look at access.log).

As opposed to #2998

**Comment by sergei-maertens** [comment]
Same check on test environments (limited access logs to `/admin/` URLs):

5 / 15533  are logic log views, which is `0.03%`. I think we can remove this.

**Comment by joeribekker** [comment]
Refinement: @sergei-maertens will bring this up in refinement at DH

**Comment by sergei-maertens** [comment]
We can remove it *before* building an alternative.
