### ISSUE TITLE
Geboorte > datum missing from the possible prefill attributes in Haal centraal

### ISSUE THREAD

**Issue by SilviaAmAm** [open-formulieren/open-forms#3258]
### Product versie / Product version

2.2.x

### Omschrijf het probleem / Describe the bug

https://brp-api.github.io/Haal-Centraal-BRP-bevragen/v2/redoc
https://brp-api.github.io/Haal-Centraal-BRP-bevragen/v1/redoc

According to the Haal Centraal specs, there should be a `geboorte.datum` (v2) or a `geboorte.datum.datum` (v1) field. However, in our prefill configuration, this option is not present:
![Screenshot from 2023-07-13 14-31-15](https://github.com/open-formulieren/open-forms/assets/19154114/993fb29f-a589-4802-9c19-297b74910b7b)

It looks like in the code, the field `geboorte.datum.datum` has the name `Geboorte > Datumingangonderzoek > Datum`
![Screenshot from 2023-07-13 16-18-13 (1)](https://github.com/open-formulieren/open-forms/assets/19154114/29ab3d0d-a333-4604-bb58-c2c5a513a405)

The naming should be checked to make sure it's consistent.

### Screen resolution

None

### Device

None

### OS

None

**Comment by joeribekker** [comment]
Refinement: Manual changes needed; it only affects the visual label and not the property-names.
