### ISSUE TITLE
Using a list as data source that contains items with spaces creates values that are unusable in templates

### ISSUE THREAD

**Issue by LaurensBurger** [open-formulieren/open-forms#3277]
### Product versie / Product version

2.2.0

### Omschrijf het probleem / Describe the bug

When a list is used as data source for checboxes/selectboxes component the items in the list are duplicated for key + value. If these items contain spaces the values that are mapped are unusable in templates. 

### Stappen om te reproduceren / Steps to reproduce

List with 3 items with spaces
![image](https://github.com/open-formulieren/open-forms/assets/112621537/5ea9d876-5701-4e99-a5fa-015a60115aae)

use this list in checkbox component:
![image](https://github.com/open-formulieren/open-forms/assets/112621537/6420488d-b8ae-4988-9acf-7e8471a535b8)

looks good:
![image](https://github.com/open-formulieren/open-forms/assets/112621537/57e8b242-245e-4095-9cd6-61a45aecfeb4)

But using these values in templates is not possible:
![image](https://github.com/open-formulieren/open-forms/assets/112621537/d4736b6c-ab64-40ef-879d-bf15cc075f10)
 

### Verwacht gedrag / Expected behavior

When the item from the list are duplicated to Key & Value, perhaps the spaces should be stripped to make them usable in templates?

### Screen resolution

None

### Device

None

### OS

None

**Comment by sergei-maertens** [comment]
I recognize the problem, but the suggested fix only works when the data is in your control. If you're fetching values from a remote data source that contains spaces, the same problem still exists and cannot be mitigated.

I feel that custom template tags/filters for this purpose are better suited so you could do something like `{% get_value 'selectievakjes' 'optie 1' %}`, but that's just brainstorming quickly.

**Comment by joeribekker** [comment]
Refinement: This might be resolved by using datatype "object" to construct a tuple of key-values, to be used in the form choices for radiobuttons.

For service fetch, when there's keys with spaces, we should construct a 3-tuple with JQ: key, value, label. And use map in the JsonLogic in Opties-expressies.

It would be great if we test if this works AND then create recipe in the documentation for this.
