### ISSUE TITLE
If ANY Catalog API is down, you can not configure a ZGW API set

### ISSUE THREAD

**Issue by joeribekker** [open-formulieren/open-forms#3279]
### Product versie / Product version

2.2.0

### Omschrijf het probleem / Describe the bug

Sentry ID: 335396

The ZGW API set wants to retrieve a list of all zaaktypen, from all catalogs. Maybe we should not do this at all, or make it asynchronous, and move it to a dropdown.

I see this pattern quite often. Realtime connections that, if they fail, crash the app. Maybe we need something like `admin_requests` that handles errors gracefully with an error message? Ofcourse it still is case-by-case implementation aspect on how to proceed further.

This is also true for the Appointment configuration > location field.

### Screen resolution

None

### Device

None

### OS

None

**Comment by joeribekker** [comment]
Refinement: Needs to be discussed with @sergei-maertens before implemented.

**Comment by joeribekker** [comment]
Bumped in prio in overleg met Utrecht.

**Comment by joeribekker** [comment]
This can probably not be solved genericly, but we can create generic utils/functions to deal with these kind of issues. The functions should then be used where these issues happen.

**Comment by sergei-maertens** [comment]
Discussed the approach - decorating the admin class to catch exceptions is fine, this decorating itself can be made a bit more tidy by using django's `@method_decorator` (for example, see https://docs.djangoproject.com/en/4.2/topics/class-based-views/intro/#decorating-the-class)

However, as discussed there are some issues with the prototype:

* the exception class is handled in a generic way but the messages are specific to a particular field - this won't work if you have multiple fields that fetch data (such as zaaktypen & informatieobjecttypen each) - the error message then has the risk of not being useful enough or just being plain wrong (pointing to the wrong field)
* The current approach with `return None` as fallback results in removing the field from the admin form, which is confusing if you have an error message referring to that field. There is (apparently) a better approach to do this "enrichment" where the default field for the model field is rendered as fallback when something goes wrong. This goes right in the `limit_to_location` field in the admin for appointments configuration, so surely some inspiration can be found there. Patching zgw-consumers to apply the same pattern is also definitely an option.
* Finally, perhaps the error should just be generic and something along the lines of "Could not load data for field {field_verbose_name} - enable and check the request logs for more details"

**Comment by joeribekker** [comment]
> Finally, perhaps the error should just be generic and something along the lines of "Could not load data for field {field_verbose_name} - enable and check the request logs for more details"

I can live with that.

One question: What happens when data for a field cannot be loaded and someone presses "save"?

**Comment by sergei-maertens** [comment]
> One question: What happens when data for a field cannot be loaded and someone presses "save"?

The fallback field (textinput, for `models.CharField` or `models.URLField`) will still display the actual value (if it was configured) or be blank if nothing was selected yet, and the usual validation will kick in.

So if all my remarks are incorporated, it should not be possible to accidentally break configurations.
