### ISSUE TITLE
Nieuwe installaties hebben Engelse teksten (e-mail) bij de Nederlandse instellingen

### ISSUE THREAD

**Issue by joeribekker** [open-formulieren/open-forms#3308]
### Product versie / Product version

2.1.4

### Omschrijf het probleem / Describe the bug

![image](https://github.com/open-formulieren/open-forms/assets/96970/41a52f20-3c12-4f31-a239-37b8da40c9b3)

### Screen resolution

None

### Device

None

### OS

None

**Comment by joeribekker** [comment]
Refinement: Most likely similar to the copy-issue, runtime the default language is retrieved which can differ.

**Comment by joeribekker** [comment]
Hint might be here: https://django-modeltranslation.readthedocs.io/en/latest/usage.html?highlight=default#auto-population-modes-1

**Comment by bart-maykin** [comment]
Opened an [issue](https://github.com/deschler/django-modeltranslation/issues/698) in the django-modeltranslation library to add support for model.field default value translation on model creation.

**Comment by sergei-maertens** [comment]
@bart-maykin you can implement the feature 😄

**Comment by sergei-maertens** [comment]
Migrations are involved, no longer backporting this.
