### ISSUE TITLE
The dropdown selection for appointments is hard to navigate

### ISSUE THREAD

**Issue by joeribekker** [open-formulieren/open-forms#3312]
### Product versie / Product version

2.3.0-alpha.0

### Omschrijf het probleem / Describe the bug

Dropdown rendering is off:
![image](https://github.com/open-formulieren/open-forms/assets/96970/27203fad-15e9-4282-9c49-cce492ef7c51)

If the list is long, it cannot be scrolled and becomes really unclear whats happening:
![image](https://github.com/open-formulieren/open-forms/assets/96970/4679b3e5-f4e9-4f63-a701-882672d90f41)

### Screen resolution

1920 x 1080

### Device

Laptop

### OS

Windows

### Browser

Edge

**Comment by sergei-maertens** [comment]
Screen resolution is important information here, on my (larger-than-normal) monitors I don't have issues. Can you specify it? I presume 1920x1080?
