### ISSUE TITLE
Step is visited even though it's marked as n/a

### ISSUE THREAD

**Issue by joeribekker** [open-formulieren/open-forms#3316]
### Product versie / Product version

2.3.0-alpha.0 

### Omschrijf het probleem / Describe the bug

Taiga Hlmr 26

In het formulier zit een tabblad dat soms niet hoeft te tonen (bijv. bij keuze 'Ik wil een vergoeding aanvragen voor kinderopvang om sociale of medische redenen. ' op het tabblad 'Uw hulpvraag').  
In de tab-overzicht in de zijbalk toont deze stap dan ook als 'n.v.t.': Echter schakelt het formulier er toch naar over wanneer op het tab ervoor op 'Volgende' geklikt wordt.

![image](https://github.com/open-formulieren/open-forms/assets/96970/98f384ca-1379-46de-9b39-7d2570491c8e)

### Screen resolution

None

### Device

None

### OS

None

**Comment by hlmr-erik** [comment]
Not sure if this is actually a bug or a mistake on my end in configuring: I set the rule that marks this step as n/a to trigger -from this step-. Might well be that showing the page happens before the triggers loads then. Setting it to trigger from a step earlier fixes it.

**Comment by sergei-maertens** [comment]
Yeah, trigger from only triggers when the configured step is reached - so blocking the step that you're assigning the trigger to is misconfiguration indeed.

This feature is meant to essentially "execute this trigger and rule when all necessary data from previous steps is available"
