### ISSUE TITLE
Logging in to a form with eHerkenning doesn't return KvK prefill

### ISSUE THREAD

**Issue by hlmr-erik** [open-formulieren/open-forms#3323]
### Product versie / Product version

2.3.0-alpha0

### Omschrijf het probleem / Describe the bug

Logging in to a form with eHerkenning through Signicat results in all KvK-prefill fields remaining empty, regardless of the 'Identifier role' chosen in the component configuration. Using the KvK-demo plugin does return prefill data.

The log file shows:
![image](https://github.com/open-formulieren/open-forms/assets/111565013/f9f90dd4-5dc6-4f21-a73a-c8b71d660ab7)
![image](https://github.com/open-formulieren/open-forms/assets/111565013/f225a4a6-1028-44f1-8b8b-32ebd67e59b8)
![image](https://github.com/open-formulieren/open-forms/assets/111565013/a2fca94f-4f5d-4b61-a8c7-993dd9a7302e)
![image](https://github.com/open-formulieren/open-forms/assets/111565013/735f3ec1-347a-48a2-ac7a-69c029a4ec74)

### Screen resolution

None

### Device

None

### OS

None

**Comment by joeribekker** [comment]
Getest en is geen bug. Kan je dit via het ticketsysteem melden?
