### ISSUE TITLE
Styling of text in radio buttons label OpenID Connect

### ISSUE THREAD

**Issue by hlmr-erik** [open-formulieren/open-forms#3327]
### Product versie / Product version

2.3.0-alpha0

### Omschrijf het probleem / Describe the bug

The label-text of the radio buttons partially runs vertically instead of horizontally (even when disabling our custom css and design tokens)

![image](https://github.com/open-formulieren/open-forms/assets/111565013/b4a686f0-edcb-4f90-9ff2-9870576def89)

### Screen resolution

None

### Device

None

### OS

None

**Comment by joeribekker** [comment]
I think duplicate of ... @sergei-maertens mentions this for afspraken as well.

**Comment by sergei-maertens** [comment]
#3207 indeed
