### ISSUE TITLE
Dockerhub image versies niet compliant met semver geeft issues bij pullen

### ISSUE THREAD

**Issue by sudeshjethoe** [open-formulieren/open-forms#3339]
### Product versie / Product version

2.2.1

### Omschrijf het probleem / Describe the bug

In dockerhub staan images met niet standaard naamgeving in de tags die wij niet kunnen wegfilteren uit onze pipeline (obv [Harbor](https://goharbor.io/docs/2.2.0/administration/configuring-replication/create-replication-rules/). Hierdoor pullen wij standaard images die we niet nodig hebben en eigenlijk niet willen hebben.

Het gaat specifiek om versies die letterlijk een .X in de naam hebben (bijv. 2.2.X)

Hierbij het verzoek om ofwel semver te gebruiken bij het publiceren of niet en dit niet te mixen. Een alternatief zou kunnen zijn om het patch nummer weg te laten zoals dit ook bij andere projecten gedaan wordt (e.g. 2.2, zie ook [Alpine](https://hub.docker.com/_/alpine/tags))

Zie ook
https://semver.org/#backusnaur-form-grammar-for-valid-semver-versions
```
<version core> ::= <major> "." <minor> "." <patch>

<major> ::= <numeric identifier>

<minor> ::= <numeric identifier>

<patch> ::= <numeric identifier>
```

### Screen resolution

None

### Device

None

### OS

None

**Comment by joeribekker** [comment]
Refinement: we gaan de .X weglaten en de images pushen als `2.2`, conform the base Python images en alpine.

Hiervoor moeten onze github actions workflows aangepast worden (en de job die automatisch de dockerhub description bijwerkt).

**Comment by joeribekker** [comment]
@joeribekker dit heeft een PO nodig

**Comment by joeribekker** [comment]
Refinement: @sudeshjethoe ook Alpine heeft niet semver tags: 

![image](https://github.com/open-formulieren/open-forms/assets/96970/1070471d-1fd8-4d20-857b-78ff6b82161b)

Sergei merkt op dat Docker-images build information (met + als separator) niet toestaan, wat wel mag volgens semver. Dit ticket conflicteert daarom ook met de wens van gemeente Utrecht om geautomatiseerde build tags te publiceren (met nieuwe base image).

**Comment by sudeshjethoe** [comment]
Een naam gebruiken, zoals "edge" is idd niet semver, maar lijkt er ook niet zodanig veel op dat we die images onbedoeld zouden kunnen binnenhalen met harbor.

Als jullie een streepje ipv een plus gebruiken is dat ook geen issue omdat we dat kunnen wegfilteren.

2.3.0-hodm.2 is OK
2.2.0 is OK
2.2 is OK
2.2.X is NOK
