### ISSUE TITLE
Validate that products can be combined together

### ISSUE THREAD

**Issue by joeribekker** [open-formulieren/open-forms#3347]
When selecting multiple products and/or products for multiple persons, please perform the appropriate check if these products can be combined and/or done for multiple persons.

I'll leave it up to the developer to see when this check can be made (ie. upon selecting the product, or upon next step, or in the summary screen).

**Comment by sergei-maertens** [comment]
> When selecting multiple products and/or products for multiple persons, please perform the appropriate check if these products can be combined and/or done for multiple persons.

is that still not the case then? OF now queries JCC with the already selected product IDs

**Comment by joeribekker** [comment]
Hmm, well, if it is implemented I guess so. I picked 2 products I thought could not be booked together. I'll compare against jccs own page.

**Comment by sergei-maertens** [comment]
We'll hear from JCC if we're doing something wrong (still).
