### ISSUE TITLE
Show correct date/time for appointments in the confirmation mail

### ISSUE THREAD

**Issue by joeribekker** [open-formulieren/open-forms#3358]
Ref: LV 98

When you add the field-variable that holds the date/time, it shows correctly. But in the auto-generated part, it does not:

![image](https://github.com/open-formulieren/open-forms/assets/96970/d066db72-8d88-4768-ad87-b86a13a4eab0)

**Comment by sergei-maertens** [comment]
Weird, looks like localisation is disabled then in the templates? I'll look into it.

**Comment by sergei-maertens** [comment]
Backports:

* stable/2.2.x: a7552069a5c58118031e2091433c4c75db5efee9, 6b6ec2ee83b809047c5ccfe31d7611e9c6c7318b\
* stable/2.1.x: f49b304bc3cbc13bda458cda9fd6c1af36611671, 244f944b86d1bffaaa2fac18ccd199ab6712bd31
* stable/2.0.x: 152527960ea32316c58fefe25cc5a0005314a166, 6148a2e06a569370cf29445f994ffa7e370268a9
