### ISSUE TITLE
Familymembers component error (stuf-BG)

### ISSUE THREAD

**Issue by LaurensBurger** [open-formulieren/open-forms#3368]
### Product versie / Product version

2.1.5

### Omschrijf het probleem / Describe the bug

Stuf-BG endpoint answers with:
```xml
    <antwoord>
        <object StUF:entiteittype="NPS">
          <inp.bsn>12341234</inp.bsn>
          <inp.heeftAlsKinderen StUF:entiteittype="NPSNPSKND">
            <gerelateerde StUF:entiteittype="NPS">
              <inp.bsn>12341234</inp.bsn>
              <geslachtsnaam>Lastname</geslachtsnaam>
              <voorvoegselGeslachtsnaam xsi:nil="true" StUF:noValue="geenWaarde"></voorvoegselGeslachtsnaam>
              <voornamen>Firstname</voornamen>
            </gerelateerde>
        </object>
      </antwoord>
```

which turns into:
```
{
@entiteittype: 'NPS', 
geslachtsnaam: 'Lastname', 
inp.bsn: '12341234', 
voornamen: 'Firstname', 
voorvoegselGeslachtsnaam: 
   {
   @http://www.w3.org/2001/XMLSchema-instance:nil: 'true', 
   @noValue: 'geenWaarde'
   }
}

```
which causes: sequence item 1: expected str instance, collections.OrderedDict found
because of `{@http://www.w3.org/2001/XMLSchema-instance:nil: 'true', @noValue: 'geenWaarde'}`

Which results in a 500
![image](https://github.com/open-formulieren/open-forms/assets/112621537/f88d444b-9761-439a-8437-7a023a2e5ba6)

sentry: 337366

### Screen resolution

None

### Device

None

### OS

None

**Comment by sergei-maertens** [comment]
Refinement: needs similar fix as c4503cf9e3b99f719d6bdccb4e52f99c5e23265e
