### ISSUE TITLE
Translation warning for empty "Toelichtingssjabloon"

### ISSUE THREAD

**Issue by LaurensBurger** [open-formulieren/open-forms#3375]
### Product versie / Product version

2.1.5

### Omschrijf het probleem / Describe the bug

internal: db16
When the "Toelichtingssjabloon" is empty it will return a translation warning for both languages. 
This should not happen when both versions (en + nl) of the field are empty.
![image](https://github.com/open-formulieren/open-forms/assets/112621537/a2492765-944e-4d39-ba53-195405e3c4a8)

Since the "toelichtingsjabloon" is optional and often left blank, this wanring should only occur if one version is different from the other.

**Comment by sergei-maertens** [comment]
Refinement: suggested fix accepted. We should also check other translatable, optional fields for similar behaviour.
