### ISSUE TITLE
Translations: Date/Datetime components warn for translations of "dd-mm-yyyy" & "dd-MM-yyyy HH:mm"

### ISSUE THREAD

**Issue by LaurensBurger** [open-formulieren/open-forms#3382]
### Product versie / Product version

2.1.x - 2.2.x

### Omschrijf het probleem / Describe the bug

Date and Datetime components in a form with translations will always show requirements for translations.
This is cause by their placeholders:
  "placeholder": "dd-mm-yyyy",
  "placeholder": "dd-MM-yyyy HH:mm",

This can only be solved by removing the placeholder.

**Comment by sergei-maertens** [comment]
Refinement:

* placeholder cannot be changed at form design time
* form design reports that placeholder is missing translation
* placeholder cannot be translated in translations tab

-> proper solution would be to exclude `placeholder` from translations, which is *hard* in the current form builder

postponing this to the new form builder
