### ISSUE TITLE
Phone number validation

### ISSUE THREAD

**Issue by SilviaAmAm** [open-formulieren/open-forms#3383]
### Thema / Theme

Other

### Omschrijving / Description

Den Haag Taiga user story 567

Wish:
The user should be able to enter dutch phone numbers in national or international format (06... vs +31 6 ...) and foreign phone numbers should only be entered in international format.

### Added value / Toegevoegde waarde

Currently, if both dutch phonenumber/international phone number validation is turned on, the user can only enter durch phone numbers in international format.

**Comment by sergei-maertens** [comment]
Refinement: let's change the behaviour of multiple validators to be OR-ed rather than AND-ed - the latter does not make sense with the current set of validators we implement.
