### ISSUE TITLE
The number 1000000000000000000000 in a currency component is changed to 121 

### ISSUE THREAD

**Issue by SilviaAmAm** [open-formulieren/open-forms#3384]
### Product versie / Product version

master (6ba14238019948a14c550e0d7b439042a80219d8)

### Omschrijf het probleem / Describe the bug

Den Haag Taiga user story 557

Entering the number 1000000000000000000000 (1 with 21 zeroes) in a currency component is changed automatically to 121.

**Comment by sergei-maertens** [comment]
I guess it's trying to put down `1e21`?

I'm curious what the use case for these high values is though

**Comment by sergei-maertens** [comment]
Refinement: while a valid report, we can't seem to picture a practical/realistic use case for such large numbers at this time. This was found by a tester deliberately trying to find bugs, so for now marking this as wontfix.
