### ISSUE TITLE
Inconsistent errors for email component

### ISSUE THREAD

**Issue by SilviaAmAm** [open-formulieren/open-forms#3385]
### Thema / Theme

Frontend

### Omschrijving / Description

Den Haag Taiga user story 555

![Screenshot from 2023-08-18 14-09-05](https://github.com/open-formulieren/open-forms/assets/19154114/3bfd11ad-e37f-4105-8c65-2e9812d88399)

![Screenshot from 2023-08-18 14-09-26](https://github.com/open-formulieren/open-forms/assets/19154114/27d6db78-bd44-463c-a559-8da2d33b7749)

They would like a consistent error display.

**Comment by sergei-maertens** [comment]
Refinement: the top error is the browser validator behaviour, which is surprising as we expected that to be turned of -> make sure this is disabled.
