### ISSUE TITLE
Validate that form definitions in form steps don't have duplicate keys

### ISSUE THREAD

**Issue by sergei-maertens** [open-formulieren/open-forms#339]
Each formdefinition is created using a FormIO.js builder, and multiple definitions are combined into a form through the `FormStep` model. However, this makes it possible that form-definitions duplicate some form field keys. If you then merge the submission data of all form steps, you can have steps that overwrite other step data.

When adding a form step, we need to validate that this doesn't happen.

**Comment by sergei-maertens** [comment]
#1071 added detection + a warning for this in the UI

**Comment by sergei-maertens** [comment]
Probably better would be to prefix the key with a step identifier, but this is a breaking change and also makes user-content templates tricky (confirmation e-mail, confirmation page...)

**Comment by SilviaAmAm** [comment]
@sergei-maertens I think this is fixed now because of variables?
