### ISSUE TITLE
Wysiwyg editor options go outside viewport in small windows

### ISSUE THREAD

**Issue by SilviaAmAm** [open-formulieren/open-forms#3391]
### Product versie / Product version

2.1.3

### Omschrijf het probleem / Describe the bug

Den Haag issue 568

If you want to add a content component and your browser has a small window, some of the options are not reachable.
![Screenshot from 2023-08-21 16-00-56](https://github.com/open-formulieren/open-forms/assets/19154114/e1f4d1b2-062a-4125-b5ad-7d6ae6015c59)

### Screen resolution

None

### Device

None

### OS

None

**Comment by sergei-maertens** [comment]
Refinement: mobile support for the form designer is best-effort.

We can take this into account when implementing the new form builder.

**Comment by joeribekker** [comment]
Refinement: Doublecheck if this is still an issue.

**Comment by SilviaAmAm** [comment]
![Screenshot from 2024-01-22 13-18-25](https://github.com/open-formulieren/open-forms/assets/19154114/866a776a-8deb-4b05-b734-af3fd901f2d4)
Looks like it's not a problem with the new builder
