### ISSUE TITLE
eh_service_uuid and eh_service_instance_uuid have same field name in NL translation

### ISSUE THREAD

**Issue by CharString** [open-formulieren/open-forms#3393]
### Product versie / Product version

latest

### Omschrijf het probleem / Describe the bug

![image](https://github.com/open-formulieren/open-forms/assets/325643/32b9a999-a96f-40c2-91a3-6c61aabe9e36)

Did not check other locales

### Screen resolution

None

### Device

None

### OS

None

**Comment by sergei-maertens** [comment]
This needs fixing in the library

**Comment by bart-maykin** [comment]
Fixes when updating to new version of django-digid-eherkenning after the pr of https://github.com/maykinmedia/django-digid-eherkenning/pull/42 gets approved

**Comment by CharString** [comment]
PR Merged in the library, but maybe we should postpone a release? There might be more fixes incoming during the upcoming testing.
