### ISSUE TITLE
Allow link in co-sign e-mails

### ISSUE THREAD

**Issue by LaurensBurger** [open-formulieren/open-forms#3413]
### Thema / Theme

Admin

### Omschrijving / Description

internal: Venr 71, rid 142

Allow OF users to decide if they want to include links in co-sign request e-mails.
As the feature currently does not support links in these e-mails the co-sign flow seems very basic and not user friendly. 
OF users should be able to make the choice whether they want to adhere to not include links in messages (like digid/mijnoverheid) or not. 

Added value / Toegevoegde waarde

UX!

**Comment by sergei-maertens** [comment]
> Allow OF users to decide if they want to include links in co-sign request e-mails.

Preferably I'd just make this always include links without configuration option to simplify things, and come with a proper explanation on why this is okay. The discussion in the Code For NL Slack was eye-opening for me that there's no actual official policy about links in emails. I think as long as we can properly motivate the decision, we should be good, but let's let @joeribekker  have the final say.

**Comment by joeribekker** [comment]
Refinement: Business decision: Let's add the link as default behaviour, where the link points to the form. It should be possible to turn off this behaviour (so no link). There should be some text to guide both scenarios (not sure if possible with the email template?) like: Click the link below to co sign, OR Find form X to co sign.
