### ISSUE TITLE
Change button for co-signing

### ISSUE THREAD

**Issue by LaurensBurger** [open-formulieren/open-forms#3414]
### Thema / Theme

Frontend

### Omschrijving / Description

currently a co-sing authentication step looks like this:
![image](https://github.com/open-formulieren/open-forms/assets/112621537/017e3205-8c85-44f9-8d67-6f443976dd5b)

The 2 identical buttons seem confusing and while there is a line explaining the use of the 2nd button, don't make it very clear.

Suggested to make it more clear these options are specifically for co-singing: 
![image](https://github.com/open-formulieren/open-forms/assets/112621537/b4116b29-5c79-452f-877f-01dd9337745a)

**Comment by sergei-maertens** [comment]
I like it :+1:

**Comment by LaurensBurger** [comment]
suggestion: if #3413 is done - could the co-sign options be hidden for "normal" visitors and only be shown when a user arrives through a co-sign link from a e-mail?

**Comment by vaszig** [comment]
Issue #3483 has been created for @LaurensBurger suggestion.
