### ISSUE TITLE
2.3.0.rc1 issues

### ISSUE THREAD

**Issue by LaurensBurger** [open-formulieren/open-forms#3415]
### Product versie / Product version

2.3.0.rc1

### Omschrijf het probleem / Describe the bug

- [x] "TemplateDoesNotExist logging/events/registration_debug.txt" when opening a submission sentry: 337539 #3417
- [x] Not selecting truth box causes form to crash when submitting https://github.com/open-formulieren/open-forms-sdk/pull/540
- ~~no formdata under "samenvatting" / {% summary %} confirmation e-mail~~
- [x] asterisk for privacy and truth (overzicht step) seem out of place (a newline below string)
- ~~Uncaught (in promise) Missing projectId (console in form builder, no impact)~~

**Comment by sergei-maertens** [comment]
> asterisk for privacy and truth (overzicht step) seem out of place (a newline below string)

Known issue that was pushed back to fix, WYSIWYG markup in this layout turns out to be hard to fix. We'll need to consult with NL DS for this.

> Uncaught (in promise) Missing projectId (console in form builder, no impact)

This has been a bug in react-formio since The Early Days and is out of our control to fix, can be safely ignored.
