### ISSUE TITLE
Bulk-import infrastructure configuration is broken

### ISSUE THREAD

**Issue by hlmr-erik** [open-formulieren/open-forms#3421]
### Product versie / Product version

?-2.3.0

### Omschrijf het probleem / Describe the bug

The text of the importing page says this:
![afbeelding](https://github.com/open-formulieren/open-forms/assets/111565013/9e0d9109-6483-492a-a3cb-d719a900c954)

However, selecting multiple zips at once doesn't work. Only a single one at a time.

Trying to import the bulk-export of another instance does -seem- to work in the Docker image:
![afbeelding](https://github.com/open-formulieren/open-forms/assets/111565013/6cab5eca-1e44-45b4-baa1-db87c85feb5b)
<br><br>
Though this happens in the background:

```
open-forms-master-celery-1         | [2023-08-25 13:58:46,514: INFO/MainProcess] Task openforms.forms.admin.tasks.process_forms_import[6d820e17-eb63-4c3b-add0-fee4de4b450d] received
open-forms-master-celery-1         | [2023-08-25 13:58:46,514: DEBUG/MainProcess] TaskPool: Apply <function fast_trace_task at 0x7fb29e81c1f0> (args:('openforms.forms.admin.tasks.process_forms_import', '6d8
20e17-eb63-4c3b-add0-fee4de4b450d', {'lang': 'py', 'task': 'openforms.forms.admin.tasks.process_forms_import', 'id': '6d820e17-eb63-4c3b-add0-fee4de4b450d', 'shadow': None, 'eta': None, 'expires': None, 'gr
oup': None, 'group_index': None, 'retries': 0, 'timelimit': [None, None], 'root_id': '6d820e17-eb63-4c3b-add0-fee4de4b450d', 'parent_id': None, 'argsrepr': "('imports/import_forms_4e9900d1-1fe4-423a-b76d-70
41001bc542.zip', 1)", 'kwargsrepr': '{}', 'origin': 'gen57@3091d2b9e0e5', 'ignore_result': False, 'properties': {'correlation_id': '6d820e17-eb63-4c3b-add0-fee4de4b450d', 'reply_to': '76e0d417-8071-3945-841
9-bf45907393d0', 'delivery_mode': 2, 'delivery_info': {'exchange': '', 'routing_key': 'celery'}, 'priority': 0, 'body_encoding': 'base64', 'delivery_tag': '7d379660-3f17-4862-b20c-c5b567737520'}, 'reply_to'
: '76e0d417-8071-3945-8419-bf45907393d0', 'correlation_id': '6d820e17-eb63-4c3b-add0-fee4de4b450d', 'hostname': 'celery@8f1b2bb4510b',... kwargs:{})
open-forms-master-celery-1         | [2023-08-25 13:58:46,524: ERROR/ForkPoolWorker-1] Task openforms.forms.admin.tasks.process_forms_import[6d820e17-eb63-4c3b-add0-fee4de4b450d] raised unexpected: FileNotF
oundError(2, 'No such file or directory')
open-forms-master-celery-1         | Traceback (most recent call last):
open-forms-master-celery-1         |   File "/usr/local/lib/python3.10/site-packages/celery/app/trace.py", line 451, in trace_task
open-forms-master-celery-1         |     R = retval = fun(*args, **kwargs)
open-forms-master-celery-1         |   File "/usr/local/lib/python3.10/site-packages/celery/app/trace.py", line 734, in __protected_call__
open-forms-master-celery-1         |     return self.run(*args, **kwargs)
open-forms-master-celery-1         |   File "/app/src/openforms/forms/admin/tasks.py", line 84, in process_forms_import
open-forms-master-celery-1         |     with zipfile.ZipFile(private_media_storage.open(import_file), "r") as zip_file:
open-forms-master-celery-1         |   File "/usr/local/lib/python3.10/site-packages/django/core/files/storage.py", line 38, in open
open-forms-master-celery-1         |     return self._open(name, mode)
open-forms-master-celery-1         |   File "/usr/local/lib/python3.10/site-packages/django/core/files/storage.py", line 243, in _open
open-forms-master-celery-1         |     return File(open(self.path(name), mode))
open-forms-master-celery-1         | FileNotFoundError: [Errno 2] No such file or directory: '/app/private_media/imports/import_forms_4e9900d1-1fe4-423a-b76d-7041001bc542.zip'
```

Bulk import of a 17mb file on the production environment results in:
![afbeelding](https://github.com/open-formulieren/open-forms/assets/111565013/b457c068-bc18-4ed2-acac-da220f2b0212)

### Screen resolution

None

### Device

None

### OS

None

**Comment by sergei-maertens** [comment]
Refinement - there's a bit to unpack here

1. The upload help text should be less ambiguous - we allow uploading a zip file containing other zip files (bulk export) or json files (single export). Rephrasing this to "Upload your exported ZIP-file" would probably be sufficient here. It was never the intent to allow multiple ZIP file uploads.
2. The bulk import with docker-compose appears to be misconfigured - we suspect that the private media volume is not mounted in both the uwsgi and celery worker containers, causing the file not to be found.
3. The 413 error is an infrastructure issue - we need to configure nginx to allow larger uploads to this particular bulk-import endpoint (and apply the same example in the docker-compose configuration).

**Comment by hlmr-erik** [comment]
Additionally, the bulk import seems to succeed
https://user-images.githubusercontent.com/111565013/263263084-6cab5eca-1e44-45b4-baa1-db87c85feb5b.png

..even when one of the included forms fails to import. In this case, all subsequent forms in the zip won't be imported, though the user might suppose everything succeeded because of above notice. Please make the bulk import show any errors that occur, and continue with the next form in the package on encountering an error.

**Comment by SilviaAmAm** [comment]
To do:
- [ ] Update help text of upload file field
- [ ] Check DH size of bulk export
- [ ] Update nginx configuration based on this limit
- [ ] Fix docker compose configuration
- [ ] Figure out what to do if some import goes wrong

**Comment by sergei-maertens** [comment]
Failed imports could be logged and then incorporated in the email digest that we're setting up via #3402

**Comment by SilviaAmAm** [comment]
More PRs to be merged

**Comment by SilviaAmAm** [comment]
One more to merge :)
