### ISSUE TITLE
Qmatic: form crash on form submit with outgoing log requests enabled

### ISSUE THREAD

**Issue by LaurensBurger** [open-formulieren/open-forms#3437]
### Product versie / Product version

2.2.1
lv: 98
### Omschrijf het probleem / Describe the bug

When outgoing requests log is enabled and a (appointment) form is submitted to Qmatic, the form crashes. 
sentry: 338227
"can't escape str to binary"

This entry is missing from the logs, but the appointment is made nonetheless. 
Disabling logging fixes the issue.

**Comment by sergei-maertens** [comment]
Some preliminary analysis reveals this happens when the requests are made (and logged) when running celery tasks *and* elastic APM tracing is active (it's the DB trace that seems to be crashing on the binary model fields, even though the content is empty)

**Comment by joeribekker** [comment]
Refinement: Sergei thinks its a bug in APM but we can see if we prevent saving/logging when binary content is involved. Sergei mentions it even crashes when the (binary) content is empty.

**Comment by sergei-maertens** [comment]
Some thoughts I had - perhaps the library should just wrap it's entire `emit` implementation with a decorator that surpresses any unexpected exceptions to make it generally robust.

The drawback of that approach is that you may lose log records that you expected to be there, but that is currently already a problem if transactions are rolled back so it's not making things worse.

**Comment by joeribekker** [comment]
Would this (wrap entire emit) be preferred over using Redis?

**Comment by sergei-maertens** [comment]
> Would this (wrap entire emit) be preferred over using Redis?

I think both are needed, redis-connections can still be borked for whatever reasons so then a network error would cause issues.

Using redis would solve the problem of log records not persisting when the parent transaction savepoint is rolled back (which the logging library knows nothing about) + should automatically result in log records being purged/expired and is better from a privacy perspective (not having data means you cannot inadvertedly leak it).
