### ISSUE TITLE
During the redirect to DigiD/eHerkenning login portals, a 'Samlrequest' dialog shows

### ISSUE THREAD

**Issue by hlmr-erik** [open-formulieren/open-forms#3438]
### Product versie / Product version

2.3.0

### Omschrijf het probleem / Describe the bug

It's not super intrusive, but would be nicer if it is hidden from the end user.

![image](https://github.com/open-formulieren/open-forms/assets/111565013/ba2f862c-d90f-49ff-8cb9-e7898ffa0806)

![firefox_2023-08-31_14 16 36](https://github.com/open-formulieren/open-forms/assets/111565013/f4e7a4be-8fa7-4b90-890e-5164c7db2b34)

### Screen resolution

None

### Device

None

### OS

None

**Comment by SilviaAmAm** [comment]
For when we do refinement: 
this looks the same as this issue: https://github.com/maykinmedia/django-digid-eherkenning/issues/25

**Comment by joeribekker** [comment]
This is not a bug. We use POST-binding for SAML. To make this screen go away, we need REDIRECT-bining. Thus, this is a feature and needs a stakeholder @hlmr-erik

**Comment by joeribekker** [comment]
This should be fixed by the referenced tickets.
