### ISSUE TITLE
Date component - no error for min/max date input.

### ISSUE THREAD

**Issue by LaurensBurger** [open-formulieren/open-forms#3443]
### Product versie / Product version

2.3.0

### Omschrijf het probleem / Describe the bug

DH: 577
Date components with validation for minimum and maximum dates do not inform the user about this requirement. 
It is clear when clicking the component, because out of range dates will not be available, but if you type in a date that is outside the available range the component will clear itself without informing the user why.

**Comment by joeribekker** [comment]
Refinement: Similar to the time-component issue.

**Comment by SilviaAmAm** [comment]
This is a flatpickr issue: https://github.com/flatpickr/flatpickr/issues/2698
