### ISSUE TITLE
Component-specific default map settings don't accept full coordinates

### ISSUE THREAD

**Issue by hlmr-erik** [open-formulieren/open-forms#3445]
### Product versie / Product version

2.3.0

### Omschrijf het probleem / Describe the bug

The full coordinates, as they are accepted in the general configuration, might be thus: 
52.1326332
5.291266

It seems like the fields are configured as regular number fields: they don't accept points in the input, only commas.

Trying to type the coordinates, and aftwards pasting them from clipboard:
![firefox_2023-09-04_09 50 26](https://github.com/open-formulieren/open-forms/assets/111565013/18c0904f-5e9f-4cef-884b-bd43d0e2cc3d)

A workaround consists of inserting the proper coordinates in the JSON of the component.

### Screen resolution

None

### Device

None

### OS

None

**Comment by joeribekker** [comment]
Refinement: We suspect the bug is about that you cannot add more than 2 decimals.
