### ISSUE TITLE
translations: Cannot save translation in different "layers" (groups)

### ISSUE THREAD

**Issue by LaurensBurger** [open-formulieren/open-forms#3466]
### Product versie / Product version

2.3.0

### Omschrijf het probleem / Describe the bug

utr: 116
hadm: 70

Translating a form where certain components are part of a group, saving translations for these components seem to remove all other translations in the same form step. 
This seems to only work 1 way > Adding translation to the components within groups. 
When you add translations to the non nested components - all translations survive.

### Stappen om te reproduceren / Steps to reproduce

Create form with translations
create a step
Add textfield1 to step
add fieldgroup1 to step
add textfield2 to fieldgroup1

Translate textfield1 + textfield2 save = texdfield1 lost translation

**Comment by joeribekker** [comment]
Refinement: Several people have fought to fix this, this time it will be ... @sergei-maertens

**Comment by joeribekker** [comment]
Refinement: Sergei tries to weasel his way out of this with some babbling on datamodel fixing on how data components are stored. We can also store all translations per component. Either way its a lot of work and those resources could be used to fix where the translations are stored and do it in the new formio builder.
