### ISSUE TITLE
Copy form: null value in column "prefill_plugin" violates not-null constraint

### ISSUE THREAD

**Issue by LaurensBurger** [open-formulieren/open-forms#3467]
### Product versie / Product version

2.3.0

### Omschrijf het probleem / Describe the bug

Migrated form components contain incorrect "prefill" json:
```json
  "prefill": {
    "plugin": null,
    "attribute": null,
    "identifierRole": "main"
  },
```
This causes crashes on import and copy of forms.

Updating the component changes null to "" and solves the copy issue
```json
  "prefill": {
    "plugin": "",
    "attribute": "",
    "identifierRole": "main"
  },
```

### Screen resolution

None

### Device

None

### OS

None

**Comment by joeribekker** [comment]
Refinement: Clear what should be done to fix, not hard.
