### ISSUE TITLE
CSP header "form-action" should be set and include obvious values

### ISSUE THREAD

**Issue by joeribekker** [open-formulieren/open-forms#3477]
Currently, Internet.nl gives us a warning for the CSP-headers regarding the missing form-action directive.

We should set this to: `form-action: 'self' https://digid.nl https://*.digid.nl https://eh.signicat.nl ` etc... Ogone as well!

Or, we should bite the bullet and implement the Redirect binding.

**Comment by joeribekker** [comment]
Refinement: We could tackle this similarly to analytics, to dynamicaly add CSP headers based on configurations (eherkenning can come from the metadata URLs in the identity provider XML, Ogone has a default and an override URL, and DigiD are.. default BUT also take the from the XML because they can use brokers).

**Comment by joeribekker** [comment]
Refinement:

* Grab URLs from XML (SingleSignOn/SingleLogout POST bindings)
* Cache URLs in something like `get_form_action_urls` for a day
* Invalidate this cache upon saving the model instance: Check Django Solo implementation

**Comment by vaszig** [comment]
Discussed this with @sergei-maertens as well.

The second task does not require caching, we only need the function which will be part of the library itself. The urls are already saved in the database and they are retrieved from there, so it's not necessary to cache them.
