### ISSUE TITLE
The co-sign options could be hidden for "normal" visitors

### ISSUE THREAD

**Issue by vaszig** [open-formulieren/open-forms#3483]
### Thema / Theme

Frontend

### Omschrijving / Description

This is a suggestion from Laurens.

Currently a co-sing authentication step is always shown so it would be more clear if we find a way to "hide" it from normal users and only be shown when a user arrives through a co-sign link from a e-mail.

**Comment by joeribekker** [comment]
Refinement: Several ways to tackle this. It might be blocked by the ticket for hash/path based routing (#3362) so we can push information via the URL query params. Alternatively, use toggle link to make the co sign button less prominent yet findable for people with the co sign instructions.

**Comment by sergei-maertens** [comment]
Realized via #4320
