### ISSUE TITLE
Top padding on components cause extra white space when the element above it is hidden

### ISSUE THREAD

**Issue by LaurensBurger** [open-formulieren/open-forms#3485]
### Product versie / Product version

2.3.0

### Omschrijf het probleem / Describe the bug

When a component is underneath a hidden component, it's `padding-top: 24px;` causes extra whitespace.
Example where 1st and 2nd component are shown, 2nd component gets the extra 24px padding because it's the second component in the step. `.openforms-form-control:not(:first-child)`
![image](https://github.com/open-formulieren/open-forms/assets/112621537/23da9459-0291-451e-95ae-e1e5756ac654)

**Comment by joeribekker** [comment]
Refinement: This will probably be fixed when we use more NLDS components. Added the label NLDS for when we tackle this and this becomes a checkbox item to see if it is fixed.

**Comment by sergei-maertens** [comment]
Hopefully fixed with removed form control styles which use flexbox gaps now. Need to verify it.

**Comment by sergei-maertens** [comment]
Not fixed automatically with flexbox, will create a patch to address this.
