### ISSUE TITLE
Slowdown due to reusable form defintions lookup when loading/starting a form.

### ISSUE THREAD

**Issue by LaurensBurger** [open-formulieren/open-forms#3491]
### Product versie / Product version

2.3.0

### Omschrijf het probleem / Describe the bug

Internal: LV 107

When a user creates a new form, or opens a existing form: Open forms always looks up all "reusable" form definitions. 

The calls to this endpoint: /api/v2/form-definitions?is_reusable=true&page=1&used_in= are paginated with 24 items per page. 

The paginated results contain all the data of the form definition, including translation. 

When the total amount of reusable form definition grows, the loading time automatically grows along with it. 
Example: 
environment with 416 defintions:
![image](https://github.com/open-formulieren/open-forms/assets/112621537/60131def-c48e-4668-bec3-31010e1eaaee)
Each request takes approx: 600ms x 17 = 10 seconds of loading only form definitions each time a form is opened or a new form is added.

This seems rather long and can only increase with the amount of forms but also extra data (translations) being included in these requests.

**Comment by joeribekker** [comment]
Refinement: We can create a separate endpoint to only return the name/uuid to prevent the heaps of data returned for the pulldown. We do need to refactor the client to retrieve the form definition detail when you actually want to use it. Pagination can be dropped for this endpoint. Sergei is not convinced so i'll let this sink in a  bit.
