### ISSUE TITLE
Deal with the case where Haal Centraal returns a partner without BSN

### ISSUE THREAD

**Issue by SilviaAmAm** [open-formulieren/open-forms#3524]
One of the test BSN of Haal Centraal v2 gives this back:

```json
{"type":"RaadpleegMetBurgerservicenummer","personen":[{"kinderen":[],"partners":[{"naam":{"voornamen":"Jean Marie","geslachtsnaam":"Beaudelaire","voorletters":"J.M."}}]}]}
```

However, we always expect a BSN for the family members component.

In Stuff BG, we ignore any family member without BSN, so maybe we should do the same thing.

**Comment by joeribekker** [comment]
Refinement:

1. Lets make the behaviour consistent and ignore those without a BSN
2. Let's add a help-text in the relevant component (preferably a bit more visible than behind a tooltip) that indicates this behaviour
3. Joeri will raise this issue with the stakeholders on how to deal with this.
