### ISSUE TITLE
Update analytics tools according to new CSPSetting model

### ISSUE THREAD

**Issue by vaszig** [open-formulieren/open-forms#3558]
We have already updated digid-eherkenning and Ogone (see PR #3514 ) in order to be connected with the CSPSetting model (with a generic foreign key).

We should do the same for the analytics tools for consistency.

**Comment by joeribekker** [comment]
Refinement: This will be part of adding Piwik Pro to bring CSP settings in line with DigiD/eHerkenning/Ogone.
