### ISSUE TITLE
Add ability to hide Table label in repeating groups (saved)

### ISSUE THREAD

**Issue by LaurensBurger** [open-formulieren/open-forms#3576]
### Thema / Theme

Frontend

### Omschrijving / Description

* SED 79
* DH 563

As a form designer i don't want to show the labels of tables, when a repeating group is saved.

When a table is included in a repeating group the label will always show when the repeating group is saved. 
Removing the label or setting:   "hideLabel": true, still renders a ":" when saving the repeating group. 
![image](https://github.com/open-formulieren/open-forms/assets/112621537/30eb60d9-6134-48de-83ce-3204db8e3c5c)

I would like to toggle the visibility of the label and it to not render any extra ":" in a repeating group.

**Comment by SilviaAmAm** [comment]
Looking at the issue in question for DH, I think this refers to content components in repeating groups.
