### ISSUE TITLE
Zgw zaken: Incorrect mapping of fields

### ISSUE THREAD

**Issue by LaurensBurger** [open-formulieren/open-forms#3580]
### Product versie / Product version

2.3.2

### Omschrijf het probleem / Describe the bug

https://github.com/open-formulieren/open-forms/blob/0cfac75454a3d9801f093e5002784dd304021181/src/openforms/registrations/contrib/zgw_apis/plugin.py#L157 
certain fields in OF zgw create zaak plugin are named incorrect: 
     "betrokkeneIdentificatie.verblijfsadres.woonplaatsNaam": 
     "betrokkeneIdentificatie.verblijfsadres.huisnummer": 
     "betrokkeneIdentificatie.verblijfsadres.postcode": 
The should instead be named: 
     "betrokkeneIdentificatie.verblijfsadres.wplWoonplaatsNaam": 
     "betrokkeneIdentificatie.verblijfsadres.aoaHuisnummer": 
     "betrokkeneIdentificatie.verblijfsadres.aoaPostcode": 

as per: 
https://github.com/VNG-Realisatie/gemma-zaken/blob/3873bebd4c93d6803b0cda8f43dcf47d3cc56bd8/api-specificatie/zrc/1.5.x/openapi.yaml#L13605

**Comment by alextreme** [comment]
Note that all 6 fields for verblijfsadres are incorrect, not only the 3 mentioned:

        "betrokkeneIdentificatie.verblijfsadres.woonplaatsNaam": RegistrationAttribute.initiator_woonplaats,
        "betrokkeneIdentificatie.verblijfsadres.postcode": RegistrationAttribute.initiator_postcode,
        "betrokkeneIdentificatie.verblijfsadres.straatnaam": RegistrationAttribute.initiator_straat,
        "betrokkeneIdentificatie.verblijfsadres.huisnummer": RegistrationAttribute.initiator_huisnummer,
        "betrokkeneIdentificatie.verblijfsadres.huisletter": RegistrationAttribute.initiator_huisletter,
        "betrokkeneIdentificatie.verblijfsadres.huisnummertoevoeging": RegistrationAttribute.initiator_huisnummer_toevoeging

Also verified in Zaken API v1.0/v1.2.1

https://github.com/VNG-Realisatie/gemma-zaken/blob/3873bebd4c93d6803b0cda8f43dcf47d3cc56bd8/api-specificatie/zrc/1.2.x/1.2.1/openapi.yaml

`    VerblijfsAdres:
      required:
      - aoaIdentificatie
      - wplWoonplaatsNaam
      - gorOpenbareRuimteNaam
      - aoaHuisnummer
      type: object
      properties:
        aoaIdentificatie:
          title: Aoa identificatie
          description: De unieke identificatie van het OBJECT
          type: string
          maxLength: 100
          minLength: 1
        wplWoonplaatsNaam:
          title: Wpl woonplaats naam
          type: string
          maxLength: 80
          minLength: 1
        gorOpenbareRuimteNaam:
          title: Gor openbare ruimte naam
          description: Een door het bevoegde gemeentelijke orgaan aan een OPENBARE
            RUIMTE toegekende benaming
          type: string
          maxLength: 80
          minLength: 1
        aoaPostcode:
          title: Aoa postcode
          type: string
          maxLength: 7
        aoaHuisnummer:
          title: Aoa huisnummer
          type: integer
          maximum: 99999
          minimum: 0
        aoaHuisletter:
          title: Aoa huisletter
          type: string
          maxLength: 1
        aoaHuisnummertoevoeging:
          title: Aoa huisnummertoevoeging
          type: string
          maxLength: 4
        inpLocatiebeschrijving:
          title: Inp locatiebeschrijving
          type: string
          maxLength: 1000`
