### ISSUE TITLE
(webkit) month height too low flatpicker

### ISSUE THREAD

**Issue by sergei-maertens** [open-formulieren/open-forms#3584]
Affects 2.3, 2.4, probably older versions too

![image](https://github.com/open-formulieren/open-forms/assets/112621537/c1c96b3e-0de5-448b-b19f-6a5227239a81)
should look like: 
![image](https://github.com/open-formulieren/open-forms/assets/112621537/e0cb390c-1dcf-47e5-bde0-7c6e9458fe7e)

**Comment by joeribekker** [comment]
Refinement: This is not really blocking anyone but doesn't look right. We assume this will be fixed with the mythical new form renderer.
