### ISSUE TITLE
Objects API registration backend no longer works with OF 2.4.0, raises 412 HTTP 

### ISSUE THREAD

**Issue by alextreme** [open-formulieren/open-forms#3604]
### Product versie / Product version

2.4.0

### Omschrijf het probleem / Describe the bug

Sending in via the Objecten API no longer works with HTTP 412. Raised via Utrecht Taiga 146 and reproduced on the test environment:

https://open-forms.test.maykin.opengem.nl/admin/submissions/submission/2630/change/

{"traceback": "Traceback (most recent call last):\n  File \"/app/src/openforms/registrations/tasks.py\", line 185, in register_submission\n    result = plugin.register_submission(\n  File \"/app/src/openforms/registrations/contrib/objects_api/plugin.py\", line 200, in register_submission\n    response.raise_for_status()\n  File \"/usr/local/lib/python3.10/site-packages/requests/models.py\", line 1021, in raise_for_status\n    raise HTTPError(http_error_msg, response=self)\nrequests.exceptions.HTTPError: 412 Client Error: Precondition Failed for url: https://objecten.test.opengem.nl/api/v2/objects\n"}

This is most likely due to missing the Content-Crs header in the API client refactor, which is a required field when POSTing to the Objects API

" Value: "EPSG:4326"
The 'Coordinate Reference System' (CRS) of the request data. According to the GeoJSON spec, WGS84 is the default (EPSG: 4326 is the same as WGS84)."

https://redocly.github.io/redoc/?url=https://raw.githubusercontent.com/maykinmedia/objects-api/master/src/objects/api/v2/openapi.yaml#tag/objects/operation/object_create

### Screen resolution

None

### Device

None

### OS

None

**Comment by sergei-maertens** [comment]
Zaken API will be affected too.

Another good reason why the tests should test against a real implementation

**Comment by joeribekker** [comment]
or not refactor too much at the same time...

**Comment by joeribekker** [comment]
Fijn opgeschreven trouwens @alextreme !

**Comment by sergei-maertens** [comment]
@Viicos can you please make a hotfix PR to address this? I'm amending another existing issue with tasks on how to structurally improve this.
