### ISSUE TITLE
Leave number fields intact, don't add dot-formatting to registration backends

### ISSUE THREAD

**Issue by hlmr-erik** [open-formulieren/open-forms#3605]
### Thema / Theme

Plugins

### Omschrijving / Description

Please leave the formatting of the contents of number fields to BE systems. Dot-formatting is only useful when a human would be processing the form data (as maybe when the form is submitted as an e-mail). Having dots added to fields made to contain a year, KVK number etc. is undesirable. As is allowing users to fill a field with text as well, or setting a custom RegEx filter each and every time.

![image](https://github.com/open-formulieren/open-forms/assets/111565013/1512857e-e022-418f-8f93-54c7411a78d5)

**Comment by sergei-maertens** [comment]
I suspect this is a template localization issue and not directly related to the frontend data input.

**Comment by joeribekker** [comment]
Refinement: This can probably be solved by adding localize off-tag in the template. Preferably make this a global option on sandbox rendering backend (see: `openforms.template` module)
