### ISSUE TITLE
Als gemeente wil ik user-input valideren dmv data uit het Basisregistratie Kadaster (BRK)

### ISSUE THREAD

**Issue by joeribekker** [open-formulieren/open-forms#3607]
Als formulierontwikkelaar wil ik een koppeling maken met het BRK, om bepaalde user-input te valideren met de data die in het BRK opgeslagen staat.

Ref: DH 609

**Voorbeeld**

Formulier: Heruitgifte erfpacht aanvragen

- User logt in met DigiD
- Controle BRK: is de naam van de aanvrager (volgens inlog DigiD/BRP) van de aanvrager gelijk aan de geregistreerde zakelijk gerechtigde voor het adres waarvoor de aanvraag geldt in de BRK?

Indien correct: user kan doorgaan naar volgende stap

Indien niet correct, toon foutmelding:

Uit controle van uw gegevens blijkt dat u deze aanvraag niet kunt doen. Voor meer informatie neem contact op [...]

- [x] https://github.com/open-formulieren/types/issues/29 / https://github.com/open-formulieren/types/pull/30
- [x] https://github.com/open-formulieren/formio-builder/issues/65 / https://github.com/open-formulieren/formio-builder/pull/68
- [x] https://github.com/open-formulieren/open-forms/pull/3646
- [x] https://github.com/open-formulieren/open-forms-sdk/pull/623
- [x] Implement formatter for custom component type (backend) for PDF, email, CLI...)
- [x] Implement `address` component in SDK
- [x] Implement BRK service integration
- [x] Implement backend validator to check provided address with authenticated user, in the BRK

**Comment by Viicos** [comment]
- https://github.com/open-formulieren/types/issues/29
- https://github.com/open-formulieren/formio-builder/issues/65
