### ISSUE TITLE
Time validation: When max is set by user causes warning. 

### ISSUE THREAD

**Issue by LaurensBurger** [open-formulieren/open-forms#3611]
### Product versie / Product version

2.4.1

### Omschrijf het probleem / Describe the bug

Setting a max time to 09:05 allows the user to set 09:04 etc: 
![image](https://github.com/open-formulieren/open-forms/assets/112621537/e6f44751-2326-4256-8cae-cc616a8c7cf3)

The max set should be the same as the user can input.

**Comment by sergei-maertens** [comment]
How do number fields treat this? If you specify max 100, is that inclusive or can you enter at most 99?

**Comment by joeribekker** [comment]
Refinement: We suspect inclusive/exclusive issue.
