### ISSUE TITLE
Objects API integration: pausing and restarting DigiD form causes hashed BSNs to be sent to the Objects API (only Demo BSN?)

### ISSUE THREAD

**Issue by alextreme** [open-formulieren/open-forms#3613]
### Product versie / Product version

2.4.0

### Omschrijf het probleem / Describe the bug

Submitted and analysed via DH OF Taiga 617

When pausing and restarting a DigiD form which uses the Objects API registration backend the bsn is sent to the Objects API as a hashed value.

After testing we can only reproduce this using the Demo BSN DigiD registration backend. Requires further analysis to first determine why this occurred for DH.

This seemed to be a regression of #2301 from Open Formulieren 1.1.8.

Further analysis from @LaurensBurger and me, this issue is applicable for:
- Demo BSN DigiD

This is not applicable:
- DigiD-SAML (because requires you to relogin)
- DigiD-OIDC within 15 minutes (continue during the same DigiD session)
- DigiD-OIDC >15 minutes (new DigiD session)

Unknown, to be tested:
- eHerkenning-SAML?
- eHerkenning-OIDC?

![image](https://github.com/open-formulieren/open-forms/assets/226839/f8305642-0365-43d8-b418-cdf556326fa2)

**Comment by joeribekker** [comment]
Refinement: Adding to milestone but low prio because it appears to only be happening with the demo plugin (which is still weird).

**Comment by alextreme** [comment]
@joeribekker the Taiga issue was updated that Laurens was able to reproduce this by pauzing and restarting twice in combination with the DigiD-OIDC integration. As such it is more relevant than only the demo plugin.

**Comment by SilviaAmAm** [comment]
I could reproduce it by logging in with DigiD (OIDC), pausing/resuming the form, and then submitting the form.
