### ISSUE TITLE
form embedded via iframe 

### ISSUE THREAD

**Issue by sjoerdie** [open-formulieren/open-forms#3615]
### Thema / Theme

Frontend

### Omschrijving / Description

Reported by Omgevingsdienst regio Utrecht (taiga 33):

Embed forms using `<iframe>` is not working.

A security error "not allowed" is displayed by the browser.

### Added value / Toegevoegde waarde

I understand from Sergei this is not tested and currently not supported.

### Aanvullende opmerkingen / Additional context

Adding to CSP has no effect.

` add_header X-Frame-Options "ALLOW-FROM <domain>";` in nginx has no effect.

**Comment by sergei-maertens** [comment]
I would really, really like to understand which problems embedding via iframe is supposed to solve.

Browsers keep tightening security measures (and that's a good thing), which makes iframes less and less viable.

**Comment by joeribekker** [comment]
Iframe will not be supported. Embedding is the way to go but there are improvements needed to make it work as it should. In 2.5 we hope to have tackled this.
