### ISSUE TITLE
Release 2.5 testing notes

### ISSUE THREAD

**Issue by sergei-maertens** [open-formulieren/open-forms#3616]
I'm adding some notes for release-testing (by hand) that are relevant and need to be double/triple checked.

- [x] Hash based routing (or not) @SilviaAmAm 
    - [ ] ~Validate against ODRU (see Taiga)~
    - [x] Embed a form in a "third party CMS" with hash based routing, on a subpath with the `?form=<form-id>` query string
    - [x] Ensure that a form can be started from this embed page
    - [x] Ensure that a form can be paused and resumed from this embed page
    - [x] Ensure that the co-sign flow still works (form with co-sign and have another person do the cosign check/confirmation)
    - [x] Appointment with demo plugin
    - [x] Check the appointment cancellation flow 
- [x] Test the  above flows in our own backend without hash based routing:
    - [x] Pause and resume
    - [x] Cosign
    - [x] Appointment cancellation

Test task orchestration refactor @vaszig :

- [x] Test a form with payment and cosign:
           - Ensure that upon submitting the form, no confirmation email is sent but a cosign request is sent.
           - Upon payment, a confirmation email is sent
           - Upon cosign a confirmation email is sent with the cosigner in the CC
           - Check that registration works
- [x] Test a form without payment:
            - Upon completion the confirmation email is sent
- [x] Test retrying to register submissions
- [x] Test a form with appointments

Styling refactors:  @SilviaAmAm 

- [x] Styling tests when submitting a form as registrator on behalf of a customer

PDF generation: @SilviaAmAm 

- [x] Check styling of confirmation/summary PDF (following WeasyPrint upgrade)

React 18 upgrade (#3697) @Viicos 

- [x] Check form designer (tabbed interface, adding/modifying/removing components...)
- [x] Check form definition admin (add / edit)
- [x] Design token editor for style/theme page
- [x] Plugin configuration in global configuration page
- [x] Form versions, viewing + restoring
- [x] Session timeout widget (bottom right in admin, counter + popup)

**Comment by SilviaAmAm** [comment]
Styling problems noticed:
 - [ ] Dropdown (missing the arrow and a bit too short): 
![Screenshot from 2024-01-23 11-53-25](https://github.com/open-formulieren/open-forms/assets/19154114/72ded450-b006-4a58-b4cb-f437b82b3588)
![Screenshot from 2024-01-23 11-54-09](https://github.com/open-formulieren/open-forms/assets/19154114/8696ac35-0857-453a-963d-8b306d053d7b)
- [ ] The asterisk has moved further down
![Screenshot from 2024-01-23 11-58-37](https://github.com/open-formulieren/open-forms/assets/19154114/87c311cb-2c83-459f-b46a-ba30d50d2e76)

**Comment by Viicos** [comment]
Empty time component can't be saved by default: the placeholder for min/max time is incorrect:
![image](https://github.com/open-formulieren/open-forms/assets/65306057/145d92ee-bac7-492b-bc1f-2af933f25c46)

**Comment by vaszig** [comment]
- [ ] Completion retry flag is not properly updated


![Image](https://github.com/open-formulieren/open-forms/assets/63058071/cd02ca10-92ef-431d-bf9a-d0b15dfe7fe0)

If we force a form with a registration to fail and then try to register again the submission in the admin, the registration succeeds but the flag still shows a red cross (`needs_on_completion_retry=True` - but it should be False)

**Comment by sergei-maertens** [comment]
> Embed a form in a "third party CMS" with hash based routing, on a subpath with the `?form=<form-id>` query string

Tested and it's broken - the query string parameter does not get sent along to the backend (SDK issue).
