### ISSUE TITLE
Select familymembers bugs out

### ISSUE THREAD

**Issue by joeribekker** [open-formulieren/open-forms#3625]
Open Forms 2.4.1

Ref: Taiga Utr 76
Ref: Sentry 341872

**Comment by sergei-maertens** [comment]
Seems to be same problem as #3368

We need a proper StUF handler for this sort of processing, types are not consistent of what we get back.

**Comment by sergei-maertens** [comment]
https://github.com/open-formulieren/open-forms/blob/c5a2d3821895dc4dbb7b1a29103d4359756e11f9/src/stuf/stuf_bg/client.py#L79 Looks generic but doesn't seem to handle the `#text` case linked above.

**Comment by Viicos** [comment]
Note for the future: as a Pydantic enthusiast, https://github.com/dapper91/pydantic-xml might be handy.

Looking at the Sentry local variables dumped, it's strange that this is happening:

![Image](https://github.com/open-formulieren/open-forms/assets/65306057/c3307e54-6cc4-4cc4-80dd-0dcd945798e3)


`authentiek` and `voorvoegselGeslachtsnaam` should have been filtered out by `_remove_nils`
