### ISSUE TITLE
Cannot pause and resume forms

### ISSUE THREAD

**Issue by SilviaAmAm** [open-formulieren/open-forms#3626]
### Product versie / Product version

19f34cb8ce79879069b3e3710027d6640ee06811 

### Omschrijf het probleem / Describe the bug

When resuming the form, this happens:
![Screenshot from 2023-11-21 15-29-53](https://github.com/open-formulieren/open-forms/assets/19154114/e0bfadde-4761-45ec-aabb-1edeef30c6b0)

### Screen resolution

None

### Device

None

### OS

None

**Comment by SilviaAmAm** [comment]
This is indeed not affecting the stable versions. 

@sergei I am not sure if we yet have tests that could catch this :S

**Comment by sergei** [comment]
Wrong Sergei 😉
