### ISSUE TITLE
Form crash when invalid time is entered by user

### ISSUE THREAD

**Issue by LaurensBurger** [open-formulieren/open-forms#3647]
### Product versie / Product version

2.4.1

### Omschrijf het probleem / Describe the bug

DH 624

ValueError - Could not parse time 'Invalid date'
![image](https://github.com/open-formulieren/open-forms/assets/112621537/ea95c0c1-0869-43cb-8e4e-a752224a6cd4)

if validation is set (min max) the form does not crash:
![image](https://github.com/open-formulieren/open-forms/assets/112621537/a8f656fd-9386-4cab-b22c-6fa308bdf120)

### Stappen om te reproduceren / Steps to reproduce

Add a time component to a form
enter: 25:00
form crashes

**Comment by sergei-maertens** [comment]
We should figure out if/how we can get rid of the 'Invalid date' in the input field value, which apparently gets sent to the backend.

A hotfix could be to specifically catch this "value" and treat is as empty?

**Comment by sergei-maertens** [comment]
I agree that the difference in behaviour is likely a race condition/timing discrepancy
