### ISSUE TITLE
Digid-oidc: Return after cancel not according to DigiD requirements

### ISSUE THREAD

**Issue by LaurensBurger** [open-formulieren/open-forms#3656]
### Product versie / Product version

2.4.1

### Omschrijf het probleem / Describe the bug

Digid-oidc (and eHerkenning) has no route for cancelled logins. The user is always shown a "generic" error screen which in the case of DigiD does not meet the requirement:

_Als de gebruiker het authenticatieproces annuleert (SAML-statuscode "AuthnFailed" of CGI-statuscode 0040), komt de gebruiker terug op de inlogpagina vanwaar getracht is de authenticatie te starten. Dit gebeurt in hetzelfde browserscherm. Er dient een melding getoond te worden met de mededeling dat het inloggen is geannuleerd._

digid-oidc
![image](https://github.com/open-formulieren/open-forms/assets/112621537/7e47352a-c9a9-44a9-9f78-fdc5f77217ac)
Digid
![image](https://github.com/open-formulieren/open-forms/assets/112621537/afbd77e3-4b1c-4555-8c12-a1d6f56cab57)

Digid-oidc does not return to the login page, and does not mention the cancellation

**Comment by StefSchots1993** [comment]
Dimpact is stakeholder

**Comment by joeribekker** [comment]
Refinement: We should also check the regular Logius DigiD cancel action to get back to the form with a proper error message.

**Comment by vaszig** [comment]
This is not easy to reproduce. @LaurensBurger could you please provide us with a link to a form where we can see this?at least to see the network and maybe find out from the urls what's happening.

**Comment by StefSchots1993** [comment]
@vaszig -> https://acc-formulier.dimpact.nl/testformulier-servicedesk/startpagina here you go :-D 

Choose "login DigiD" -> Now you're in the DigiD login screen, chose "annuleren" you're redirected to  https://acc-formulier.dimpact.nl/testformulier-servicedesk/startpagina?_start=1&of-auth-problem=digid_oidc which issn't a correct redirect according to Logius the DigiD provider. You should actually be redirected to "https://acc-formulier.dimpact.nl/testformulier-servicedesk/startpagina" again where you can sellect all authentication methods again + a message that the DigiD loggin is canceled. 

If further context or info is needed, please let me know!

**Comment by vaszig** [comment]
Thanks for the context and the specific form @StefSchots1993 . I will speak with Laurens as well if this is needed.
