### ISSUE TITLE
Max date validation in the past doesn't take 'Including current date' into account

### ISSUE THREAD

**Issue by hlmr-erik** [open-formulieren/open-forms#3671]
### Product versie / Product version

2.4.1

### Omschrijf het probleem / Describe the bug

Setting the validation for a date field to 'max in the past' -> 'including current date' does indeed make the current date selectable in the datepicker. However, it triggers a validation error after that.

![image](https://github.com/open-formulieren/open-forms/assets/111565013/936dcf9f-783f-484d-97a0-b215e5308930)

![image](https://github.com/open-formulieren/open-forms/assets/111565013/13f270fa-f325-4177-bf6c-a15877c11760)

### Stappen om te reproduceren / Steps to reproduce

1. Add date component to form
2. Set the maximum date validation to 'In the past'
3. Check 'Including current date'
4. Choose current date from datepicker

### Screen resolution

None

### Device

None

### OS

None

**Comment by joeribekker** [comment]
Refinement: Maybe this is already fixed with patches in 2.4.2, please check @vaszig
