### ISSUE TITLE
As end-user, I always want to know if a backend registration failed

### ISSUE THREAD

**Issue by joeribekker** [open-formulieren/open-forms#370]
Maybe we should handle `Exception` here:

https://github.com/open-formulieren/open-forms/blob/50668b4d1aa625e3b6f4b515da5614c38618763b/src/openforms/registrations/submissions.py#L38

If a plugin causes an uncatched exception, the submission plugin handler will crash, and not update the submission status to failed.

**Comment by sergei-maertens** [comment]
https://github.com/open-formulieren/open-forms/blob/5e67644f2a82afce21010ad248b815d1585a0fc0/src/openforms/registrations/tasks.py#L311

covers this
