### ISSUE TITLE
(Allow to) change co-sign texts to B1 Dutch

### ISSUE THREAD

**Issue by hlmr-erik** [open-formulieren/open-forms#3702]
### Thema / Theme

Frontend

### Omschrijving / Description

As per https://www.communicatierijk.nl/vakkennis/rijkswebsites/aanbevolen-richtlijnen/taalniveau-b1, we'd like for the texts regarding the co-sign functionality to be written in a more accessible level of Dutch (B1), or preferably be able to adjust it ourselves. 

Suggestion for the e-mail to the original submitter:

> **Belangrijke informatie over mede-ondertekenen**
> 
> Wij kunnen uw aanvraag nog niet verwerken, want deze moet eerst worden mede-ondertekend. We hebben het verzoek hiervoor gestuurd, naar het e-mailadres dat u heeft ingevuld: {partner_e-mail}
> 

Suggestion for the e-mail to the co-signer:

> Beste ,
> 
> {digid_first_name} {digid_prefix} {digid_last_name} heeft het formulier "{form_name}" ingevuld. Voordat wij dit kunnen verwerken, moet u dit mede-ondertekenen. Klik op deze link: {form_link} om het formulier te openen. Daarna wordt u doorgestuurd naar een pagina waar u inlogt met uw DigiD. 
> Nadat u bent ingelogd, voert u de volgende code in: {submission_id}

I don´t know if the component could be used where the co-signer isn´t the partner of the original submitter? If not, the sentences could be made easier still by referring to the partner.

**Comment by sergei-maertens** [comment]
Partner is indeed an assumption - this could probably also be used for a "voogd" who isn't necessarily family.

I like the suggestions, should be easy enough to incorporate this, but I'll wait until our next refinement to get it added to the board.
