### ISSUE TITLE
Update DigiD-library after fix is done

### ISSUE THREAD

**Issue by joeribekker** [open-formulieren/open-forms#3703]
### Product versie / Product version

2.5.0-alpha

### Omschrijf het probleem / Describe the bug

See: https://github.com/maykinmedia/django-digid-eherkenning/issues/51

### Screen resolution

None

### Device

None

### OS

None

**Comment by SilviaAmAm** [comment]
In the latest version (ef49482f9cf98ca8c92f2c61b4f9f3702b2b6df8) this is no longer an issue (see comment in the django-digid-eherkenning issue).
