### ISSUE TITLE
Update submission confirmation page (to clarify payment)

### ISSUE THREAD

**Issue by SilviaAmAm** [open-formulieren/open-forms#3726]
Currently, when a user submits a form which requires payment, they see this page:
![Screenshot from 2023-12-29 10-25-44](https://github.com/open-formulieren/open-forms/assets/19154114/f06654cd-a793-427c-b0ef-7a5a19215101)
Once they pay, then they see this screen:
![Screenshot from 2023-12-29 10-37-06](https://github.com/open-formulieren/open-forms/assets/19154114/aaffcbdb-b217-4590-9b64-a016a3efe27d)

This can be misleading, because from the confirmation page one may overlook the fact that a payment is still required.

**New design idea**

If the form requires payment, there will be a page with heading "Betalen" and an extra 'payment' step in the progress indicator.
The body will have the submission reference and the button to pay. Maybe the link to download the submission report could be added under the payment button.

After the user has paid (or if no payment is needed), then comes the "bevestiging" pagina. This says (if relevant) that the payment has been received, the submission reference and it shows the link to download the submission report. It also should have the 'Terug naar de website' button. 
Here there is no need to show the progress indicator.

**Comment by sergei-maertens** [comment]
Backend PR needs merging still
