### ISSUE TITLE
Allow validating the min/max amount of checked items in selectboxes

### ISSUE THREAD

**Issue by joeribekker** [open-formulieren/open-forms#3727]
Currently, it's not possible to count the number of checkboxes that are ticked.

For example, I want to make sure you the user checked at least 3 checkboxes, in order to continue with the form.

![image](https://github.com/open-formulieren/open-forms/assets/96970/a2be78f3-aba9-4114-a892-b68e13874a29)

This is caused by JSON-logic not being able to handle objects. Best I can do now is use all the exact keys to create an array first.

```json
{
  "<": [
    {
      "reduce": [
        [
          {"var": "choices.a"},
          {"var": "choices.b"},
          {"var": "choices.c"},
          {"var": "choices.d"}
        ],
        {
          "+": [
            { "if": [{ "===": [{ "var": "current" }, true] }, 1, 0 ]},
            {"var": "accumulator"}
          ]
        },
        0
      ]
    },
    3
  ]
}
```

Either we add validation on the component to simply say: minimum/maximum. Or we add a JSON-logic operator.
For simplicity, I would prefer the first.

**Comment by joeribekker** [comment]
Refinement: This is a builtin feature of FormIO so we can just enable/use it

**Comment by sergei-maertens** [comment]
@vaszig https://github.com/open-formulieren/types/actions/runs/7788059468 0.21.0 types release is building
