### ISSUE TITLE
Pre-release Q/A results for 2.5.0 (form builder) wip

### ISSUE THREAD

**Issue by LaurensBurger** [open-formulieren/open-forms#3733]
### Product versie / Product version

2.5.0

### Omschrijf het probleem / Describe the bug

**Components**
- [x] Date + datetime: Can only edit on initial creation, editing a existing date / datatime component will not work (high) https://github.com/open-formulieren/formio-builder/pull/109
- [x] Columns: Adding column via "+Add column" breaks the component, shows empty modal. (high) #3745
- [x] AddressNL (invalid, frontend PR was not merged yet)
![image](https://github.com/open-formulieren/open-forms/assets/112621537/a5d023f3-0e3f-471b-b749-4074213d67c5)
- [x] Repeating group: tooltip for button labels all show "Groep toevoegen-tekst" instead of: "Toevoegen", "Opslaan", "verwijderen" (low fixed via https://github.com/open-formulieren/formio-builder/commit/a58c41abff1e0cafef854069e7cf39e6d6bf010e)
- [x] Content: missing "label" field (wontfix: deliberate action)
- [x] Content: "Weergavestijl" not saving in editor > "CustomClass: null" (medium, fix via https://github.com/open-formulieren/formio-builder/commit/28f926d22613751325e665de7a9ede1f85a0bc0b)
- [x] Textfield: validation plugins missing both phone number plugins (wontfix: this is actually a fix that we added, use phonenumber field instead)
- [x] Textfield: "show character amount" shows the amount available instead of currently entered in field (seems the right way to do this, so the description in the editor is incorrect? "Toon live het aantal karakters gebruikt in het veld.") (low: check how the sdk deals with this)  
    
    This turns out to be broken in the old builder actually, the `maxLength` default is shown but not saved in the component, meaning there is actually not character limit being applied.  
    
    The combination of `validate.maxLength` and `showCharCount` indeed should show the number of remaining characters.
    
    https://github.com/open-formulieren/formio-builder/commit/88f13c9bf2f6896ab09f30a930d3df673600fb8f fixes the preview

- [x] Date/Datetime/time: Datetime field empties itself when a invalid date is entered, date+time fields show a (nice) warning (high)
  
  Occurs when you set a validation, e.g. date/datetime must be in the future and then enter an invalid value. The date field still displays the invalid value and shows the validation error, the datetime field removes the invalid value and displays no validation error.

  The behaviour is consistent with the old form builder, so marking this as wontfix for now, but it's a different issue/bug to fix.

- [x] Upload - front and backend (high) looks like an isolated incident, data migration in 18e90a5adaaacbf19fe99ded9ee718aaf8dfc0c4 fixes it (via #3710) 
![image](https://github.com/open-formulieren/open-forms/assets/112621537/55641579-05fa-4fdc-ad2d-4daa755b9560)
- [x] textarea: "automatic size adjust" renders a scrollbar (low, fix in [3827d4662f8bd46dd409e3d4c1ccd5b48742c64c](https://github.com/open-formulieren/formio-builder/commit/3827d4662f8bd46dd409e3d4c1ccd5b48742c64c))
![image](https://github.com/open-formulieren/open-forms/assets/112621537/dae155f9-8820-48a3-b110-baf9123602b5)

**General quirks:**
- [x] if a variable exists in a repeating group, new components use the same variable name instead of incrementing (high - wontfix for now)
  
  Did some investigating, and there is different behaviour between adding fields in the form definition admin vs. the form admin. The form admin does append a suffix (e.g. add text field, then add edit grid, then add text field inside edit grid gives you the keys: `textField`, `editGrid`, `textField1`). This behaviour is consistent with the old form builder (though inconsistent between FormDefinition and Form admin).
  
  Another consistent behaviour is when you add a second text field to the edit grid - both old and new form builder will create another key `textField1` and show validation errors on both fields warning for duplicated keys.

### These all seem to emerge with developer tools open: disable cache
- [ ] Dropdowns can turn into a different state, unsure how and is only: 
![image](https://github.com/open-formulieren/open-forms/assets/112621537/a8c4c331-7fd1-41ae-8478-8349e24f4bd6) (medium)
- [ ] flickering during load  (high)
[flickering.webm](https://github.com/open-formulieren/open-forms/assets/112621537/b0822840-cc8a-4c84-b69b-68c7c0ebb7a6)
   - While flickering: 
![image](https://github.com/open-formulieren/open-forms/assets/112621537/e3aaac48-8668-4931-9a64-a02041c417a8)

**Comment by sergei-maertens** [comment]
Discussed with Laurens - the flickering appears to be on his machine only so it's unlikely this is caused by the new form builder (as it also happens on the Django login page).

That wraps up this ticket.
