### ISSUE TITLE
The ZGW API configuration crashes when operation cannot be found

### ISSUE THREAD

**Issue by joeribekker** [open-formulieren/open-forms#3743]
Sentry: 347240

**Comment by Viicos** [comment]
I think this was fixed by: - https://github.com/maykinmedia/zgw-consumers/pull/77 but still missing a release and bump in OF

**Comment by SilviaAmAm** [comment]
It seems to happen because one of the configured APIs has as operation ID for the GET of `/api/v1/zaaktypen` `ZaakTypeGetAll` (instead of `zaaktype_list`) and the client gives a `ValueError`.

Discussed: fixing this in zgw-consumers

**Comment by SilviaAmAm** [comment]
Need to upgrade zgw-consumers in OF
