### ISSUE TITLE
Making a postcode component optional through logic changes the validation behaviour

### ISSUE THREAD

**Issue by SilviaAmAm** [open-formulieren/open-forms#3744]
### Product versie / Product version

2.4.2

### Omschrijf het probleem / Describe the bug

DH Taiga 632

If a postcode component is made not required by (backend) logic, then the `validate` in JSON of the component is:

```
"validate": {
      "required": false
    },
```
While if it is not touched by the logic, then it is:
```
"validate": {
   "custom": "",
   "unique": false,
   "pattern": "^[1-9][0-9]{3} ?(?!sa|sd|ss|SA|SD|SS)[a-zA-Z]{2}$",
   "plugins": [],
   "multiple": false,
   "required": true,
   "maxLength": "",
   "minLength": "",
   "customMessage": "Invalid Postcode",
   "customPrivate": false,
   "strictDateValidation": false
 }
```
The missing pattern/customMessage keys result in the error message being different if an invalid postcode is entered.
![Screenshot from 2024-01-08 15-33-35](https://github.com/open-formulieren/open-forms/assets/19154114/d356728b-fe64-475d-9a58-98d6986e060c)

### Stappen om te reproduceren / Steps to reproduce

- Create a form with two required postcode components.
- Add a logic rule that says: "If `true` then make the secode postcode component not required"
- Save the form

In the SDK, fill in the form and enter 2 invalid postcodes. Notice the different errors.

### Screen resolution

None

### Device

None

### OS

None

**Comment by sergei-maertens** [comment]
Skip backport, reasoning here: https://github.com/open-formulieren/open-forms/pull/3750#issuecomment-1884870460

Fix is incomplete though, we're not handling old form exports yet.

**Comment by sergei-maertens** [comment]
Clarified a bit more - we can backport the fix *without* the data migration. It won't break existing forms (but the bug will still be present). If that's a deal breaker, a manual action is possible where you remove and re-add the logic action.
