### ISSUE TITLE
Adding multiple repeating groups to the same step "matches" key's of 1st and last component

### ISSUE THREAD

**Issue by LaurensBurger** [open-formulieren/open-forms#3762]
### Product versie / Product version

2.5.0

### Omschrijf het probleem / Describe the bug

When you add multiple repeating groups the first one and the last one seem to always increment at the same time, which causes:
![image](https://github.com/open-formulieren/open-forms/assets/112621537/37530e98-6c18-46d3-afae-f3fcc0e7c9cc)

### Stappen om te reproduceren / Steps to reproduce

In a step add multiple repeating groups
See warning at first and last component

### Screen resolution

None

### Device

None

### OS

None

**Comment by sergei-maertens** [comment]
Seems to have had the same cause as #3761
