### ISSUE TITLE
New form builder - styling does not support dark mode

### ISSUE THREAD

**Issue by sergei-maertens** [open-formulieren/open-forms#3774]
The new form builder CSS does not support dark mode yet.

Components affected (there may be more, please check)

- [ ] Dropdowns
  ![image](https://github.com/open-formulieren/open-forms/assets/5518550/36f044bb-f7cf-4890-80f1-74cf323846da)
- [x] Preview buttons
  ![image](https://github.com/open-formulieren/open-forms/assets/5518550/8fc5fef5-8421-44ec-a818-9b3b437891bf)
- [x] Translations table
  ![image](https://github.com/open-formulieren/open-forms/assets/5518550/7e04b3d1-f07f-4db9-b58e-69f6da3c2507)
- [x] Validation > error message translations table
  ![image](https://github.com/open-formulieren/open-forms/assets/5518550/02c28c28-e239-48f2-bf21-4cb0f447842f)
- [x] JSON preview
  ![image](https://github.com/open-formulieren/open-forms/assets/5518550/13c47558-aeb3-4759-a915-698d9cda4f35)

**Comment by Viicos** [comment]
Fixed:
![image](https://github.com/open-formulieren/open-forms/assets/65306057/a27c4b3f-fa21-452d-a831-237a525042ba)
![image](https://github.com/open-formulieren/open-forms/assets/65306057/f652694f-e8a2-4094-ae19-241b5e36c4a1)
![image](https://github.com/open-formulieren/open-forms/assets/65306057/7d0beb52-b1ea-48ee-a565-047ec9d039e8)

**Comment by Viicos** [comment]
For the react-select component, this will most probably require some work
