### ISSUE TITLE
Check if content-component is rendered properly in summary page

### ISSUE THREAD

**Issue by joeribekker** [open-formulieren/open-forms#3778]
Ref. DH 88

**Comment by SilviaAmAm** [comment]
It is rendered without formatting:

![Image](https://github.com/open-formulieren/open-forms/assets/19154114/9d5b552d-5903-43ae-b71d-1ddf4099fba0)
![Image](https://github.com/open-formulieren/open-forms/assets/19154114/9e18d1e2-7623-455d-aa46-a7cb6c359c9c)

**Comment by joeribekker** [comment]
This is ok, but it should not show the label. I think Sergei had worked on this, check PRs. If not, please remove the label.
