### ISSUE TITLE
Always show button to abort a form/submission

### ISSUE THREAD

**Issue by SilviaAmAm** [open-formulieren/open-forms#3791]
### Thema / Theme

Frontend

### Omschrijving / Description

In the GovMetric feature, a button was added to abort a submission which then sends the user to the GovMetric feedback page.

Maybe this button should be present also if GovMetric is not enabled. This would also enable to refactor the component `ExistingSubmissionOptions` to reuse the same code as the `AbortionButton`.

Things to consider:
- Authenticated users
- Forms where submission is not enabled should probably not have an abortion button.

### Added value / Toegevoegde waarde

Code reuse
Consistency

### Aanvullende opmerkingen / Additional context

https://github.com/open-formulieren/open-forms-sdk/pull/634

**Comment by LaurensBurger** [comment]
related: #2459
