### ISSUE TITLE
As customer I want to see the form reference on the payment transaction

### ISSUE THREAD

**Issue by joeribekker** [open-formulieren/open-forms#3793]
Ref: Taiga UTR 159

The referencenumber (`OF-<xxxxxx>` or `<zaaknummer>`) should be set as payment reference. Currently, OF uses a separately generated number.

If we have payment retries we could do: `{{ zaaknummer }}_{{ poging }}` if needed

Since the transaction numbers need to be unique, we need to make sure the OF-numbers are "made unique" maybe by adding a prefix or whatever.

**criteria**

* [ ] The payment reference needs to be globally unique (the OF public reference number gets reused over time).
* [ ] The OF-reference needs to be in the payment reference
* [ ] Add VCR tests
* [ ] Determine if an attempt postfix is needed (for example when you cancel the first payment, and make another attempt).

**Comment by Viicos** [comment]
Refinement after reading the Ogone documentation:
- The `ORDERID` parameter is described as a _unique order number_ in the "legacy" documentation, and as a _merchant order reference_ in the Ingenico docs (and an example with letters is given). It is thus probably safe to include letters in it, but this will have to be tested with VCR tests.

Tasks:
- [ ] Tweak the reference number generation. Currently, a random string of length 6 is generated and checked against existing Submissions to avoid duplicates. This means that the reference number could be reused over time as submissions get deleted from time to time. Two options:
  - Use a time based ID:
    - UUIDv1: relies on the MAC address, probably not suitable
    - [ULID](https://github.com/ulid/spec): Probably too long
    - Others: [xid](https://github.com/rs/xid), ...
  - Keep the current implementation, but keep a record (in DB?) of all the generated references
- [ ] Adapt submission payment code:
  - is `payment_order_id_prefix` in the global config still relevant? Is `order_id` vs `public_order_id` still relevant?

**Comment by alextreme** [comment]
Discussed with Utrecht (Taiga 200), and the solution as described with the number of attempts wasn't done conform spec of this Github issue:

"we kunnen de prefix met het jaartal er wel afhalen, maar wat na het zaaknummer komt staat nu als volgt gedefinieerd OF-nummer/xxx. Dat moet OF-nummer_xxx zoals ook in het betreffende github issue stond"

**Comment by Viicos** [comment]
Tracking in https://github.com/open-formulieren/open-forms/issues/4156
