### ISSUE TITLE
Make the co-sign text on the confirmation page and e-mail configurable

### ISSUE THREAD

**Issue by hlmr-erik** [open-formulieren/open-forms#3807]
### Thema / Theme

Frontend

### Omschrijving / Description

As we would like to [integrate the text about co-signing](https://taiga.maykinmedia.nl/project/gemeente-haarlemmermeer-open-formulieren/issue/77) in our regular templates for the confirmation page and e-mail, we would like for these texts to be configurable and to be shown conditionally based on the status of {% cosign_complete %}.

### Aanvullende opmerkingen / Additional context

Related to the first item here: https://github.com/open-formulieren/open-forms/issues/3149

**Tasks**

- [x] Make email text configurable
- [x] Make confirmation page text configurable

**Comment by joeribekker** [comment]
Discussed with the team: We currently have a safeguard that makes sure you have the proper template tags present in your email template.

If we add the variable, this means you take responsibility for the proper texts. We need to have a "regular" and "expert" method of formatting these emails in a broader sense without making this confusing for the end user.

**Comment by sergei-maertens** [comment]
Utrecht requested some changes to cosign that are easiest to provide by making email templates configurable, so this aspect is going to be tackled.

**Comment by sergei-maertens** [comment]
Needs backport added due to audit/security concerns and waiting for 2.7 is not an option.

**Comment by sergei-maertens** [comment]
The request email text is now configurable, which addresses part of this user story. For the rest there is still a stakeholder needed, so I'm removing this ticket from the project board again.

**Comment by sergei-maertens** [comment]
Via #4320 the confirmation template is also configurable now. This will be available starting with Open Forms 3.0
