### ISSUE TITLE
Regression: Hide n/a forms steps no longer working after starting a form.

### ISSUE THREAD

**Issue by LaurensBurger** [open-formulieren/open-forms#3835]
### Product versie / Product version

2.5.0 - 2.5.1

### Omschrijf het probleem / Describe the bug

When a the "Hide non-applicable form steps" is set to true, form steps are only hidden when the form loads (start page)
![image](https://github.com/open-formulieren/open-forms/assets/112621537/24f5c84a-5f94-4b1f-a994-ed2ab73f8d66)

_(start page before starting the forms)_
![image](https://github.com/open-formulieren/open-forms/assets/112621537/b5bde950-ee08-4c1d-bb98-eba36c2c558d)

But after starting a form, steps that became n/a later are not hidden:
![image](https://github.com/open-formulieren/open-forms/assets/112621537/44ec80ca-01d1-45f8-aa75-d1ddfe664f1e)

These steps should also be hidden as it was in 2.4.x version

**Comment by LaurensBurger** [comment]
Update: It's also the "reverse" - Steps that start as n/a and are made applicable do not show up at all in the progress-indicator.

**Comment by vaszig** [comment]
Navigating to a non-applicable step from a completed one has an issue as well.

If we choose to show non-applicable steps (General configuration) and we have completed the previous steps, we should not be able to navigate to the non-applicable step.
