### ISSUE TITLE
Multiple uploads & removal returns 403's instead of a 204

### ISSUE THREAD

**Issue by LaurensBurger** [open-formulieren/open-forms#3858]
### Product versie / Product version

2.5.2

### Omschrijf het probleem / Describe the bug

sentry: 338224

When a user uploads multiple files (at once, this does not occur when uploading files 1 by 1) and removes multiple files, the status code changes from 204 to 403 after the 1st upload is removed.

Upload multiple files:
![image](https://github.com/open-formulieren/open-forms/assets/112621537/8368e21e-9445-4340-b6ec-35aff4b8f2d7)

Remove 4 files:
![image](https://github.com/open-formulieren/open-forms/assets/112621537/734c56e6-4d74-432d-8fa7-af4d4d40030c)

network tab shows 1x 203 3x 403 
![image](https://github.com/open-formulieren/open-forms/assets/112621537/fd18d737-371a-4465-941d-5ab51cd7926d)

**Comment by sergei-maertens** [comment]
This is a race condition that was predicted:

```py
def append_to_session_list(session: SessionBase, session_key: str, value: Any) -> None:
    # note: possible race condition with concurrent requests
    ...
```
the uploads are being done in parallel and it looks like the last file to succeed is overwriting the session data as a whole rather than appending.
