### ISSUE TITLE
Identity provider: (XML) metadata-URL: AttributeError 'bytes' object has no attribute 'encode'

### ISSUE THREAD

**Issue by LaurensBurger** [open-formulieren/open-forms#3873]
### Product versie / Product version

2.5.2

### Omschrijf het probleem / Describe the bug

Sentry: 349175 

Signicat metadata

**Comment by sergei-maertens** [comment]
-> do backport

**Comment by sergei-maertens** [comment]
Backported to 2.4.x, older versions were on django-digid-eherkenning 0.8.1 or older that didn't have this feature yet.
