### ISSUE TITLE
Update dependencies after Django 4.2 upgrade

### ISSUE THREAD

**Issue by sergei-maertens** [open-formulieren/open-forms#3878]
Some things noticed during #3049 that are not essential for the upgrade, but should be done nevertheless:

- [x] Update to Celery 5.3 (to get rid of `pytz` dependency) (waiting on a new `django-yubin` release)
- [x] Try django-csp 3.8 release candidate (see https://github.com/mozilla/django-csp/issues/184#issuecomment-1917485698)
- [x] Release & use new maykin-python3-saml library version
- [x] Update docs deps: Sphinx, extensions
- [ ] ...

**Comment by joeribekker** [comment]
Made an issue about Django Yubin release here: https://github.com/APSL/django-yubin/issues/76
