### ISSUE TITLE
Allow hidden fields to be sent to registration systems

### ISSUE THREAD

**Issue by joeribekker** [open-formulieren/open-forms#3890]
### Thema / Theme

Admin

### Omschrijving / Description

Hidden fields are currently not sent to the registration backend. Can we make this happen, optionally?

Request comes from Utrecht who wants this, using the Objects API where it's added to `{{ data }}` so it automatically ends up in the registration system. It was not enough that they could manually add it elsewhere in the JSON field.

**Comment by joeribekker** [comment]
I left triage label but also added it to the sprint because Utrecht needs this but I can also see it conflicting with #3688

**Comment by sergei-maertens** [comment]
https://github.com/open-formulieren/open-forms/blame/master/src/openforms/formio/rendering/structured.py - this seems to skip the hidden fields/nodes which is unfortunate if you're trying to register submission data to the objects API :)

**Comment by sergei-maertens** [comment]
Refinement: the new registration mechanism in the objects API will not be able to handle `additionalProperties: true` in 2.6.0, so the problems of Utrecht are not solved in time yet. Meaning we need to implement this.

The fix should be rather straight forward.
