### ISSUE TITLE
2.5.2 is missing "defaultValue" fix for file component

### ISSUE THREAD

**Issue by LaurensBurger** [open-formulieren/open-forms#3899]
### Product versie / Product version

2.5.2

### Omschrijf het probleem / Describe the bug

multiple 2.5.2 environments are still seeing upload components breaking when "Allow multiple" is checked. 
![image](https://github.com/open-formulieren/open-forms/assets/112621537/14f43b81-53a5-4e08-8801-23addedf2877)

Maykin-test does not seem affected.

**Comment by sergei-maertens** [comment]
Duplicate, fix already done but not released yet.

It only affects editing new/existing components, if you leave existing components untouched, it should be okay.
