### ISSUE TITLE
Co-sign component stalls submission even when field is hidden

### ISSUE THREAD

**Issue by hlmr-erik** [open-formulieren/open-forms#3901]
### Product versie / Product version

2.4.5

### Omschrijf het probleem / Describe the bug

We conditionally show the co-sign field based on a preceding choice. Even when the field is hidden, the submission is now stalled for co-sign; as apparently (Taiga HLMR 86) the stalled-for-co-sign is triggered by the form containing a required co-sign component, whether this component is hidden or not. Making the field non-required through logic, based on mentioned preceding choice, seemed workable; but in this case the form still gets stalled.

### Stappen om te reproduceren / Steps to reproduce

-Add a radiogroup to a form
-Add a required co-sign component to the form
-Set the co-sign component to appear only when one of the radiogroup choices is made

Further steps to reproduce the workaround failing:
-Add a rule on the logic tab, specifying the co-sign field to be marked not-required based on a choice in the radiogroup
-Make said choice
-Observe the form still gets stalled after submission.

### Verwacht gedrag / Expected behavior

For the form to be stalled for co-sign only then and when the element is 1. Shown and 2. Required.

### Screen resolution

None

### Device

None

### OS

None

**Comment by sergei-maertens** [comment]
Looking at the current code (master@565e5d1787c699b791472a69e2f51028dd3b415f, 3.0.0-alpha.1) this is still the case, and an important consideration for Cosign v3

@hlmr-erik I'm currently wrapping up a number of cosign improvements and looking forward to the future. Would it be acceptable for you if the cosign 'component' is moved/hardcoded to be on the summary/confirmation page? We will of course still make it possible to make cosigning required/optional through form logic.

**Comment by sergei-maertens** [comment]
#4888 made it possible to work on a fix for this :tada: it will be included in Open Forms 3.0
