### ISSUE TITLE
ZGWOptionsForm does not handle multiple fields - eigenschappen update properly

### ISSUE THREAD

**Issue by vaszig** [open-formulieren/open-forms#3909]
### Product versie / Product version

2.5.0

### Omschrijf het probleem / Describe the bug

The mappings are not updated according to the user's update in the formstep. If for example a field is modified-deleted there is a crash.

### Stappen om te reproduceren / Steps to reproduce

1. create two fields in a formstep
2. set up a zaakeigenschap mapping for both fields
3. delete one of the fields in the form definition
4. check back in the zaakeigenschappen mapping

### Screen resolution

None

### Device

None

### OS

None

**Comment by sergei-maertens** [comment]
Backport is not needed, case property mappings is a 2.6.0 feature (found out while cherrypicking)
