### ISSUE TITLE
Cannot remove (simple) logic from components

### ISSUE THREAD

**Issue by LaurensBurger** [open-formulieren/open-forms#3920]
### Product versie / Product version

2.5.x (new form builder)

### Omschrijf het probleem / Describe the bug

Once set, the option to remove the simple logic triggers does not appear. and the form builder can only select True/False
![image](https://github.com/open-formulieren/open-forms/assets/112621537/46320fad-336b-4d3d-a969-9f94ffdcfdf1)
or other components. 

Can only be removed by editing the JSON "conditional"

**Comment by hlmr-erik** [comment]
This also goes for the styling of a free text component
![image](https://github.com/open-formulieren/open-forms/assets/111565013/cc3331ca-e79c-494d-9f65-383f8e20b67e)

**Comment by nikkiysendoorn1** [comment]
PR: https://github.com/open-formulieren/formio-builder/pull/125

**Comment by sergei-maertens** [comment]
TODO: update backend with patch versions of @open-formulieren/formio-builder when they're published.
