### ISSUE TITLE
content component is missing Json view/editor

### ISSUE THREAD

**Issue by LaurensBurger** [open-formulieren/open-forms#3928]
### Product versie / Product version

2.5.x

### Omschrijf het probleem / Describe the bug

![image](https://github.com/open-formulieren/open-forms/assets/112621537/00c481bd-bbf5-4da1-b6a1-9a53175e9aca)

**Comment by joeribekker** [comment]
Refinement: So these buttons need to be added:

![image](https://github.com/open-formulieren/open-forms/assets/96970/0a610d88-642e-4384-86a3-dd6c2b402822)
