### ISSUE TITLE
CSP form-action rules from eHerkenning xml not sufficient

### ISSUE THREAD

**Issue by LaurensBurger** [open-formulieren/open-forms#3930]
### Product versie / Product version

2.5.2

### Omschrijf het probleem / Describe the bug

Both KPN and Signicat redirect to domains that are not present in the xml in the eHerkenning configuration which in turn "breaks" eHerkenning as the CSP for form-action is triggered.

**Comment by joeribekker** [comment]
Refinement: There is a workaround (correct me if I'm wrong @LaurensBurger ) to add the CSP headers manually, so prio is low. @LaurensBurger do you have the URLs for us so we can add them by default?

**Comment by vaszig** [comment]
This is fixed by #3965
