### ISSUE TITLE
Number: not allowed to set decimal to 0

### ISSUE THREAD

**Issue by LaurensBurger** [open-formulieren/open-forms#3943]
### Product versie / Product version

2.5.x (new form builder)

### Omschrijf het probleem / Describe the bug

Number component won't accept 0. The Currency component does however.
It does work setting 0 in the json of the Number component component. 
![image](https://github.com/open-formulieren/open-forms/assets/112621537/e4f816d7-21bc-4e95-9cfa-bf2e017d76cb)

**Comment by vaszig** [comment]
Reopen issue for when the new version of the formbuilder is ready.
