### ISSUE TITLE
Form definition admin styling is broken since Django 4.2 upgrade

### ISSUE THREAD

**Issue by sergei-maertens** [open-formulieren/open-forms#3947]
### Product versie / Product version

master / ac70173e71115c2582bf7dedb617e4fde04e9897

### Omschrijf het probleem / Describe the bug

The styling in the form definition admin page is broken after the Django 4.2 upgrade.

![image](https://github.com/open-formulieren/open-forms/assets/5518550/fe4b110c-0a92-424b-8597-3d16b44c2feb)

### Stappen om te reproduceren / Steps to reproduce

Navigate to "add form definition" in the admin.

### Verwacht gedrag / Expected behavior

Page looks normal without overflowing content

### Screen resolution

bigger

### Device

Desktop

### OS

Linux

### Browser

Chrome

**Comment by joeribekker** [comment]
Refinement: Victorien also noticed that all input fields became a little smaller. This might be related. The actual ticket is about the form editor not showing properly. See the form-editor on what it should look like.

You can find this in the admin menu > misc > form definitions.
