### ISSUE TITLE
Add multiple LoAs to eHerkenning and eIDAS and update the service catalog template

### ISSUE THREAD

**Issue by joeribekker** [open-formulieren/open-forms#3950]
See: https://developer.signicat.com/broker/eherkenning-broker/eherkenning-service-catalogue.html#introduction

* [x] The template for the service catalog should match the Signicat template:
      Noticed differences:
      - [x] Missing node `ServiceDescriptionURL`
      - [x] They don't have sets of `EntityConcernedTypesAllowed`, just the KvKnr
      - [x] Missing `ServiceRestrictionsAllowed`
      - ~[ ] Missing Requested attributes~ => These are configurable
      - [x] `ServiceURL` node should have english and dutch version
      - [x] `PrivacyPolicyURL` node should have english and dutch version
      - [ ] They don't have the signature node => The XSD has no value for the `minOccurs` and the default is `1` (https://www.w3.org/TR/xmlschema-0/#OccurrenceConstraints). So I think we need to leave this field in?

* [x] ~Change default LoA for eHerkenning to LoA2plus (as per januari 1, 2024)~ => The default is already LoA3
* [x] Change default LoA for eIDAS to LoA3 (as per januari 1, 2024) and make it configurable. https://github.com/maykinmedia/django-digid-eherkenning/pull/64
* [x] https://github.com/maykinmedia/django-digid-eherkenning/issues/58
* [x] Add `https://*.eherkenning.nl` to form-actions CSP directive if eherkenning is configured https://github.com/open-formulieren/open-forms/pull/3965

**Comment by SilviaAmAm** [comment]
Still need to update the library in OF
