### ISSUE TITLE
Location in repeating groups is functional but requires editing the json

### ISSUE THREAD

**Issue by LaurensBurger** [open-formulieren/open-forms#3993]
### Product versie / Product version

2.5.x

### Omschrijf het probleem / Describe the bug

Using the dropdown to select the postcode and housenumber components for the location service within a repeating group seems to include too much information for it to work. 
![image](https://github.com/open-formulieren/open-forms/assets/112621537/9ef2fa24-69fe-44ed-9eb2-2ece58611aa6)

The "herhalendeGroep." part causes the issue. And when we manually remove this part from the json
![image](https://github.com/open-formulieren/open-forms/assets/112621537/96cd23c4-9c73-4162-bc3c-87f2a32866dd)
the location is correctly filled in a repeating group. 

![image](https://github.com/open-formulieren/open-forms/assets/112621537/9490e7e9-3210-40fb-a00b-f5a85970c21b)

but look like this in the form builder:
![image](https://github.com/open-formulieren/open-forms/assets/112621537/0d881c20-23f1-46b3-966e-808fbe9d3af3)

### Screen resolution

None

### Device

None

### OS

None

**Comment by sergei-maertens** [comment]
From Taiga this seems to already be an issue from before the new form builder

**Comment by joeribekker** [comment]
Refinement: Let's deprecate this feature entirely and add the autofill to the existing addressNL component.

**Comment by sergei-maertens** [comment]
@vaszig you can pick this up. This concerns the `addressNL` component. You will have to touch the `types`, `form-builder`, `open-forms` and `open-forms-sdk` repositories for this.

- [ ] Add form builder option to addressNL component: boolean `deriveAddress`. Default `false`.
- [ ] When enabled, in the SDK this component needs to query the backend for the street name + city. The inputs for this are postcode + house number (these inputs are already provided in the addressNL component).
- [ ] The component only *displays* (as read-only?) the street and city, the user cannot edit this value.
- [ ] The data must be included in the submission data, and the backend must validate that it was not tampered with (probably a secret from the backend should be included based on the returned values, so we don't need to hit the network again during validation)
- [ ] Whenever the postcode or house number inputs change value, the street name + city need to be derived again.
- [ ] Deprecate the old functionality for street name + city derivation in the text field component.

**Comment by alextreme** [comment]
@joeribekker @sergei-maertens discussed with Laurens, this deprecation will likely have a significant impact with DH and Utrecht due to how using the 'addressNL' component modifies the transmitted data to the Objects API. We don't know how this was developed but please ensure there is backwards-compatibility to avoid surprises for existing forms and objecttypes

**Comment by sergei-maertens** [comment]
I've created #4418 for this - I don't think 2.7.0 is realistic for this, but at the earliest the legacy situation will be deleted in Q4 2024 so there's still time.
