### ISSUE TITLE
Add more columns to admin/submissionreport

### ISSUE THREAD

**Issue by LaurensBurger** [open-formulieren/open-forms#4005]
### Thema / Theme

Admin

### Omschrijving / Description

As a admin when looking for a specific submission report i have a hard time finding the right one.
The admin view currently only shows: "form title: Document"

I would like to at least be able to search for submission id and public reference. 

Alternatively perhaps it would be nice to be able to download these documents directly from submissions/submission as is already possible for attachments. 
![image](https://github.com/open-formulieren/open-forms/assets/112621537/505b996a-ea08-4e90-b35d-dda1c92e406f)

**Comment by joeribekker** [comment]
Refinement: We go for the alternative, allow downloads from submission details (audit trail should reflect downloading files). Maybe be part of a bigger redesign of the subission detail page.
