### ISSUE TITLE
Block/discourage the use of dots in component keys? 

### ISSUE THREAD

**Issue by LaurensBurger** [open-formulieren/open-forms#4009]
### Thema / Theme

Form designer

### Omschrijving / Description

currently a user can create a key that results in unexpected behavior. 
example:
![image](https://github.com/open-formulieren/open-forms/assets/112621537/0792ffd3-46bf-4dee-b305-6e51b4ec8e86)

This key automagically changes the "veldengroep" to a dict/object?
![image](https://github.com/open-formulieren/open-forms/assets/112621537/2fbcbe1a-7e4f-4091-9a26-df75fe8ea165)

In the submission the data is also inconsistent: 
![image](https://github.com/open-formulieren/open-forms/assets/112621537/0a415690-f344-4c38-ab51-6349d0749f02)
![image](https://github.com/open-formulieren/open-forms/assets/112621537/f6a330bc-23ba-4ca3-b066-2abfd6ed095c)

**Comment by sergei-maertens** [comment]
This is formio's behaviour which we can't change, it's going to lead to a whole bunch of other unexpected problems.

The displaying of `[object Object]` for the fieldset should never happen, that's a bug on our end.

The submission admin/display of submitted data is some old code that can definitely be improved too, so let's just fix those things instead.

**Comment by joeribekker** [comment]
@sergei-maertens refinement agrees.

**Comment by sergei-maertens** [comment]
backend PR is still open
