### ISSUE TITLE
"You are modifying an existing form definition.." does not seem to show consistently

### ISSUE THREAD

**Issue by LaurensBurger** [open-formulieren/open-forms#4021]
### Product versie / Product version

2.5.2 - 2.6.0

### Omschrijf het probleem / Describe the bug

When a form builder opens a step/definition that is used in multiple forms they see a warning informing them the changes made in this step will affect more forms. 
![image](https://github.com/open-formulieren/open-forms/assets/112621537/ef1589d3-ace5-4eb9-834e-2f2345e2b4b2)

This warning however shows sometimes, but other times it does not. And this behavior is not correct going by the data present in the admin. 

usedIn:
![image](https://github.com/open-formulieren/open-forms/assets/112621537/b3724d0c-be62-4373-846b-1595ad287ae0)
![image](https://github.com/open-formulieren/open-forms/assets/112621537/4c953668-2a5d-4527-8fe6-ece1b8650d7a)

**Comment by vaszig** [comment]
After investigation this is working as expected. 

Tested locally and on the test environment and modifying an existing form definition in a form that uses it, we get a warning which mentions the correct number of the forms that will be affected.
Discussed this with Laurens as well and we will close this for now as it happened with the original issue as well (LV 151) .
