### ISSUE TITLE
Use the Monaco Editor for the JSON Edit component

### ISSUE THREAD

**Issue by Viicos** [open-formulieren/open-forms#4051]
The admin currently uses a basic editor for JSON content. Using the [Monaco Editor](https://github.com/microsoft/monaco-editor/) will greatly improve dealing with JSON (folding, auto-closing brackets/quotes, etc).

There are two implementations of the editor in React:

https://github.com/suren-atoyan/monaco-react
https://github.com/react-monaco-editor/react-monaco-editor

The second one requires some webpack plugin, and I couldn't make it work. The first one does seem to work fine, so it should be used.

**Comment by sergei-maertens** [comment]
Needs backend PR to update the formio-builder version
