### ISSUE TITLE
Default value for radio component cannot be undone

### ISSUE THREAD

**Issue by LaurensBurger** [open-formulieren/open-forms#4064]
### Product versie / Product version

2.5.x - 2.6.0

### Omschrijf het probleem / Describe the bug

Once you set a default value for a radio component in the form builder, this choice cannot be undone. You can select another value.
![Kooha-2024-03-27-08-58-48](https://github.com/open-formulieren/open-forms/assets/112621537/c1f3abb2-b30c-4319-9c43-c7a52840c47c)

It is possible to remove the defaultValue from the json.

**Comment by sergei-maertens** [comment]
-> needs a "clear" icon or something like that. HTML-spec wise, this is correct behaviour (and Formio.js does it wrong)

**Comment by joeribekker** [comment]
Refinement: there is a workaround: (for Laurens) edit the JSON; (for clients) please dont do that and just remove and re-add the component.
