### ISSUE TITLE
It's not possible to enter a MFA recovery token

### ISSUE THREAD

**Issue by sergei-maertens** [open-formulieren/open-forms#4072]
### Product versie / Product version

2.6.0

### Omschrijf het probleem / Describe the bug

Taiga HLMM 105

When going through the login flow, you are prompted to enter your token/second factor. At the bottom of the 'dialog', there's a link to use a recovery token. Clicking that link doesn't allow you to enter a recovery token, instead it redirects you back to the username/password login screen.

### Stappen om te reproduceren / Steps to reproduce

0. Ensure you have generated backup tokens for your account
1. Go to the /admin/
2. Log in with username + password
3. Instead of entering a token, click the "Use a recovery token" link
4. Observe that you need to authenticate again instead of being able to enter a token

### Verwacht gedrag / Expected behavior

Go to screen to enter a recovery token instead of logging in again.

### Screen resolution

None

### Device

None

### OS

None

**Comment by Viicos** [comment]
Hum, I can't see the "Use a recovery token" link on our test env?

**Comment by sergei-maertens** [comment]
You need to enter username + password first, and then you get the screen prompting for your token/second factor. That page has a recovery token link, at least for me with my YubiKey.

**Comment by sergei-maertens** [comment]
Reproduced with Joeri - you need to make sure you have generated backup tokens first!

**Comment by Viicos** [comment]
Makes sense :facepalm:
