### ISSUE TITLE
Registration PDF does not update to display the payment status correctly

### ISSUE THREAD

**Issue by LaurensBurger** [open-formulieren/open-forms#4080]
### Product versie / Product version

2.5.4
Vught 68
RID 195

### Omschrijf het probleem / Describe the bug

When the environment is set to: `wait_for_payment_to_register=True`
The PDF included in the registration should refelct the successes of the payment. But at the moment it can only display the "old" status:
![image](https://github.com/open-formulieren/open-forms/assets/112621537/1911228b-bb22-454e-a7ff-7a90e61b694f)

since it was generated before the payment status was updated.
![image](https://github.com/open-formulieren/open-forms/assets/112621537/64f7a575-05d5-47a2-9804-8cfab00ddca8)

It should be regenerated at this point to reflect the right payment status.

---

We're including the user-download PDF here to reflect the same status (so, you download a document that states you paid).

* [x] Add timestamp to PDF when it is generated: #4139 
* [ ] Handle the case where registration is done before and after payment.
* [ ] The PDF after payment needs to reflect the updated payment status and this updated PDF needs to be sent to the registration backend. Whether the PDF is regenerated always during registration or just after payment, is up to the dev, but I (Joeri) wants that the PDF that the client can download is the same as the one sent to the registration backend (with a preference for the same physical file).

**Comment by joeribekker** [comment]
Refinement: Maybe we should drop support for payment after creating the registration. But, that would make the "betaalstatus" field useless so technically it seems still relevant.

The issue is how to deal with a new version of the PDF that says payment is complete, for all registration backends.

Joeri will ask if the feature "payment after registration" is still needed.

**Comment by alextreme** [comment]
@joeribekker voorstel om dit een stuk kleiner te maken: 

Nu staat er "Totaalbedrag te voldoen"

Ik stel voor om dit te hernoemen naar: "Totaalbedrag"

Dan werkt het voor beide situaties en is het issue verholpen

**Comment by sergei-maertens** [comment]
> [@joeribekker](https://github.com/joeribekker) voorstel om dit een stuk kleiner te maken:
> 
> Nu staat er "Totaalbedrag te voldoen"
> 
> Ik stel voor om dit te hernoemen naar: "Totaalbedrag"
> 
> Dan werkt het voor beide situaties en is het issue verholpen

@vaszig let's make a small PR with this language change and that should relieve the pressure on this ticket

**Comment by joeribekker** [comment]
removing from 2.8 because in 2.7 we made the text more generic that should at least it is correct (however its not detailed).
