### ISSUE TITLE
Duplicate requests when starting a form

### ISSUE THREAD

**Issue by LaurensBurger** [open-formulieren/open-forms#4082]
### Product versie / Product version

2.6.1
test env form 116

### Omschrijf het probleem / Describe the bug

When a form is started the network tab shows multiple identical requests being made.
The requests are 100% identical except for the "X-Csrftoken"

The final request to: `https://openformulieren.nl/api/v2/submissions/ac85c059-4f3b-4b21-a118-4e68ab29fbba/steps/96de5e46-b978-40e8-8fe3-cabd4d3bc13f?`
seems to also trigger a redraw in the front-end.

example DH
![image](https://github.com/open-formulieren/open-forms/assets/112621537/b19b6b11-4135-4c07-ba6e-286dde4a30fd)

example maykin test with bsn:
![image](https://github.com/open-formulieren/open-forms/assets/112621537/7c5bc8fa-f185-46ab-998d-048513198f76)

and without bsn:
![image](https://github.com/open-formulieren/open-forms/assets/112621537/11558560-4ee5-4b9b-bf1a-b8802087bb71)

Only occurs on starting the form. 
not sure if relevant: Navigating the form also shows sentry making 2 requests each step with unique sessionids
![image](https://github.com/open-formulieren/open-forms/assets/112621537/2df2222b-ac1e-43a9-b993-4e53bb88a0c7)

**Comment by joeribekker** [comment]
Refinement: Unsure whether this causes real-world problems but we should look into it. Sergei and Silvia mention 403 issues in the dev environment but unsure if related.

**Comment by Viicos** [comment]
I'm able to repro, but have no idea where this is coming from. I once had the 403 error, as one of the calls to the API endpoint is using another submission UUID for some reason

**Comment by LaurensBurger** [comment]
reloading after loading is done: 
![Kooha-2024-04-09-12-47-28](https://github.com/open-formulieren/open-forms/assets/112621537/e71656b2-2e5e-4fe3-b83c-2f5ad2dc3df9)
