### ISSUE TITLE
Hidden required choicefields that do not have a value, don't validate

### ISSUE THREAD

**Issue by joeribekker** [open-formulieren/open-forms#4096]
Ref: Taiga Utrecht 195

```
rest_framework.exceptions.ValidationError: {'steps': [{}, {'data': {'bentUEenPersoonOfEenBedrijf': [ErrorDetail(string='"" is een ongeldige keuze.', code='invalid_choice')]}}, {}]}
```

> In dit formulier wordt deze vraag verborgen d.m.v. de logica. Als dit veld wél wordt getoond is het een verplichte vraag. Kan het zijn dat doordat de verborgen velden sinds 2.6.1 worden meegestuurd de backend deze waardes ook valideert en daarover struikelt?

**Comment by Viicos** [comment]
@joeribekker Which form ID on our test env?

**Comment by sergei-maertens** [comment]
Probably we'll need more cases here: https://github.com/open-formulieren/open-forms/blob/3ef4ea6bd4a1d720f67073da2bec37269fd62bc7/src/openforms/formio/serializers.py#L80 and of course a regression test

**Comment by sergei-maertens** [comment]
This may have the same cause as DH#671 and be fixed by #4114

**Comment by Viicos** [comment]
This is only reproducible if `clear on hide` is _not_ set
