### ISSUE TITLE
Als beheerder wil ik aangeven welke velden worden doorgezet naar de registratie backend

### ISSUE THREAD

**Issue by joeribekker** [open-formulieren/open-forms#412]
In StUF-ZDS en ZGW APIs zitten heel veel velden. Welke moeten gevuld worden? En met welke waarden.

Vanuit het formulier moeten deze gekoppeld kunnen worden.

Samen met gemeenten moet gekeken worden welke velden dit zijn.

**Comment by Hugo-ter-Doest** [comment]
Kunnen de in het formulier ingevulde waarden ook als Zaakeigenschappen of ExtraElementen worden meegestuurd?

**Comment by joeribekker** [comment]
Volgens mij worden alle velden in het formulier meegegeven als extraElement bij StUF-ZDS. ZaakEigenschappen zijn niet mogelijk nu. Wel kan je velden aan specifieke ZGW of StUF-attributen hangen maar de selectie van attributen is beperkt.

**Comment by sergei-maertens** [comment]
Zaakeigenschappen are possible since a while, so that should cover everything that's needed. Specific requests happen from time to time in their own tickets, closing this to clean up.
