### ISSUE TITLE
forms with no category are displayed multiple time in de forms list

### ISSUE THREAD

**Issue by LaurensBurger** [open-formulieren/open-forms#4124]
### Product versie / Product version

2.5.5 - 2.6.2

### Omschrijf het probleem / Describe the bug

The list of forms without a category is shown multiple times in the forms overview list, while forms with a category are only shown once. 

example with a category:
![image](https://github.com/open-formulieren/open-forms/assets/112621537/9d15d81f-72c3-4b41-8fc8-2332051d3383)

searching for forms without a category: 
![image](https://github.com/open-formulieren/open-forms/assets/112621537/d0ab07a6-110d-4bf4-a79e-f1038b24ffcb)

all of them show up 4 times. 

in another environement they find 2 for each form. 

These are not unique forms, just the items in the list. They all link to the same form.

perhaps the pagination triggers the duplication?
![image](https://github.com/open-formulieren/open-forms/assets/112621537/769485cf-6cf4-4f18-ac6b-ae538061ac6c)

### Screen resolution

None

### Device

None

### OS

None

**Comment by joeribekker** [comment]
Refinement: reproducible on our test env; dont make the code better - waiting for new design.
