### ISSUE TITLE
Objects API v2 registration crashes with fieldsets

### ISSUE THREAD

**Issue by Viicos** [open-formulieren/open-forms#4141]
### Product versie / Product version

2.6.2

### Omschrijf het probleem / Describe the bug

With the following configuration:

```python
submission = SubmissionFactory.from_components(
    [
        {
            "key": "fieldset",
            "type": "fieldset",
            "components": [
                {
                    "key": "fieldset.textfield",
                    "type": "textfield"
                }
            ]
        },
    ],
    completed=True,
    submitted_data={
        "fieldset": {
            "textfield": "some_string",
        },
    },
)
```

The objects API v2 registration crashes:

```sh
openforms/submissions/models/submission_value_variable.py line 57, in get_variable
    return self.variables[key]
KeyError: 'fieldset'
```

Due to how the submission values variable state is being used

### Screen resolution

None

### Device

None

### OS

None

**Comment by joeribekker** [comment]
Refinement: Some discussion about whether this is caused by the modern data format function or that its caused by some part of the code that still uses the old mechanism.
