### ISSUE TITLE
Stuf-ZDS with "wait for payment" sends "old" data, not including the payment status

### ISSUE THREAD

**Issue by LaurensBurger** [open-formulieren/open-forms#4145]
### Product versie / Product version

2.5.5

### Omschrijf het probleem / Describe the bug

LV: 160

Wait for payment works up until the "creerZaak" where it seems to use the old payment status instead of updating the {{ betalings_indicatie }}.

This results in submissions always containing
        <ZKN:betalingsIndicatie>(Nog) niet</ZKN:betalingsIndicatie>

**Comment by Viicos** [comment]
Quickly discussed with Laurens, this method:

https://github.com/open-formulieren/open-forms/blob/c488afc8cd3edcafe9bbe148e0713c867f46bc07/src/stuf/stuf_zds/client.py#L219-L248

Can be called when payment was done (this is the case when `wait_for_payment_to_register=True`), but it assumes it is not the case and can only set the payment to `NVT` (not applicable) or `NOT_YET`. It should take into account the submission's payment status instead.
