### ISSUE TITLE
Bring errors/warning to the "front"

### ISSUE THREAD

**Issue by LaurensBurger** [open-formulieren/open-forms#4155]
### Thema / Theme

Form designer
hrlmmr: 121

### Omschrijving / Description

As a form designer i want to be informed about errors from the form builder view.
Currently a component can have a warning or error nested deep inside one of the tabs:
![image](https://github.com/open-formulieren/open-forms/assets/112621537/adeaa7db-f52f-409f-8c78-1dcf9f759419)

If this error was also present in the tab:
![image](https://github.com/open-formulieren/open-forms/assets/112621537/5f1c5b94-1f78-4321-b281-3e1050a45321)
and perhaps even the form builder:
![image](https://github.com/open-formulieren/open-forms/assets/112621537/8b443394-ebc0-4cd7-b23f-2615f4c93671)

will greatly help form builders with debugging forms. 

Moved import/export report part to: #4170

**Comment by sergei-maertens** [comment]
We can only run the validations when the modal is opened, but the suggestions to put a marker on the tab is a good one.

**Comment by joeribekker** [comment]
Refinement: Should be easy patch to show an error in a tab. There should be already some hook for this.

**Comment by Viicos** [comment]
After investigation: this is already an existing feature, but it wasn't working for the date validation.
