### ISSUE TITLE
Enabling an analytics tool without selecting the 'Analytics cookie consent group' gives 500 error

### ISSUE THREAD

**Issue by SilviaAmAm** [open-formulieren/open-forms#4165]
### Product versie / Product version

2.6.x

### Omschrijf het probleem / Describe the bug

In the admin, in a fresh  'analytics tools' configuration page (nothing else configured, in particular no 'Analytics cookie consent group' configured):
- Add a source id (nl/en) for govmetric
- Check the box 'enable govmetric'
- Observe the 500

**Comment by joeribekker** [comment]
Refinement: The cookie group is not created by default. This should be fixed.

@SilviaAmAm will add the technical error here.

**Comment by Viicos** [comment]
> will add the technical error here.

I'm able to reproduce
