### ISSUE TITLE
registration is always removed when copying a form

### ISSUE THREAD

**Issue by LaurensBurger** [open-formulieren/open-forms#4173]
### Product versie / Product version

2.5.6 - 2.6.3
hrlmmr: 101
lv: 164

### Omschrijf het probleem / Describe the bug

When copying a form, the registration tab will always be empty. 
It seems to happen for any type of registration.

![image](https://github.com/open-formulieren/open-forms/assets/112621537/5bbca3e8-1318-4fb8-95e2-1b1f7c54cb4b)

**Comment by sergei-maertens** [comment]
I've seen this somewhere else, I think there's a duplicate ticket somewhere from haarlemmermeer

**Comment by LaurensBurger** [comment]
i thought so too.. but can't find it.

**Comment by hlmr-erik** [comment]
https://taiga.maykinmedia.nl/project/gemeente-haarlemmermeer-open-formulieren/issue/101

**Comment by sergei-maertens** [comment]
@hlmr-erik we avoid pasting direct links to Taiga in Github on the off-chance that someone decides to point their botnet at it :grimacing: I've edited your comment

thanks for the extra information though, much appreciated!

**Comment by hlmr-erik** [comment]
Ah ok 👍 I've removed the comment history as wel

**Comment by joeribekker** [comment]
Linked to #4184
