### ISSUE TITLE
Submission stuck loop "Meerdere backends geconfigureerd op het formulier" (multiple backends configured on the form)

### ISSUE THREAD

**Issue by LaurensBurger** [open-formulieren/open-forms#4174]
### Product versie / Product version

2.6.3

### Omschrijf het probleem / Describe the bug

Den Haag stakeholder

see submission 3511 on test env. 
This is a failing submission, but is being retried non-stop for days. 
sentry: 354684

**Comment by joeribekker** [comment]
@sergei-maertens can you check how easy it is to backport this?
