### ISSUE TITLE
Missing required fields "aoaIdentificatie" in zgw api registration

### ISSUE THREAD

**Issue by LaurensBurger** [open-formulieren/open-forms#4191]
### Product versie / Product version

2.6.3

### Omschrijf het probleem / Describe the bug

#3580 in alex's comment about more missing fields. We seem to have missed 1 more: 
`VerblijfsAdres: required: - aoaIdentificatie`

`{"type":"[https://zgwzaak.nl/ref/fouten/ValidationError/","code":"invalid","title":"Invalid](https://zzgwzaak.nl/ref/fouten/ValidationError/%22,%22code%22:%22invalid%22,%22title%22:%22Invalid) input.","status":400,"detail":null,"instance":"urn:uuid:d611a6d1-4276-49f8-a902-4991b7a422a0","invalidParams":[{"name":"betrokkeneIdentificatie.verblijfsadres.aoaIdentificatie","code":"required","reason":"Dit veld is vereist."}]}`

**Comment by joeribekker** [comment]
![image](https://github.com/open-formulieren/open-forms/assets/96970/c9c0cd81-98d2-4455-8f67-3ecebf4d7390)

Can be empty but we do need to pass it along.

**Comment by joeribekker** [comment]
Bug in Open Zaak: https://github.com/open-zaak/open-zaak/issues/1627
