### ISSUE TITLE
Session persistance causes login choice te be ignored

### ISSUE THREAD

**Issue by LaurensBurger** [open-formulieren/open-forms#4199]
### Product versie / Product version

2.6.x

### Omschrijf het probleem / Describe the bug

When form A is a form with authentication and i start form B without authentication, form B will ignore this and also be authenticated. 
Complete with prefill and auth_* object being present in the submission. 

This behavior does not seem correct, my choice when starting a form should not be ignored and my authentication object should not be present in form B.

### Stappen om te reproduceren / Steps to reproduce

Create 2 forms that share authentication options
Open both front-ends of the forms
Login to first form using open "Inloggen met Demo BAN (test)"
Login to seconde form not using "Inloggen met Demo BAN (test)" but "Start form" 
Check both submissions, the should contain the same Authentication details:
![image](https://github.com/open-formulieren/open-forms/assets/112621537/ab6780df-2522-48f8-ad11-ea3b92c859fb)

### Screen resolution

None

### Device

None

### OS

None

**Comment by joeribekker** [comment]
Blocked so @sergei-maertens can review @Viicos proposal (that he will write :p)

**Comment by Viicos** [comment]
This is the current timeline of the submission creation with login info:
- The user lands on the SDK form page, and chooses to login with a specific provider.
- The login is handled by the provider, and the `handle_return` method of the auth plugin is then called. This method is responsible for setting the `"form_auth"` key of the session with some values. For example, the Digid plugin does the following (`FORM_AUTH_SESSION_KEY = "form_auth"`):
https://github.com/open-formulieren/open-forms/blob/3a8dbdd1cb19ad5aab607c2cccae9e0d1e91bc57/src/openforms/authentication/contrib/digid/plugin.py#L92-L97
- At this stage, the submission **wasn't created yet**.
- When the submission gets created through the API, the viewset will send a `submission_start` signal, responsible for grabbing the `"form_auth"` key from the session, and creating a `AuthInfo` model tied to the newly created submission.

So what happens here is that the user started one submission (and used a login option), and by starting a second submission for a different form, the same Django session is used, so the logic in the `submission_start` signal receiver applies.

---

One option would be to restructure the session structure, e.g. by separating the auth info by submission uuid:
```python
session[submission.uuid]["form_auth"] = {
    "plugin": PLUGIN_ID, 
    "attribute": AuthAttribute.bsn, 
    "value": bsn,
    ...
} 
```

But as said before, there is _no_ submission when the plugin sets the auth info on the submission. One solution I can think of is creating a temporary id, and then find a way to link it to the submission uuid once created. Anyway, refactoring the session structure will require a lot of changes, including [some extensions](https://github.com/open-formulieren/open-forms-ext-token-exchange).

**Comment by joeribekker** [comment]
Can't we link the login button to OF backend, create submission, then redirect to digid and attach the auth info to the submission?

**Comment by Viicos** [comment]
That could work as well, I'm not sure how much work it represents however

**Comment by sergei-maertens** [comment]
I'll need to talk this through - there's information passed during submission creation from the frontend/SDK to the backend that only the SDK knows and we need to validate that to prevent malicious user input

this would also bring us to two different code paths for submission creation, because anonymous submissions need to be handled by the SDK still and I'm not particularly eager to complicate things more in the frontend code, following the code/execution flow over multiple requests is already complicated enough as it is IMO

**Comment by sergei-maertens** [comment]
Simpler thought: can we not let the SDK pass an extra body key that indicates the form is being started anonymously? Then the backend can detect that and not attach the auth info to the created submission.

This isolates it on an individual submission basis and leaves the SDK in control with a single code-path, backend code/plugins don't need to be updated.

IMO once a submission is started and the auth info is attached, this auth info should also just be removed from the session.

**Comment by joeribekker** [comment]
refinement:

* delete form auth session key/data as soon as possible
* have an extra field when creating the form (flag saying this is anonymous)
