### ISSUE TITLE
If adblocker is enabled, the GovMetric faces are not loaded

### ISSUE THREAD

**Issue by SilviaAmAm** [open-formulieren/open-forms#4208]
### Thema / Theme

Frontend

### Omschrijving / Description

When an adblocker like uBlock origin is enabled, this happens:
![image](https://github.com/open-formulieren/open-forms/assets/19154114/25b70557-03c4-43d7-9fc6-8f4da66a01b9)
![image (1)](https://github.com/open-formulieren/open-forms/assets/19154114/802692a5-7cf8-43a6-9c98-18719c55c47e)

Maybe we should have the smiley faces locally and not load them from govmetric

**Comment by joeribekker** [comment]
Let's use local assets in that case, like the other vendors.
