### ISSUE TITLE
As a user I want to show content components in the summary screen

### ISSUE THREAD

**Issue by shea-maykinmedia** [open-formulieren/open-forms#421]
Currently the summary screen does not show content components since there is not data to be filled in for these components.  

Requirements:
- [ ] Display the content component properly styled in the Summary page of the SDK
- [ ] Give the admin the option to not display the content component.  Eg. A checkbox "Display on Summary Page"
- [ ] Content needs to be properly escaped to prevent a potential Cross Site Scripting attack

Issue split off from #240

**Comment by sergei-maertens** [comment]
We have this since 1.1.0 now - it's even configurable if these components should be visible in the summaries or not.
