### ISSUE TITLE
Users can upload too many files

### ISSUE THREAD

**Issue by LaurensBurger** [open-formulieren/open-forms#4222]
### Product versie / Product version

2.6.x

### Omschrijf het probleem / Describe the bug

When a upload component has a max files limit set, a user is able to upload more. 

When trying to upload 4 files at once: 
![image](https://github.com/open-formulieren/open-forms/assets/112621537/3a936f1f-6ce2-47f6-9e79-0b0badc3d769)

but when i first upload 2 files, followed by 4 at once
![image](https://github.com/open-formulieren/open-forms/assets/112621537/f0d2d283-de42-463e-9efe-d0501d69bbc9)

results in +3 uploaded files. Which are successfully processed/submitted.

**Comment by sergei-maertens** [comment]
Backend validation PR is still pending
