### ISSUE TITLE
Backend validation not applied for components inside fieldsets (with a nested key)

### ISSUE THREAD

**Issue by Viicos** [open-formulieren/open-forms#4241]
### Product versie / Product version

2.6.x

### Omschrijf het probleem / Describe the bug

Only when the key of the component inside the fieldset is `fieldset_key.component_key`, backend validation will not be applied.

Regression test:

```python
def test(self):
    component: FieldsetComponent = {
        "type": "fieldset",
        "key": "fieldset",
        "label": "A field set",
        "components": [
            {
                "type": "textfield",
                "key": "fieldset.textfield",
                "label": "Text field",
                "validate": {"required": True},
            },
        ],
        "hidden": False,
    }

    is_valid, errors = validate_formio_data(component, {"fieldset": {"textfield": ""}})

    self.assertFalse(is_valid)
```

### Screen resolution

None

### Device

None

### OS

None

**Comment by sergei-maertens** [comment]
Solution: allow `build_serializer_field` to return `None` or otherwise handle this, so that layout components (fieldset, columns, content) do not result in serializer fields being added for validation
