### ISSUE TITLE
Text area with 3500+(?) characters crashes pdf generation

### ISSUE THREAD

**Issue by LaurensBurger** [open-formulieren/open-forms#4255]
### Product versie / Product version

2.5.x - 2.6.x

### Omschrijf het probleem / Describe the bug

sentry: 353356
RID 192
Venray 103

When a submission contains a textarea with large amounts of text the submission crashes because after 5 minutes the pdf is not generated. 
user will see a error:
![image](https://github.com/open-formulieren/open-forms/assets/112621537/faeb2be5-7ba5-4505-9bb4-487c5dda419b)
![image](https://github.com/open-formulieren/open-forms/assets/112621537/b1449b19-1f92-4335-87f1-e4aacac20bfa)

**Comment by joeribekker** [comment]
Refinement: It was commented that even with a 1000 characters, PDF generation takes forever.

**Comment by alextreme** [comment]
@joeribekker @stevenbal FYI discussed with Laurens we have multiple customers with this issue now, if possible ensure that we have a backport for our 2.5/2.6-customers for this bug
