### ISSUE TITLE
Error message returns “null” for a radiogroup

### ISSUE THREAD

**Issue by Ollie-nl** [open-formulieren/open-forms#4262]
### Product versie / Product version

2.6

### Omschrijf het probleem / Describe the bug

As a user, I expect a clear and accessible error message.
Now, the error message returns a "null".

![image](https://github.com/open-formulieren/open-forms/assets/48805670/b3c523a7-0554-45bb-bea5-58e04d0befba)

More input about this bug:
https://github.com/frameless/strapi/issues/643

### Stappen om te reproduceren / Steps to reproduce

Leave all radio buttons in a radio group unselected and click on the submit button of the form

### Verwacht gedrag / Expected behavior

Show clear description

### Screen resolution

unknown

### Device

Desktop

### OS

MacOS

### Browser

Safari

**Comment by LaurensBurger** [comment]
component in this form has a defaultValue: "null", instead of null.

**Comment by sergei-maertens** [comment]
The results were analyed (Internal Taiga 815) and no further actions are necessary.
