### ISSUE TITLE
List to import FD contains duplicates & is incomplete.

### ISSUE THREAD

**Issue by LaurensBurger** [open-formulieren/open-forms#4276]
### Product versie / Product version

2.6.x

### Omschrijf het probleem / Describe the bug

When i want to import a form definition and use the dropdown list to select a existing form definition the list presented to me is not correct. 
The list contains duplicate entries that point to the same FD
It's also missing some

example: We have 4 reusable FD's 
![image](https://github.com/open-formulieren/open-forms/assets/112621537/dbc8e05f-2878-45c3-a57b-a001d2c89170)

I would expect to see these in a list when importing like:
- Contactblok PART [NAAM]-0318x
- Contactblok PART [NAAM]-0318xx
- Contactblok PART [NAAM]-0318x
- Contactblok PART [NAAM]-0318

But instead it shows:
![image](https://github.com/open-formulieren/open-forms/assets/112621537/56a6e11e-8c48-43ac-b888-9cbe10ddc344)

When looking at the html it's even more confusing
```html
  <option
    value="https://frm.nl/api/v2/form-definitions/b525c9c1-b829-4319-bc70-fdc035c71cd4"
  >
    Contactblok PART [NAAM]-0318x
  </option>
  <option
    value="https://frm.nl/api/v2/form-definitions/4421e271-9fda-4fa1-b6b1-7d5892a67a9a"
  >
    Contactblok PART [NAAM]-0318x
  </option>
  <option
    value="https://frm.nl/api/v2/form-definitions/b525c9c1-b829-4319-bc70-fdc035c71cd4"
  >
    Contactblok PART [NAAM]-0318x
  </option>
```
option 1 and 3 are duplicates, and the options for 
- Contactblok PART [NAAM]-0318
- Contactblok PART [NAAM]-0318xx

are missing from the list.

What's also strange is the total amount of reusable form defintions is: 302
![image](https://github.com/open-formulieren/open-forms/assets/112621537/acf70e08-1f73-478d-b9e2-9aab7060d134)
![image](https://github.com/open-formulieren/open-forms/assets/112621537/6835a784-6044-4150-8f91-8a69756fb33f)

the items in the html list add up to 302 (but we know the list has duplicates)
The results from the request to: api/v2/form-definitions?is_reusable=true&page=x
does however not result in 302 FD. 
```
/api/v2/form-definitions?is_reusable=true = 24
/api/v2/form-definitions?is_reusable=true&page=2 = 24
/api/v2/form-definitions?is_reusable=true&page=3 = 24
.. 
/api/v2/form-definitions?is_reusable=true&page=12 = 24
/api/v2/form-definitions?is_reusable=true&page=13 = 2
```
which is a total of 290

### Screen resolution

None

### Device

None

### OS

None

**Comment by joeribekker** [comment]
Refinement: Maybe a distinct missing? What is it joining with to cause duplicates? Is it pagination? Good luck Vasz

**Comment by vaszig** [comment]
The real problem here is that we do have duplicates sometimes and doesn't have to do with what we render or what we get from the API call.

For example when we export a form with a reusable form definition and a file component and we import it again we can see that we have an extra form definition created.

This is pointing to the older issue #4133 (this going to be tackled) so this can be closed.
