### ISSUE TITLE
SVG logo's do not show in gmail

### ISSUE THREAD

**Issue by LaurensBurger** [open-formulieren/open-forms#4277]
### Thema / Theme

Frontend

### Omschrijving / Description

When i use a svg logo in open forms my confirmation emails will not display a logo for some users because gmail does not support svg. 
![image](https://github.com/open-formulieren/open-forms/assets/112621537/7df6099c-f027-417c-8ca6-efeb0643382f)
![image](https://github.com/open-formulieren/open-forms/assets/112621537/c812c00a-d312-4feb-881d-58c685c139bb)

Open forms should either provide a fallback method to another image type or warn the administrator of using svg as a logo and it's effects for gmail inboxes.

**Comment by joeribekker** [comment]
Refinement: We can add a new field "email logo" that only accepted non-svgs.
