### ISSUE TITLE
Logic triggers with boolean variables don't work correctly

### ISSUE THREAD

**Issue by sergei-maertens** [open-formulieren/open-forms#4291]
### Product versie / Product version

latest (fdb19fdd6625e0281bdaed4a39a90f4f9150ec26)

### Omschrijf het probleem / Describe the bug

When I use a simple logic rule and use a boolean variable (checkbox component, boolean user defined variable...) as a trigger, this rule is not correctly serialized to JSON.

The resulting expression is:

```json
{
  "==": [
    {
      "var": "kanAfvalOphalen"
    },
    "true"
  ]
}
```

and it should be:

```json
{
  "==": [
    {
      "var": "kanAfvalOphalen"
    },
    true
  ]
}
```

UI representation:

![image](https://github.com/open-formulieren/open-forms/assets/5518550/b12fbac2-79f0-4af7-82d8-b7177db1cdb4)

The workaround is to use advanced logic instead of simple logic.

### Stappen om te reproduceren / Steps to reproduce

1. Add user defined variable `foo` with data type boolean
2. Add a simple logic rule
3. Select the variable `foo` in the "Als" dropdown
4. Select de operation "is gelijk aan"
5. Select "de waarde"
6. Select the comparison value "Ja"
7. Now, click the cog icon and click "Toon/verberg DSL weergave"

Any actions associated with this rule don't execute (for both true/false cases) because a string will never be equal to a boolean.

### Verwacht gedrag / Expected behavior

Selecting Yes/No in the dropdown configures an actual boolean in the JSON logic expression, and my actions execute properly.

### Screen resolution

None

### Device

None

### OS

None

### Browser

Chrome

**Comment by joeribekker** [comment]
Refinement: Removed backport label because no one complaint and we might break things for people relying on the bug behaviour. It seems this can be solved with an easy patch.
