### ISSUE TITLE
Can't select components inside an editgrid for the appointments configuration of a form

### ISSUE THREAD

**Issue by Viicos** [open-formulieren/open-forms#4300]
### Product versie / Product version

2.6.x

### Omschrijf het probleem / Describe the bug

I'm not familiar with the appointments configuration, but noticed the following when trying to select a component that is defined inside an editgrid:

https://github.com/open-formulieren/open-forms/assets/65306057/3b7ce265-295e-4997-a86a-73899125f9c5

### Stappen om te reproduceren / Steps to reproduce

1. Define an editgrid component with a textfield component inside
2. Go to appointments tab, try selecting something for _Last name component_

### Screen resolution

None

### Device

None

### OS

None

**Comment by joeribekker** [comment]
Refinement: This is about the old way of appointments which is deprecated and theres a new variant available where this is not an issue. Also, using repeating groups here is weird. And this, closing.
