### ISSUE TITLE
Derive location (street name or city) does not work when using components with dot(s) in key

### ISSUE THREAD

**Issue by Viicos** [open-formulieren/open-forms#4301]
### Product versie / Product version

2.6.x

### Omschrijf het probleem / Describe the bug

Our SDK does the following before making a call to the API to get the address:

```js
const isValidHouseNumber = HOUSE_NUMBER_REGEX.test(data[this.component.deriveHouseNumber]);
const isValidPostcode = POSTCODE_REGEX.test(data[this.component.derivePostcode]);
```

This is basically the same issues as in the backend, where `{"nested": {"key": "value"}}["nested.key"]` does not work without using the `FormioData` structure.

https://github.com/open-formulieren/open-forms-sdk/blob/eb42df41b4ede4f77c76528c42419c59b3aa8605/src/formio/components/TextField.js#L63-L65

Additionally, when defining a textfield inside an editgrid with the _Location_ tab configured, this will not work in the SDK (but does it really make sense?). This is part of a bigger issue: what are the features allowed for components inside an editgrid?

### Stappen om te reproduceren / Steps to reproduce

1. Create two textfield components, at least one of them should have a `.` in the key (e.g. `"nested.textfield"`).
2. Create a third textfield, and configure the _Location_ tab so that either the Postcode or House number component is the one with a dot in the key.
3. SDK will not be able to locate the right component value

### Screen resolution

None

### Device

None

### OS

None

**Comment by joeribekker** [comment]
Refinement: We're deprecating the old way of deriving streetname/city and use AddressNL component in #3993 and with that, this ticket can be closed.
