### ISSUE TITLE
As municipality I want to pass co-sign information to the Objects API

### ISSUE THREAD

**Issue by joeribekker** [open-formulieren/open-forms#4302]
* [x] Make co-signer BSN available in Object-registration template (legacy) and as variable (new method) that can be mapped
* [x] Make the co-sign date available in Object-registration template (legacy) and as variable (new method) that can be mapped

**Comment by sergei-maertens** [comment]
I'm not sure if we store BSN as is, I think this is rather generalized via an `AuthInfo` construct that knows which plugin was used and the identifier value. OTOH we also seem to special case some auth static variables...
