### ISSUE TITLE
Als gemeente Utrecht wil ik de mail van mede-ondertekenen wijzigen en mede-ondertekenaar doorgeven aan de Objecten API

### ISSUE THREAD

**Issue by joeribekker** [open-formulieren/open-forms#4303]
Meta ticket for these 2 features:

* [x] #3807 (limited to the mail template part)
* [x] #4302

This is described by Utrecht as follows:

> 1. We willen de info van de mede-ondertekenaar meegeven in de registratie naar de Object registratie.
> Daarvoor hebben we onderstaande regel aan de JSON template toegevoegd.
> "Mede-ondertekend_door": "{{ co_signer }}", maar dit werkt niet

Dit gaan we mogelijk maken. De exacte variabele zal wellicht anders zijn.
Er komen 2 variabelen (naam nog onzeker):

1. co_signer_bsn -- het gaat dus echt om het BSN, naam e.d. krijgen we niet vanuit DigiD en zou via een extra call naar de BRP moeten verlopen. De naam laten we dus even buiten scope!
2. co_sign_date -- de datum waarom is mede-ondertekend (deze kwam naar voren in het eerdere gesprek met jullie)

> 2. We willen het template van de mede-ondertekenaars mail aanpassen
> - het OF-nummer moeten we kunnen verwijderen
> - de link is gebaseerd op een Open Forms URL, we willen dit graag ook via Strapi laten lopen en dus de URL 
aanpassen (Deze heeft wat mij betreft niet de hoogste prio, het werkt met de Open Forms link ook).
Het mooist zou zijn dat dit een variabele wordt die in meerdere templates is te gebruiken.

We gaan inderdaad de template van de mail wijzigbaar maken. Je kan dan het OF-nummer er dan uit slopen. We maken dit ENKEL wijzigbaar op globaal niveau (dus niet per formulier).

Dat van die link laten voor nu buiten scope.

**Comment by Viicos** [comment]
I think this can now be closed?

**Comment by sergei-maertens** [comment]
Yes, now that it's backported.
