### ISSUE TITLE
Als zaak-behandelaar wil ik dat documenten een meer sprekende titel krijgen

### ISSUE THREAD

**Issue by joeribekker** [open-formulieren/open-forms#4319]
### Thema / Theme

Plugins

### Omschrijving / Description

In Decos JOIN, documents are shown by their title. Currently, we set the title in StUF-ZDS to "bijlage". We could use the -already configurable- file name (maybe without extension). Beware that the `title` attribute can only hold 200 characters.

* [x] Fixed in StUF-ZDS (definitely needed)
* [x] Fixed in ZGW API (check if fix needed and if so, do it)

**Comment by joeribekker** [comment]
Refinement: Should we use the label, the filename or new field to configure?
Estimate: label or filename: 1 day; new field 2-3 days

**Comment by joeribekker** [comment]
So, we already seem to have a "Title" field. The tooltip says its used in the Documenten API. This should then also be used as the "titel" attribute for StUF-ZDS. Please also check if this field is actually used in the Documenten API (for both Object and ZGW registrations).

![Image](https://github.com/user-attachments/assets/7908c81c-9d74-46ad-b415-8fb882d1e918)

Please also amend the tooltip to reflect it also works in StUF-ZDS.

**Comment by vaszig** [comment]
This was already the case for ZGW APIs. It was updated for StUF-ZDS as well. The tooltip was not changed since it's not referring to the ZGW APIs specifically but it has a general text (Titel voor het document in de Documenten API).
