### ISSUE TITLE
Add integration with Expoints feedback tool

### ISSUE THREAD

**Issue by joeribekker** [open-formulieren/open-forms#4356]
### Thema / Theme

Frontend

### Omschrijving / Description

Similar to GovMetric, we need to add the Expoints feedback tool.

Documentation: https://documentation.expoints.nl/external/Help/Popup

Desired result: A feedback button is shown on the side/below the form (configurable on the Expoints side). This button shows a popup with questions.

We will get a test-account at Expoints to test the workings. It only works (or button appears) when you accept the cookies, for example on Rotterdam:

![2024-06-04-049V4PaLPs](https://github.com/open-formulieren/open-forms/assets/96970/0e9cdd2d-44d2-4999-85ba-8817479f19f2)

**Comment by stevenbal** [comment]
I had a meeting with Haarlemmermeer and Expoints and Expoints will send me a separate script that I can use to test the integration, where the feedback tool works just like it does on production, but without sending the actual feedback data

**Comment by stevenbal** [comment]
> We will get a test-account at Expoints to test the workings. It only works (or button appears) when you accept the cookies, for example on Rotterdam

@joeribekker does you mean that for Open Forms it should also only work after accepting cookies?

**Comment by stevenbal** [comment]
I tested it over https locally, and the widget works:

![image](https://github.com/open-formulieren/open-forms/assets/29249171/2c7245bd-90a5-4fa3-96ab-946e497c0afe)
