### ISSUE TITLE
PaymentID vanuit Ogone meesturen als extraElement via ZaakDMS

### ISSUE THREAD

**Issue by olenitsj** [open-formulieren/open-forms#4380]
Conclusions on how we'll approach this: https://github.com/open-formulieren/open-forms/issues/4380#issuecomment-2247845001

### Thema / Theme

API

### Omschrijving / Description

**Context**: Een formulier waar betalingen via ideal/creditcard plaats vinden(Ogone).

Bij het creëren van een zaak via ZaakDMS(stuf-zds) willen wij de PaymentId als een extraElement mee opgestuurd krijgen. 

Dit is nodig zodat wij de paymentID i.c.m een product code aan SAP door kunnen geven voor het registeren van een verkoop.

De alternatief die wij hebben, is gebaseerd op de referentie die door openforms wordt meegestuurd richting ogone, de betalingID op te zoeken via de OgoneAPI, maar dit is erg omslachtig als de gegevens direct na het voltooien van betaling al bekend zijn bij openforms. 

### Added value / Toegevoegde waarde

Geen extra koppeling met ogone nodig voor het ophalen van de paymentId op basis van een door openforms mee gegeven referentie.

**Comment by olenitsj** [comment]
We concluderen net, dat andere velden zoals, bedrag/prijs. Niet via ZaakDMS mee wordt getuurd. De scope van deze story wordt iets groter dan initieel gedacht. Ik kom nog terug met de concrete betaling/ogone data waar we naar op zoek zijn

**Comment by joeribekker** [comment]
> We concluderen net, dat andere velden, zoals: bedrag/prijs. Niet via ZaakDMS mee wordt getuurd. De scope van deze story wordt iets groter dan initieel gedacht.
> 
> We moeten namelijk ook de volgende velden mee krijgen: Payment.completed (zou altijd true moeten zijn) Payment.amount Payment.public_order_ids (OF- id die mee word gestuurd als ref naar ogone van uit openforms) PaymentId (de id welke terug wordt gestuurd door ogone, is anders dan de OF- ref)

We already sent the Payment status as part of the default Zaak-attributes. No need for this one right? We can however include the other fields:

* amount - extraElement
* public_order_ids - zaak kenmerken?
* paymentId - extraElement

Estimate: 3 days

**Comment by CMasselink** [comment]
>We already sent the Payment status as part of the default Zaak-attributes. No need for this one right? We can however include the other fields:

You are right, there is no need for an extra payment status since it is part of the default zaak-attributes.

>amount - extraElement
public_order_ids - zaak kenmerken?
paymentId - extraElement

public_order_ids can be an extraElement as well.

**Comment by alexvdL-utrecht** [comment]
Hierbij goedkeuring voor deze opdracht voor de gemeente Utrecht. @joeribekker Hebben jullie hiervoor ruimte. Onze wens is dat dit half augustus beschikbaar is voor acceptatie. Inhoudelijke aansturing door @olenitsj .

**Comment by joeribekker** [comment]
Aangegeven dat volgende release eind september is. Alex gaat intern kijken of dat kan.

**Comment by alexvdL-utrecht** [comment]
@joeribekker Utrecht is voornemens om in de eerste week van October, OO's te migreren waar ook formulieren met betalingen gebruikt worden. Midden augustus in acceptatie is al erg krap. Aangezien wij de koppeling ook nog moeten, bouwen, testen en live brengen en ook de migratie team moet de ruimte krijgen om hun migratie scripts te bouwen, testen en accepteren gerelateerd aan betalingen.
Daarom het verzoek om hiervoor toch een 2.7.x uit te brengen. Kan deze bijvoorbeeld mee in 2.7.1? Of zijn we daarvoor al te laat?

**Comment by joeribekker** [comment]
@alexvdL-utrecht dit is geen patch, dit is een feature. Het kan dus niet zomaar mee in een patch release omdat het gedrag anders is. We kunnen het als extensie doen hopelijk als tijdelijke oplossing, dat kost extra tijd. In 2.8 zit het dan zonder extensie.

Lingo: OO=Organisatie Onderdelen?

**Comment by joeribekker** [comment]
@alexvdL-utrecht @CMasselink kunnen jullie bevestigen dat dit om `extraElementen` in een StUF-ZDS bericht gaat, vanuit Open Formulieren (zoals @olenitsj aangeeft)? Wij hadden zelf namelijk gedacht dat het ging om een attribuut in het Object, dat jullie ESB dan vertaalt naar een StUF-bericht?

**Comment by sergei-maertens** [comment]
@olenitsj de image tag `utrecht-zds-2.7.x` is vanaf nu beschikbaar op Docker Hub (zie https://hub.docker.com/r/openformulieren/open-forms/tags), dus jullie kunnen dit deployen en uittesten op jullie O/T/A omgevingen. Deze is *ietsje* nieuwer dan 2.7.4.

Er komt volgens onze reguliere release cycle ook nog een tag `utrecht-zds-2.7.5` - er is nog geen concrete datum bekend hiervoor, maar dit zou binnen de 4 weken moeten gebeuren.

**Comment by olenitsj** [comment]
@sergei-maertens, Do we need to configure something to return the payment attributes in the stuf ZDS creerzaak soap measage?

Right now, we have the 2.7.x (Gemeente Utrecht extension) version installed, but we don't see any of the payment information.

**Comment by sergei-maertens** [comment]
@olenitsj ik heb weer toegang - hierbij een screenshot van de default-instellingen:

![image](https://github.com/user-attachments/assets/2951bf9e-42e1-45e0-889b-7a489b63be23)

Dit resulteert in de `extraElementen` met naam `payment_completed`, `payment_amount`, `payment_public_order_ids.0` en `provider_payment_ids.0` indien er 1 betaling was bij de formulierinzending.

**Comment by olenitsj** [comment]
Done https://taiga.maykinmedia.nl/project/gemeente-utrecht-common-ground-platform/issue/283
