### ISSUE TITLE
Pausing form breaks when no address is supplied - disabling the "Continue later" button

### ISSUE THREAD

**Issue by LaurensBurger** [open-formulieren/open-forms#4382]
### Product versie / Product version

2.6.7 - 2.7.0

### Omschrijf het probleem / Describe the bug

When a user makes a mistake and supplies no emailadres in the pause modal
![image](https://github.com/open-formulieren/open-forms/assets/112621537/e53ecc65-69bb-44cb-9db9-77e22eb34757)
a spinner is shown indefinitely and the "Continue later" button is disabled. 
This will not change for the entire session.
![image](https://github.com/open-formulieren/open-forms/assets/112621537/98dfa382-fb00-40a4-9a78-3da5314dedb6)

If a user supplies no, or a invalid e-mailadres this should be a quick warning and they should be able to correct this mistake to provide a valid adres or save the form in a later stage.

**Comment by sergei-maertens** [comment]
Technical direction: this modal form should just be a simple Formik form with basic (client-side) validation to prevent this.
