### ISSUE TITLE
Open Forms API - retrieving all forms via API on testenvironment is very slow

### ISSUE THREAD

**Issue by alextreme** [open-formulieren/open-forms#4393]
### Product versie / Product version

2.7.0

### Customer reference

Taiga OIP 2236

### Omschrijf het probleem / Describe the bug

The /api/v2/forms endpoint is very slow, leading to the OF-OIP client integration to become unworkable.

Low-priority, as this only affects environments with very large number of forms:

![image](https://github.com/open-formulieren/open-forms/assets/226839/9dde1b72-8c54-4b6e-a933-92eb144bba48)

This can be reproduced by increasing the timeout (currently on 1 second) to 30 seconds and going to a OIP PDC admin product page:

https://open-inwoner-test.maykin.nl/admin/openformsclient/configuration/

### Screen resolution

None

### Device

None

### OS

None

**Comment by sergei-maertens** [comment]
We addressed this in #3825 - you should not be using these endpoints anymore, instead you should use the optimized, public API endpoint `/api/v2/public/forms`

**Comment by alextreme** [comment]
Thanks, this indeed felt like deja-vu. Will request Paul to pick this up for openforms-client
