### ISSUE TITLE
Create a prefill plugin to prefill with values from an external reference (initially only for Objects API)

### ISSUE THREAD

**Issue by stevenbal** [open-formulieren/open-forms#4396]
Add advanced settings for Objects API registration to store the necessary config (with a button to populate it from the registration configuration). These advanced settings should contain:
- what Objects API group to use
- what Objecttype to use
- path to the BSN in the object

~~Replace the current way of prefilling in the form Variables tab by adding a button `Configure` to open a modal. In this modal you can configure the required prefill information and also modify the general config for the Objects API prefill.~~ -> this modal already exists, the implementation of the form is part of https://github.com/open-formulieren/open-forms/issues/4608

Based on the selected `plugin` the other fields might vary. I think our current prefill options only require `Prefill attribute` and `Prefill identifier role`. For the Objects API plugin, we should also show the `advanced settings` mentioned above and indicate that this is form level configuration. We could split the modal to indicate the difference between this form level config and the variable level config. This modal is to avoid having to switch back and forth between tabs and reopening the modal, which isn't great UX

**Comment by sergei-maertens** [comment]
reopening because I can't tell if anything else is needed for this ticket :grimacing:
