### ISSUE TITLE
Validation for fields within AddressNL component

### ISSUE THREAD

**Issue by LaurensBurger** [open-formulieren/open-forms#4420]
### Thema / Theme

Form designer

### Omschrijving / Description

to add to: #4418 

Currently forms might be validating on the "city" and "postcode" fields. The AddressNL component does not seem to support validation on the fields within the component. 

If this validation is lost these forms would have no way of using both the AddressNL component and BAG plugin.

**Comment by sergei-maertens** [comment]
Which validations can you do now that you can't do in the AddressNL field?

**Comment by LaurensBurger** [comment]
Only allow form te be filled in by residents of "Sergei City". If i don't have authentication/prefill for a form i would apply validation to the city field to achieve this. 
![image](https://github.com/open-formulieren/open-forms/assets/112621537/41230c2b-8fb3-463c-b3c9-478a9c439bed)

**Comment by sergei-maertens** [comment]
Okay, so a regex validation on individual nested fields would suffice then, I presume? And of course being able to specify validation error messages.

**Comment by LaurensBurger** [comment]
Yes - that sounds sufficient

**Comment by joeribekker** [comment]
Refinement: Allow regex on city and postal code.
