### ISSUE TITLE
Migrate admin JSON components to Monaco editor

### ISSUE THREAD

**Issue by Viicos** [open-formulieren/open-forms#4424]
### Thema / Theme

Admin

### Omschrijving / Description

Following https://github.com/open-formulieren/open-forms/issues/4051, there are still places where the Monaco Editor can be used in the admin, but requires more work regarding styling.

In order of priority:

* [x] Form logic rules: Advanced JSON-logic trigger
* [x] Form logic rules: Assign variable-action
* [x] Variables tab: Default value for objects and arrays
* [x] Service fetch logic expression
* [x] Form logic rules: Show DSL

**Comment by joeribekker** [comment]
Estimate: 1 week
