### ISSUE TITLE
payment adds unsuccessful payments tot amount. 

### ISSUE THREAD

**Issue by LaurensBurger** [open-formulieren/open-forms#4425]
### Product versie / Product version

2.6.7

### Customer reference

Utrecht 243

### Omschrijf het probleem / Describe the bug

When a payment is retried multiple times, each amount get's added to the total when 1 of these tries is successful Resulting in the wrong payment.amount.

Example where only 1110 was paid, the rest never completed.
payment.amount was 4 X EUR 19,90 = EUR 79,60

![image](https://github.com/open-formulieren/open-forms/assets/112621537/c82d446f-313b-411b-b5d1-834fad2c3596)

**Comment by sergei-maertens** [comment]
Seems like two issues are happening here:

- [ ] Fix incorrect payment amount being sent to the Objects API
- [ ] Figure out why failed payments are not marked as such (bulk update issue?)
