### ISSUE TITLE
Ogone can possibly hit the payment return URL with POST

### ISSUE THREAD

**Issue by sergei-maertens** [open-formulieren/open-forms#4427]
### Product versie / Product version

2.6.7 | master

### Customer reference

Sentry Utrecht 359809

### Omschrijf het probleem / Describe the bug

Request seen in Sentry: `<rest_framework.request.Request: POST '/payment/:uuid/return?action=cancel'>`

Return URLs in the ogone plugin only accept GET requests - *possibly* this is a configuration issue in Ogone but we should investigate

Stumbled on this while investigating #4425 

### Stappen om te reproduceren / Steps to reproduce

Unclear yet

### Verwacht gedrag / Expected behavior

Payment cancellation doesn't cause HTTP 500 errors on our end.

### Screen resolution

None

### Device

None

### OS

None

**Comment by joeribekker** [comment]
refinement: need to check whether this is actually configurable in Ogone, then reproduce it on Utrecht environment, etc.

**Comment by sergei-maertens** [comment]
This appears to be exactly the same case as #2362 for which Ogone claimed it would not happen in production.

**Comment by sergei-maertens** [comment]
It's really a duplicate of #2362 - we can't fix this on our end. I've reached out to Utr. on Taiga and sent a support request to Ogone to reopen the ticket/case, that's all we can do at this point.
