### ISSUE TITLE
Add error-boundary to the registration modal in the variables tab

### ISSUE THREAD

**Issue by joeribekker** [open-formulieren/open-forms#4432]
### Product versie / Product version

latest (pre 2.7)

### Omschrijf het probleem / Describe the bug

All my hard work gets lost if Objects API is not reachable and I switch to the variables tab to assign variables.

### Screen resolution

None

### Device

None

### OS

None

**Comment by sergei-maertens** [comment]
Re-opening - the bug was fixed, but I still think it's a good idea to add an explicit error boundary for the bugs that are not known yet :)
