### ISSUE TITLE
Objecten API - Per formulier DMS route bepalen

### ISSUE THREAD

**Issue by joeribekker** [open-formulieren/open-forms#4437]
**Reference:** [PF-114](https://dimpact.atlassian.net/browse/PF-114)

### Jira description

h3. Userstory

*Als* functioneel beheerder
*Wil ik* bij ingediende formulieren die via de object-registratiemethode worden opgeslagen, per formulier kunnen aangeven in welke API de aanvraag-PDF en eventuele bijlages, voorzien van hun bijbehorende ZTC-metadata, opgeslagen worden.
*Zodat ik* flexibel ben in het gebruik van mijn voorkeurs-dms.

Eventuele oplossingsrichting:

**Comment by joeribekker** [comment]
Refinement: Duplicate of #4267

**Comment by sergei-maertens** [comment]
Going to close this, as this particular piece of functionality is available since Open Forms 2.7. Further related development/improvements are tracked in #4267
