### ISSUE TITLE
Force downloading of PDF from confirmation page, instead of letting the browser open.

### ISSUE THREAD

**Issue by LaurensBurger** [open-formulieren/open-forms#4488]
### Thema / Theme

Frontend

### Omschrijving / Description

Browsers are very eager to open pdf's for their users, but this behavior does not really fit with the kinds of PDF's that OF generates, which are definitely more of the kind you would want to actually save on your disk.

Since the user loses the ability to download the pdf again after the session is gone, the 
"Download PDF" should force a actual download of the PDF via the "download" attribute which seems to be supported by all [modern browsers.](https://caniuse.com/mdn-html_elements_a_download)

- [x] Set up proper URL without exposing API endpoint details
- [x] Add Content-Disposition headers to force download

**Comment by sergei-maertens** [comment]
We'll need to do this server side, since the attribute does not work on cross origin downloads (which is the case with embedding) in Chrome
