### ISSUE TITLE
Pausing form triggers "Submission.finalised_registration_backend_key" causing incorrect registration selection

### ISSUE THREAD

**Issue by LaurensBurger** [open-formulieren/open-forms#4502]
### Product versie / Product version

2.6.x

### Omschrijf het probleem / Describe the bug

Pausing a form causes the registration to be set, which can lead to submissions registering to the wrong back-end when it's changed after un-pausing. 

### Stappen om te reproduceren / Steps to reproduce

create a form with 2 registration option
create a checkbox 
create logic for this checkbox to change registration on select. 
start form and pause submission
continue submission and click checkbox 
watch submission use registration for unchecked checkbox

### Verwacht gedrag / Expected behavior

registration backend should not be saved when pausing a form

**Comment by sergei-maertens** [comment]
workaround: not relying on implicit default, but add an explicit inverse logic trigger that selects "the" other registration backend
