### ISSUE TITLE
Import of legacy Objects API registration forms is not possible anymore

### ISSUE THREAD

**Issue by sergei-maertens** [open-formulieren/open-forms#4516]
Version: 2.7.0

importing form with v1 Object Api registration causes error: "Er is iets foutgegaan bij het importeren van formulier: {'registration_backends': [{'options': {'objects_api_group': [ErrorDetail(string='Dit veld is vereist.', code='required')], 'objecttype': [ErrorDetail(string='Must be a valid UUID.', code='invalid')]}}"

I have an export of such a form provided by Laurens.

Culprit seems to be 4acd2f4

**Comment by Viicos** [comment]
https://github.com/open-formulieren/open-forms/pull/4343 did not take form imports into account (even though the PR template with checkboxes was present 🫣).
