### ISSUE TITLE
Form variable dropdowns take up too much horizontal space

### ISSUE THREAD

**Issue by sergei-maertens** [open-formulieren/open-forms#4519]
### Product versie / Product version

2.7.0

### Omschrijf het probleem / Describe the bug

![image](https://github.com/open-formulieren/open-forms/assets/5518550/93296f5d-962f-4fbb-8c07-06d6236261d4)

These dropdowns are sized based on the length of the options, which is excessively large with the new static variables present.

### Screen resolution

bigger

### Device

Desktop

### OS

Linux

### Browser

Chrome

**Comment by joeribekker** [comment]
Refinement: Suggested to add a max-inline-size to the dropdown, to limit the max size of ONLY the dropdown field. The options can still be wider AND make this into a React dropdown with search.
