### ISSUE TITLE
When using OIDC the session can expire while I'm working, without any message showing.

### ISSUE THREAD

**Issue by joeribekker** [open-formulieren/open-forms#4528]
### Product versie / Product version

2.6.10

### Omschrijf het probleem / Describe the bug

When you're in the form editor, the OIDC session can expire, even when working.

### Stappen om te reproduceren / Steps to reproduce

1. Configure the admin interface to allow admin session to last 60 minutes
2. _presumably_ the keycloak OIDC session is set to a lower value than that
3. Log in as usual to the admin, using OIDC
4. Wait 55 minutes (possibly shorter depending on the Keycloak session duration, but this is a guess)
5. Navigate to `/admin/`
6. Observe the redirect to `/admin/login/failure/` and the matching error page

### Screen resolution

None

### Device

None

### OS

None

**Comment by Viicos** [comment]
Is this similar to https://github.com/open-formulieren/open-forms/issues/3760?

**Comment by joeribekker** [comment]
yes!

**Comment by sergei-maertens** [comment]
Refinement: need steps on how to reproduce. May be related to the `SessionRefreshMiddleware`?

Timebox for an hour to look if we can find something suspicious - if the refresh middleware redirects you to the OIDC provider when trying to submit the changes made in the form designer, you lose all your work and that's... less than ideal.

**Comment by joeribekker** [comment]
Refinement: We need steps to reproduce this. Preferrably without waiting 30 minutes.

**Comment by joeribekker** [comment]
Refinement: @LaurensBurger could you try to reproduce this, this week?

**Comment by LaurensBurger** [comment]
This seems to mainly show itself when clicking the "validation" tab of a component which in turn crashes the modal.

Refreshing the page solves the issue, until the oidc session has expired again.

**Comment by sergei-maertens** [comment]
I think the validation tab crashing the modal is a side effect of the expired session, as it makes an API call which then returns a 403, which we can't properly handle :thinking:

**Comment by sergei-maertens** [comment]
I've updated the description with my actions I did today based on their timestamps - I got the 403 screen.

**Comment by stevenbal** [comment]
@sergei-maertens I tried this locally by setting a very short timeout in Keycloak and managed to reproduce it as well
![image](https://github.com/user-attachments/assets/b6668a4d-9ed5-47c8-93b3-2d22c04008e1)

![image](https://github.com/user-attachments/assets/cffd2fba-9b0f-4b1c-bfdf-10039bd9fdf9)

**Comment by stevenbal** [comment]
Discussed with Sergei:

1. A possible "fix" could be to ensure that the Keycloak session timeout is longer than the session timeout on the side of Open Forms, which should then result in a prompt to refresh your session from Open Forms which should also refresh the Keycloak session
2. Another way to deal with this could be to remove the OIDC session refresh logic from Open Forms completely, and just use OIDC (Keycloak) for logging in, but manage the session only from Open Forms itself. This does mean that sessions can no longer be managed from Keycloak and if users are deleted from Keycloak, they will still be authenticated in Open Forms until the session times out there

**Comment by joeribekker** [comment]
Can't we read the session timeout from some Keycloak response? I can image it mentions how long we have before we need to use our refresh token? We can then maybe runtime adjust the session length to match Keycloak?

**Comment by sergei-maertens** [comment]
oh and have we checked that this has nothing to do with `OIDC_RENEW_ID_TOKEN_EXPIRY_SECONDS `? See https://mozilla-django-oidc.readthedocs.io/en/stable/installation.html#validate-id-tokens-by-renewing-them

The default is set to 15 minutes, our 60 min django session would cause some misalignment there,  but this may be a red herring

**Comment by stevenbal** [comment]
@sergei-maertens I think all `OIDC_RENEW_ID_TOKEN_EXPIRY_SECONDS` does is trigger Open Forms to request a new token from Keycloak (via the SessionRefresh middleware), and if the session is still alive in Keycloak, the user should just be able to continue with their session in Open Forms. If we bring it in line with the django session timeout, I guess you would be notified in time when your session is about to expire, but this doesn't give any certainty of the session still existing in Keycloak

**Comment by stevenbal** [comment]
Discussed with Joeri and Sergei: I will go for the option to remove the sessionrefresh middleware, which means that Open Forms itself is the only application responsible for managing the user session after the user has logged in via OIDC
