### ISSUE TITLE
Parametrize the position of the "back to previous step" link/button

### ISSUE THREAD

**Issue by sergei-maertens** [open-formulieren/open-forms#4544]
Taiga DH 685, business case "ondernemers"

DH wishes to move the "back" link from the button row below the form fields to between the step title and "step x from total" text.

![image](https://github.com/user-attachments/assets/c2baf83f-4d38-4eb2-b835-073ae28325d6)

**Tasks**

* [x] Support icon in back link, possible route is SVG background image. Alternative was offert by Robbert NL DS -> check with him & Sergei what the status is
* [x] Via theme/styling/design tokens: refactor the page structure (CSS grid?) so that we can arrange the order/position of UI elements through design tokens. Existing/other instances should keep the current layout.

**Comment by sergei-maertens** [comment]
Refinement: careful, harder than it looks like

**Comment by robinmolen** [comment]
At this point only 'previous' button can be moved using css variables. If we would like the support re-arranging the other components as well, then some extra styling will be needed. All instances use the current layout as default.

I haven't changed anything just yet for the design tokens and the arrow icon also needs implementing, I'll discuss these with Sergei later this week.

**Comment by robinmolen** [comment]
Discussed this with Sergei and we are gonna solve this situation a bit differently:

The UI will have two 'previous' buttons, that will be hidden/shown using design tokens.

**Comment by robinmolen** [comment]
The form will have two 'previous' buttons. One at the very top of the form, that is hidden by default. And one in the bottom of the form (the same location as the current 'previous' button).

Using design tokens you can show/hide both buttons separately

**Comment by robinmolen** [comment]
For the back arrow icon we gonna use the unicode icon, like the introduction page
