### ISSUE TITLE
Send file backend is not configurable

### ISSUE THREAD

**Issue by marnixdessing** [open-formulieren/open-forms#4575]
### Product versie / Product version

2.7.1

### Omschrijf het probleem / Describe the bug

I would expect the SENDFILE_BACKEND option would be configurable using an environment variable. This is for open forms installations that do not run behind an nginx proxy and want to use different [send file backends](https://django-sendfile2.readthedocs.io/en/latest/backends.html)

See https://github.com/open-formulieren/open-forms/blob/master/src/openforms/conf/base.py#L346
I'll create a PR to adres this issue.

### Screen resolution

None

### Device

None

### OS

None

**Comment by sergei-maertens** [comment]
I've changed the classification to enhancement since this was deliberate - our team can only support nginx and our official deployment examples also put nginx in front of the app container.

I do understand that if you want to use another webserver that being able to configure this is desirable.
