### ISSUE TITLE
Empty fields show as "not filled in" in pdf summary

### ISSUE THREAD

**Issue by LaurensBurger** [open-formulieren/open-forms#4597]
### Product versie / Product version

2.6.13 

### Customer reference

RID 209

### Omschrijf het probleem / Describe the bug

Fields with no value are now shown in the pdf as "not filled in"

![image](https://github.com/user-attachments/assets/73469e1b-95c5-40f6-82a7-47a73c4c6a02)
seems to be introduced [here](https://github.com/open-formulieren/open-forms/commit/47cf9032f3c4267e0b68c6d7a1db4bac63be3fd0) 

### Screen resolution

None

### Device

None

### OS

None

**Comment by sergei-maertens** [comment]
I don't understand what your expectation is here - can you clarify?

**Comment by LaurensBurger** [comment]
To not show this string but instead leave it empty like the user did.

**Comment by sergei-maertens** [comment]
we will make sure this is done in 2.6.14
