### ISSUE TITLE
Translation tab unusable when long variable names are used for answers in checkboxes, choice & radio

### ISSUE THREAD

**Issue by LaurensBurger** [open-formulieren/open-forms#4636]
### Product versie / Product version

2.7.x

### Customer reference

LV 194

### Omschrijf het probleem / Describe the bug

When a the answers user rather long variable names they cause parts of the translation tab to slide under adjacent components: 
![image](https://github.com/user-attachments/assets/ababe15c-0127-42d2-8e10-8a3da16b0d92)
rendering the tab useless as the user is not able to even click the "EN" part or comfortably add/edit the translations. 

Breaking these long values should solve this issue - but i'm also not sure why these values should even be displayed at all in this tab - as it would not provide much help with translations?

**Comment by joeribekker** [comment]
Word-break would be the easiest fix here. I guess zooming out could work as a workaround.

**Comment by robinmolen** [comment]
@joeribekker Who is the owner of this issue?
