### ISSUE TITLE
Translations of checkboxes, radio & choice answers show as required when removed

### ISSUE THREAD

**Issue by LaurensBurger** [open-formulieren/open-forms#4637]
### Product versie / Product version

2.7.x - latest

### Customer reference

LV 195

### Omschrijf het probleem / Describe the bug

Translations become required fields after saving them once, not allowing a form builder to remove the translations for the answers:
![image](https://github.com/user-attachments/assets/f002ef78-6c92-4acf-b5ce-a667d1aa7462)

This does not seem to happen for other translations like labels, tooltips etc.

### Screen resolution

None

### Device

None

### OS

None

**Comment by joeribekker** [comment]
Refinement: Confirmed. It also happens with options for radio-options on `latest`.

**Comment by robinmolen** [comment]
This issue will be resolved in the release after 2.8 (so probably release 3.0)

Until this issue is resolved, users can workaround this situation by defining option translations.

**Comment by sergei-maertens** [comment]
note to self: depends on new formio-builder release
