### ISSUE TITLE
TinyMCE missing drop down for headers, paragraph.

### ISSUE THREAD

**Issue by LaurensBurger** [open-formulieren/open-forms#4653]
### Product versie / Product version

2.7.6

### Omschrijf het probleem / Describe the bug

![image](https://github.com/user-attachments/assets/81d7e8aa-370e-4d02-98ff-31cee94ebcd2)
![image](https://github.com/user-attachments/assets/f288ef2e-4340-421b-91e6-3ab479b6e441)

Workaround is available through shortcuts: 
Kop 1	Shift + Alt + 1
Kop 2	Shift + Alt + 2
Kop 3	Shift + Alt + 3
Kop 4	Shift + Alt + 4
Kop 5	Shift + Alt + 5
Kop 6	Shift + Alt + 6
Alinea	Shift + Alt + 7

**Comment by stevenbal** [comment]
Backports:
* https://github.com/open-formulieren/open-forms/pull/4667
* https://github.com/open-formulieren/open-forms/pull/4668
* https://github.com/open-formulieren/open-forms/pull/4669
