### ISSUE TITLE
Windows users cannot upload .zip 

### ISSUE THREAD

**Issue by LaurensBurger** [open-formulieren/open-forms#4658]
### Product versie / Product version

2.6 - latest

### Omschrijf het probleem / Describe the bug

When a windows user uploads a zip file they will always get a error about the file not being a zip:
![image](https://github.com/user-attachments/assets/0694caef-31c1-4d22-84f5-db0825ff0fd7)

Testen in browserstack 
Windows 10 + 11
Chrome, Edge and Firefox. 

This does not occur for Mac or Linux systems

**Comment by joeribekker** [comment]
refinement: Joeri will check the header that is used. then @vaszig is assigned.

**Comment by joeribekker** [comment]
@vaszig content type reported: `application/x-zip-compressed`
