### ISSUE TITLE
Hidden components with "Multiple values" trigger validation

### ISSUE THREAD

**Issue by LaurensBurger** [open-formulieren/open-forms#4659]
### Product versie / Product version

latest

### Customer reference

no particular but it get's reported 

### Omschrijf het probleem / Describe the bug

Hidden component with "Multiple values" set get their defaultValue changed from:
```json 
  "defaultValue": null,
```
to:  

```json
  "defaultValue": [
    null
  ],
```

This causes validation to trigger right after loading since their value is now [] instead of [ null ]

```josn 
  "telefoonnummer": []
```

This can be resolved by changing the defaultValue to via the json of the components:

```json
  "defaultValue": [],
```

**Comment by joeribekker** [comment]
Refinement: Task estimated here is changing the default value to an array (`[]`) without the `null`. 

Robin can do this in an hour. So, let's timebox this to 2 hours. After that, the proper estimate is: (whatever Robin thinks)

**Comment by robinmolen** [comment]
I cannot reproduce this issue. I've followed these steps:
- Create a new form
- Add a radio button field, that isn't required, with a option
- Add a textfield, with the option multiple values and **without** defining a default value
  - _(in the json this now indeed has the default value of `[null]`)_
- Add advanced logic to the textfield to only show if the previously defined radio has its value checked
- Save form and open it
- Go to the form step, keep the radio button unchecked, and go to the next step

**Comment by robinmolen** [comment]
I've made a PR that ensures that textfields always have a valid value (so `null` will be turned into `''`).

When a textfield (with the default value `null`) gets the `multiple values` property, the default value will change to `['']`.

**Comment by sergei-maertens** [comment]
Looking at https://github.com/open-formulieren/formio-builder/pull/184 I fail to see how this relates to the reported bug. Combined with the [comment](https://github.com/open-formulieren/open-forms/issues/4659#issuecomment-2376440711) saying it can't be reproduced, I suspect we're looking in the wrong place.

For any fix to be attempted, the issue must first be reproduced, then a failing regression test needs to be provided and finally a patch. The failing regression test now passing then proves the patch works, the regression test proves the problem is understood and will be prevented in the future.

**Comment by sergei-maertens** [comment]
This seems to be some sort of regression of #2213 - that one was limited to copying, but here it seems to apply even for new text fields dragged into the editor.

When fixing this, make sure to check all related issues (and issues related to #3128) for possible regressions.

**Comment by sergei-maertens** [comment]
I quickly checked email component, and it has the same issue - `defaultValue` is `null`.

**Comment by sergei-maertens** [comment]
Discussed in the office:

1. Let's write an e2e regression test with playwright, for reference: https://github.com/open-formulieren/open-forms/blob/master/src/openforms/forms/tests/e2e_tests/test_form_designer.py
2. the test should: drag and drop the textfield (and other affected types) component, click the save button (without additional changes), and save the form definition
3. then query the created FD and assert that the component `defaultValue` is equal to the empty string (as opposed to `None`)
4. for the patch, you can probably apply the same fixup like the `cosign.js`, see 1e8d6af3cc
