### ISSUE TITLE
Migrations hang on Azure Container Apps at the last few migration steps

### ISSUE THREAD

**Issue by admsallai** [open-formulieren/open-forms#4682]
### Product versie / Product version

latest, 2.7.6, 2.6.14

### Omschrijf het probleem / Describe the bug

When running Open-forms in Azure Container Apps, database migrations hangs. Container is then after some time terminated.

- version 2.6.14 migration hangs on 0009
- version 2.7.6 hangs on 0012
- latest version hangs on 0013

![Screenshot 2024-09-18 103240](https://github.com/user-attachments/assets/328a2dcb-c8d1-4987-828b-ef22456d57af)

### Stappen om te reproduceren / Steps to reproduce

1. Create Azure Container App
2. Create Azure PostgreSQL server and empty database
3. Setup correct environment variables for Container App to connect to PostgreSQL database
4. Run Container App (and look into console logs)

### Verwacht gedrag / Expected behavior

Finish the migration and run the same as when using docker-compose and test running the app locally.

### Screen resolution

None

### Device

None

### OS

None

**Comment by admsallai** [comment]
*UPDATE*

Apparently migrations require Redis to be configured properly before finishing. After Redis is configured, migrations finish without issues. 

It would be really helpful to have better logging about what is the issue, instead of just migrations hanging. Could help a lot when troubleshooting.

**Comment by joeribekker** [comment]
Alright, glad it got solved :)

The Docker-compose does mention it depends on Redis.
