### ISSUE TITLE
If an icon is added by the submitter, the request cannot be registered (StUF-ZDS registration)

### ISSUE THREAD

**Issue by vaszig** [open-formulieren/open-forms#4687]
### Product versie / Product version

latest

### Customer reference

Taiga RDL 210

### Omschrijf het probleem / Describe the bug

If an icon is inserted in a text field, the StUF-ZDS registration will not work.

### Verwacht gedrag / Expected behavior

This should be handled correctly and make sure that all the emojis are properly utf-8 encoded.

### Screen resolution

None

### Device

None

### OS

None

**Comment by sergei-maertens** [comment]
More information came to us and it seems like the service bus vendor doesn't properly support full utf-8 encoding.
