### ISSUE TITLE
Performance regression in Objects API (legacy) validation

### ISSUE THREAD

**Issue by sergei-maertens** [open-formulieren/open-forms#4695]
### Product versie / Product version

master / 70771b792a183889247dfbe914547d1986505012

### Omschrijf het probleem / Describe the bug

Noticed this while testing something completely different.

If you have the Objects API registration plugin configured with legacy document type URLs, then the backend will fetch *all* available document types in the Catalogi API to validate these URLs. This is really bad performance if there are multiple pages of document types.

Part of the waterfall in APM:

![image](https://github.com/user-attachments/assets/7dab30a8-04e8-4b12-b02e-d119f1c6e5dd)

Due to the pagination handling, these requests are performed sequentially too, compounding the problem. The total time of the request handling is 2 minutes in this particular instance.

Instead, the validation should be simplified:

1. Check that the document type resource URL has the same prefix as the configured Catalogi API in the selected Objects API group
2. Once that is okay, retrieve the document type (you can even use a `HEAD` request if API version is 1.1+ to further optimize) and check that the status code is `200`

With 3 potential fields, that should give at most 3 requests, but all of them tiny.

### Stappen om te reproduceren / Steps to reproduce

1. Add an Objects API registration plugin to a form
2. Configure a legacy Document type URL (not the Catalogue + Document type dropdown!)
3. Save the form
4. Observe the API calls made to the Catalogi API

### Verwacht gedrag / Expected behavior

Saving a form is performant again.

### Screen resolution

None

### Device

None

### OS

None

**Comment by sergei-maertens** [comment]
Please also check if older versions are affected by this!

**Comment by stevenbal** [comment]
@sergei-maertens this issue also occurs for 2.7.x, I'll make a PR for that as well
