### ISSUE TITLE
Accessibility improvements - Aria tags

### ISSUE THREAD

**Issue by robinmolen** [open-formulieren/open-forms#4717]
### Thema / Theme

Frontend

### Omschrijving / Description

This issue is related to #4622

This issue targets the aria improvements of the accessibility rapport:

- [x] 1.1.1
- [x] 4.1.2
- [x] 4.1.3

**Comment by robinmolen** [comment]
For 4.1.3: The loaders now use a translatable (the react-intl FormattedMessage) text alternative. The alert messages now have the role "alert"

**Comment by robinmolen** [comment]
1.1.1: The logo in the banner now has a more suitable text alternative

**Comment by sergei-maertens** [comment]
reopen for backend PR
