### ISSUE TITLE
Styling for delete button is broken

### ISSUE THREAD

**Issue by sergei-maertens** [open-formulieren/open-forms#4726]
### Product versie / Product version

master / 1a67d2acf48fb8e1d9b6fa9dbaadff09ee22f361

### Omschrijf het probleem / Describe the bug

![image](https://github.com/user-attachments/assets/62e516db-da40-4241-9c4e-856d75614810)

Possibly related to 531bb8bd711a1d07f8b05320403512de923a87d7

### Stappen om te reproduceren / Steps to reproduce

1. Go to form definitions change page
2. scroll down to see delete button

### Verwacht gedrag / Expected behavior

Button has full height

### Screen resolution

None

### Device

None

### OS

None

### Browser

Brave / Chromium

**Comment by robinmolen** [comment]
Seems like some broken django styling..? Will take a look tomorrow

**Comment by robinmolen** [comment]
This was due to some bootstrap styling applied to this page. It set the box-sizing to border-box, which calculates/renders height and padding differently.

I've added some styling that fixes this issue for the `deletelink` class
