### ISSUE TITLE
When configured with multidomain's via Keycloak, hide the domain options with is_current=False

### ISSUE THREAD

**Issue by alextreme** [open-formulieren/open-forms#4753]
### Thema / Theme

Admin

### Omschrijving / Description

Taiga RID 220

OF currently registers in multidomain.Domain with `is_current=False` if a Keycloak domain isn't active. @LaurensBurger and I suggest that we hide these Domains from the pulldown to avoid outdated keycloak domain options to be shown

**Comment by joeribekker** [comment]
Just delete the records from the database. If this is populatd in our SaaS deployment scripts, then those should be adjusted.
