### ISSUE TITLE
int as value of select component issue

### ISSUE THREAD

**Issue by LaurensBurger** [open-formulieren/open-forms#4772]
### Product versie / Product version

2.8.0

### Customer reference

DH 707

### Omschrijf het probleem / Describe the bug

Having an int as a value in a "select" component 

![image](https://github.com/user-attachments/assets/9ef5fc83-7218-4002-9350-7a35710fc0b2)

will trigger "AssertionError openforms.submissions.tasks.pdf.generate_submission_report" and fail to register the submission with 
`(Inzending 4118): PDF generatietaak mislukt`

sentry 375771 

### Screen resolution

None

### Device

None

### OS

None

**Comment by joeribekker** [comment]
@LaurensBurger the JSON doesn't seem to contain an int?

**Comment by LaurensBurger** [comment]
just because theres a number given as select option:
![image](https://github.com/user-attachments/assets/c63d09a4-f82e-448e-9f9e-35bfe134d587)

**Comment by LaurensBurger** [comment]
Addionally, i believe related: when a int is used as a value - this int will be shown in the overview step, instead of the label:
![image](https://github.com/user-attachments/assets/427cbcb0-4fb6-4dee-adf8-574ca9307ca8)
![image](https://github.com/user-attachments/assets/cb56b5e0-0aec-48e7-94a9-06f4b32d8099)
