### ISSUE TITLE
Windows users: Uploaded zip "The file is not a .zip"

### ISSUE THREAD

**Issue by LaurensBurger** [open-formulieren/open-forms#4773]
### Product versie / Product version

2.7.x - 2.8.x

### Customer reference

Dimpact 169

### Omschrijf het probleem / Describe the bug

#4658 solved the mime part, but now windows users always see:
![image](https://github.com/user-attachments/assets/4584aae7-3fb5-4838-9b09-e3553584238b)

**Comment by vaszig** [comment]
Tested in Browserstack for Windows 10, 11 and for the browsers Mozilla Firefox, Edge and Google Chrome. This was not able to be reproduced and has the expected behaviour (tested for the updated versions of OF after #4658 was merged and backported).

**Comment by vaszig** [comment]
Closing this issue for now according to the comment above (see issue comments on taiga as well).
