### ISSUE TITLE
.msg files cannot be uploaded

### ISSUE THREAD

**Issue by LaurensBurger** [open-formulieren/open-forms#4795]
### Product versie / Product version

tested on 2.7.x 2.8.x

### Customer reference

Utr 306

### Omschrijf het probleem / Describe the bug

Sentry: 313314 

When uploading a .msg file and after **navigating to the next step** the upload component shows a error: 
![image](https://github.com/user-attachments/assets/9430596f-ece6-44e4-bc75-0c7e0d49b894)

`ValidationError
{'data': {'bestandsupload': {0: {'type': [ErrorDetail(string="Het bestandstype kon niet bepaald worden. Controleer of de bestandsnaam met een extensie eindigt (bijvoorbeel '.pdf' of '.png').", code='blank')]}}}}`

Tested with multiple OSes, and multiple files and environments.

**Comment by joeribekker** [comment]
Resembles #4773
