### ISSUE TITLE
Als gemeente wil ik na het selecteren van een zaaktype, ook het product selecteren en meesturen met de inzending

### ISSUE THREAD

**Issue by joeribekker** [open-formulieren/open-forms#4796]
### Thema / Theme

Frontend

### Omschrijving / Description

In the ZGW API configuration for a form, allow configuration of the product. Available products can be retrieved from the Zaaktype (producten_en_diensten).

**Tasks**

* [x] When the zaaktype is configured on form-level, retrieve products and show them in the admin as dropdown
* [x] When the form is submitted, also submit the product in the Zaak-POST.

### Added value / Toegevoegde waarde

Allows a single zaaktype to be used with multiple products.

**Comment by robinmolen** [comment]
The product configuration input is populated by the products of the selected case type. If the case type has multiple versions, that the products are fetched from the version that is active at the moment of configuration.

**Comment by robinmolen** [comment]
Discused with Sergei, for the product select we want to show some information about the product (other then the product url). For testing purposes we need to use the `catalogi.preprod-rx-services` API to fetch case types with filled in "productenOfDiensten" (to get an accurate idea of what real products would look like). Currently this information isn't available
