### ISSUE TITLE
As developer I want to test the DigiD and e-Herkenning test steps

### ISSUE THREAD

**Issue by joeribekker** [open-formulieren/open-forms#481]
So the Logius tests won't find any obvious issues.

See the checklist: https://www.logius.nl/diensten/digid/documentatie/digid-checklist-testen

**Comment by SilviaAmAm** [comment]
We need to fix the following points:
- [ ] T6 When the login is cancelled, there should be a message in the form login page saying that the login was canceled.
- [ ] T13 While in a session, there should be a log-out button visible at all times
- [ ] T14 Session duration of max 15min

**Comment by joeribekker** [comment]
**T14**
Let's add a maximum session time on Shea's code for "users" (=forms) https://github.com/open-formulieren/open-forms/pull/514  I don't want to differentiate between digid forms and non-digid forms for now.

**T13**
This should probably be an API-endpoint to trigger logout at DigiD as well? However, logout doesn't make sense if not logged in with DigiD/e-Herkenning etc. Only show button if authenticated.
