### ISSUE TITLE
Daily digest always reports BRK issues, for all users/environements regardless of configuration.

### ISSUE THREAD

**Issue by LaurensBurger** [open-formulieren/open-forms#4821]
### Product versie / Product version

2.7.9+

### Customer reference

anyone with a addressNL component in a form

### Omschrijf het probleem / Describe the bug

```
De instellingen voor 'BRK client' zijn niet geldig (KVK endpoint is niet geconfigureerd). 
Component of plugins die hiervan gebruik maken zullen niet goed werken.
```
the configuration:
![image](https://github.com/user-attachments/assets/2c497836-7b6c-4356-9d31-14a5b1c92420)

While the check is very thorough - at least a BRK service should be set for this check to make sense for the users?

**Comment by joeribekker** [comment]
Refinement: AddressNL probably has no BRK-plugin enabled, still leading to this digest message. Digest BRK-check should ignore AddressNL components without the BRK plugin.
