### ISSUE TITLE
Summary title in email is visible even if no fields are sent

### ISSUE THREAD

**Issue by joeribekker** [open-formulieren/open-forms#4831]
### Product versie / Product version

2.8.1

### Omschrijf het probleem / Describe the bug

![image](https://github.com/user-attachments/assets/586a8c7f-a5da-429c-ba5d-9a30b290d329)

### Verwacht gedrag / Expected behavior

There should be no title.

### Screen resolution

None

### Device

None

### OS

None

**Comment by LaurensBurger** [comment]
`{% summary %}` should not be included in the confirmation email template in the first place?
