### ISSUE TITLE
As a user I only want to add Kvk validation to applicable components

### ISSUE THREAD

**Issue by shea-maykinmedia** [open-formulieren/open-forms#484]
Currently Kvk validation can be added to all components though I think it should only be available in the TextField and Numbers Components.

![Screenshot 2021-07-12 at 15 40 10](https://user-images.githubusercontent.com/60747362/125298489-78370200-e328-11eb-981a-7c54c4d6dc03.png)

**Comment by sergei-maertens** [comment]
Validators can be specified to apply only to certain component types, was implemented in an earlier release.
