### ISSUE TITLE
Cannot empty registration fields

### ISSUE THREAD

**Issue by LaurensBurger** [open-formulieren/open-forms#4853]
### Product versie / Product version

2.8.x

### Customer reference

DH: 719

### Omschrijf het probleem / Describe the bug

emptying fields that previously had data in them is not possible in certain registration options. 
These fields are not required.
email: 
![image](https://github.com/user-attachments/assets/82e05cb7-d484-4bb5-a20d-6e90ed47b159)
```json
[
    {
        "name": "registrationBackends.0.options.emailContentTemplateHtml",
        "code": "blank",
        "reason": "Dit veld mag niet leeg zijn."
    },
    {
        "name": "registrationBackends.0.options.emailContentTemplateText",
        "code": "blank",
        "reason": "Dit veld mag niet leeg zijn."
    }
]
```

objects: 
![image](https://github.com/user-attachments/assets/be1b9d71-3456-46d4-938d-9224eb378805)
```json
[
    {
        "name": "registrationBackends.0.options.productaanvraagType",
        "code": "blank",
        "reason": "Dit veld mag niet leeg zijn."
    },
    {
        "name": "registrationBackends.0.options.contentJson",
        "code": "blank",
        "reason": "Dit veld mag niet leeg zijn."
    },
    {
        "name": "registrationBackends.0.options.paymentStatusUpdateJson",
        "code": "blank",
        "reason": "Dit veld mag niet leeg zijn."
    }
]
```

The only workaround seems to be roming the registration entirely. which is quite frustrating with the v2 obejcts api where all variable mappings will be lost. 

### Screen resolution

None

### Device

None

### OS

None

**Comment by joeribekker** [comment]
Might be just `allow_blank=True` missing on the serialize.
