### ISSUE TITLE
oidc_org: RuntimeError Unknown attribute: employee_id

### ISSUE THREAD

**Issue by LaurensBurger** [open-formulieren/open-forms#4863]
### Product versie / Product version

2.7.9 + 2.8.1

### Customer reference

Utrecht: 313

### Omschrijf het probleem / Describe the bug

I cannot start a form as a employee selecting this option crashes the form:
sentry: 380096

### Screen resolution

None

### Device

None

### OS

None

**Comment by joeribekker** [comment]
I figure @sergei-maertens means it gets lots somewhere due to our work on machtigen?

Estimate: 1-2 days

**Comment by robinmolen** [comment]
Sergei's guess is correct. We currently handle cases for bsn and kvk (DigiD, Eherkenning), but employee login doesn't seem to be handled
