### ISSUE TITLE
Windows users cannot upload csv files

### ISSUE THREAD

**Issue by LaurensBurger** [open-formulieren/open-forms#4886]
### Product versie / Product version

2.8.1

### Customer reference

DH 721

### Omschrijf het probleem / Describe the bug

Like #4658 it seems windows users are also not able to upload CSV files: 
![image](https://github.com/user-attachments/assets/02b6adbb-3fff-44b1-bd9f-d7cf76d82ec0)

Not reproducible on linux

**Comment by sergei-maertens** [comment]
@LaurensBurger we're not able to reproduce this yet, @vaszig will add screenshots
