### ISSUE TITLE
As admin, I want to create an export of all submissions to compare them with registration systems

### ISSUE THREAD

**Issue by joeribekker** [open-formulieren/open-forms#4930]
The goal is to see if Open Forms submitted more or less forms then the number of cases created in backend systems. So, the admin wants to compare the submitted forms to the created cases in another system.

To this end, we'll expand on the existing statistics page, and add an export function.

**Tasks**

1. Add date-range filter to statistics: https://pypi.org/project/django-daterange-filterspec/
2. Add export bulk action: Export statistics
3. Upon export, generate the statistics details based on timeline logger events from succesfull submissions
4. Export the columns: public reference, form name, submission datetime

Note: I know the date in the existing view doesn't match the expectations. It now filters on "last submission" date. In a followup issue, this will be addressed.

**Comment by robinmolen** [comment]
What do we do about the `submissions removal limit` options? These can be set to "Submissions will be deleted", and completely remove the submission data. This would then result into less exportdata then expected.

(I think the successful submission log is preserved, so we will be able to count the amount of submissions that were successful)

I doubt we want to remove the "Submissions will be deleted" option. So do we just export all the submissions that are remaining? (This would than be different then the expected amount, and would also be different the amount we show in the statistics)

This could of course also happen with manual removal of submissions..

**Comment by sergei-maertens** [comment]
The suggested library is not maintained and doesn't appear to test/support Python > 3.10 and Django > 4.0, so we will not be adding this dependency.
