### ISSUE TITLE
Cosign information missing in StUF ZDS

### ISSUE THREAD

**Issue by joeribekker** [open-formulieren/open-forms#4946]
### Product versie / Product version

2.7?

### Customer reference

Mail Utrecht

### Omschrijf het probleem / Describe the bug

Cosign info is added to the objects API but not in StUF ZDS

### Screen resolution

None

### Device

None

### OS

None

**Comment by sergei-maertens** [comment]
Duplicat of #4762, will be available in Open Forms 3.0
