### ISSUE TITLE
Betaalstatus doorzetten naar registratiebackend

### ISSUE THREAD

**Issue by joeribekker** [open-formulieren/open-forms#502]
Afgesplitst van #273 

Nader uit te werken:

- [x] De betaalstatus moet via de verschillende registratiebackends doorvloeien.
- [x] Registratiebackend StUF-ZDS
- [x] ZGW APIs: `betalingsindicatie=geheel` en `betaaldatum` zetten
- [x] Demo/etc (geen actie maar niet stuk)

Email (zie #264)

**Comment by Bartvaderkin** [comment]
Dit valt ook onder #317
