### ISSUE TITLE
As user I want to see the zaaknumber on the confirmation page

### ISSUE THREAD

**Issue by joeribekker** [open-formulieren/open-forms#510]
Builds on top of #243 

If this is not possible within X time, then the zaaknumner should at least be in the confirmation mail (note that the mail can only be sent if this registratration backend number is known).

Fixed by open-formulieren/open-forms-sdk#62

**Comment by Bartvaderkin** [comment]
Discussed with Joeri: we add a polling call to the confirmation page that starts just after the PDF polling completed. 

If the zaak is registered within 3 seconds it returns and prints the Submission.registration_id, else we generate and display an internal reference number (with a note stating it is temporary).

**Comment by sergei-maertens** [comment]
Implemented in https://github.com/open-formulieren/open-forms-sdk/pull/62
