### ISSUE TITLE
Can't create form definitions with Date fields

### ISSUE THREAD

**Issue by SilviaAmAm** [open-formulieren/open-forms#513]
How to reproduce:

In the admin, create a new form definition. In the builder, add a Date field. Then, save the form definition.
This gives the following error:

`FormDefinition with ID 1 appears to contain snake_case keys in its formiojs configuration. This is known to cause issues with the prefill module`

**Comment by shea-maykinmedia** [comment]
For reference this is caused because of the configuration coming from FormIO https://github.com/formio/formio.js/issues/4254 

I'll hopefully have a fix for this soon though.
