### ISSUE TITLE
KvK API Search got deprecated, we need to switch to KvK API Zoeken...

### ISSUE THREAD

**Issue by joeribekker** [open-formulieren/open-forms#529]
See: https://developers.kvk.nl/nl/apis/zoeken

**Comment by Bartvaderkin** [comment]
Note this API has a lot less information then the old one:

It is easy to see in the diff of the response mock: https://github.com/open-formulieren/open-forms/pull/543/files#diff-96760b963f93e9dad9c81bdfaa5b4b1e04f2d1a8bb1f339a3ce5642cd56a39d3
