### ISSUE TITLE
Implement logging out functionality

### ISSUE THREAD

**Issue by SilviaAmAm** [open-formulieren/open-forms#532]
- [x]  Backend: an endpoint that when called deletes the current session. The call should be `DELETE /api/v1/authentication/session`. There should thus be an `api` package in the `authentication` package/module.
- [x] Frontend: a logout button that is visible from within every form, if the user is authenticated. Clicking this button should call the endpoint mentioned above. The button should be under the line with previous/next page. https://github.com/open-formulieren/open-forms-sdk/pull/49

**Comment by sergei-maertens** [comment]
SDK PR open-formulieren/open-forms-sdk#49 was merged
