### ISSUE TITLE
Refactor styling of backend registration options forms

### ISSUE THREAD

**Issue by shea-maykinmedia** [open-formulieren/open-forms#558]
Related to #547 

For that ticket we are using this library https://github.com/rjsf-team/react-jsonschema-form to show the form.

In order to style the forms from the project to look like the Django admin we are overriding some css styling in `_app_overrides.scss` however a more optimal solution would be to use our own built components for this.

We should see if or how this could be accomplished since future versions of Django may have different styling in the admin screens and this could make these forms look out of place.

**Comment by sergei-maertens** [comment]
Done a while ago.
