### ISSUE TITLE
Als gemeente wil ik dat burgers kunnen inloggen op een formulier met OpenID-connect

### ISSUE THREAD

**Issue by joeribekker** [open-formulieren/open-forms#565]
Naast DigiD, eHerkenning en eIDAS moet er ook ingelogd kunnen worden middels OpenID-connect.

Via OpenID-connect kan worden doorverbonden naar DigiD (Anoigo) of AzureAD bijvoorbeeld. Er komen bepaalde claims/attributen mee waaronder het BSN, KvK-nummer of bepaalde rol. Deze attributen moeten gemapped kunnen worden op een slimme manier, bijvoorbeeld om de claim "digid_bsn" op `Submission.bsn` te zetten.

**Comment by sergei-maertens** [comment]
Removing this one from the project board until upstream dependencies are sorted out and we can properly test this.

**Comment by stevenbal** [comment]
Ik zal docker-compose.yml uitbreiden met een container voor Keycloak en fixtures zodat dit lokaal te testen is

**Comment by stevenbal** [comment]
Development setup toegevoegd in https://github.com/open-formulieren/open-forms/pull/592/commits/260202d7eceae19de289ecedbeac4866c23c6c05
