### ISSUE TITLE
Suwinet prefill

### ISSUE THREAD

**Issue by VerbeekIT** [open-formulieren/open-forms#586]
Als burger van de gemeente wil ik graag dat mijn aanvraagformulieren zoveel mogelijk voor ingevuld worden. Voor het ophalen van data bij de Belastingdienst of bij Suwinet, moet ik hiervoor een juist subOIN meegeven met de serviceaanroep. De aangeroepen servive kan dan controleren of dit verzoek om uitwisseling van data gehonoreerd mag worden. 

There are many different APIs in Suwinet:

* Bijstandsregelingen
* BRPDossierPersoonGSD
* DUODossierPersoonGSD
* DUODossierStudiefinancieringGSD
* GSDDossierReintegratie
* IBVerwijsindex
* KadasterDossierGSD
* RDWDossierDigitaleDiensten
* RDWDossierGSD
* SVBDossierPersoonGSD
* UWVDossierAanvraagUitkeringStatusGSD
* UWVDossierInkomstenGSDDigitaleDiensten
* UWVDossierInkomstenGSD
* UWVDossierQuotumArbeidsbeperktenGSD
* UWVDossierWerknemersverzekeringenGSDDigitaleDiensten
* UWVDossierWerknemersverzekeringenGSD
* UWVWbDossierPersoonGSD

The responses can contain many nested keys. For example, a person can have multiple salaries + benefits (so the responses would correspond to "arrays of objects" if turned into JSON).

This is problematic because the form designer does not know in advance how much data will come back.

To discuss:
- How will the form designer configure how a component will be prefilled? 
- How are we going to deal with "prefilling repeating groups"?
- How do we deal with the many APIs of Suwinet? 
- Do we need to do extra processing of the data? For example, convenience method to calculate the total income or something.

**Comment by joeribekker** [comment]
Refinement: For now, we will just get the data exposed as used-defined variable in Open Forms. You can select "Suwinet" as Prefill plugin. And as attribute, you can select an operation (one of the 16 SOAP-services, which all have 1 operation).

![Schermafbeelding 2023-07-13 110049](https://github.com/open-formulieren/open-forms/assets/96970/82e56d05-6670-4e4e-880d-3121de2d67a2)

...that can be used in Content-components:

![Schermafbeelding 2023-07-13 110234](https://github.com/open-formulieren/open-forms/assets/96970/13d39541-b60a-4942-936a-82e8e128b348)

The SOAP-calls require 2 attributes: BSN and period. The BSN can be obtained from DigiD but the date is a different matter. I think it's unavoidable to create "settings" for prefill attributes but maybe these settings can be determined during the form... so it takes variables again.

Let's postponed this last issue and start with:

* [ ] Add Suwinet plugin
* [ ] Create 16 SOAP-services and expose them as "plugin attribute"
* [ ] Objectify the SOAP-responses so they are accessible as JSON-path in the variable (ie. `inkomens.0.waarde`)
* [ ] Determine the datatype automatically based on the selected attribute (probably they are all lists or objects).

**Comment by joeribekker** [comment]
Refinement: We scoped this ticket to only work with a few of the Suwinet (DKD) requests that can work as prefill, meaning, it can get the information based on the BSN provided by a DigiD login. Specifically, we target the income-related calls.

The calls that require (so, when not optional) additional inputs (start date, end date, postal code, etc.) are out of scope. These could be tackled later but require an additional mechanism that doesn't fit prefilling. Rather, it requires "if all inputs are available" then perform the call.
