### ISSUE TITLE
As form designer I want the default layout options from Form.io

### ISSUE THREAD

**Issue by joeribekker** [open-formulieren/open-forms#615]
For example, people cannot add multiple fields next to eachother due to table/column -compononent missing

**Comment by sergei-maertens** [comment]
This will have serious impact on the (mobile) styling so tread carefully.

I also seem to remember that accessibility guidelines advise against this in general.

**Comment by shea-maykinmedia** [comment]
Just fyi, this ticket adds the column component https://github.com/open-formulieren/open-forms/issues/673 which has a pull request open at the moment.

**Comment by joeribekker** [comment]
Noted, but streetname and streetnumber are typically in column style format on desktop. On mobile they can be below eachother ofcourse.

**Comment by sergei-maertens** [comment]
Columns were added a long time, haven't seen a demand for other layout components.
