### ISSUE TITLE
Refactor fixed list of appointment plugins to dynamic plugin list

### ISSUE THREAD

**Issue by joeribekker** [open-formulieren/open-forms#623]
`openforms.appointments.models.py:9`

```
class AppointmentsConfig(SingletonModel):
    config_path = models.CharField(
        _("config path"),
        choices=AppointmentsConfigPaths,
        max_length=255,
        blank=True,
    )
```

Why is this a fixed list of plugins? We have dynamic choices enumerated from the base plugin registry?

**Comment by shea-maykinmedia** [comment]
This field needs to refer to the config singleton model that we want to use, currently either `JccConfig` or `QmaticConfig`.  Therefore we made a DjangoChoices class that contains the path to the model (so we can use `import_string`) and the human readable value which is then displayed to the user in the admin screen.

**Comment by sergei-maertens** [comment]
The field should consume a registry of plugins for choices rather than having a statically defined choices list, similar to all the other modules that have multiple backends/plugins to achieve the same functionality.
