### ISSUE TITLE
Handle import/export version compatibility of forms and examples

### ISSUE THREAD

**Issue by Bartvaderkin** [open-formulieren/open-forms#629]
The import functionality doesn't handle exported forms from other versions of the application:

- import/export between deployments that run different versions of the code
- examples in the documentation and manual can go stale (both in code as in downloadable .zip files)

Importing an old export will currently crash and raise a KeyError.

**Comment by joeribekker** [comment]
Hmm, ok, that's unfortunate. I'll fix them
