### ISSUE TITLE
Upgrading to setuptools >= 58 breaks the build

### ISSUE THREAD

**Issue by sergei-maertens** [open-formulieren/open-forms#632]
See also https://github.com/dmeranda/demjson/issues/40 and https://setuptools.readthedocs.io/en/latest/history.html#v58-0-0

django-yubin depends on pyzmail36, which is a fork of pyzmail that does install on python 3.6+ (supposedly).

This relies on the `use_2to3` keyword (https://github.com/ascoderu/pyzmail/blob/master/pyzmail/setup.py#L104) to convert the Python 2 code to Python 3 _at package installation time_ ( :exploding_head: ).

Setuptools 58 removed this parameter, so now we get Python 2 code in our build which breaks things.

For the time being, I'm pinning setuptools to < 58.0 in CI etc. and keeping track of the issue here.

**Comment by nielstron** [comment]
You might want to switch to [demjson3](https://GitHub.com/nielstron/demjson3) in case you really only want to support Python 3 anymore.

**Comment by sergei-maertens** [comment]
Fixed via 3e9a8ea4d8b533641a1a95c38159ba66a30c3d5f, django-yubin dropped pyzmail36
