### ISSUE TITLE
As user I want to explicitely approve the use of my submitted data.

### ISSUE THREAD

**Issue by joeribekker** [open-formulieren/open-forms#642]
Part of #323 

The summary page should include something like:

![image](https://user-images.githubusercontent.com/96970/124611717-fea79b80-de71-11eb-8792-631979d33ba0.png)

I'll describe what needs to be done here:

- [x] Add option to show this checkbox on the summary page, in the global config
- [x] Add non-required field in te global config model: `privacy_policy_link`
- [x] Add required field in te global config model:  `privacy_policy_label` (default should be: "Ja, ik heb kennis genomen van het {{ privacybeleid }} en geef uitdrukkelijk toestemming voor het verwerken van de door mij opgegeven gegevens.")
- [x] The summary page shows a checkbox like the image above (but can probably be a one-liner) where the label is taken from the `privacy_policy_label`.
- [x] The word between curly braces can be replaced with a hyperlink to the `privacy_policy_link` (to keep it somewhat in line with other variables used in OF). If no link, then just remove the curly braces.
- [x] Only allow submission if the checkbox is checked.

**Comment by sergei-maertens** [comment]
> Add non-required field in te global config model: privacy_policy_link

Is this different from the privacy policy configured through environment variables/django settings?

**Comment by SilviaAmAm** [comment]
I think that the setting `PRIVACY_POLICY_URL` is currently being used for both the privacy policy to generate the metadata/service catalog of eHerkenning and to have in the footer of the openforms template. My understanding is that after this ticket, the latter will be replaced with the value configurable from these new settings. But @joeribekker should confirm :stuck_out_tongue:

**Comment by joeribekker** [comment]
Ah, it's an env variable. I thought it was admin configurable already.

Please make it admin configurable as you described @SilviaAmAm I suspect this might change in their CMS sometimes and I don't want a reply for that.

**Comment by sergei-maertens** [comment]
I think that introduces some complexities with the digid/eherkenning setting(s) that now have a dynamic aspect. @SilviaAmAm - maybe we should change the digid/eherkenning package to have a single setting pointing to a callable (function) that outputs the settings, which defaults to the current static Django setting approach.

In Open Forms, we can then use a custom function that pulls parts of the configuration from the config model(s).

**Comment by joeribekker** [comment]
Or, allow the management command to generate it accept a parameter that points to the privacy url (i think thats the only setting that can change on an active digid connection.

**Comment by sergei-maertens** [comment]
that can't change Django/DigiD settings though

**Comment by joeribekker** [comment]
True
