### ISSUE TITLE
Implement submission status endpoint

### ISSUE THREAD

**Issue by sergei-maertens** [open-formulieren/open-forms#651]
- [x] Auth relies on submission permission (~~session based~~ timestamped HMAC based)
- [x] ~~Remove session-cleanup from `_complete` endpoint (we need it for status endpoint checks)~~
- [x] Return root ID status: pending/errored/completed (see https://github.com/open-formulieren/open-forms/pull/617#discussion_r706061018)
- [x] Return contextual information
    - [x] (appointment) error message, if relevant
    - [x] generated PDF report download link
    - [x] ~~make payment endpoints token-based rather than session based & include links~~ not needed at this point
    - [x] confirmation page content (from template)
- [ ] Implement SDK as client/caller

**Comment by joeribekker** [comment]
Copying my nice table here from earlier PR review:

Why don't we keep state cleaner:

`status`
* done (for all ready and exception states)
* in progress (for other states)

`result` (when `status` is *done*)
* retry (to have the user retry the submission)
* fail (submission failed, no point to retry the same submission)
* success (submission was received and all mandatory checks succeeded)

And, remove `processing_aborted`.

The combinations are then pretty clear:

`status` | `result` | action
--- | --- | ---
in progress | - | show spinner to user
done | retry | redirect user back to summary page, showing `error_message`
done | fail | redirect user back to start of the form, showing `error_message`
done | success | redirect/show user the confirmation page, displaying content/report/payment link
