### ISSUE TITLE
Admin login via OIDC not compatible with 2FA

### ISSUE THREAD

**Issue by stevenbal** [open-formulieren/open-forms#693]
If I try to login to the admin with OpenID Connect (while 2FA is enabled for the admin), I am simply redirect to the same login screen, making the login process impossible in this case

![image](https://user-images.githubusercontent.com/29249171/134180191-f5852707-681e-4f4e-8f49-8a43a10cf027.png)

**Comment by sergei-maertens** [comment]
The documentation advises disabling 2FA when using OID. I'd say this is a matter of correctly configuring your instances.

**Comment by joeribekker** [comment]
Agree with Sergei.
