### ISSUE TITLE
Appointment dropdowns don't display persisted data correctly

### ISSUE THREAD

**Issue by sergei-maertens** [open-formulieren/open-forms#700]
Currently when you submit the form (step) for an appointment, and later return to this step, the values are not correctly shown.

The cause for this is because the `Select` component mutates the data before submitting (hooking into the `beforeSubmit` method call). There, the value (`<option value="foo" />`) is converted into an object for the product and location and submitted as nested object to the backend.

This is required because the summary page should display the proper labels instead of the raw underlying values, and the data is encapsulated this way since we can't access non-existent Formio instances (these are only available on the actual form steps).

Possible ways to solve this:

* update React state on submit with the display values so that can be re-used later
* change dropdowns to be `values` dropdowns and rely on the default behaviour. This requires the backend to inject the appointment config and make API calls, which degrades performance of the logic check call (!)
* ... ?

See also #698 which relates to this

**Comment by SilviaAmAm** [comment]
After https://github.com/open-formulieren/open-forms-sdk/pull/83 the values in the dropdowns are displayed properly, but there is still an extra `<option></option>` which gets added.

**Comment by sergei-maertens** [comment]
Tested and demoed last Thursday, good enough for now at least.
