### ISSUE TITLE
IntegrityError -  null value in column "availability_strategy"

### ISSUE THREAD

**Issue by sjoerdie** [open-formulieren/open-forms#739]
Reported by: Township Horst aan de Maas and Venray.

User runs in to: https://github.com/open-formulieren/open-forms/issues/720

Used browser console to find out what was wrong. After correcting mistakes it results in to error 500:
null value in column "availability_strategy" violates not-null constraint
DETAIL:  Failing row contains (42, 0, 18, 34, e3d652dd-6534-4350-a26c-085c33f6744a, null, f, , , ).

Please resolve ASAP, thank you.

**Comment by sjoerdie** [comment]
Removed collumn availability_strategy from table forms_formstep for all databases.

**Comment by sergei-maertens** [comment]
For posterity - when squashing the migrations an operation was forgotten to delete a column which is no longer used. This should only affect environments that have been deployed between sprint-6 and sprint-7 tags.
