### ISSUE TITLE
Re-test "Submission completion hangs on failing StUF registration and doesn't return PDF link"

### ISSUE THREAD

**Issue by Bartvaderkin** [open-formulieren/open-forms#769]
I have a form with a StUF registration backend that has an undetermined issue that makes it fail registration and enter a retry loop.

This should be invisible to the user but somehow also blocks the status call from returning the PDF link to the browser; all I get is `status: in_progess` forever until the connection gets throttled.

This happened on Noordoostpolder's test environment: 

My form: https://noordoostpolder.test.open-formulieren.nl/backend-test-form-stuf/  ( https://noordoostpolder.test.open-formulieren.nl/admin/forms/form/13/change/ )

My submission has a ton of retry logs: https://noordoostpolder.test.open-formulieren.nl/admin/submissions/submission/99/change/

If you look in Sentry you see it hangs: 

- https://sentry.maykinmedia.nl/maykin-media/open-forms/?environment=noordoostpolder-test
- https://sentry.maykinmedia.nl/maykin-media/open-forms/issues/292180/?environment=noordoostpolder-test
- https://sentry.maykinmedia.nl/maykin-media/open-forms/issues/292178/?environment=noordoostpolder-test
- (it also takes down the email task: https://sentry.maykinmedia.nl/maykin-media/open-forms/issues/290959/?environment=noordoostpolder-test)

So there are multiple issues here, this issue is about how the async system breaks:

- [x] Stuf registation fails
- [x] The failing registration somehow blocks the PDF link for being generated or delivered
- [x] Email queue fails after this registration starts failing

**Comment by Bartvaderkin** [comment]
Here is another submission that took forever to get processed: https://noordoostpolder.test.open-formulieren.nl/admin/submissions/submission/103/change/ (note the long delays between log records)

**Comment by joeribekker** [comment]
Should be fixed in #784

**Comment by sergei-maertens** [comment]
@Bartvaderkin since you were most familiar with this one, can you please re-test that the fixes from sprint 8 didn't break this again?

**Comment by Bartvaderkin** [comment]
Looks good: 

https://noordoostpolder.test.open-formulieren.nl/admin/submissions/submission/273/change/

https://noordoostpolder.test.open-formulieren.nl/admin/django_yubin/message/49/change/
