### ISSUE TITLE
FormStep can be submitted despite failing validation

### ISSUE THREAD

**Issue by sjoerdie** [open-formulieren/open-forms#778]
Raised by Maykin:

Form: https://open-forms.test.maykin.opengem.nl/test-logica/
Logic:
![issue65](https://user-images.githubusercontent.com/85243022/136205955-673e4ce8-640c-4743-bf10-82cce0679078.png)

Fill in today and click next step quickly, it will just continue.
![issue65_2](https://user-images.githubusercontent.com/85243022/136206098-de62f7a0-cabb-4600-bcac-45dcdc91cd60.png)

Repeat, just wat a few seconds, step will be blocked. 

![issue65_3](https://user-images.githubusercontent.com/85243022/136206156-bcb011ab-7c44-403a-b029-156779d7f072.png)

I noticed this for other logic steps also and you dont have to be that quick about it.

**Comment by stevenbal** [comment]
This also occurs for regular validation/required fields, probably has to do with the `_check_logic` calls?
![TRERc2v18E](https://user-images.githubusercontent.com/29249171/136799433-bf6fb31f-0f8d-4227-8c0b-ef7f8f941ba8.gif)

**Comment by stevenbal** [comment]
Seems like the `canSubmit` attribute ([here](https://github.com/open-formulieren/open-forms-sdk/blob/main/src/components/FormStep.js#L80)) is always `true` after doing the form logic check

**Comment by shea-maykinmedia** [comment]
Actually I was wrong about what I said before.  This code is calling the SubmissionStep endpoint, not the Submission endpoint, and so it's calling this serializer https://github.com/open-formulieren/open-forms/blob/master/src/openforms/submissions/models.py#L489-L491 which then refers to this property https://github.com/open-formulieren/open-forms/blob/master/src/openforms/submissions/models.py#L489-L491

**Comment by sergei-maertens** [comment]
This was fixed in #762 (ac314a0b9789574cbf2bb6f9913be519db885926) and https://github.com/open-formulieren/open-forms-sdk/pull/95
