### ISSUE TITLE
Logic for if add AND

### ISSUE THREAD

**Issue by sjoerdie** [open-formulieren/open-forms#782]
Raised by municipality Utrecht:

Ability to use logic for multiple fields: If X has value Z AND Y has value X then ACTION. 

Je kunt nu logica maken op basis van één veld/vraag.
Graag mogelijk maken dat je logica op basis van meerdere vragen kan maken.
Bijvoorbeeld:
Heeft u een partner ja/nee
Heeft u kinderen ja/nee
Vragen laten verschijnen in de diverse situaties zoals Partner ja en kinderen ja
Partner ja en kinderen nee
Partner nee en kinderen ja
Partner nee en kinderen nee

**Comment by sergei-maertens** [comment]
Possible through complex logic rules.
