### ISSUE TITLE
As admin, I want to start a BPMN process in Camunda

### ISSUE THREAD

**Issue by joeribekker** [open-formulieren/open-forms#81]
Building on #79 we should support the sending the submission to kick off a Camunda process.

> For that purpose, often form fields are also [re-combined into a single derived process variable](https://bitbucket.org/maykinmedia/open-forms/src/ad823f9a293552cbeda6a98568cec12c60b15742/src/openforms/formbuilder/models/config.py#lines-52). This also means that often not all the `form.cleaned_data` should be passed into the process as process variables.
>
> In short - you need a way to serialize the data for further processing, and you want it in a way that makes you compliant with all privacy-oriented legislation.

**Comment by sergei-maertens** [comment]
#326 duplicated this and is tracking the state.
