### ISSUE TITLE
Logic not working for "field set components"

### ISSUE THREAD

**Issue by sjoerdie** [open-formulieren/open-forms#810]
Raised by municipality Riddeliemers:

Form: https://open-forms.test.maykin.opengem.nl/issue-1/
Logic:
![issue1](https://user-images.githubusercontent.com/85243022/137335574-e3dd7cba-a2b3-4d4d-a660-8b70ac1aecbe.png)

Select "ja" should make the component unhidden. However it does not work.

**Comment by SilviaAmAm** [comment]
This is related to https://github.com/open-formulieren/open-forms/issues/824 (see comment https://github.com/open-formulieren/open-forms/issues/824#issuecomment-952709228)

**Comment by sjoerdie** [comment]
See taiga issue https://taiga.maykinmedia.nl/project/open-formulieren-deelnemende-gemeenten/issue/115

"Het lijkt erop dat ik geen logica kan loslaten op fieldsets. Klopt dat?"

Not sure if this is related?

**Comment by SilviaAmAm** [comment]
I think it is related and was fixed by https://github.com/open-formulieren/open-forms/pull/859

**Comment by joeribekker** [comment]
Agree this seems fixed.
