### ISSUE TITLE
Menu displays underneath select boxes in mobile view

### ISSUE THREAD

**Issue by stevenbal** [open-formulieren/open-forms#872]
Noticed that the form menu (when expanded), is displayed underneath select boxes on mobile devices

![2XN1JreIwx](https://user-images.githubusercontent.com/29249171/139815364-a01f0156-273b-4a81-8c83-77c5733d9a26.gif)

**Comment by sergei-maertens** [comment]
Ah the fun of z-index fighting... thanks for the report!

**Comment by sergei-maertens** [comment]
Fixed via #2053
