### ISSUE TITLE
Toevoegen bijlage werkt niet meer (in Chrome)

### ISSUE THREAD

**Issue by alextreme** [open-formulieren/open-forms#877]
N.a.v. Taiga issue 126 (zie issue voor voorbeeldformulier):

Bij deze doorlopen, ik kon zonder problemen in Firefox een afbeelding-bijlage uploaden en weer downloaden, echter dit lijkt inderdaad niet (meer) te werken in Chrome daar is het stuk. Het is dus waarschijnlijk een cross-browser probleem.

De afbeelding wordt wel geupload en is daarna te downloaden als ik in developer tools de response van de OpenForms API bekijk, echter de frontend registreert in Chrome niet dat de afbeelding is ingeladen (ongeacht of je een bestand kiest of naar de upload-widget sleept). Je ziet wel iets korts flitsen maar de widget blijft leeg:

**Comment by Bartvaderkin** [comment]
Ik kan dit in Chrome reproduceren als ik het test op online server, want gek genoeg werkt het vanaf localhost wel.

Bijv. https://open-forms.test.maykin.opengem.nl/bart-test-upload/

**Comment by Bartvaderkin** [comment]
I tried pinning when or why this happens but I still cannot reliably reproduce this. I tested this again in Chrome and Firefox, in regular and in privacy mode, and with or without reloads.

When it does happen I see the upload request going out to the backend, and the response looks normal and the included URL works when I check it, but somehow the widget never requests the image for display (or doesn't displays the filename and the red X for non-image file fields).

**Comment by joeribekker** [comment]
Another report in Taiga 216

**Comment by alextreme** [comment]
Gereproduceerd in Den Haag Taiga #232 - Error: Javascript error: Uncaught (in promise) TypeError: i.map is not a function (utils.js line 99)

Details voor het reproduceren zijn toegevoegd aan de taiga issue.

**Comment by joeribekker** [comment]
Taiga 192 (check size):

Bestandsgrootte controle werkt niet goed. Nginx config moet waarschijnlijk iets mee gebeuren en per email versturen (registratie backend) van grote bestanden.

**Comment by alextreme** [comment]
Ter aanvulling, Taiga #232 is wel iets anders: zoals daarin gereproduceerd zorgt het toevoegen van een bestand in een formulier ervoor dat de bevestigingspagina altijd tot een Javascript error leidt. Het is dus anders dan de oorspronkelijke issue, waarin dit alleen een probleem was in Chrome.

**Comment by joeribekker** [comment]
Ik gebruik dit als een soort kapstok issue voor file upload.

**Comment by Bartvaderkin** [comment]
Some issues:

- [ ] Original implementation used a `image` property in the component with an object to hold some custom form settings. It happens that Formio expects a boolean `image` so this collides. Solution: namespace all custom component properties in a `of` namespace (eg: `of.image.resize.apply`, `of.image.resize.width` etc)
- [ ] There is a problem with immutabe React state data leaking into where Formio expects mutable. An error `"TypeError: can't define array index property past the end of an array with non-writable length"` gets raised here: https://github.com/formio/formio.js/blob/2eee0e7ae0282a6fd1942dec4c0e73d2d248b7f2/src/components/file/File.js#L758
- [ ] .. ?

**Comment by Bartvaderkin** [comment]
- [ ] Taiga 126 (original breakage) fixed (1-3)
- [ ] Taiga 216 (copy of original breakage) fixed (1-3)
- [ ] Taiga 215 (file type filter) fixed (FIX 1)
- [ ] Taiga 232 (i.map JS error) (FIX 3)
- [ ] Taiga 192 (file size)

**Comment by sergei-maertens** [comment]
Last bullet is moved to separate ticket, closing this one.
