### ISSUE TITLE
 PDF weergave is nog steeds niet goed

### ISSUE THREAD

**Issue by alextreme** [open-formulieren/open-forms#879]
Taiga issue 122:

Zie bijlage en voorbeeldformulier in Taiga issue

- [x] Alle woorden in een veldnaam beginnen met een hoofdletter

- [x] Alle antwoorden beginnen met een kleine letter.

- [x] Onder aan de PDF staan 2 koppen. Wat is daar de functie van?
Kunnen we deze tekst aanpassen en of verwijderen?

Hulp nodig?
Contactgegevens

https://taiga.maykinmedia.nl/media/attachments/e/e/a/1/a3de3bb9b3b00bcf2a00ef0bae8b72e0b1e587eaabf3b1b25e2bf8f3293c/pdf-weergave.jpg#_taiga-refresh=issue:14117

**Comment by Bartvaderkin** [comment]
- Ik heb een aanpassing gedaan voor "Alle woorden in een veldnaam beginnen met een hoofdletter"

- Wat betreft "Alle antwoorden beginnen met een kleine letter." ik heb even in hun admin gekeken en wat je ziet in de screenshot zijn de *waardes* die ze hebben opgegeven in die widgets (en niet de *labels*). 

- Die twee koppen hebben geen helemaal geen content in de template dus ik denk dat die uit een oud ontwerp komen. Ik haal ze voor nu weg totdat we er content voor hebben.
