### ISSUE TITLE
Sentry admin - ValidationError: Er bestaat al een Formulier definitie met eenzelfde URL-deel.

### ISSUE THREAD

**Issue by alextreme** [open-formulieren/open-forms#885]
Sentry error wat structureel optreedt (426 keer), zou in mijn ogen netjes afgevangen moeten worden. Onduidelijk wat voor impact dit heeft op formulier-beheerders:

https://sentry.maykinmedia.nl/maykin-media/open-forms/issues/291000/

**Comment by joeribekker** [comment]
Deze is op verschillende manieren verbeterd en de eindgebruiker ontvangt hier een melding van. Ik sluit daarom dit ticket.
