### ISSUE TITLE
Sentry celery - Received unregistered task of type KeyError('openforms.submissions.tasks.cleanup_on_completion_results').

### ISSUE THREAD

**Issue by alextreme** [open-formulieren/open-forms#886]
https://sentry.maykinmedia.nl/maykin-media/open-forms/issues/291000/events/0c6e0c4c89f74e878586387fa025825f/

Received unregistered task of type KeyError('openforms.submissions.tasks.cleanup_on_completion_results').
The message has been ignored and discarded.

Did you remember to import the module containing this task?
Or maybe you're using relative imports?

Please see
http://docs.celeryq.org/en/latest/internals/protocol.html
for more information.

The full contents of the message body was:
b'[[], {}, {"callbacks": null, "errbacks": null, "chain": null, "chord": null}]' (77b)

**Comment by sergei-maertens** [comment]
Might be because of an import in the package `__init__.py`

**Comment by Bartvaderkin** [comment]
I think the link to the Sentry event is a mistake and should be https://sentry.maykinmedia.nl/maykin-media/open-forms/issues/291494/

**Comment by alextreme** [comment]
Yes you're correct Bart, sorry!

**Comment by Bartvaderkin** [comment]
Maybe this is caused because we re-import the tasks in the `__init__.py`? When I inspect the worker is has different paths then in the BEAT config, but it is only a problem for this task.

![celery-tasks](https://user-images.githubusercontent.com/54805673/141315306-ced8d77e-180c-4993-a592-8bbab2bd471a.png)

**Comment by Bartvaderkin** [comment]
After discussion with @sergei-maertens I expanded the BeatConfigTest to check for use of full paths in the beat configuration instead of to re-imports. 

See the failing build of the first commit in the PR.
