### ISSUE TITLE
Translate "remaining"

### ISSUE THREAD

**Issue by sjoerdie** [open-formulieren/open-forms#890]
Observations so far (SDK):

* Text field, remaining characters counter says "remaining"

![remaining](https://user-images.githubusercontent.com/85243022/140909237-c2e219a1-6106-43a4-ab31-012100219718.JPG)

See: https://github.com/formio/formio.js/blob/4.11.x/src/components/_classes/input/Input.js#L156

I tried, but couldn't fix it.

**Comment by joeribekker** [comment]
Opgelost hier: https://github.com/open-formulieren/open-forms/pull/1079/files#diff-c8f1839bf4cd7d4167b7b5266290cdba5137719bf6dcea41f24c3c263002a39cR215
