### ISSUE TITLE
Form logic not working for selectBoxes

### ISSUE THREAD

**Issue by sjoerdie** [open-formulieren/open-forms#891]
Raised by municipality LV - Taiga issue 132

This does not work:

![logic_fail_again](https://user-images.githubusercontent.com/85243022/140933659-93e22de6-0d59-47dc-a0e0-e1e598d60484.png)

When using native logic in the "Bestandupload field", it does work. But our customer wants to use it cross form definitions (hence form logic), which is not possible with the native logic. 

Please fix. 

![logic_notfail](https://user-images.githubusercontent.com/85243022/140934297-654cd661-f82d-4a8f-b18c-ca3b68a18553.png)

**Comment by SilviaAmAm** [comment]
The issue here is that there is a field `selectBoxes` and the logic checks if the value of the selectBoxes component is equal to a value (e.g. 5). This won't work, because the value of the selectBoxes is:

```
    "selectBoxes": {
        "1": false,
        "2": false,
        "3": true
    }
```

So it is never going to be equal to a number.
