### ISSUE TITLE
Allow uploading an OAS instead of providing a URL to the OAS

### ISSUE THREAD

**Issue by joeribekker** [open-formulieren/open-forms#920]
Some organisations change their OAS URL often (bad practice but part of life I guess). To prevent issues, we should add a way to upload the OAS.

- [x] Add OAS-upload field in the ZGW consumers library
- [x] Validate that at least the OAS URL or File field are filled (thus, both are optional but MAX one needs to be filled - not both)
- [x] Release new ZGW consumers version
- [x] Update version in Open Forms.

**Comment by Bartvaderkin** [comment]
I linked the PR for ZGW consumers above
