### ISSUE TITLE
Various UX improvements to components

### ISSUE THREAD

**Issue by joeribekker** [open-formulieren/open-forms#929]
UX improvements:

* [x] Increase margins between components
* [x] Remove side margins when using column component
* [x] Remove side margins when using fieldset component
* [x] Add equal (and a little more) space between step icon and the step label (2nd screenshot)

![image](https://user-images.githubusercontent.com/96970/141793602-c037a9c5-1965-46c6-bde6-a78d0963a556.png)

![image](https://user-images.githubusercontent.com/96970/144660884-547d390e-99b1-4e68-843d-46742282fe6f.png)

**Comment by alextreme** [comment]
Deassigning due to shifting Shea to a different project
