### ISSUE TITLE
Support optional appointment fields

### ISSUE THREAD

**Issue by joeribekker** [open-formulieren/open-forms#931]
We currently link some form fields to appointment fields. These fields are mandatory.
In addition, we should include a list of optional fields to link to form fields. (note the # comments)

**JCC**

- clientID # This is the BSN...
- clientLastName: String (max 128 chars)
- clientSex: String ("M" or "F")  # DO NOT SUPPORT
- clientDateOfBirth: DateTime
- clientInitials: String (max 128 chars, considered to be the first name)
- clientAddress: String (max 64 chars)
- clientPostalCode: String (max 16 chars)
- clientCity: String (max 80 chars)
- clientCountry: String (max 128 chars)
- clientTel: String (max 16 chars)
- clientMail: String (max 254 chars)

**Qmatic**

{
"firstName" : "Voornaam",
"lastName" : "Achternaam",
"email" : "test@test.com",
"phone" : "06-11223344",
"addressLine1" : "Straatnaam 1",
"addressLine2" : "4th floor",  # DO NOT SUPPORT
"addressCity" : "Plaatsnaam",
"addressState" : "Zuid Holland",  # DO NO SUPPORT
"addressZip" : "1111AB",
"addressCountry" : "Nederland",
"identificationNumber" : "1234567890", # This is the BSN
"dateOfBirth" : "1900-01-31"
}

**Comment by alextreme** [comment]
Deassigning due to shifting Shea to a different project

**Comment by sergei-maertens** [comment]
Tackled with the appointment rework released in 2.3 - the fields are retrieved from JCC's backend or from the Qmatic plugin configuration.
