### ISSUE TITLE
Style the form definition admin editor similar to how its done in the React-based form editor

### ISSUE THREAD

**Issue by joeribekker** [open-formulieren/open-forms#938]
Please timebox this on an hour or so, because the form definition editor might disappear anyway.

Current situation, form elements are shown above the form editor area:

![image](https://user-images.githubusercontent.com/96970/141823968-05235ab7-2aa8-4507-bf2d-d3ab8b3933bc.png)

Alex could fix it by disabling flex:

![image](https://user-images.githubusercontent.com/96970/141824125-a455d1e9-a4fc-49a1-ba58-573a35fddcc6.png)

but this seems not a really stable way to do it...

**Comment by sergei-maertens** [comment]
Works in my local env and I remember fixing this in 0c3af306cbad95bfc7a9099ef23e311fa2c6c99f 9 days ago
