### ISSUE TITLE
Pressing next/previous might take a while for the form step to load

### ISSUE THREAD

**Issue by joeribekker** [open-formulieren/open-forms#942]
We could at least indicate that it's doing something and/or block the button so it will not be pressed again.

**Comment by sergei-maertens** [comment]
I made a pass at this with the logic check, make sense to extend this to the submission phase.

**Comment by joeribekker** [comment]
and "made a pass at thiss" means this was optimized in another ticket or that you confirm that it could be better?

**Comment by sergei-maertens** [comment]
Tracked this down to the submit data call as biggest culprit, which is invoked after clicking "next". The loading of the next step itself is already put behind a spinner. Now after the submit data click has been done, the component is put in the "navigating" state which displays the loader as well.
