### ISSUE TITLE
Filter out AVG-related log entries in the submission admin

### ISSUE THREAD

**Issue by joeribekker** [open-formulieren/open-forms#943]
Currently, the list of log entries contains AVG related entries.

Maybe we can add a tag to log entries for submission related log entries, to only show those log entries on that page.

**Comment by Bartvaderkin** [comment]
1. Are there AVG-tagged entries we DO want to show on the submission page? Eg: can we filter on entries not-tagged with AVG? Or do we want an additional tag?
1. Do we need to do something for 'historic' data on the test environments? If we filter submission logs on a new tag existing logs would disappear. I could migrate records on the event name and add the tag.

**Comment by joeribekker** [comment]
@Bartvaderkin 

1. No. Can exclude avg
2. No need to take historic data into account. It's all testing and no production yet.
