### ISSUE TITLE
Users need to re-login when continuing a form or changing their appointment

### ISSUE THREAD

**Issue by joeribekker** [open-formulieren/open-forms#957]
Currently, it's unclear how this works and/or what is the desired behaviour.

* [x] Investigate the current behaviour of a form, where authentication required, is continued with a resume-link (from "tussentijds opslaan").
* [x] Investigate the current behaviour of an appointnent form, where authentication required, where the user clicked on the link to change the appointment.

**Verduidelijking nodig**

* [x] Is inloggen opnieuw nodig na hervatten van formulier na tussentijds opslaan (mits het originele formulier inloggen verplicht had) -> JAAA
* [x] Is inloggen opnieuw nodig om afspraak te wijzingen (mits het originele formulier inloggen verplicht had) -> JAAA

**Comment by SilviaAmAm** [comment]
This is what happens now when a user resumes a form by clicking on a link `/submission/<submission_id>/<token>/resume`:

1. The token and the submission ID are checked
2. If valid, the submission is re-added to the session
3. The user is redirected to the last edited step of the form in the SDK: `/stap/<step_slug>?submission_uuid=<submission_uuid>`
4. The SDK uses the submission id in the query param to retrieve the submission data and loads it in the state.

To make the user login again, the `ResumeSubmissionView` can check if the form requires a login and:

- if yes: redirect to a new `/resume?next='/step/step_slug?submission_uuid=<submission_uuid>'` where the user does the login and then gets redirected to the 'next' url
- if no: same as now

For cancelling/changing an appointment, the flow is similar as when resuming a form.

**Comment by sergei-maertens** [comment]
@SilviaAmAm analysis/design on how to tackle this. This takes out the step where for re-login the user has to select the authentication method (as we re-use what was initially used), so I think there should be no or minimal SDK changes needed.

# Resume form with login flow

I've worked out the flows for both initial and resume authentication flows for a form.

Note that this approach explicitly takes into consideration the following issues/
user stories:

* #XXX: displaying authentication status in submission audit log
* #XXX: ability/mechanism for co-signing (additional authentication on top of main auth)

Below are two sections: a description of the flow users go through and a section
describing (some of) the technical changes needed in the codebase to facilitate this.

## Authentication flows

For completeness sake, both the initial and resume flows are described to see where
the overlap is, and how they work together. Changes to both flows are needed.

**Initial form start authentication**

1. User starts form and login options are presented (DigiD, eHerkenning, EIDAS)
2. User selects plugin, e.g. DigiD
3. SDK redirects user to backend login flow
    - ?next parameter is set to form URL + `_start=1`
4. Backend redirects to DigiD with correct RelayState
5. User authenticates with DigiD
6. DigiD redirects user back to backend
7. Backend (plugin) processes authentication
   - obtains BSN (or other param)
8. Backend sets session data:

   ```py
   request.session["form_auth"] = {
       "plugin": "digid",
       "attribute": AuthAttributes.bsn,
       "value": "123456782",
   }
   ```
9. Backend redirects back to form (with SDK supplied ?next parameter)
10. SDK invokes submission start (=`Submission` create API call)
11. Backend processes session data:

   ```py
   auth = session["form_auth"]
   submission.auth_plugin = auth["plugin"]
   setattr(submission, auth["attribute"], auth["value"])
   submission.save(update_fields=["auth_plugin", auth["attribute"]])
   ```
12. Done - auth details are now stored on the submission and can be verified later.

**Resume form authentication**

1. User clicks resume link in e-mail
2. Backend verifies link
    - load submission from database
    - validate submission + token
3. Backend checks login requirements. If `submission.form.login_required`, continue with
   auth flow. Else simply shortcut authentication step, not worked out here.
4. Backend currently does not have `form_auth` session key set (!)
5. Backend inspects `submission.auth_plugin` and starts the authentication flow for that
   plugin. The `?next` param is set to the same URL/view (submission resume).
6. User authenticates with identity provider (DigiD)
7. DigiD redirects user back to backend
8. Backend (plugin) processes authentication
   - obtains BSN (or other param)
9. Backend sets session data:

   ```py
   request.session["form_auth"] = {
       "plugin": "digid",
       "attribute": AuthAttributes.bsn,
       "value": "123456782",
   }
   ```
10. Backend redirects back to resume link (backend supplied ?next parameter)
11. Backend now has `form_auth` session key set.
12. Backend verifies link
    - load submission from database
    - validate submission + token
13. Backend checks form login requirements
    - `submission.form.login_required`
    - `submission.auth_plugin` + `submission.bsn` match `request.session["form_auth"]`
14. Store submission ID in session, granting end-user access to modify it.
15. Redirect back to relevant SDK step for form.

## Cosebase changes

- [ ] Add `Submission.auth_plugin` field, storing the plugin ID of the used
      authentication backend.

      This information will also be relevant for Bart's work in fixing the audit trail.

- [ ] Update `openforms.submissions.views.ResumeSubmissionView` to check authentication
      status before adding the submission to the session
      - look at session to check authentication status
      - if not authenticated, invoke the stored auth plugin and ensure after succesful
        auth the user is redirected to the same view again
      - if/when authenticated, validate that session auth state matches recorded submission
        auth state
      - if everything is valid, add the submission to the session and redirect to the
        form

To do later, refactor and decoupling auth module:

* Create model `SubmissionAuth` with fields `plugin_id`, `attribute` and `value`.
  This is a generic model suitable for all authentication backends, and should be
  part of the base auth plugin.
* Store the ID of the `SubmissionAuth` record in the `form_auth` session key.
* On submission start, correlated the `session["form_auth"]` to the submission record
  (`OneToOneField`).
