### ISSUE TITLE
Prefill implementation issues

### ISSUE THREAD

**Issue by Bartvaderkin** [open-formulieren/open-forms#977]
There are some issues in the prefill:

- [x] Currently it cannot work on the first step, because the required authentication information is copied from the session to the submission when the submission record is created, which happens after the prefill for the first step is retrieved. (it works in some demos because they have a default demo bsn/kvk set)
-  ~~The prefill retrieve from external system happens multiple times because it is part of the serializer *of the logic calls*.~~ non-issue, not doing anything with this. If it's performing bad because of slow KVK API for example, we can look into caching.
- ~~The apply_prefil code runs on an unsaved submission (maybe not a problem)~~ incorrect conclusion because of unexpected submissions admin UI

**Comment by sergei-maertens** [comment]
RE: the first point - this is probably more related to the `Submission.kvk` not being saved than calls being made before something is available.

I checked the flow of the SDK, and the `SubmissionStep` component requires a `Submission` to exist in the state, which is created after loging (if login is required). So, that should already hold all the necessary information required for pre-fill. The form step configuration/definition is read from the `SubmissionStep` resource, which is only available after submission is created.

Conclusion: probably solved by ensuring that `submissions.kvk` is saved after log-in (from the session) and no SDK changes needed.
