### ISSUE TITLE
Clean up the various data-printing methods

### ISSUE THREAD

**Issue by sergei-maertens** [open-formulieren/open-forms#979]
* ~~`Submission.get_printable_data`~~ edit 2024: was deleted with formatters
* * `Submission.get_merged_data`

`get_merged_data` is probably not needed anymore and should be replaced with `get_printable_data`. In #978 some dirty fixes have been applied, which need to be cleaned up.

See also the comment https://github.com/open-formulieren/open-forms/pull/982#discussion_r754340465 for a more extendable strategy.

**Comment by sergei-maertens** [comment]
the description in the ticket may be seriously outdated, please investigate what we can and should do. See also #4009 which is related to these functions.

**Comment by Viicos** [comment]
Closing as it was tackled in #4110.
